### ISSUE TITLE
 Could not resolve all files for configuration ':react-native-image-picker:classpath'

### ISSUE THREAD

**Issue by SOftEngrAtta** [react-native-community/react-native-image-picker#1001]
My application running properly but getting configuration issue after use **react-native-image-picker** plugin 

![im-pckr](https://user-images.githubusercontent.com/24714813/49735865-48c04480-fcaa-11e8-97fa-d397d62f75dd.PNG)

Dependencies : 

"dependencies": {
    "native-base": "^2.8.1",
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "^5.1.0",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-image-picker": "^0.27.1",
    "react-native-progress": "^3.5.0",
    "react-native-typography": "^1.4.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^3.0.7",
    "rxjs": "^6.3.3"
  }

**Comment by MatthieuPeyrot** [comment]
@SOftEngrAtta this PR seems to fix the issue https://github.com/react-native-community/react-native-image-picker/pull/1000

**Comment by SOftEngrAtta** [comment]
my issues has been resolved #999
