### ISSUE TITLE
react-native-image-picker error

### ISSUE THREAD

**Issue by WKMadushanka** [react-native-community/react-native-image-picker#1004]
A problem occurred configuring project ':react-native-image-picker'.
> Could not resolve all files for configuration ':react-native-image-picker:classpath'.
   > Could not find any matches for com.android.tools.build:gradle:2.2.+ as no versions of com.android.tools.build:gradle are available.

//////How can I fix this issue

**Comment by Aloving** [comment]
I've got the same problem...

**Comment by Xifeat** [comment]
Hello, 

Same issue here :) !

**Comment by WKMadushanka** [comment]
> I've got the same problem...


subprojects {
    if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
        }
    }
}









add this to your build.gradle file

**Comment by WKMadushanka** [comment]
> Hello,
> 
> Same issue here :) !


subprojects {
    if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
        }
    }
}



apply this to your build.gradle file where situate in your main folder structure

**Comment by rgpass** [comment]
If anyone tries @WKMadushanka's solution but then gets a similar error message but for `react-native-vector-icons`, you can repeat the same solution.

```
subprojects {
    if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/" }
            }
        }
    }

    if (project.name.contains('react-native-vector-icons')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/" }
            }
        }
    }
}
```

**Comment by Mohammad-Khalid23** [comment]
@rgpass there no need to check multiple time if statement , the work can be done like this.

subprojects {project ->
    if (
        project.name.contains('react-native-fast-image') || 
        project.name.contains('react-native-image-picker') || 
        project.name.contains('react-native-svg') ||
        project.name.contains('react-native-vector-icons')) {
        buildscript {
            repositories {
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }    
        }
    }
}

**Comment by rashidul-hasan** [comment]
try updating the version of `react-native-image-picker` to `0.27.2` in your `package.json`
