### ISSUE TITLE
android studio build error

### ISSUE THREAD

**Issue by crly** [react-native-community/react-native-image-picker#1005]
Could not find com.android.tools.build:gradle:2.2.3.
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
    https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
Required by:
    project :react-native-image-picker

**Comment by yuvaraj119** [comment]
Yes, I too got the same error I changed 2.2.3 to 3.2.1, added google() in repositories of image picker library android build.gradle file

**Comment by crly** [comment]
> Yes, I too got the same error I changed 2.2.3 to 3.2.1, added google() in repositories of image picker library android build.gradle file

I try to changed 2.2.3 to 3.2.1，same mistake

**Comment by crly** [comment]
> > > > Yes, I too got the same error I changed 2.2.3 to 3.2.1, added google() in repositories of image picker library android build.gradle file
> > > 
> > > 
> > > I try to changed 2.2.3 to 3.2.1，same mistake
> > > ![image](https://user-images.githubusercontent.com/17537229/49794177-f185a700-fd71-11e8-8c70-f965eb349d60.png)
> 
> there are two repositories add google() in both

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

**Comment by yuvaraj119** [comment]
Follow this path for changing file
node-modules -> react-native-image picker - >android -> build.gradle file changes i made

**Comment by yannou788** [comment]
Hi

You can try to add this line in the **android/build.gradle** (in the root android folder): 

`subprojects {
    if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
        }
    }
}`

**Comment by enigmasteron** [comment]
Just update picker to last version (0.27.2)
