### ISSUE TITLE
On uploading the corrupted image the application getting crashed in iPhone.

### ISSUE THREAD

**Issue by VivekSharma-zymr** [react-native-community/react-native-image-picker#1008]
On Selecting the corrupted image the application is getting crashed, Please refer below image and try to upload from the 
![asas](https://user-images.githubusercontent.com/43979991/49853955-c604ca00-fe0e-11e8-812b-7ac991d39c5a.png)
gallery. I have attached the corrupted image here.

**Comment by VivekSharma-zymr** [comment]
Any update on this for reference, I have attached the screenshot.
![asas](https://user-images.githubusercontent.com/43979991/50885225-24739700-1413-11e9-999e-ce1dac07fa42.png)

**Comment by VivekSharma-zymr** [comment]
Any updates on the above query, Waiting for your reply. We have this critical blocker in our application.

**Comment by anniewey** [comment]
Please reopen this issue, it's still happening
