### ISSUE TITLE
video compression duration and size 

### ISSUE THREAD

**Issue by nicoara** [react-native-community/react-native-image-picker#1009]
Hi,
I was using Whatsapp ant it compresses video phenomenally, from 40 mb to 5 mb (85% reduction) while keeping good quality. I am wondering if I can achieve similar results with this library.

I have tried to use the compression for a 40 mb video using image-picker, and the compression takes a whole few minute, so I cannot add this to production.
For a 17 mb video, for the below options, it takes ~70 seconds, which is very long. Also is there a callback to know the percent of how much is done from the compression process?

My options are:

```
    const options = 
      {
        mediaType: 'video',
        videoQuality: 'high',
        durationLimit: 10,
        takePhotoButtonTitle: null, //'Take video...', //bug at taking video with camera so far 27/10/2018
        title: 'Select Video',
        //noData,maxWidth and maxHeight shorten time for ImportPhoto to return image
        noData: true,
        maxWidth: 1000, //speeds up compressImage to almost no time
        maxHeight: 1000, //speeds up compressImage to almost no time
        storageOptions: {
          path: 'videos',
          skipBackup: true
        }
      }
    ImagePicker.showImagePicker(options, response => {

```

### Solution
My goal is to have a decent video after compression of under 10 mb, with the waiting time for about 10 seconds for the compression. How large can the original video be? What are the options to use? 

### Additional Information
* React Native version: [0.54.4]
* Platform: [both]
* Development Operating System: [MacOS]
* Dev tools: [Xcode and Android Studio]
* Device: [Samsung Galaxy S4 with Android 5.0.1]

Thanks

**Comment by nicoara** [comment]
Anyone?!

**Comment by siyukok** [comment]
I have also encountered this problem, and there is no solution for the time being. Have you solved it？

**Comment by devpascoe** [comment]
I also would love to know people's approach

**Comment by micahkatz** [comment]
There is a library called pako that I use for compression with react native. This takes base64 data (such as a video) and compresses it to whatever amount you decide. It will take longer for a mightier compression though. Then, you will need to decompress the data any time you are trying to watch it. Below is the link to this library
[https://www.npmjs.com/package/pako](url)

**Comment by devpascoe** [comment]
@michahkatz nice, will look into pako. Be good to receive say compressed full 1080p vid from the client, decompress on server side, transcode etc then deliver back to client full streamed version 👍

**Comment by micahkatz** [comment]
@devpascoe If you are trying to manage videos and images on an efficient and great scale, I highly recomment Cloudinary. Instead of pako, which works fine for compression, this deals with many more things such as height and width, quality of the img, etc. If you are interested in this method, I can give you some code to which you can use Cloudinary. React-Native for cloudinary does not have an up-to-date library, but I have made one of my own. Here are the docs to Cloudinary — let me know if you want help integrating it with RN https://cloudinary.com/

**Comment by DavitVosk** [comment]
@micahkatz can you please provide usage examples for `pako` and `cloudinary` ?

**Comment by mayurchoudharyst2020** [comment]
Is there any way to compress video in android and ios
