### ISSUE TITLE
iOS real device can't choose image from library

### ISSUE THREAD

**Issue by JoKeRxbLaCk** [react-native-community/react-native-image-picker#1012]
Hi guys,
I'm working with this library to my project. I am able to get it work on simulator but when I try to run my app on a real iOS device (iPhone X) I can't select an image from library. If I tap on Choose from library nothing happens. I am only able to take a picture.
This is the implementation:

    handleChoosePhoto() {
            const options = {
                noData: true,
            }

            try {
                 ImagePicker.showImagePicker(options, response => {
                     if (response.uri) {
                         this.setState({ photo: response, avatar: response.uri });
                         this.handleUploadPhoto();
                     }
                 });
             } catch (error) {
                 console.log(error);
             }
         }

And this is the Info.plist file:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
        	<key>CFBundleDevelopmentRegion</key>
	        <string>en</string>
	       <key>CFBundleDisplayName</key>
	      <string>mobileapp</string>
	      <key>CFBundleExecutable</key>
	      <string>$(EXECUTABLE_NAME)</string>
	      <key>CFBundleIdentifier</key>
	      <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	      <key>CFBundleInfoDictionaryVersion</key>
	      <string>6.0</string>
	      <key>CFBundleName</key>
	      <string>$(PRODUCT_NAME)</string>
	      <key>CFBundlePackageType</key>
	      <string>APPL</string>
	      <key>CFBundleShortVersionString</key>
	      <string>1.0</string>
	      <key>CFBundleSignature</key>
	      <string>????</string>
	      <key>CFBundleVersion</key>
	      <string>1</string>
	      <key>LSRequiresIPhoneOS</key>
	     <true/>
	     <key>NSLocationWhenInUseUsageDescription</key>
	     <string/>
	     <key>UILaunchStoryboardName</key>
	     <string>LaunchScreen</string>
	     <key>UIRequiredDeviceCapabilities</key>
	     <array>
		    <string>armv7</string>
	     </array>
	     <key>UISupportedInterfaceOrientations</key>
	     <array>
		    <string>UIInterfaceOrientationPortrait</string>
		    <string>UIInterfaceOrientationLandscapeLeft</string>
		    <string>UIInterfaceOrientationLandscapeRight</string>
	    </array>
	    <key>UIViewControllerBasedStatusBarAppearance</key>
	    <false/>
	    <key>NSAppTransportSecurity</key>
            <dict>
		    <key>NSAllowsArbitraryLoads</key>
		    <true/>
		    <key>NSExceptionDomains</key>
		    <dict>
			    <key>localhost</key>
			    <dict>
				    <key>NSExceptionAllowsInsecureHTTPLoads</key>
				    <true/>
			    </dict>
		    </dict>
	    </dict>
	    <key>UIAppFonts</key>
	    <array>
		    <string>Entypo.ttf</string>
		    <string>EvilIcons.ttf</string>
		    <string>Feather.ttf</string>
		    <string>FontAwesome.ttf</string>
		    <string>Foundation.ttf</string>
		    <string>Ionicons.ttf</string>
		    <string>MaterialCommunityIcons.ttf</string>
		    <string>MaterialIcons.ttf</string>
		    <string>Octicons.ttf</string>
		    <string>Roboto_medium.ttf</string>
		    <string>Roboto.ttf</string>
		    <string>rubicon-icon-font.ttf</string>
		    <string>SimpleLineIcons.ttf</string>
		    <string>Zocial.ttf</string>
		    <string>AntDesign.ttf</string>
		    <string>FontAwesome5_Brands.ttf</string>
		    <string>FontAwesome5_Regular.ttf</string>
		    <string>FontAwesome5_Solid.ttf</string>
	    </array>
	    <key>NSPhotoLibraryUsageDescription</key>
	    <string>For choosing a photo</string>
	    <key>NSCameraUsageDescription</key>
	    <string>For taking a photo</string>
    </dict>
    </plist>

Do you know why this is happening? I'm using:
react-native-cli: 2.0.1
react-native: 0.57.8
and the latest version of the react-native-image-picker.

Thank you.

**Comment by nwaughachukwuma** [comment]
Am also not able to use this Library on a real Android device, as nothing happens when I try to open Gallery or camera. Please what could the problem be?

**Comment by joelgetaction** [comment]
Did you ask for permission to use the camera roll and camera first?  Just listing the usage descriptions in your plist isn't enough - you need to ask for permissions first, before trying to launch the image picker.  The image picker will only launch if permissions have been granted to your app to use the camera.  You could look in settings to verify this.  Note that I haven't used this library directly, I'm just guessing based on my own past experience ... Good luck!

**Comment by nwaughachukwuma** [comment]
I finally solved it. I was using a maxSDKVersion=23 in AndroidManifest permission:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" tools:replace="android:maxSdkVersion"/>`
 so it was only granting permissions to devices in that range. Had to change it to 28, so it works perfectly now. Thanks @joelgetaction for your help

**Comment by joelgetaction** [comment]
You're welcome @nwaughachukwuma :-)

**Comment by tigo0** [comment]
Any news on the original issue for the iOS? I am also not able to open the gallery on real device, while on simulator it works. @JoKeRxbLaCk.

**Comment by NainalChauhan** [comment]
@JoKeRxbLaCk Did you find any solution for that? I am also facing the same issue in iOS, choose from library option in not responding and then upon restarting, the app crashes and again restarts from the screen where the Image picker has been used.

**Comment by bsqu** [comment]
@JoKeRxbLaCk I just ran into the same problem on iOS. 
I had to add:

`<key>NSMicrophoneUsageDescription</key>
<string>$(PRODUCT_NAME) would like to your microphone (for videos)</string>`

to my Info.plist before the Choose from Library option would work.
Permission to use the microphone is never asked for, but the entry is required for some reason.

**Comment by kevinwu127** [comment]
If the phone's cache for the images for the app was reset somehow, the path to the image file for iOS does not exist to ImagePicker.
Current Behavior for "older, uncached" images or images that were taken before the app was installed/reinstalled.
Error message:
```
Error: Cannot find image data
    at createErrorFromErrorData (NativeModules.js:155)
    at NativeModules.js:104
    at MessageQueue.__invokeCallback (MessageQueue.js:414)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at e (RNDebuggerWorker.js:1)
```

When the image is found however, the sourceURL is defined, so ImagePicker knows where the image is (in the Gallery), but it cannot resolve that sourceURL into a response image in {APP_ID}/tmp, where ImagePicker reads from first (?). 

Expected Behavior: I would think it would use the sourceURL to generate a path to the image, copy it to the tmp folder, then return the tmp path.

react-native-cli: 2.0.1
react-native: 0.59.4

**Comment by kevinwu127** [comment]
Line 260 in ios/ImagePickerManager.m is questionable to me with regards to the above issue, unless the path is set to the permanent directory otherwise. I am not a Swift developer so this is my initial hunch for now.
```swift
// We default to path to the temporary directory
NSString *path = [[NSTemporaryDirectory()stringByStandardizingPath] stringByAppendingPathComponent:fileName];
```

**Comment by hugoh59** [comment]
Updates?
