### ISSUE TITLE
ImagePicker.launchCamera and ImagePicker.launchImageLibrary failed in android 8.0

### ISSUE THREAD

**Issue by EvanMaFYH** [react-native-community/react-native-image-picker#1014]
### Description

Explain what you did, what you expected to happen, and what actually happens.
I use 'ImagePicker.launchCamera' or 'ImagePicker.launchImageLibrary' directly instead of 'ImagePicker.showImagePicker' ,however, when i use './gradlew assembleRelease' to build an apk ,there is no response on android 8.0(android version less than 8.0 is ok)
It is strange that if i use 'react-native run-android' to run on an android 8.0 device ,it works perfectly 
### How to repeat issue and example

I just use the example the library provides,the only difference is that i use 'ImagePicker.launchCamera' or 'ImagePicker.launchImageLibrary' directly instead of 'ImagePicker.showImagePicker'

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by yz1311** [comment]
do you have the WRITE_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE  permissions?

**Comment by EvanMaFYH** [comment]
@yz1311 of course,as i said above,I also try the example the library provides,unfortunately,it does not work either

**Comment by yz1311** [comment]
i use this library like you did,just launchImageLibrary intead of showImagePicker. In android 8, it works fine.
I use `react-native-permissions` to check if the permissions are granted.
It is worth noting that,in android 8,
you must request WRITE_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE both.this behavior is different from android7 or  android6

**Comment by EvanMaFYH** [comment]
thanks a lot, I will try it next time, now, I use react-native-image-crop-picker because no one responded for a long time
however, I think the library can do it for developers or explain more exactly in README for lots of 'react nativers' are not familiar with the native platform
thanks

**Comment by ysnfez** [comment]
Can anyone help me with uploading image to windows server ? my company is willing to pay. thank you ImagePicker.launchCamera check the quality of image it's sending to windows server :(
![Head Office_1_MISC_May13_2019_photo1](https://user-images.githubusercontent.com/9275520/58195416-ec6c4280-7c95-11e9-9930-93a2caf45fcc.jpg)
