### ISSUE TITLE
Got response "didCancel", - expected result - get normal object with image uri, path, type, etc...

### ISSUE THREAD

**Issue by hadson19** [react-native-community/react-native-image-picker#1017]
### Description
I've used  `showImagePicker` to load user photo from gallery or camera

```     
ImagePicker.showImagePicker({
  title,
  storageOptions: {
    skipBackup: true,
    path: "images",
  },
  quality: 0.8,
  maxWidth: 720,
  maxHeight: 1280,      
}, response => {
  ....
})
```
Actual Result: 
 ` {didCancel: true}`

Expected result:
 Get image information (uri, path, type, etc...)
  e.g.
```
{
    data:"..."
    fileName:"test.jpg"
    fileSize: 2501
    height:380
    isVertical:true
    originalRotation:0
    path:"..."
    type:"image/jpeg"
    uri:"..."
    width:380
}
```
### How to repeat issue and example

- Install any File storage with access to photo (e.g. Explorer File Manager '9xgeneration')
- try to load user picture using method `showImagePicker`

e.g. 
```
  ImagePicker.showImagePicker({
      title,
      storageOptions: {
        skipBackup: true,
        path: "images",
      },
      quality: 0.8,
      maxWidth: 720,
      maxHeight: 1280
  },
  response =>  console.log('response', response)
)
```
- before picking any picture the new windows should apper to select storage

![pickput image](https://user-images.githubusercontent.com/4102119/50986818-7fd77f00-1510-11e9-9a91-93091f37d8e4.png)

- click on default gallery icon to pick up the picture (click on "Just once")
- select available image

The result:  ` {didCancel: true}`

### Additional Information
* React Native version: 0.57.2
* Platform: emulator Android 8.0
* Development Operating System: Windows
* Dev tools: Android Studio 3.2.1

It's also reproduciung on android 7.x

P.S. If we have only Gallery (which is selecting by default) all works fine.

**Comment by hackdie** [comment]
im having same issue, i found out that happens when i have more than 1 app to choose. (as i can see you have also two)

**Comment by elkinjosetm** [comment]
Same here, have anyone found a solution for this issue?

**Comment by Jacky9425** [comment]
Hi, the issue still exist when i have more than one option of app selection to trigger photo gallery. Unless one of the app is set to default then the image is uploaded successfully.
Any chance i can redirect the component to one gallery app at a time rather than allowing the app to detect multiple app selections?

**Comment by PedramVeisi** [comment]
Having the same issue.

**Comment by Jacky9425** [comment]
Im using `react-native-image-crop-picker` as an alternative to upload image from gallery. However the package has issue with uploading image via camera capture (random chances of getting a success upload), so im using both packages but one for gallery image and another for camera.

**Comment by johanforslund** [comment]
I'm having the same issue when there are two gallery apps to choose from (and none of them is set as default).
