### ISSUE TITLE
Android 64 bit native library

### ISSUE THREAD

**Issue by malonguwa** [react-native-community/react-native-image-picker#1023]
Google Play will start to ONLY accept 64-bit version android App if there is any native code in the project after Aug 2019:
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

Does this react-native-image-picker lib is in 32-bit? or 64-bit? I am still new to the android, the react native 0.58 will included the support of 64-bit version of react native app, does this react-native-image-picker will be able to provide 64-bit version, so we can able to keep using this lib after 2019 Aug with new Google Play Policy?

**Comment by joaodematejr** [comment]
AC

**Comment by charpeni** [comment]
64-bit version is available since react native 0.59, this also applies to this library if built with react native 0.59 or greater.
