### ISSUE TITLE
path and type are undefined on Ios

### ISSUE THREAD

**Issue by radjivF** [react-native-community/react-native-image-picker#1025]
### Description
taking or selecting a picture on ios give you undefined data

path and type

example of what I receive 

```data: "/9j/4AAQSkZJRgABAQAASABIAAD/4QBYRXhpZgAATU0AKgAAAA"
fileName: "IMG_0003.JPG"
fileSize: 291283
height: 333
isVertical: false
latitude: 65.682895
longitude: -17.548928333333333
origURL: "assets-library://asset/asset.JPG?id=9F983DBA-EC35-42B8-8773-B597CF782EDD&ext=JPG"
timestamp: "2012-08-08T18:52:11Z"
uri: "file:///Users/radjivcarrere/Library/Developer/CoreSimulator/Devices/CC92E675-70A1-45A4-9E05-B5CCCA28F9E4/data/Containers/Data/Application/ABA3C2B9-81AA-4A3C-AF12-52EE782DDF02/Documents/images/C9E9ECE5-441A-44D9-9E7E-527480B2A878.jpg"
width: 500 
```

### How to repeat issue and example

Just run the package on ios

my config are 

Environment:
  OS: macOS 10.14.2
  Node: 10.15.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by rash6795** [comment]
+1

**Comment by rash6795** [comment]
any solution on this ?
