### ISSUE TITLE
Can't run any ImagePicker functions, help!

### ISSUE THREAD

**Issue by chai86** [react-native-community/react-native-image-picker#1026]
I'm using the code from the ReadMe on react-native-image-picker page, but i receive an error, after it successfully installed (and i also set the correct permissions on info.plist.

When attempting to openGallery() i get the following warning and no image library opens:

Possible unhandled Promise Rejection TypeError; undefined is not a function (near...reactNativeImagePicker.default.launchImageLibrary...)

Here's my code:

```
import ImagePicker from 'react-native-image-picker';
.....

class App extends Component {

  constructor(props) {
    super(props)

    state = {
      fileURL: '',
    }
  }

   //function
   openGallery = async () => {
      const options = {
        mediaType: 'video'
      }

    ImagePicker.launchImageLibrary(options, (response) => {
      console('Response = ', response);

      if(response.didCancel){
        console.log('User cancelled image picker');
      }
      else{
       this.setState({ fileURL: response.uri });
      }
    });
 }

render() {
  return (
   <View style={styles.container}>      
    <Button 
       style={{margin: 20}}
       onPress={this.openGallery}
       title='Open Gallery'
       backgroundColor='blue'
    />
   </View>

);

 }   
}
```

Neither .showImagePicker(), launchCamera() and launchImageLibrary() don't work. 

Any idea why??

**Comment by adimshev** [comment]
Did you add libRNImagePicker.a into Build Phases -> Link Binary With Libraries ?

**Comment by chai86** [comment]
No i'm not using Xcode, i'm using VS Code. How do you do it in VS code?

I've also updated the info.plist, so it can't be an issue there. 

Strange, as v0.27.0 used to work just fine, the most recent version doesn't run any function (showImagePicker, launchImageLibrary).

**Comment by adimshev** [comment]
When you say info.plist it means iOS, but if you say VS code it means Android.
You have troubles with iOS or with Android?

**Comment by adimshev** [comment]
Try to remove async

**Comment by chai86** [comment]
Nope, you can code iOS and Android apps in VS code. I have removed Async, but still the same issue

**Comment by adimshev** [comment]
It looks like you don't finish installation.

**Comment by adimshev** [comment]
console('Response = ', response); - should crash app

**Comment by chai86** [comment]
Install succeeded in my terminal, but when i console.log(ImagePicer.launchImageLibrary) i get: 

```
ƒ showImagePicker(options, callback) {
      if (typeof options === 'function') {
        callback = options;
        options = {};
      }

      return ImagePickerManager.showImagePicker((0, _objectS…
```

**Comment by adimshev** [comment]
For Android you have to add permissions into AndroidManifest.xml

**Comment by chai86** [comment]
I'm building an iOS app using React Native on a Mac

**Comment by chai86** [comment]
Yes, i'd like to try what you suggest, but i have no idea how to do that in VS code

**Comment by nani92** [comment]
Hi @chai86 . I had same problem.
Look [here](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md), **Post-install steps** resolved problems for me.

Hope it helps!

**Comment by Nour-El-Jamassi** [comment]
I have this issue , any answer

**Comment by Nour-El-Jamassi** [comment]
??

**Comment by sheilarnold** [comment]
I have this problem but for Android. I made the settings described in the [README ](https://github.com/react-native-image-picker/react-native-image-picker)but it doesn't work.
