### ISSUE TITLE
Callback is never called on Android when user denies permissions.

### ISSUE THREAD

**Issue by adimshev** [react-native-community/react-native-image-picker#1027]
### Description

Callback is never called on Android when user denies permissions.
Expected callback with error, but nothing happens.
On iOS, it works like a charm (callback with error).

### How to repeat issue and example

`ImagePicker.launchImageLibrary({ noData: true }, res => console.warn ( JSON.stringify ( res, null, 4 ) ) );`

When I deny permission in the permission warning, it starts a callback with error. It's cool!
But when I call `ImagePicker.launchImageLibrary` another time, it doesn't trigger the callback.

### Additional Information

* React Native version: 0.57.1
* Platform: Android 9
* Development Operating System: Mac OS Mojave 10.14.2
* Dev tools: Android SDK Tools 26.1.1, Android Platform Tools 28.0.0

**Comment by pencilcheck** [comment]
For me, the callback is never called even after selecting an image for some reason...

**Comment by bernhardt1** [comment]
@adimshev did you find a solution to this? It doesn't seem to be solved yet - go away stalebot

**Comment by adimshev** [comment]
No solution

**Comment by bernhardt1** [comment]
@adimshev I'm midway through building a solution now.

Use PermissionsAndroid to check the camera permission manually before calling **launchImageLibrary:** https://facebook.github.io/react-native/docs/permissionsandroid

**Comment by anniewey** [comment]
Is there any workaround other than checking manually?
