### ISSUE TITLE
./gradlew installRelease: Could not resolve all artifacts for configuration ':react-native-image-picker:debugUnitTestRuntimeClasspath

### ISSUE THREAD

**Issue by showtan001** [react-native-community/react-native-image-picker#1029]
### Description

./gradlew installRelease Report an error.

### How to repeat issue and example

- Android
- react-native: "0.57.8"
- react-native-image-picker: "0.28.0"

### Additional Information

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-image-picker:debugUnitTestRuntimeClasspath'.
   > Could not resolve org.mockito:mockito-core:1.+.
     Required by:
         project :react-native-image-picker
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/org/mockito/mockito-core/maven-metadata.xml.
               > Could not HEAD 'https://jcenter.bintray.com/org/mockito/mockito-core/maven-metadata.xml'.
                  > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml.
               > Could not HEAD 'https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                  > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml.
               > Could not get resource 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                  > Could not GET 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                     > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

 help me, thanks!

**Comment by meiqi1992** [comment]
how to resolved?

**Comment by meiqi1992** [comment]
@showtan001  need help?

**Comment by Jeijie** [comment]
+1

**Comment by lifan-github** [comment]
+1

**Comment by phips28** [comment]
+1

**Comment by shouhuori** [comment]
+1

**Comment by Testor10** [comment]
+1

**Comment by Johan-dutoit** [comment]
+1 does not add to the issue.  I'd suggest you update your gradle, etc.  If that still does not work then create a new issue with more information about your setup.
