### ISSUE TITLE
InputAccessoryView does not re-appear 

### ISSUE THREAD

**Issue by alexandrzavalii** [react-native-community/react-native-image-picker#1032]
### Description
I am using InputAccessoryView, which is a sticky textInput as in this example:
https://github.com/facebook/react-native/blob/master/RNTester/js/InputAccessoryViewExample.js

When I open the library textInput slides down, and becomes hidden, after I close the photo library, the textInput doesn't show up.

### How to repeat issue and example
Just stick in the example mentioned above, the react-native-image-picker, and try to open/close photo library.

### Solution

We need to make sure textInput which is wrapped inside InputAccessoryView to be shown again.

### Additional Information

* React Native version: 0.58.1
* Platform: iOS
* Development Operating System: MAC
* Dev tools: xCode, VScode

**Comment by stwiname** [comment]
This is still an issue with `3.0.0-vnext.2` and react-native 62.0

**Comment by Johan-dutoit** [comment]
Unless I am missing something @stwiname, this doesn't seem relevant to the image picker at all.  Share some images and some reproduction code, so we can determine where this issue really belongs.
