### ISSUE TITLE
TypeError: _reactNativeImagePicker2.default.launchImageLibrary is not a function

### ISSUE THREAD

**Issue by singhiskamal** [react-native-community/react-native-image-picker#1033]
Hey i am new in react native.I need some help
I am getting this error while using react-native-image-picker
TypeError: _reactNativeImagePicker2.default.launchImageLibrary is not a function

I have done all the things except one,i haven't downgraded my 
classpath 'com.android.tools.build:gradle:3.0.1'

to 2.2+
and also the zip file to gradle-2.14.1-all.zip
as after doing this another dependency doesn't work.
So please suggest  me what to do.
Thanks in advance.

**Comment by riyaz1620390** [comment]
```
@Nullable
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.asList(
      .........
      new ImagePickerPackage()   // <-- add this to your application class people!
    );
  }
```

**Comment by KirilVelichkov** [comment]
@riyaz1620390  and what if you use expo and windows PC with react native ?? 
I am also facing this error. I have linked react native to the package and still getting the error

**Comment by Johan-dutoit** [comment]
@KirilVelichkov you cannot use this package with expo.

**Comment by singhiskamal** [comment]
> ```
> @Nullable
>   @Override
>   public List<ReactPackage> createAdditionalReactPackages() {
>     return Arrays.asList(
>       .........
>       new ImagePickerPackage()   // <-- add this to your application class people!
>     );
>   }
> ```

Thanks for the help, @riyaz1620390 I have resolved the issue, the problem with me was that I was building this using wifi, without installing new build from USB after installing any new library and same with this one, so after I installed using USB and then it started working....
