### ISSUE TITLE
storageOptions.cameraRoll: true (DON'T save image) / false(SAVE IMAGE) in Android

### ISSUE THREAD

**Issue by truongluong1314520** [react-native-community/react-native-image-picker#1037]
### Description

    const options = {
        mediaType: "photo",
        quality: 1,
        noData: true,
        storageOptions: {
            cameraRoll: true,
        }
    };

This is my options for "photo". Please let me know if I did something wrong. The cameraRoll equal "true", there is no image save, but the image will be saved when "false"

    const options = {
        mediaType: "video",
        quality: 1,
        noData: true,
        storageOptions: {
            cameraRoll: true,
        }
    };

This is my options for "video". Please let me know too if I did something wrong. The cameraRoll equal "true" or "false", the recorded video is always saved

### How to repeat issue and example

This is the code for "photo":

    onCameraPress = () => {

        const options = {
            mediaType: "photo",
            quality: 1,
            noData: true,
            storageOptions: {
                cameraRoll: true,
            }
        };

        ImagePicker.launchCamera(options, (response) => {

            if (response.didCancel) {
                console.log('User cancelled image picker');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            } else {
                // Go to Picture and DCIM folder to check the image
            }
        });
    };

This is the code for video:

    onVideoPress = () => {

        /*
         * More info on all the options is below in the API Reference... just some common use cases shown here
         *
         * https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md
         */

        const options = {
            mediaType: "video",
            quality: 1,
            noData: true,
            storageOptions: {
                skipBackup: true,
                cameraRoll: true,
                waitUntilSaved: true,
            }
        };

        ImagePicker.launchCamera(options, (response) => {

            if (response.didCancel) {
                console.log('User cancelled image picker');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            } else {
                // Go to Picture and DCIM folder to check the video
            }
        });

    };

I use this code and run it on my simulator, the issue appear

### Solution

Sorry, I don't know what to suggest

### Additional Information

* React Native version: 0.57.4
* Platform: Android version 8.1 (API 27)
* Development Operating System: MacOS 10.14.1

Please let me know if you need any information

**Comment by lbelavoir** [comment]
This issue might be related to #986

**Comment by truongluong1314520** [comment]
Hi @lbelavoir , thank you for your comment. I take a look at that issue, but it looks like the image always be saved. In my case it is completely revert.

I made my code run, but can you or someone take a note at this, so that we can consider it later

**Comment by lbelavoir** [comment]
@truongluong1314520 by related I was thinking that it seems that this all save / unsave image seems a bit broken.
