### ISSUE TITLE
Does this lib support multi select for android?

### ISSUE THREAD

**Issue by dbarner1** [react-native-community/react-native-image-picker#1041]
Does this lib support multi select photos for android?

Thanks!
Dave

**Comment by dbarner1** [comment]
I see it doesn’t support iOS, which is fine. Just curious on android.

**Comment by HarshitMadhav** [comment]
No, the library doesnt support multiple image selection for both android and iOS.

**Comment by evanjmg** [comment]
Any suggestions on opening this or using an alternative library?
