### ISSUE TITLE
Not Get GPS Location (launchCamera from the App)

### ISSUE THREAD

**Issue by haifahrul** [react-native-community/react-native-image-picker#1043]
Hi, 

I want to get the GPS location from launchCamera and launchImageLibrary from the App.

I have readed the issue #608 and #178 but not much help.
I have implemented [this](https://github.com/react-native-community/react-native-image-picker/issues/178#issuecomment-396550364), but still not get exif data or GPS location. 

I tested in Android 7.1.1 and 8, but the image not contain GPS location.

- If I launchCamera from the App -> Didn't get the GPS location 
- I take picture from Camera Android (Not from the App), then I launchImageLibrary (ffrom the App) -> the GPS is getting.

Whether it's cause permission on Android or something else?

Any one can help?

Thanks

**Comment by anetka31** [comment]
I need to get GPS location from a photo selected by the user from the image library.

@haifahrul  Did you find a solution? Can you suggest how to do it?

**Comment by jvence** [comment]
Having the same problem. Just logged it again https://github.com/react-native-image-picker/react-native-image-picker/issues/1626

**Comment by mithleshsps** [comment]
Having the same problem.
