### ISSUE TITLE
"No such file or directory" on Android only

### ISSUE THREAD

**Issue by jonahgreenthal** [react-native-community/react-native-image-picker#1045]
### Description

What I did: I chose a photo from the gallery on my Android phone or emulator.

What I expected to happen: A `response` object should be returned containing meaningful information about the photo I chose.

What actually happens: The `response` object is the following:
```
{error: "/storage/emulated/0/DCIM/Camera/20190227_143840.jpg (No such file or directory)"}
```
(or an equivalent object with a different filename)

### How to repeat issue and example

Here's my code to launch the picker:
```
ImagePicker.launchImageLibrary({
  mediaType: 'photo',
}, response => this.processPhotoFromLibrary(other params, response))
```

Here's the source of `processPhotoFromLibrary`:
```
processPhotoFromLibrary = (other params, response) => {
  const uri = response.path || response.uri // Android gives both, but the path is the one we want; iOS only gives uri
  if (uri) {
    // Process the photo (using response and other params). This branch works fine on iOS and sometimes on Android, but not always
  } else if (!response.didCancel) {
    // This is the branch that's being run when it shouldn't be (on Android only)
    console.warn('Could not process photo from library', response)
  }
}
```

### Solution

Somehow the `response` object is not getting created properly. I don't know enough about `rn-image-picker` or the native code/APIs to identify the actual issue.

### Additional Information

* React Native version: 0.57.7
* Platform: Android
* Development Operating System: Mac OS X 10.14.3
* Dev tools: Android 7.0, writing my code in Atom, running emulator through Android Studio 3.1.2

**Comment by angielle** [comment]
have you solved this? I am experiencing the same issue.

**Comment by jonahgreenthal** [comment]
No, I couldn't figure it out :-(

I'd still like help if anyone knows!

**Comment by daleixo-vg** [comment]
I'm having the same problem. It looks like the plugin is moving or deleting the selected file from the gallery.

**Comment by maximus123123** [comment]
add 'file://' to the start of the path, don't know why there has to be a difference between ios and android

**Comment by Tommy1990** [comment]
This is the difference of base system for getting asserts.Thats is base foundtion difference,in iOS ，you should slice the prefix of "file:///" in assert url.




| |
majipeng1990
|
|
邮箱：majipeng1990@163.com
|

Signature is customized by Netease Mail Master

On 05/09/2019 20:44, maximus123123 wrote:

add 'file://' to the start of the path, don't know why there has to be a difference between ios and android

**Comment by jonahgreenthal** [comment]
Leave open until fix confirmed
