### ISSUE TITLE
Multipart body must have at least one part

### ISSUE THREAD

**Issue by houzhanshan** [react-native-community/react-native-image-picker#1047]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by arminghm** [comment]
Could you please explain more? 
Also I think the issue is not related to this repo.

**Comment by jacquesdev** [comment]
Could be related to this https://github.com/square/okhttp/issues/3411

**Comment by vinit98** [comment]
> Could you please explain more?
> Also I think the issue is not related to this repo.

HI @arminghm 
So I am currently having this issue on android device.
When we give permission to camera but not to storage, this error appears

**Comment by jacquesdev** [comment]
@vinit98. The default setting is to store the image. If you change the setting to false (sorry can't remember what it is now), you wouldn't need the storage permission

**Comment by lylest** [comment]
I am facing the same problem

**Comment by lylest** [comment]
I successfully solved this issue using axios library it helps you to send data to the server especially images, and other binary files although i successfully send the image to the PHP handler I still haven't able to catch the received file but this code helps you to get started with axios


code her
import  axios from 'axios';

export default class Productadd extends React.Component {

   state = {
      photo:null,
      price:'',
      pname:''
   }

 
  render() {
    let { photo } = this.state;
    return (
      <View style={styles.container}>
     
         <TouchableOpacity style={styles.opp}
         onPress={this.upload.bind(this)}>
         <Text style={styles.postleft}>POST PRODUCT</Text></TouchableOpacity>
         
          
         <View style={styles.photobox}>
         <TouchableOpacity style={styles.closex}
         onPress={() => this.props.navigation.navigate("Homie")}>
              <Ionicons style={styles.closetext}
              name="md-close-circle-outline" size={70} color="#fff"
              />
        </TouchableOpacity>
          
           {photo &&
          <Image source={{ uri:photo}} 
          style={styles.imageUp} />}
      

         </View>
         <TouchableOpacity 
         onPress={this._pickImage} style={styles.btn}>
          <Text style={styles.addpico}>Choose photo</Text>
         </TouchableOpacity>

          <TextInput style={styles.write}
           placeholder='write price'
           onChangeText={(price)=>this.setState({price})}
           value={this.state.price}/>

         <TextInput style={styles.write}
           onChangeText={(pname)=>this.setState({pname})}
           value={this.state.pname}
          placeholder='Product name'/>
          

      </View>
    );
  }

   _pickImage = async () => {
         let result = await ImagePicker.launchImageLibraryAsync({
           allowsEditing: true,
           aspect: [4, 3],
         });

          console.log(result);

          if (!result.cancelled) {
            this.setState({
              photo: result.uri
            });
          }
} 
//end of image picker

 upload = ()=>{
   //alert();
    this.setState({pname:this.state.pname});
    this.setState({photo:this.state.photo});

     const ProductName = this.state.pname;
     const photo = this.state.photo;

     //console.log("somehting".photo);
     //alert("somehting".ProductName);

     //let localUri = photo.uri;
     const Mydata = new FormData();
      Mydata.append('file', photo);
      axios({
        method:'post',
        url: 'https://sizoni.000webhostapp.com/sell/upload.php',
        data:Mydata

      }).then(res=>{
        console.log(res);
        let RESI = JSON.stringify(res);
        console.log(RESI);
        alert(RESI);
      }).catch(error=>{
        let ERRR= JSON.stringify(error);
        //console.log(ERRR);
      })


 }
 //end of upload function

}
