### ISSUE TITLE
uri doesn't work after restarting the app when choosing the image from gallery.(Android)

### ISSUE THREAD

**Issue by blueturtle13g** [react-native-community/react-native-image-picker#1054]
Hello, I installed the library and successfully showed the image, then I saved the uri using redux-persist and also copied it somewhere and compared it with the uri after rebooting, they were the same but instead of image, I was getting a bluish color. I tested both on my device and android emulator.
When I choose taking an image with camera, it saves my image in `photos` folder and after restarting the app, I'm able to see the picture again in my app, but when I choose from gallery, it doesn't save it in `photos` folder and after restarting it shows a bluish color:
![filmbaz](https://user-images.githubusercontent.com/38331860/54981444-e9badd00-4fc5-11e9-9541-8bbb7c5555f0.png)
this is my uri after restarting the app: `content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20190310_123752.jpg`

It's strange because when I get the bluish color and again choose the same picture from my gallery I get the same uri as above and it works!!! although it's the same as before restarting.
this is my code:
```
chooseFile = () => {
    ImagePicker.showImagePicker({
        title: 'عکس پروفایل خود را انتخاب کنید',
        cancelButtonTitle: 'خروج',
        takePhotoButtonTitle: 'عکس گرفتن...',
        chooseFromLibraryButtonTitle: 'انتخاب از گالری...',
        storageOptions: {
            skipBackup : true
         }
    }, res => {
        if (res.didCancel) {
            console.log("User cancelled");
         } else if (res.error) {
            console.log("Error", res.error);
        } else {
            console.log("Picker Response:", res);
            // saving in redux
            this.props.updateProp({ key: USER_IMG, value:  res.uri });
        }
   });
};
// then showing it:
<Image style={{height: "100%", width: "100%", borderRadius: 140}} source={{ uri: user_img }}/>
```

### How to repeat issue and example
yarn add react-native-image-picker
react-native link react-native-image-picker
establish the boilerplate and choose an image not from camera.
restart the app.

### Solution

I suppose, Images that we choose from download, DCIM, etc. folder should also be saved in `photos` folder to be persistant.

### Additional Information

* React Native version: "0.59.1"
* Platform: Android
* Development Operating System: Windows
* react-native-image-picker : "^0.28.0",

**Comment by ahmetfarukekinci** [comment]
I have same issue. After restarting app uri return but react native image component fails to load it.

**Comment by joris1995** [comment]
I have the same issue! Any luck so far?

**Comment by juanantoniofj** [comment]
Same happens in iOS, any clue?

**Comment by Ashkan-Oliaie** [comment]
same here

**Comment by Johan-dutoit** [comment]
See https://github.com/react-native-community/react-native-image-picker/issues/107

**Comment by PrestanceDesign** [comment]
Same issue today for me too. After restarting app, the uri is present in my redux-persist stora but image is not displayed.

**Comment by PrestanceDesign** [comment]
For Android, I use `response.path` instead `response.uri`and it's working.
https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md

`response.uri` seems to be temporary path which it's kill at the same time the app is close.

**Comment by GuilhermeTrivilin** [comment]
Replace response.uri for response.path, and is work.
