### ISSUE TITLE
android - App crashes as soon as we try to launch the camera.

### ISSUE THREAD

**Issue by Vineet15** [react-native-community/react-native-image-picker#1055]
Plugin version is the latest.
React-native version - 0.58.6
Getting the following error log - 

System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

**Comment by blueturtle13g** [comment]
have you granted the required permissions?

**Comment by Vineet15** [comment]
I have added the required below permissions in the AndroidManifest file - 

<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />

**Comment by Vineet15** [comment]
I have added the required below permissions in the AndroidManifest file - 

<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />

**Comment by blueturtle13g** [comment]
which below??? I can't see anything in your comment.
anyway, you should ask for permissions at runtime while app launches, ie in the `componentDidMount`.
take a look at [react-native-permissionsandroid](https://facebook.github.io/react-native/docs/permissionsandroid)

**Comment by jimji1005** [comment]
paste the codes that you are using to launch the camera @Vineet15

**Comment by Vineet15** [comment]
const options = {
                quality: 1.0,
                maxWidth: transformUI(200),
                maxHeight: transformUI(200),
                allowsEditing: true,
                storageOptions: {
                    skipBackup: true,
                    path: null,
                },
            };

            ImagePicker.launchCamera(options, (response) => {
                if (response.didCancel) {
                    // User cancelled picker
                } else if (response.error) {
                    // Error
                } else if (response.customButton) {
                    // Custom button tapped
                } else {
                    
                }
            });

**Comment by phillbaker** [comment]
Seems similar to https://github.com/react-native-community/react-native-image-picker/issues/732?

**Comment by Vineet15** [comment]
finally I got it working after many days of investigation.
Following are the steps -

1. Create a "xml" folder under android/app/src/main/res
2. add provider_paths.xml file to it with following content in it -
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>

3. Add the following to AndroidManifest.xml inside <application> tag
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
4. clean build and run the project, the camera should work just fine.

Note - I tested this on Samsung device running OS android 8.0

Hope this helps!!
