### ISSUE TITLE
Could not invoke ImagePickerManager.launchCamera

### ISSUE THREAD

**Issue by Slexom** [react-native-community/react-native-image-picker#1061]
### Description

Calling `ImagePicker.launchCamera` not show request for permission but generate the following error on android.

![image](https://user-images.githubusercontent.com/9221469/55706681-161d2300-59e2-11e9-8312-9255c09cbf2a.png)

### How to repeat issue and example

1. call ImagePicker.launchCamera

### Additional Information

* React Native version: 0.59.1
* Platform: Android (5.1 with error, 7.1(LineageOS 14.1) without error, 8 with error)
* Development Operating System: MacOS & Windows
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

#### Packages
```
    "react": "16.8.3",
    "react-native": "0.59.1"
    "react-native-image-picker": "^0.27.2",
```

#### Manifest
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
    package="a.package.name">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/> 
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/> 
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/> 
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
...

</manifest>
```

**Comment by rashmimhatre100** [comment]
Any breakthrough?

**Comment by ObidosDev** [comment]
Try to add 
`<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
to your AndroidManifest.xml
