### ISSUE TITLE
skipBackup is not work

### ISSUE THREAD

**Issue by eh1user2** [react-native-community/react-native-image-picker#1070]
I set skipBackup is false and try to backup to iCloud but fail.

        const options = {
            title: '',
            takePhotoButtonTitle: 'TakePhoto', 
            chooseFromLibraryButtonTitle: 'PhotoLibrary',
            cancelButtonTitle: 'Cancel', 
            mediaType: 'photo',
            quality: 1, 
            storageOptions: {
                skipBackup: false,
                path: 'images',  
            }
        };

**Comment by winkelsdorf** [comment]
Settings `skipBackup: true` just tells iOS to NOT backup. You're expecting that setting it to `false` means that data is automatically backuped to iCloud, which is a wrong assumption.

See https://developer.apple.com/icloud/documentation/data-storage/index.html for a detailed explanation.

For having a working iCloud backup you'll have to store your images within the User documents directory. By default, without setting `path`, the images are stored in a temporary directory like `Caches`.

Try setting:
```js
storageOptions: {
    skipBackup: false,
    path: 'images',
  },
```

This will create the folder `images` within the User documents directory. It should be backuped automatically later.
