### ISSUE TITLE
Gradle script introduce hidden dependency

### ISSUE THREAD

**Issue by OleksandrKucherenko** [react-native-community/react-native-image-picker#1081]
Description:
- JsonSlurper parser has an issue in resolving symbolic links. When this project mapped on the file system to rootProject via a symbolic link, the execution of this line fails. Stack trace shows that call `file('../package.json')` gives the correct path, but when parser try to access the file, a path with a symbolic linked folder cannot be resolved properly.

```text
Caused by: java.io.FileNotFoundException: /Users/user.name/projects/app/clients/android/modules/package.json (No such file or directory)
        at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:154)
```

![Project structure](https://user-images.githubusercontent.com/6419758/57928778-ed762c00-78b1-11e9-8c2b-c01f72327900.png)

Code issue:
https://github.com/react-native-community/react-native-image-picker/blob/c78cb2c9879e8bdf8efee73ddff9123696b85de1/android/build.gradle#L5-L7

Solution:
```gradle
import java.nio.file.Files

/** Get file of the project */
static File fileOfProject(prj, filePath) {
    final projectDir = prj.projectDir
    final resolvedDir = Files.isSymbolicLink(projectDir.toPath())
        ? Files.readSymbolicLink(projectDir.toPath())
        : projectDir.toPath()

    return new File("${resolvedDir}", filePath)
}

def computeVersionName() {
    // dynamically retrieve version from package.json
    def slurper = new JsonSlurper()
    def json = slurper.parse(fileOfProject(project,'../package.json'), "utf-8")
    return json.version
}
```

**Comment by OleksandrKucherenko** [comment]
@janicduplessis @charpeni ^ Please check

**Comment by charpeni** [comment]
Sounds good, can you send a PR and tag me in?

**Comment by OleksandrKucherenko** [comment]
@charpeni Yes, I will try to make asap

**Comment by OleksandrKucherenko** [comment]
@charpeni ^

**Comment by OleksandrKucherenko** [comment]
@janicduplessis @charpeni any updates? have you a chance to take a look at PR?

**Comment by cylim** [comment]
I am curious why we need to set the versionName dynamically, most project are using "1.0", since it is not a standalone apps, the versionName in the gradle file doesn't affect a lot.

**Comment by Johan-dutoit** [comment]
I've already removed this in the new branch I'm working on.
