### ISSUE TITLE
screen goes black trying to take photo or select from library

### ISSUE THREAD

**Issue by NativLouie** [react-native-community/react-native-image-picker#1086]
# Bug

On iphone 6 everything works fine but on iphone 6s and X, when i try to take a photo or choose from library a black blank screen appears and app crashed.  when my code is in the same location as the avatar for uploading it works but when imported from another location i experience this problem.

## Environment info

React native info output:

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 236.57 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-vector-icons: 6.0.1

Library version: x.x.x
react-native-cli: 2.0.1
react-native: 0.59.8
## Steps To Reproduce

Describe what you expected to happen:

1. click on avatar to upload photo or take a photo

2.  prompts me to click on photo

3. take me to library to select photo to be uploaded

## Reproducible sample code

 helperfunction.js

```
import ImagePicker from 'react-native-image-picker';



export const photoUpload =()=>{
    const options = {
        title: 'Select Avatar',
        camera: [{ name: 'fb', title: 'Take a picture' }],
        storageOptions: {
          skipBackup: true,
          path: 'images',
        },
      };
  
      return new Promise(((resolve, reject) => {
        console.log('1')
        ImagePicker.showImagePicker(options, (response) => {
            if (response.didCancel) {
                console.log('2')
                reject('User cancelled image picker');
            } else if (response.error) {
                console.log('3')
                reject('ImagePicker Error: ', response.error);
            } else if (response.camera) {
                console.log('14')
                reject('User tapped custom button: ', response.camera);
            } else {
                console.log('5')
                const source = {uri: response.uri};
                resolve(source);
            }
        })
    }))
}
```

 App.js

```
handlePhotoUpload = async () =>{
    const data = await photoUpload()
    console.log(data)
    if (data){
      this.setState({
        photo: data
      });
    }
  }
```

**Comment by VadymBezpalko** [comment]
+1

**Comment by jchiotaka** [comment]
Sounds like you're missing "Privacy - Photo Library Usage Description" in your Info.plist

**Comment by jlobusta** [comment]
I am having the issue on real-device in test flight version.
Library seems to work fine in both my device and simulators.
The issue is not consistent. Sometimes it's working properly. Sometimes not. 
Device: iPhone7 and iPad Pro (Latest ios version: 13.5.1

react: 16.11.0
react-native: 0.62.2
