### ISSUE TITLE
Takes a lot of time to take/show image result.

### ISSUE THREAD

**Issue by almikurniawan** [react-native-community/react-native-image-picker#1089]
I use react-native-image-picker version 0.28.1 and react native 0.55 in android noughat. anybody help me?

**Comment by Tommy1990** [comment]
zip the picture source,or make a loading. The size of the pictue is a litter bigger for rendering by cpu.




| |
majipeng1990
|
|
邮箱：majipeng1990@163.com
|

Signature is customized by Netease Mail Master

On 05/29/2019 14:45, almikurniawan wrote:

I use react-native-image-picker version 0.28.1 and react native 0.55 in android noughat. anybody help me?

**Comment by almikurniawan** [comment]
Thanks @tommy1990 , how to zip the picture source?

**Comment by Tommy1990** [comment]
set options of quality for img or videoQuality for video.I did set 0.5, the delay seems lower


| |
majipeng1990
|
|
邮箱：majipeng1990@163.com
|

Signature is customized by Netease Mail Master

On 05/30/2019 08:03, almikurniawan wrote:

Thanks @Tommy1990 , how to zip the picture source?

**Comment by almikurniawan** [comment]
Ok, thanks @tommy1990 .

**Comment by syedamirali14** [comment]
after uploading image successfully the uploaded image is taking time to show ?
anyone knows anything about it?
