### ISSUE TITLE
./gradlew installRelease failed

### ISSUE THREAD

**Issue by showtan001** [react-native-community/react-native-image-picker#1091]
react-native: 0.57.8
react-native-image-picker: 0.28.0

I don't know if it's Google or a network reason. can i help me?

Failure information:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-image-picker:debugUnitTestRuntimeClasspath'.
   > Could not resolve org.mockito:mockito-core:1.+.
     Required by:
         project :react-native-image-picker
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://jitpack.io/org/mockito/mockito-core/maven-metadata.xml.
               > Could not get resource 'https://jitpack.io/org/mockito/mockito-core/maven-metadata.xml'.
                  > Could not GET 'https://jitpack.io/org/mockito/mockito-core/maven-metadata.xml'.
                     > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml.
               > Could not get resource 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                  > Could not GET 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                     > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/org/mockito/mockito-core/maven-metadata.xml.
               > Could not HEAD 'https://jcenter.bintray.com/org/mockito/mockito-core/maven-metadata.xml'.
                  > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml.
               > Could not HEAD 'https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                  > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)
      > Could not resolve org.mockito:mockito-core:1.+.
         > Failed to list versions for org.mockito:mockito-core.
            > Unable to load Maven meta-data from https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml.
               > Could not get resource 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                  > Could not GET 'https://dl.google.com/dl/android/maven2/org/mockito/mockito-core/maven-metadata.xml'.
                     > Connect to 127.0.0.1:51788 [/127.0.0.1] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s
229 actionable tasks: 8 executed, 221 up-to-date

**Comment by phips28** [comment]
got the same

**Comment by havinhthai** [comment]
Same here, I can't build my app.

react: 16.8.3
react-native: 0.59.9

**Comment by muyexi** [comment]
@showtan001 Have you fixed it?

**Comment by marlti7** [comment]
face the same problem

**Comment by meharbhutta** [comment]
Just add it to your **android/build.gradle** under subprojects section. **(not app/gradle)**
```
if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                jcenter()
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
        }
    }
}
```

**Comment by tuantvk** [comment]
add mavenCentral to your list of repositories in the global gradle file (**android/build.gradle**)
```sh
buildscript {
    repositories {
        jcenter()
        mavenCentral() // add here
    }

    ...
}

allprojects {
    repositories {
        jcenter()
        mavenCentral() // add here
    }
}
```
https://stackoverflow.com/a/59882615
