### ISSUE TITLE
Gallery opens only once [iOS]

### ISSUE THREAD

**Issue by jaysonsorio** [react-native-community/react-native-image-picker#1096]
# Help
`"react-native": "0.59.5"`
`"react-native-image-picker": "^0.28.1"`

  When I try to upload a photo from gallery, at first try I can access the photos and select one but when I need to change the photo and access the gallery again, I'm not getting a response and the gallery does not open. I can't find the problem for this as I also don't see any activity on my debugger. Please help.

**Comment by AlifElahi** [comment]
I am facing the  exact same problem? @jaysonsorio  have found any solutions or the ans of why is it happening?

**Comment by sergeylaptev** [comment]
the same situation. But react-native version is `0.59.10`

**Comment by akhileshsinha** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/issues/1573#issuecomment-757546103
