### ISSUE TITLE
migrate to AndroidX and Bugs masives: package AlertDialog does not exist

### ISSUE THREAD

**Issue by artyom-developer** [react-native-community/react-native-image-picker#1103]
I'm changing the line of AndroidX _import android.support.v7.app.AlertDialog;_ ---> _import androidx.appcompat.app.AlertDialog;_
but I get error

# Bug
**node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/permissions/PermissionUtils.java:54: error: package AlertDialog does not exist
        AlertDialog.Builder builder = new AlertDialog.Builder(activity, module.getDialogThemeId())**;

I don't have fix this error

"react-native-image-picker": "^0.27.1"
"react-native": "0.57.5",

**Comment by Saad-Bashar** [comment]
+1, we need support for androidx. When can we have this? Anyone? :(

**Comment by Johan-dutoit** [comment]
There is a PR for this (https://github.com/react-native-community/react-native-image-picker/pull/1102), to migrate to AndroidX anyway.

If you could assist with testing this with your versions of react-native, I could certainly merge the PR.

**Comment by MonkeyMoneyFrance** [comment]
check react-native-camera version is below 2.10 (androidX implementation)

**Comment by amrita019** [comment]
Any update on this?

**Comment by Johan-dutoit** [comment]
Now that RN0.60.0, we'll release an RC shortly that will support AndroidX.

**Comment by Johan-dutoit** [comment]
Resolved in the latest version [v1.0.1](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1).
