### ISSUE TITLE
How to change 'Photos' title to 'Videos' or some other text?

### ISSUE THREAD

**Issue by packerfan626** [react-native-community/react-native-image-picker#1107]
<img width="302" alt="Screen Shot 2019-06-25 at 9 07 00 PM" src="https://user-images.githubusercontent.com/9474540/60150440-a2431900-978d-11e9-8ad4-7680c68b7042.png">

I would really like to change the 'Photos' text to 'Videos' as I am only allowing Video uploads here. Any insight on how I can do this? I messed around with the different titles within options but alas I had no luck.

**Comment by ngxu** [comment]
Hello, I also met the same problem. How did the landlord solve it?

**Comment by ngxu** [comment]
I set the selection video, but when my Android phone entered the album, the title showed "Select Pictures".

**Comment by aniciom** [comment]
for iOS you might edit the .m's file and add something like this

- (void)navigationController:(UINavigationController *)navigationController willShowViewController:(UIViewController *)viewController animated:(BOOL)animated
{
    UINavigationItem *ipcNavBarTopItem;
    UINavigationBar *bar = navigationController.navigationBar;
    
    [bar setHidden:NO];
    
    ipcNavBarTopItem = bar.topItem;

    ipcNavBarTopItem.title = @"My title";
}

Then in someway when the controller is delegated you should pass the self.options with a new attribute from code that represents the value that you want to put as title
