### ISSUE TITLE
durationLimit not working on one plus devices

### ISSUE THREAD

**Issue by sathish-cse** [react-native-community/react-native-image-picker#1108]
We set the duration limit to 2 minutes. In other android devices, It worked fine. For one plus devices it didn't stop at 2 minutes.

 ImagePicker.launchCamera(
      {
        cameraType: "back",
        mediaType: "video",
        noData: true,
        videoQuality: "medium",
        allowsEditing: true,
        durationLimit: 120, // 2 Minutes Limit
        storageOptions: {
          cameraRoll: false,
          waitUntilSaved: false,
          skipBackup: false
        }
      }

**Comment by aneena-thomas** [comment]
The issue is still there.
