### ISSUE TITLE
Could not find method testImplementation() for arguments [junit:junit:4.10]

### ISSUE THREAD

**Issue by afacar** [react-native-community/react-native-image-picker#1111]
After installation and linking I got the following build error. Any help is appreciated 👍 
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\ASUS\Apps\testapp\node_modules\react-native-image-picker\android\build.gradle' line: 56

* What went wrong:
A problem occurred evaluating project ':react-native-image-picker'.
> Could not find method testImplementation() for arguments [junit:junit:4.10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 5.34 GB / 15.86 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156
```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-image-picker": "^0.28.1"
  },

and in android/build.gradle, there is following gradle version:

dependencies {
        classpath("com.android.tools.build:gradle:3.4.0")
}

and gradle version in android/gradle/wrapper/gradle-wrapper.properties:

distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

## Steps To Reproduce

1. npm install react-native-image-picker
2. react-native link
3. react-native run-android
...

Describe what you expected to happen:

1. Build and run the app

**Comment by kerem66** [comment]
fixed issue with changing testImplementation to testİmplementation, I found out it is associated with google, you need to use your own country's alphabet I think.
