### ISSUE TITLE
android x react-native 0.60 import android.support.annotation.NonNull;

### ISSUE THREAD

**Issue by a11231g** [react-native-community/react-native-image-picker#1115]
trying to run android  app
but gome this error:
react-native: 0.60.0
    "react-native-image-picker": "^0.28.1",

node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/utils/MediaUtils.java:12: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;

 and these kind of errors ,

node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/permissions/PermissionUtils.java:23: error: cannot find symbol
    public static @Nullable AlertDialog explainingDialog(@NonNull final ImagePickerModule module,

I think its because of new feature of react-native: androidx
what should i do ?

**Comment by a11231g** [comment]
i found out that Replace android.support with androidx in import.
was a solution on react-native-sentry , I'll try it on react-native-image-picker to see what happens :D

**Comment by Vahe83** [comment]
@a11231g did you find any solution for react-native-image-picker case?

**Comment by Johan-dutoit** [comment]
Resolved in the latest version [v1.0.1](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1).

**Comment by subashtimalsina** [comment]
I do have the same problem. This problem made me hang for the whole day. Please fix such issues

**Comment by Liqiankun** [comment]
I had the same issue.

**Comment by piyushrajput45** [comment]
**react native build error:-  import android.support.annotation.NonNull**
_go to the terminal and open your project_

**Step 1- npm install jetifier**

_**You can use yarn, but install it locally in your project, not globally**_

**Step 2- npx jetify**

**Step 3- npx react-native run-android**
