### ISSUE TITLE
Program type already present: androidx.versionedparcelable.NonParcelField 

### ISSUE THREAD

**Issue by corradio** [react-native-community/react-native-image-picker#1119]
# Bug

During gradlew assembleRelease I get the following error:

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
> D8: Program type already present: androidx.versionedparcelable.NonParcelField    

Using RN 0.59.10 and react-native-image-picker@0.28.1

I was able to fix by adding those two lines to gradle.properties in react-native-image-picker:

```
android.useAndroidX=false
android.enableJetifier=false
```

Any recommendations moving forward?

**Comment by javi10823** [comment]
same issue here!

**Comment by AlessioCamm** [comment]
Same issue, nobody found a solution ?

**Comment by EngrJavedAbrar** [comment]
same issue is here

**Comment by johndig0027** [comment]
Same issue is here, i dont want to migrate AndroidX, How i can solve this

**Comment by gongmingqm10** [comment]
Same issue here. Anyway found a solution for this part?

**Comment by AurangsEmpire** [comment]
Same issue here for  "version": "2.3.1" :((( 
Only for Android.
