### ISSUE TITLE
[Android] App crashes automatically when opened!

### ISSUE THREAD

**Issue by TheChanDI** [react-native-community/react-native-image-picker#1122]
The app build with no error at all, but when the app tries to open it crash automatically.

**Comment by Znow** [comment]
Same here - Just installed the package and cannot open the app afterwards, no errors, nothing

**Comment by Johan-dutoit** [comment]
You'll need to add mode info to get any help.

**Comment by blumendorf** [comment]
Did you complete the steps in https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md

The app will crash if you don't set permissions.

**Comment by yankovalera** [comment]
I'm having a similar issue with Android (iOS working fine). From the Android Monitor I can see the following logs:

07-11 14:54:34.524: E/AndroidRuntime(18993): java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider"

**Comment by apolineaire** [comment]
I had the same problem while installing 1.0.1. It has a **breaking change** due to [AndroidX support](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1). 

Just rollback to 0.28.0 for the simplest solution.

**Comment by Vancly** [comment]
same problem，because of the reference to androidx , you just rollback to 0.28.1

**Comment by chaturanga836** [comment]
face the same issue, there is no errors display in the console. but app crash automaticaly

**Comment by kishansbs** [comment]
same here, after capture image app restart automatically.

**Comment by federicofreiberger** [comment]
Same here. 
Roll back worked.
No log errors, nothing, a plain crash(the app didnt even started ).

**Comment by MuhammadSulman** [comment]
I am facing same issue mentioned above in **heading**. To revert back is not good solution there must be proper solution.

**Comment by Johan-dutoit** [comment]
If you want to support AndroidX, then you have to migrate your android project (along with all your other dependencies) to AndroidX.   Alternatively, you use [jetifier](https://github.com/mikehardy/jetifier), which will 'automagically' do this for all your third-party dependencies.

**Comment by Elliot2636** [comment]
same here

**Comment by Susiantiamelia** [comment]
same here, but i can't find the solution, can someone tell me ?

**Comment by jaapHou** [comment]
一样的问题，搞了两天还是没有解决

**Comment by muhammadashfaq** [comment]
> I had the same problem while installing 1.0.1. It has a **breaking change** due to [AndroidX support](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1).
> 
> Just rollback to 0.28.0 for the simplest solution.

thanks for help . this worked for me

**Comment by hp0101** [comment]
> > I had the same problem while installing 1.0.1. It has a **breaking change** due to [AndroidX support](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1).
> > Just rollback to 0.28.0 for the simplest solution.
> 
> thanks for help . this worked for me

How can I roll back ??

**Comment by hp0101** [comment]
For anyone needs help rolling back, try 

> npm uninstall react-native-image-picker

> npm install react-native-image-picker@0.28.0

**Comment by thanh90** [comment]
but 1.x.x is mandatary for react native 0.59 or above. any solution for this ?

**Comment by thanh90** [comment]
> If you want to support AndroidX, then you have to migrate your android project (along with all your other dependencies) to AndroidX. Alternatively, you use [jetifier](https://github.com/mikehardy/jetifier), which will 'automagically' do this for all your third-party dependencies.

still crash silently

**Comment by Johan-dutoit** [comment]
Apart from the AndroidX support, v0.28.1 has the same features as v1.0.1

**Comment by firdaussoberi** [comment]
> but 1.x.x is mandatary for react native 0.59 or above. any solution for this ?

same (issue #1149 ) . am using RN 0.60.4, need the androidx support.
Anyone tested 0.28.0 works with RN  >0.59?

**Comment by evan0708** [comment]
I had same issue with my Google Pixel 2 XL, with RN 0.59.10 and ImagePicker 0.28.0. I spent five days to figure out and research, no luck.

**Comment by thanh90** [comment]
I gave up this. Currently I'm using expo 34 with expo-image-picker

**Comment by slauzinho** [comment]
So I found that for me it wasn't asking for permissions so whenever I tried to access image-picker the app would restart.

I was able to fix it by manually asking for permissions with expo-permissions, something like this:

```javascript
import * as Permissions from 'expo-permissions';
getPermissions = async () => {
    if (Platform.OS !== 'ios') {
      let { status } = await Permissions.askAsync(Permissions.CAMERA);
      if (status !== 'granted') {
        this.setState({
          error:
            'Please grant permissions to be able to upload your profile picture.',
        });
        return false;
      }
      const { status: cameraRollStatus } = await Permissions.askAsync(
        Permissions.CAMERA_ROLL
      );
      if (cameraRollStatus !== 'granted') {
        this.setState({
          error:
            'Please grant permissions to be able to upload your profile picture.',
        });
        return false;
      }
    }
    return true;
  };
```

before calling `ImagePicker.showImagePicker`

**Comment by aneesh2693** [comment]
I too had my apps crashing when selecting photos. I was just trying my luck with  try/catch in the screen. For some unkonwn reason it worked. Here is my code

`handleChoosePhoto = () => {
 const options = {
            noData: true,
            quality: 1,
            maxWidth: 200,
            maxHeight: 200,
        }
        try{
            ImagePicker.launchImageLibrary(options, response => {
                    if (response.uri) {
                    this.setState({ photo: response })
                }  
            });
        }
        catch(e) { console.error(e); }
    }`

**Comment by krutika211** [comment]
Adding this code in AndroidManifest.xml worked for me. (Crash after camera open and click picture in android 9.)
"react-native": "0.59.10",
"react-native-image-picker": "^0.28.1",

<uses-feature android:name="android.hardware.camera.any" />
<uses-feature android:name="android.hardware.camera.autofocus" />
<application 
  ...
  android:largeHeap="true"
>
  ...
</application>

**Comment by krutika211** [comment]
Adding this code to AndroidManifest.xml worked for me. (Crash in android 9 after taking image)
`<uses-feature android:name="android.hardware.camera.any" />`
  `<uses-feature android:name="android.hardware.camera.autofocus" />`
  `<application` 
      `...`
      `android:largeHeap="true" >`
  `</application>`

**Comment by safciplak** [comment]
not work for me

**Comment by deepankarsandy** [comment]
**ISSUE ON ANDROID 10 DEVICE**
exact response: `error: "/storage/emulated/0/DCIM/Camera/IMG_849.jpg: open failed: EACCES (Permission denied)"`

**Comment by sstimac** [comment]
Resolved the issue on my end by rolling back to 0.28 and , manually running Jetifier through the postinstall script -> `"postinstall": "npx jetify"`. Using the latest 0.61.5 RN

**Comment by omkar-asort** [comment]
This worked for me.
Just delete node_modules and reinstall all the packages.

**Comment by hussainhspl** [comment]
> This worked for me.
> Just delete node_modules and reinstall all the packages.

what is react native version ?

**Comment by faridsaud** [comment]
In case it is useful for anyone if you have set the option `quality` and you select a video, on android it crashes.

I end up with something like 
```
{
        noData: true,
        durationLimit: config.VIDEO_LIMIT_DURATION,
        allowsEditing: true,
        ...Platform.select({
          ios: {
            quality: 0.5,
            videoQuality: 'medium',
            mediaType: 'mixed'
          },
          android: {
            videoQuality: 'low',
            mediaType: 'mixed'
          }
        })
      },
```

**Comment by fishmeister09** [comment]
> I had the same problem while installing 1.0.1. It has a **breaking change** due to [AndroidX support](https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1).
> 
> Just rollback to 0.28.0 for the simplest solution.

still crashing upon picking image
