### ISSUE TITLE
'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'

### ISSUE THREAD

**Issue by fgagneten** [react-native-community/react-native-image-picker#1126]
# Bug

## Environment info

React native info output:

```bash
   React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 92.02 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.3.1 => 16.3.1 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

Library version: 1.0.1

After selecting the image from gallery or camera the app stop working (crash). On Android works like a charm but on iOS crash (iPhone 7)
I've already added permission description from camera and photo-gallery.

This is the error from Xcode console:

> 2019-07-15 22:57:01.987793-0300 sampleapp[809:410524] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
2019-07-15 22:57:02.149902-0300 sampleapp[809:410664] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]'
*** First throw call stack:
(0x23b48d27c 0x23a6679f8 0x23b406ce8 0x23b378754 0x104b81404 0x104b81f88 0x104b810a0 0x104b7ee88 0x106c1b6f0 0x106c1cc74 0x106c1fad4 0x106c2ddc8 0x106c2e7ac 0x23b0ad1b4 0x23b0afcd4)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

What am I doing wrong? I'm using CocoaPods

**Comment by cinder92** [comment]
im having same issue

**Comment by isnifer** [comment]
Same here
