### ISSUE TITLE
android studio sync error

### ISSUE THREAD

**Issue by dreamhb** [react-native-community/react-native-image-picker#1128]
### Description

I linked the library to my existing android project, but when I start to sync, I got an error below:
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:27:5-250:19 to override.
```
After I modify the AndroidManifest.xml like below:
```
tools:replace="android:appComponentFactory"
```
another error occurred:
```
Error:
        tools:replace specified at line:27 for attribute android:appComponentFactory, but no new value specified
android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting
```
Then I revert my previous change, and modify gradle.properties:
```
android.useAndroidX=true
android.enableJetifier=false
```
```
androidx.annotation.NonNull
androidx.annotation.Nullable
error: cannot find symbol
```

if I set both AndroidX & enableJetifer to true, another issue occurred:
```
Cannot change strategy of configuration ':rb:buildDependencies' after it has been resolved.
```
Can anyone here help me to figure this out?
Thanks!

### Additional Information

* React Native version: ^0.59.9
* Platform: Android
* Development Operating System: Ubuntu 18.04
* Dev tools: Android Studio 3.4.1
* android tools gradle version: 3.3.0

**Comment by Johan-dutoit** [comment]
See https://github.com/react-native-community/react-native-image-picker/issues/1122.

**Comment by dreamhb** [comment]
Thanks, I have rolled back to 0.28.1
