### ISSUE TITLE
How to choose more than one picture at a time

### ISSUE THREAD

**Issue by shenl923** [react-native-community/react-native-image-picker#1129]
How to choose more than one picture at a time？

**Comment by Dror-Bar** [comment]
From the readme:

This library started as a basic bridge of the native iOS image picker, and I want to keep it that way. As such, functionality beyond what the native UIImagePickerController supports will not be supported here. Multiple image selection, more control over the crop tool, and landscape support are things missing from the native iOS functionality - not issues with my library. If you need these things, [react-native-image-crop-picker](https://github.com/ivpusic/react-native-image-crop-picker) might be a better choice for you.
