### ISSUE TITLE
app got crashed on installing library on android

### ISSUE THREAD

**Issue by muhammadashfaq** [react-native-community/react-native-image-picker#1135]
# Bug

  I tried to use this for image picking but when i installed library , the app crashed in android.
  
i've tested out latest release  but disappointed.
i don't know what you guys are doing. this is main library in react-native-community. Please make some code standards to add it in react native community.

## Environment info

  React Native Environment Info:
react-native 0.59.9
react-native-cli 2.0.1
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
      Memory: 5.26 GB / 13.89 GB
    Binaries:
      Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

Library version: 1.0.1

**Comment by janczizikow** [comment]
Check out https://github.com/react-native-community/react-native-image-picker/issues/1122 - newest release supports AndroidX
