### ISSUE TITLE
react-native-image-picker: NativeModule.ImagePickerManager is null

### ISSUE THREAD

**Issue by abhiburk** [react-native-community/react-native-image-picker#1137]
# Question

I am following [this ](https://aboutreact.com/example-of-image-picker-in-react-native/) tutorial and did what was mentioned over their. I have Windows and I am working on Android App and when trying to run this newly install package and `react-native link react-native-image-picker` I recieved this error 
`react-native-image-picker: NativeModule.ImagePickerManager is null`. I tried finding but could not get solution with the exact error.

**Comment by saad21** [comment]
I have been trying to resolve this error from last 8 hours but couldn't succeed. Please use ImagePicker from expo and here is its link. https://docs.expo.io/versions/latest/sdk/imagepicker/ It will resolve your error.

**Comment by Johan-dutoit** [comment]
I haven't looked at the tutorial (nor it's code), but the installation instructions for this library can be found in the readme (https://github.com/react-native-community/react-native-image-picker#getting-started)

**Comment by abhiburk** [comment]
After degrading the package version it works but with the latest version it doesn't work.

**Comment by Johan-dutoit** [comment]
see https://github.com/react-native-community/react-native-image-picker/issues/1122

**Comment by xyunsh** [comment]
same issue

**Comment by leandrolimasi** [comment]
> After degrading the package version it works but with the latest version it doesn't work.

which version works for you?

**Comment by madandrija** [comment]
I'm on RN 0.60.5, React 16.8.6 (just updated today) and reverting from 1.0.1/1.0.2 to ^0.28.1 helped - I only had issues with tests and this fixed it

**Comment by A-Tokyo** [comment]
> I'm on RN 0.60.5, React 16.8.6 (just updated today) and reverting from 1.0.1/1.0.2 to ^0.28.1 helped - I only had issues with tests and this fixed it

Same here, I also only had issues with jest tests and downgrading to ^0.28.1 got the build running.

**Comment by Zainrajput101** [comment]
I also have this issue but i dont know how can i solved this issue

**Comment by MuhammadRaheelFayyaz** [comment]
I also have the same problem while using expo I have tried running react-native link react-native-image-picker did not work for me. This is what worked for me.

Unistall the latest version
npm uninstall react-native-image-picker
Installed version 0.28.0
npm install react-native-image-picker@0.28.0 --save
react-native link react-native-image-picker

**Comment by lgh06** [comment]
see also #1170 .

**Comment by KawaljeetSBagga** [comment]
For those using Jest, you will need to mock this library. To do so, simply create a new File called _'react-native-image-picker'_ under __test_ folder. And add following lines of code inside it:

```

import {NativeModules} from 'react-native';

// Mock the ImagePickerManager native module to allow us to unit test the JavaScript code
NativeModules.ImagePickerManager = {
  showImagePicker: jest.fn(),
  launchCamera: jest.fn(),
  launchImageLibrary: jest.fn(),
};

// Reset the mocks before each test
global.beforeEach(() => {
  jest.resetAllMocks();
});
```


This worked for me. Thanks
