### ISSUE TITLE
mediaType:'photo'  , Huawei mobile phone settings will appear video! Choosing a video will crash!

### ISSUE THREAD

**Issue by CJELLYS** [react-native-community/react-native-image-picker#1138]
"react-native-image-picker": "0.26.10",
"react": "16.3.1",
"react-native": "0.55.4",

**Comment by erez-guesty** [comment]
Same here.

Any work arround?

**Comment by cleoTang** [comment]
+1 。
Same here.

Any work arround?

**Comment by rock8808** [comment]
+1 
same here 
"react-native-image-picker":"1.0.1",
"react":"16.8.3"
 "react-native": "0.59.10",
phone :huawei honor v10 
andrord version:9
emui: 9.1.0

**Comment by rahulcs1989** [comment]
Hi, I also encountered the same problem with Huawei phones. I have given mediaType for selecting photos only and it works pretty well in all devices except for Huawei. So if the user select any video instead of photo, the app will crash. So is there any solution for this?

**Comment by cjinghong** [comment]
Same here, doing `ImagePicker.showImagePicker` with `mediaType: 'photo` as options will crash the app without throwing any errors at all.

**Comment by erez-guesty** [comment]
still an issue

**Comment by alexzzn** [comment]
find the ImagePickerModule.java file in Android projiect,and add a code`    
if (pickVideo)
    {
      requestCode = REQUEST_LAUNCH_VIDEO_LIBRARY;
      libraryIntent = new Intent(Intent.ACTION_PICK);
      // 351 line add,  filter image
      libraryIntent.setType("image/*");
    }`, i guess the imagePicker has default setType is "image/* video/*"

**Comment by alexzzn** [comment]
find the ImagePickerModule.java file in Android projiect,
``` 
    if (pickVideo)
    {
      requestCode = REQUEST_LAUNCH_VIDEO_LIBRARY;
      libraryIntent = new Intent(Intent.ACTION_PICK);
      libraryIntent.setType("video/*");
    }
    else
    {
      requestCode = REQUEST_LAUNCH_IMAGE_LIBRARY;
      libraryIntent = new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
      libraryIntent.setType("image/*");
      if (pickBoth) 
      {
        libraryIntent.setType("image/* video/*");
      }
    }
```
i guess the imagePicker has default setType is "image/* video/*"

**Comment by mingxin-yang** [comment]
issue

**Comment by marlti7** [comment]
still an issue  why close it?

**Comment by Elderkly** [comment]
+1

**Comment by Elderkly** [comment]
/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:477
imageConfig = getResizedImage(reactContext, this.options, imageConfig, initialWidth, initialHeight, requestCode);
      if (imageConfig == null) {
        imageConfig = new ImageConfig(null, null, 0, 0, 100, 0, false);
        responseHelper.putString("error", "illegal file format");
        responseHelper.invokeResponse(callback);
        callback = null;
        this.options = null;
        return;
      }
      else if (imageConfig.resized == null)
      {
        removeUselessFiles(requestCode, imageConfig);
        ...

you will fixed it

**Comment by xiaohaige** [comment]
+！
