### ISSUE TITLE
{error: "Photo library permissions not granted"}(IOS)

### ISSUE THREAD

**Issue by suresh777** [react-native-community/react-native-image-picker#1141]
Earlier it worked fine but now i checked with latest version it is showing this error

  <key>NSPhotoLibraryAddUsageDescription</key>
  <string>$(PRODUCT_NAME) would like to save photos to your photo gallery</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>$(PRODUCT_NAME) would like access to your photo gallery</string>

 "react-native": "0.59.9",
 "react-native-image-picker": "^1.0.1",

**Comment by chgsilva** [comment]
same here. Do you have any news on this?

**Comment by suresh777** [comment]
Check your app permissions in settings
