### ISSUE TITLE
Unable to make debug build due to Task :react-native-image-picker:testDebugUnitTest FAILED

### ISSUE THREAD

**Issue by dsgithub2018** [react-native-community/react-native-image-picker#1142]
Hi, I am using "react-native": "0.60.4" & "react-native-image-picker": "1.0.1" and my gradle settings look like,
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.3"

There is no issue when I am making a release build, but in debug build I am getting the following error:

> Task :react-native-image-picker:testDebugUnitTest

com.imagepicker.testing.media.ImageConfigTest > testOnImmutable FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testParsingOptions FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testUseOriginal FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testGetActualFile FAILED
    java.lang.ClassCastException

com.imagepicker.testing.ImagePickerModuleTest > testCancelTakingPhoto FAILED
    java.lang.ClassCastException

5 tests completed, 5 failed

> Task :react-native-image-picker:testDebugUnitTest FAILED

Please help me to fix this issue.

**Comment by mottardmaxence** [comment]
Hi, I have the same errors with :

```json
"react-native": "0.60.0",
"react-native-image-picker": "^1.0.1"
```

and 

```
buildToolsVersion = "28.0.3"
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
```

**Comment by thitoo** [comment]
Same issues here!

Task :react-native-image-picker:testDebugUnitTest FAILED

com.imagepicker.testing.ImagePickerModuleTest > testCancelTakingPhoto FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testOnImmutable FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testParsingOptions FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testUseOriginal FAILED
    java.lang.ClassCastException

com.imagepicker.testing.media.ImageConfigTest > testGetActualFile FAILED
    java.lang.ClassCastException

5 tests completed, 5 failed

**Comment by dsgithub2018** [comment]
Downgrading open-jdk version 11 to 8 fixes my issue.

**Comment by martin-przystalka** [comment]
This still persist on version 1.1.0, any news?

**Comment by rawbeans** [comment]
with:
```
buildToolsVersion = "28.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 28
```
and
```
"react-native": "0.60.4"
```

I am getting this error on all versions of `react-native-image-picker` that I have tried so far:
```
1.1.0
1.0.1
0.28.0
```
I am going to have to remove this package from my project until this issue is fixed. 

Is there a way to disable the tests so I can get it to at least compile?

**Comment by rawbeans** [comment]
Same issue here:

https://github.com/react-native-community/react-native-image-picker/issues/1121

**Comment by rynvva** [comment]
I don't know it will help others or not,

I'm facing this too, I'm just run ```cd android; ./gradlew clean; cd ..; npx react-native run-android```

my build is successful again

**Comment by pulpdood** [comment]
To summarise, follow instructions here to downgrade Java from v11 to v8 (v1.8*) fixed it for me: 

https://stackoverflow.com/a/24657630/2280866 

as @dsgithub2018 suggested above, then `./gradlew clean` in the android folder as @rynvva suggests

**Comment by sadikyalcin** [comment]
> This still seems to be an issue with `2.3.4` and Java `11.0.2`.
> 
> I worked around this by disabling tests for this library:
> 
> ```
> project(':react-native-image-picker').tasks.withType(Test) {
>     enabled = false
> }
> ```

Where do you do this?

**Comment by martin-przystalka** [comment]
Walkaround! I fixed this issue, use my fork instead by adding this line to `package.json`.

> "react-native-image-picker": "git+https://github.com/martin-przystalka/react-native-image-picker.git#develop"

cc @sadikyalcin

**Comment by marconett** [comment]
> Where do you do this?

at the bottom of your projects `android/build.gradle`. No need to for a fork.

**Comment by snowwhite-boss** [comment]
> Walkaround! I fixed this issue, use my fork instead by adding this line to `package.json`.
> 
> > "react-native-image-picker": "git+https://github.com/martin-przystalka/react-native-image-picker.git#develop"
> 
> cc @sadikyalcin

It works well !!!
Thanks a million.
