### ISSUE TITLE
Only need to open Gallery for photos, and need to avoid camera permission for it.

### ISSUE THREAD

**Issue by Harsh2402** [react-native-community/react-native-image-picker#1143]
# Bug

I have used this library for Android,
I need to use only gallery, no need to use Camera in the app.

If I used `showImagePicker` or `launchImageLibrary`,
I need to grant camera permission too,

If I need to avoid it for the gallery then how can I avoid it?

**Comment by Natkarock** [comment]
> # Bug
> I have used this library for Android,
> I need to use only gallery, no need to use Camera in the app.
> 
> If I used `showImagePicker` or `launchImageLibrary`,
> I need to grant camera permission too,
> 
> If I need to avoid it for the gallery then how can I avoid it?

Hello! Did you solve your problem? i have same

**Comment by Harsh2402** [comment]
@Natkarock 
No, didn't.

**Comment by GoMino** [comment]
This is sill an issue
