### ISSUE TITLE
testImplementation() error for 0.60.4

### ISSUE THREAD

**Issue by ynsgns** [react-native-community/react-native-image-picker#1145]
# Question

* Where:
Build file 'C:\Users\xxx\rn\xxxxxx\node_modules\react-native-image-picker\android\build.gradle' line: 50

* What went wrong:
A problem occurred evaluating project ':react-native-image-picker'.
> Could not find method testImplementation() for arguments [junit:junit:4.10] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

**Steps To Reproduce**

npm i react-native-image-picker
react-native link react-native-image-picker

**Comment by farkob** [comment]
Change testImplementation to testİmplementation with Turkish capital **İ**. Weird bug in gradle on Turkish systems

**Comment by cashkl** [comment]
> Change testImplementation to testİmplementation with Turkish capital **İ**. Weird bug in gradle on Turkish systems

I tried to solve 2 hours for this it is really awkward bug :(.
Thanks for solution

**Comment by toltarisa** [comment]
> Change testImplementation to testİmplementation with Turkish capital **İ**. Weird bug in gradle on Turkish systems

This is wierd.Thanks man its worked !

**Comment by sburaksak** [comment]
You can use my forked repo, solved with this commit https://github.com/sburaksak/react-native-image-picker/commit/43f2abc7a2213d5c4b87cfea80453192f44a4ac7
