### ISSUE TITLE
[iOS] Image library appears and quickly dismiss itself over native view

### ISSUE THREAD

**Issue by GlisboaDev** [react-native-community/react-native-image-picker#1147]
# Bug
When calling ImagePicker.launchImageLibrary on iOS, nothing happens on the first time, then on calling it again causes the gallery view to appears and dismiss itself right away, freezing the app after that.
Currently the screen I'm calling it has a bridged native view (tested removing all the content in there and keeping a blank `RCTViewManager` that returns an empty view and got same result). Also note that removing the native view from the JS component causes it to work as expected.

## Environment info

React native info output:

```bash  
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 80.83 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 16, 17, 18, 19, 24, 25, 26, 27, 28
        Build Tools: 25.0.2, 27.0.3, 28.0.3
        System Images: android-16 | Google APIs Intel x86 Atom, android-17 | ARM EABI v7a, android-25 | Intel x86 Atom, android-25 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: `1.0.2`

## Steps To Reproduce
Simply call `ImagePicker.launchImageLibrary` from a component with a bridged react native view.

Describe what you expected to happen:

1. Open the library to pick the image

**Comment by Johan-dutoit** [comment]
Can you attach/link a repo with the issue?

**Comment by HWBN1** [comment]
make sure you don't rerender the component while the gallery is opened

**Comment by QuentinUbi** [comment]
Got the same problem, impossible to debug. Someone got the solution for this issue ?

**Comment by QuentinUbi** [comment]
Ok I've found a solution for your problem which was mine. But I used a custom modal to open the choicePicker so I add a timeout to close the modal then open native gallery. On iOS I set the timeout to 1 sec, and i think this timeout should be variant on which device the user is. @GlisboaDev

**Comment by akhileshsinha** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/issues/1573#issuecomment-757546103
