### ISSUE TITLE
Strange crash on some iPhone models when locking the orientation

### ISSUE THREAD

**Issue by alexpopaconst** [react-native-community/react-native-image-picker#1151]
# Bug
Version 0.28.1 with React Native 0.59.0, no pods:

When launching the camera from a view that has its orientation locked, the application will crash and close without errors on an iPhone XR. It will however work as expected if the orientation is unlocked.
On an iPhone 6, launching the camera from a view with the orientation locked works without any issues.
Both devices run iOS 12.4 

## Environment info

React native info output:

 React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 24.62 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.3.0 - ~/.nvm/versions/node/v11.3.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v11.3.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1
Library version: x.x.x

## Steps To Reproduce

1. Lock the view with Orientation.lockToLandscape()
2. Attempt to launch the camera with ImagePicker.launchCamera()
3. Run the application on a iPhone XR and then on a iPhone 6

Describe what you expected to happen:

1. I would expect that the application would behave similarly on both devices

**Comment by imanshu1** [comment]
I am getting the same error.
Steps:
1. Lock device orientation. (Potrait Mode)
2. open camera with ImagePicker.launchCamera() in Landscape mode

Camera app crashes and device goes in landscape mode.
