### ISSUE TITLE
Disable/bypass 'compress video'

### ISSUE THREAD

**Issue by theabhinavdas** [react-native-community/react-native-image-picker#1152]
# Question

How can I bypass the 'Compressing Video' section during video selection through this library? Based on this Stackoverflow answer: [https://stackoverflow.com/a/48643954/6689221](https://stackoverflow.com/a/48643954/6689221), it seems that it is possible from iOS 11 onwards. 

Would be really helpful if someone can help me integrate that change, i.e.: 
`if #available(iOS 11.0, *) {
    picker.videoExportPreset = AVAssetExportPresetPassthrough
}`

TIA! :)

**Comment by chai86** [comment]
I concur. I'd like to bypass this and run a spinning loading animation (while the compressing runs in the background), and know when the compressing video is complete.

**Comment by mifi** [comment]
This has already been implemented in expo's image picker:
https://github.com/expo/expo/commit/3fd67b773e594c50bb28a7143ed9241883598105
