### ISSUE TITLE
How to configure the 'compressing video' screen?

### ISSUE THREAD

**Issue by chai86** [react-native-community/react-native-image-picker#1154]
How do i: 
--style the cancel, play and choose buttons (change font and color)
--change color of the progress bar from blue color
--remove the 'compressing video' text here
--change the background color behind the video from the deep black 

<img width="356" alt="Screen Shot 2019-08-08 at 09 47 07" src="https://user-images.githubusercontent.com/43324724/62810747-e187b800-baf6-11e9-8631-cb4e396dff78.png">

**Comment by chai86** [comment]
?

**Comment by chai86** [comment]
@marcshilling Are you able to assist on the 4 points i'd like to make some minor changes on above? Thank you

**Comment by yfuks** [comment]
I'm don't have access/work to/with `react-native-image-picker` since November 2016 (almost 3 years).
You should probably tag the maintainers.

**Comment by chai86** [comment]
@Johan-dutoit Would you be kind enough to assist me with styling the screen above please, based on the required effect?

**Comment by chai86** [comment]
@marcshilling   Would you be kind enough to assist me with styling the screen above please, based on the required effect?

**Comment by chai86** [comment]
Issue still not resolved
