### ISSUE TITLE
Wrong orientation on Samsung devices when picking images from gallery

### ISSUE THREAD

**Issue by edu1525** [react-native-community/react-native-image-picker#1155]
Hello, i'm trying to use this library to pick images from gallery, all the things is right except that when a i pick the image from the gallery it is rotated by 90 degrees. How could I handle with this issue? Thanks!

**Comment by petermercy** [comment]
I'm having this problem as well.

**Comment by Alecattie** [comment]
Hello this is still an issue, is there any solution?
