### ISSUE TITLE
native module imagepickermodule tried to override imagepicker module for module name imagepickermanager  in Android

### ISSUE THREAD

**Issue by artyom-developer** [react-native-community/react-native-image-picker#1163]
# Bug

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 132.08 MB / 7.65 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    npm: 6.10.3 - /usr/local/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x
"react-native-image-picker": "^1.0.2"

Describe what you expected to happen:

I add one line code in the MainApplication but not load app
 packages.add(new ImagePickerPackage());
and comment the line load app but not load ImagePicker

and also run react-native link in the command.

**Comment by CharlyJazz** [comment]
solved?

**Comment by Johan-dutoit** [comment]
If you're using RN > 59.0, then you should **not** be linking the packages manually.

**Comment by artyom-developer** [comment]
> solved?

yes ...
