### ISSUE TITLE
Cannot read property "showImagePicker" of undefined.  Adding in Build phase isn't working either. 

### ISSUE THREAD

**Issue by tristanv1** [react-native-community/react-native-image-picker#1166]
React-Native Info:
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1
Library Version: 1.1.0

I've followed all the necessary install steps with Cocopoads for version 1.1.0 of the app and nothing has worked.
I've search for days for how to fix my error.  Fresh install. Tried different versions. 
Tried linking, unlinking. 
No matter what I do I always get 
` Cannot read property "showImagePicker" of undefined. `

So I've then tried doing the following: Adding my files to the build phase as recommended in other issues, and then I just get duplication error instead.

When I add the files to the build phase this is what happens.
<img width="689" alt="Screen Shot 2019-09-08 at 11 35 46 PM" src="https://user-images.githubusercontent.com/24782204/64501917-82ea6100-d291-11e9-85b7-04684b56d894.png">
<img width="821" alt="Screen Shot 2019-09-08 at 11 36 03 PM" src="https://user-images.githubusercontent.com/24782204/64501918-82ea6100-d291-11e9-949b-b0d3af445ed8.png">

**Comment by LadyGaga1208** [comment]
Hi, you can restart your computer

**Comment by gallegosg** [comment]
Any fix for this issue? I've been getting the same problem on RN 0.61.2

**Comment by tristanv1** [comment]
Still nothing for me @gallegosg.   The installation does not seem to work with Cocopoads / Manually adding to Linked libraries.

**Comment by gallegosg** [comment]
@tristanv1 So using
 `import  ImagePicker  from 'react-native-image-picker'` 
instead of 
 `import { ImagePicker } from 'react-native-image-picker'`
seems to solve this issue for me
