### ISSUE TITLE
react-native-image-picker: NativeModule.ImagePickerManager is null

### ISSUE THREAD

**Issue by khuramdogar** [react-native-community/react-native-image-picker#1170]
# Bug

This error appears when I rant unit test. Please help me to mock react-native-image-picker

```bash
 react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
    • Run `react-native link react-native-image-picker` in the project root.
    • Rebuild and re-run the app.
    • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
    • Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
    * If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker

      at Object.<anonymous> (node_modules/react-native-image-picker/lib/commonjs/internal/nativeInterface.ts:18:9)
      at Object.<anonymous> (node_modules/react-native-image-picker/lib/commonjs/index.ts:10:1)
```

**Comment by IvanL0** [comment]
Have the same.

**Comment by olethanh** [comment]
Got the same error when upgrading from 0.28.1 to 1.1.0 (while upgrading to RN 0.61). On linux, runing react-native link didn't change anything.

Fixed it by providing a mock. Created a file __mocks__/react-native-image-picker.js in my project with content:

> export default  {
>   showImagePicker: jest.fn(),
>   launchCamera: jest.fn(),
>   launchImageLibrary: jest.fn(),
> }

**Comment by lgh06** [comment]
I followed https://github.com/react-native-community/react-native-image-picker/blob/11dcf311b7fdf694b60868503b73c4e04b904851/jest.setup.js  ,
added 
```javascript
NativeModules.ImagePickerManager = {
  showImagePicker: jest.fn(),
  launchCamera: jest.fn(),
  launchImageLibrary: jest.fn(),
}
```  
in jest setup js. skipped this error.

**Comment by YimingSun60** [comment]
> I followed https://github.com/react-native-community/react-native-image-picker/blob/11dcf311b7fdf694b60868503b73c4e04b904851/jest.setup.js ,
> added
> 
> ```js
> NativeModules.ImagePickerManager = {
>   showImagePicker: jest.fn(),
>   launchCamera: jest.fn(),
>   launchImageLibrary: jest.fn(),
> }
> ```
> 
> in jest setup js. skipped this error.

Hi, the jest.setup.js is not in my directory, do I need to create one and add it to 
nodemodule/react-native-image-picker directory?

**Comment by romonsalve** [comment]
> > I followed https://github.com/react-native-community/react-native-image-picker/blob/11dcf311b7fdf694b60868503b73c4e04b904851/jest.setup.js ,
> > added
> > ```js
> > NativeModules.ImagePickerManager = {
> >   showImagePicker: jest.fn(),
> >   launchCamera: jest.fn(),
> >   launchImageLibrary: jest.fn(),
> > }
> > ```
> > 
> > 
> > in jest setup js. skipped this error.
> 
> Hi, the jest.setup.js is not in my directory, do I need to create one and add it to
> nodemodule/react-native-image-picker directory?

No, in your project root create a folder named 'jest' and inside a file called setup.js

**Comment by KawaljeetSBagga** [comment]
For those using Jest, you will need to mock this library. To do so, simply create a new File called _'react-native-image-picker'_ under __test_ folder. And add following lines of code inside it:

`
import {NativeModules} from 'react-native';

// Mock the ImagePickerManager native module to allow us to unit test the JavaScript code
NativeModules.ImagePickerManager = {
  showImagePicker: jest.fn(),
  launchCamera: jest.fn(),
  launchImageLibrary: jest.fn(),
};

// Reset the mocks before each test
global.beforeEach(() => {
  jest.resetAllMocks();
});
`

This worked for me. Thanks
