### ISSUE TITLE
AppCompatActivity issue during build

### ISSUE THREAD

**Issue by nh83012001** [react-native-community/react-native-image-picker#1172]
# Bug

```bash
> Task :react-native-image-picker:compileDebugJavaWithJavac FAILED
**node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:602: error: cannot access AppCompatActivity
        if (activity instanceof ReactActivity)
                     ^
  class file for android.support.v7.app.AppCompatActivity not found
**node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:604: error: incompatible types: Activity cannot be converted to ReactActivity
          ((ReactActivity) activity).requestPermissions(PERMISSIONS, requestCode, listener);
```

  System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      Memory: 130.35 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: x.x.x
I was using version 1.0.2, but I downgraded to 0.28.1  because of react-native version 

In my dependency file I have 
implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

I am also using react-native-navigation and have seem some comments about compatibility issues with that.

**Comment by AlisanCakir** [comment]
I get the same error

**Comment by AlisanCakir** [comment]
My issue is install the another third party package to auto linking way solved by uninstall the package

**Comment by Samiksha19** [comment]
i am getting the same issue please help me with it
