### ISSUE TITLE
Setting up react-native-image-picker for RN 60 Android with jetifier

### ISSUE THREAD

**Issue by oluomoniyi** [react-native-community/react-native-image-picker#1173]
# Question

Hi Guys,

Please, I am trying to use this lib with Android on React Native 60.x.x. It says use jetifier, does anyone know actually know how to achieve this? Been scratching my head for a few hours now. Installed the jetifier lib and followed the steps on there.

Thanks a lot

**Comment by Johan-dutoit** [comment]
You should specify `"postinstall": "npx jetify"` in the scripts node in `package.json`.  This will trigger jetifier after every npm/yarn install.

**Comment by oluomoniyi** [comment]
Strange, I am sure I did that before. For some reason it works now.
Oh well all good.
Thanks @Johan-dutoit
