### ISSUE TITLE
ImagePicker.showImagePicker is not a function

### ISSUE THREAD

**Issue by hugoh59** [react-native-community/react-native-image-picker#1175]
`ImagePicker.showImagePicker is not a function
`
When calling this function i get the above error message. I'm using RN 0.60.4 and I've installed the pod.

Version 0.28.0 works however. It seems as it is due to the fact that they is no longer an index.js file from 1.0 version and that's causing my project not to find the file with exention .ts

Can you guys fix this?

**Comment by kiran-mantana** [comment]
Any Update on this issue?

**Comment by janpe** [comment]
For me this was fixed by changing `import * as ImagePicker from 'react-native-image-picker'
` to `import ImagePicker from 'react-native-image-picker`

**Comment by vadermemo** [comment]
Any solution for this issue?
These are my specs

    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-image-picker": "^0.28.1",


and this is my log

019-11-18 14:37:49.614 [error][tid:com.facebook.react.JavaScript] null is not an object (evaluating 'ImagePickerManager.showImagePicker')
2019-11-18 14:37:49.613771-0600 Bioderma[75886:1078893] null is not an object (evaluating 'ImagePickerManager.showImagePicker')
2019-11-18 14:37:49.621 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: null is not an object (evaluating 'ImagePickerManager.showImagePicker')
2019-11-18 14:37:49.621448-0600 Bioderma[75886:1077459] Unhandled JS Exception: null is not an object (evaluating 'ImagePickerManager.showImagePicker')

**Comment by kyhnlbyrk** [comment]
@vadermemo I am having a similar problem only diffrence I get is Unhandled JS Exception: null is not an object (evaluating 'o.showImagePicker') is this. Not ImagePickerManager but "o". Any solution?
