### ISSUE TITLE
when 'response.fileName' has space inside, the 'response.type' === null, it will have a wrong on upload image

### ISSUE THREAD

**Issue by dmitryguesty** [react-native-community/react-native-image-picker#1176]
This is the response I received from ImagePicker.
If fileName have no spaces type is ok:

![image](https://user-images.githubusercontent.com/38178646/65148633-4a811a80-da29-11e9-843e-2ad05851ad59.png)

Otherwise,  type is null:

![image](https://user-images.githubusercontent.com/38178646/65148760-84522100-da29-11e9-8ee1-d190032f2d2a.png)

Images from debugging...

Used Android Device.

**Comment by dmitryguesty** [comment]
The same bug that was Closed and possibly unresolved.

https://github.com/react-native-community/react-native-image-picker/issues/936

**Comment by Johan-dutoit** [comment]
Can you update the following locally (in your node_modules)?

https://github.com/react-native-community/react-native-image-picker/blob/master/android/src/main/java/com/imagepicker/ImagePickerModule.java#L729-L732

to something like this?

```
String extension = null;
int i = file.lastIndexOf('.');
if (i > 0) {
    extension = file.substring(i+1);
}

if (extension != null) {
    responseHelper.putString("type", MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension));
}
```

and report back if that makes any difference?

It's either not getting the extension or it's not getting the MimeType from the extension.  Either way, the above should provide us with an answer.

**Comment by dmitryguesty** [comment]
```
      File f = new File(path);
      responseHelper.putDouble("fileSize", f.length());
      responseHelper.putString("fileName", f.getName());
      // type
      String extension = MimeTypeMap.getFileExtensionFromUrl(path);
      String fileName = f.getName();
      if (extension != "") {
        responseHelper.putString("type", MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension));

      } else {
        int i = fileName.lastIndexOf('.');
        if (i > 0) {
          extension = fileName.substring(i+1);
          responseHelper.putString("type", MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension));
        }
      }
```

This what helped me ....

**Comment by dmitryguesty** [comment]
Added fallback to take type from fileName if not exists in URL,
Previously  condition 
```
String extension = MimeTypeMap.getFileExtensionFromUrl(path);
if (extension != null) { ...
```

is mistaken cause MimeTypeMap.getFileExtensionFromUrl returns empty string and not null in case of failure : https://developer.android.com/reference/android/webkit/MimeTypeMap

**Comment by Johan-dutoit** [comment]
If you can create a PR, that would be great!

**Comment by dmitryguesty** [comment]
I'll definitely do it soon

**Comment by kaueDM** [comment]
```
const type = `image/${fileName.split('.').slice(-1)[0]}`
```

**Comment by DodoTheDeveloper** [comment]
Good find, especially since Android needs to have the correct mime-type set in order to upload multipart-form data.

**Comment by liamjones** [comment]
This bug still exists, we're having to patch locally via patch-package to correct the logic for now

**Comment by NemanjaManot** [comment]
+ 1

**Comment by Johan-dutoit** [comment]
This should be fixed with https://github.com/react-native-community/react-native-image-picker/pull/1274.  Will release a new version shortly.
