### ISSUE TITLE
No user permissions prompt when building with  Xcode Version 11.0 (11A420a)

### ISSUE THREAD

**Issue by bryonCatalyst** [react-native-community/react-native-image-picker#1177]
### Description

When building project for iOS 13 using Xcode Version 11.0 (11A420a) GM2, I noticed that the user permissions settings seem to be ignored.  Previously, we would get the alert to grant access to image library and/or camera.  When I build using Xcode 11, the user's photo library seems to be accessible even if the user changes permissions to off in settings.  Sometimes, the permission alert shows up after the user is already presented with the photo gallery.

If I build using Xcode 10.3, everything works as expected. 

### How to repeat issue and example
Create a basic project with call to ImagePicker and build using Xcode Version 11.0 (11A420a) GM2

### Solution
Not sure, it could be a threading issue where the alert is not being displayed reliably / in a timely manner

### Additional Information

* React Native version: 0.60.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools: Xcode Version 11.0 (11A420a) GM2

**Comment by bryonCatalyst** [comment]
Based on comments and attached resources in this issue, 
**iOS doesn't need permissions for picking a single image #1159**
I think this is resolved - thanks for your support!

**Comment by callmejm** [comment]
i have same issue with you, with same environment, but i click launchCamera it not asking permission just nothing happen, but when i click launchImageLibrary, system asking permisson and after accepted it show ios gallery for me to pick image 

@Johan-dutoit
