### ISSUE TITLE
Cannot read property 'tintColor' of null

### ISSUE THREAD

**Issue by cenzovit** [react-native-community/react-native-image-picker#1186]
# Bug

Probably since the merge of PR1131, if null is passed as options to showImagePicker, a TypeError ("Cannot read property 'tintColor' of null") occurs. 

## Environment info

React native info output:

```bash
 System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 81.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 27.0.3, 28.0.1, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.9.0 => 2.9.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0 => 0.61.0
```

Library version: 1.1.0

## Steps To Reproduce

Call ImagePicker.showImagePicker passing null as options.

## Expected Behavior

I would expect the library to set the default tintColor without attempting to reference tintColor from the options object (which is null).

## Reproducible sample code

ImagePicker.showImagePicker(null, response => {
     ...
});

**Comment by vksgautam1** [comment]
Any solution?

**Comment by mohitmishra22** [comment]
you can pass an empty object instead of null as an option. See code below:

`ImagePicker.showImagePicker({}, response => {
...
})`

not sure why it's mentioned as null in docs but passing empty object works.
