### ISSUE TITLE
App restarts when I take photo

### ISSUE THREAD

**Issue by reshiDeveloper** [react-native-community/react-native-image-picker#1188]
In the emulators app works fine when take photo. but in real device app restarts again. 
I think quality is much and i reduced quality to 0.5 but anything didnt change, Please help me

**Comment by JuAlexandre** [comment]
Same issue on Android...

**Comment by raushanji** [comment]
You can use the image picker within try{...}catch(err){...} block
`try{
    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);
      if (!response.didCancel) {
      }
      if (response.didCancel) {
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        const source = { uri: response.uri };
      }
    });
    } catch(err){
      console.log(err);
    }`

**Comment by arifinoid** [comment]
Same here, this issue still occurs on low device android
