### ISSUE TITLE
Create an option to configure the color of the cancel button. 

### ISSUE THREAD

**Issue by pavlo-o-savchuk** [react-native-community/react-native-image-picker#1189]
# Feature Request

Create an option to configure the color of the cancel button. 

## Why it is needed

At the moment you can change the color of all buttons with **tintColor** option. But all the buttons are colored this way. I need to make **cancel**button color red, for example, and remain the other buttons blue colored,

**Comment by pavlo-o-savchuk** [comment]
This feature request is still relevant

**Comment by chai86** [comment]
Absolutely relevent
