### ISSUE TITLE
Android: After I take new photo on Redmi phones only, my app unexpectedly restarts (it works fine on all other android phones)

### ISSUE THREAD

**Issue by amittri** [react-native-community/react-native-image-picker#1192]
# Bug

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by FluxProjects786** [comment]
when I select image from gallery in then why app close? i am using ios simulator iphone 11

**Comment by yorickshan** [comment]
same issue
