### ISSUE TITLE
when i select image from gallery in ios simulator then app close without showing any error. 

### ISSUE THREAD

**Issue by FluxProjects786** [react-native-community/react-native-image-picker#1193]
# Bug

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by orcunorcun** [comment]
Same here!

(for IOS)

"react": "16.9.0",
"react-native": "0.61.2",
"react-native-image-picker": "^1.1.0"

**Comment by servocoder** [comment]
Same at iOS 13.1

"react": "16.8.6",
"react-native": "0.60.6",
"react-native-image-picker": "^1.1.0"

**Comment by chiennv97** [comment]
I have same issue and I repeat read document and realize I miss "add UsageDescription on iOS and some permissions on Android"
Add UsageDescription and issue fixed
you can try add this follow link https://github.com/react-native-community/react-native-image-picker/blob/v1.0.2/docs/Install.md

**Comment by ALIHASSAN65** [comment]
thanks for you contribution , issue has solved after entering the permission lines but how i can recall the permission if one time user don't allow.
