### ISSUE TITLE
Media Library Permission asked after accessing media.

### ISSUE THREAD

**Issue by ziyoshams** [react-native-community/react-native-image-picker#1194]
# Bug - iOS

We can see contents of Media Library without permissions provided. And the request for permission is asked afterwards. You can see it in action:

![image-picker-issue](https://user-images.githubusercontent.com/14338593/66405006-76a01380-e9b7-11e9-9091-422dda12b03d.gif)

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.40 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.0, 27.0.0, 28.0.0, 28.0.3, 29.0.2
      System Images: android-25 | Intel x86 Atom, android-26 | Intel x86 Atom, android-27 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    create-react-native-module: 0.10.2
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.4.1
```

Library version: 1.1.0

Describe what you expected to happen:

1. Should Request Permission first
2. Then show the Media Library.

## Reproducible sample code

Here is repo with this issue: https://github.com/ziyoshams/image-picker-issue

**Comment by Jazqa** [comment]
Duplicate of #1187. #1159 assumes the images could be used without a permission, yet the system prompts for a permission if built with the newest SDK.

**Comment by AliUZAR** [comment]
Any solution ?

**Comment by ziyoshams** [comment]
> Any solution ?

See the @Jazqa 's reply, and go to those linked issues. You will see the "solution".

**Comment by shachardevops** [comment]
+1

**Comment by Jazqa** [comment]
This is not stale as far as I know
