### ISSUE TITLE
iOS 13.1 - Error You don't have permission

### ISSUE THREAD

**Issue by dakiquang** [react-native-community/react-native-image-picker#1195]
# Bug

I select a video from the library(ImagePickerManager.launchImageLibrary) and after video file is compressed successfully, response throw "error":"You don't have permission".

Any permission that needed to be added when upgrading into iOS 13?

## Environment info

React native info output:

```bash
 "error":"You don't have permission"
```

Library version: latest
iOS software: 13.1.2

## Steps To Reproduce

1. Use ImagePickerManager.launchImageLibrary and select an video
2. After compress video, the response returns an error object
...

**Comment by dakiquang** [comment]
![image](https://user-images.githubusercontent.com/1046250/66412370-9539f500-ea1f-11e9-8c27-e41cd6d7facb.png)
I think there was a problem with moveItemAtURL

**Comment by matheustimbo** [comment]
I also have the exact same error

**Comment by zacwasielewski** [comment]
This error was already reported here: https://github.com/react-native-community/react-native-image-picker/issues/1179

There's an open pull request to fix it, but it hasn't been merged yet.

**Comment by cawfree** [comment]
Same issue, seems to affect just video.

**Comment by chengsam** [comment]
Though copyItemAtURL works, why was this error thrown?

**Comment by vincentzierigen** [comment]
this is still an error, any updates?

**Comment by Deg5112** [comment]
Can one of the author's either approve https://github.com/zipline/react-native-image-picker/commit/92d77b7a19ff49cd15623be631a657fdfd54faf9 or provide us all with an ETA on when this will be resolved? Thanks!

**Comment by Deg5112** [comment]
I noticed copyItemAtURL does not work.. as i get the following error
```
Error Domain=NSCocoaErrorDomain Code=513 "The operation couldn’t be completed. (Cocoa error 513.)" UserInfo=0x175120 {NSFilePath=/var/mobile/Applications/D83FDFF9-2600-4056-9047-05F82633A2E4/App.app/sounds/Test Tones, NSUnderlyingError=0x117520 "The operation couldn’t be completed. Operation not permitted"}
``` so it doesn't like move or copy

what did fix it for me was changing the definition of the videoUrl --> NSURL *videoURL = [info objectForKey:UIImagePickerControllerMediaURL];

per: https://stackoverflow.com/questions/3439408/nsfilemanager-creating-folder-cocoa-error-513

can we get some confirmations on this?

**Comment by srshah19** [comment]
Facing the same issue. Any updates on when a fix is scheduled to be released?

**Comment by jstettner** [comment]
Can this fix be merged ASAP please.

**Comment by Deg5112** [comment]
guys you can use this for now, it has the fix referenced in https://github.com/react-native-community/react-native-image-picker/issues/1179

"react-native-image-picker": "git+https://github.com/zipline/react-native-image-picker.git",

when the real fix is made on this repo you can always just switch back

**Comment by occrcc** [comment]
ImagePickerManager.m
line 458 
[fileManager removeItemAtURL:videoDestinationURL error:nil];
The perfect solution。

**Comment by yahacom** [comment]
I'm still have this error, any updates here?
Changing ImagePickerManager.m is a solution for now, but it's not good for continuous maintenance. imho

```
iPhone 6s Plus
iOS 13.3.1
```
```
"react-native": "0.61.4",
"react-native-image-picker": "1.1.0",
```

**Comment by jackiewung** [comment]
This error is still occurring
