### ISSUE TITLE
missing fileName and type in iOS after pick a gif 

### ISSUE THREAD

**Issue by franjorub** [react-native-community/react-native-image-picker#1198]
# Bug

## Enviroment

RN 0.59.8
iOS 11, 13

React native info output:
![imagen](https://user-images.githubusercontent.com/24401350/66706011-e38b1480-ecfb-11e9-8978-fec3da0f3666.png)

Library version: 0.28.0

## Steps To Reproduce

1. pick a gif
2. wait a susccess response
...

Describe what you expected to happen:

1. we need the fileName and type for send the image to a server

**Comment by phatmann** [comment]
It makes no sense that this issue was closed. The `type` is still null for a GIF image. It should be "image/gif".

**Comment by roycehe** [comment]
> # Bug
> ## Enviroment
> RN 0.59.8
> iOS 11, 13
> 
> React native info output:
> ![imagen](https://user-images.githubusercontent.com/24401350/66706011-e38b1480-ecfb-11e9-8978-fec3da0f3666.png)
> 
> Library version: 0.28.0
> 
> ## Steps To Reproduce
> 1. pick a gif
> 2. wait a susccess response
>    ...
> 
> Describe what you expected to happen:
> 
> 1. we need the fileName and type for send the image to a server

what's your picker options ?
noData and path  after choose gif images

**Comment by JungHsuan** [comment]
> > # Bug
> > ## Enviroment
> > RN 0.59.8
> > iOS 11, 13
> > React native info output:
> > ![imagen](https://user-images.githubusercontent.com/24401350/66706011-e38b1480-ecfb-11e9-8978-fec3da0f3666.png)
> > Library version: 0.28.0
> > ## Steps To Reproduce
> > 
> > 1. pick a gif
> > 2. wait a susccess response
> >    ...
> > 
> > Describe what you expected to happen:
> > 
> > 1. we need the fileName and type for send the image to a server
> 
> what's your picker options ?
> noData and path after choose gif images

same here. no data for gif images
