### ISSUE TITLE
UI API called on a background thread

### ISSUE THREAD

**Issue by cmmartin** [react-native-community/react-native-image-picker#1199]
Calling `ImagePicker.launchImageLibrary` causes XCode to throw the below error (or warning?). 

```
Main Thread Checker: UI API called on a background thread: -[UIImagePickerController init]
PID: 3542, TID: 802234, Thread name: (none), Queue name: com.facebook.react.ImagePickerManagerQueue, QoS: 0
```

It doesn't seem to crash the app and everything is working as expected. I'm just concerned this might be an issue down the road and curious if anyone else has any insight into why this is happening or whether we can safely ignore it?

```
"react-native": "0.60.5",
"react-native-image-picker": "^1.0.2",
```

**Comment by stefanocdn** [comment]
@cmmartin I have those messages in Xcode too. Is it very slow for you too?

**Comment by cmmartin** [comment]
@stefanocdn I'm asking for permission manually ahead of time using [react-native-permissions](https://github.com/react-native-community/react-native-permissions). It is slow to load the camera/gallery at times though

**Comment by SmartArray** [comment]
I have created a pull request (#1205) which solves this issue

**Comment by kmh0237** [comment]
This issue is very bad, it waits like 5-7 seconds before opening camera.  https://github.com/react-native-community/react-native-image-picker/pull/1265 fixes it, please merge it
