### ISSUE TITLE
Crashing after selecting image

### ISSUE THREAD

**Issue by luandro** [react-native-community/react-native-image-picker#1201]
# Bug

As soon as image is selected either from folder or from camera the app restarts itself.

## Environment info

- library version: 1.0.1
- react-native 0.60.1
- Android 6.0 - Blu Tank xtreme 4

## Steps To Reproduce

Can only reproduce on this specific model.

**Comment by fredikey** [comment]
i had this bug too
library version: 1.4.1
react-native 0.60.4
ios  13.1

**Comment by mark-slepkov** [comment]
I have this bugl on Samsung SM-A300F. It works ok on my Xiaomi.

**Comment by fredikey** [comment]
https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md

**Comment by edanedison** [comment]
I noticed this on IOS a few days ago after updating to 13.0 and an Xcode update. I had to re-add the permissions to the plist as they had gone astray for some reason....

```
	<key>NSPhotoLibraryUsageDescription</key>
	<string>$(PRODUCT_NAME) would like access to your photo gallery to change your profile picture</string>
	<key>NSCameraUsageDescription</key>
	<string>$(PRODUCT_NAME) would like to use your camera to change your profile picture</string>
```

**Comment by nemanjam** [comment]
Are they are going to fix this bug or this lib is abandoned?

**Comment by luandro** [comment]
I'm having the bug on Android, so the solution above doesn't resolve.

**Comment by NikitaNeganov** [comment]
I'm also having this on Android
react-native: 0.59.0
react-native-image-picker: ^0.28.1
Xiaomi Redmi 7 (Android 9, MIUI Global 10.3.4)

Works perfectly on ios - iPhone 6s 13.1.2 - 13.1.3

**Comment by bbored** [comment]
I get this bug randomly on android: when taking a photo the app restart
