### ISSUE TITLE
Multilanguage-Support

### ISSUE THREAD

**Issue by jschenkDD** [react-native-community/react-native-image-picker#1203]
# Feature Request

It would be very useful to be able to localize all strings within component. 'Use Photo', 'Retake' and 'Cancel' within camera view can`t be translated.

## Why it is needed

Multilanguage-Support

## Possible implementation

Props for: 

- UsePhotoTitle
- RetakeTitle
- CancelUsePhotoTitle

**Comment by Phecda** [comment]
#211 may be helpful.
It would be better if this is mentioned in README.
