### ISSUE TITLE
[Android]Set photo, crash when video is selected

### ISSUE THREAD

**Issue by 775822253** [react-native-community/react-native-image-picker#1208]
On Android devices, when the mediatype is set to photo, video should not appear, but video appears. Click OK after selection, and the app crashes.

**Comment by CxxyLucifer** [comment]
same question

**Comment by eramudeep** [comment]
same question

**Comment by TwilightOwl** [comment]
The problem still exists!
react-native-image-picker 3.1.3
react-native 0.61.5
Honor 10
Android 10
