### ISSUE TITLE
 crash when video is selected on emulator and device (Android)

### ISSUE THREAD

**Issue by eramudeep** [react-native-community/react-native-image-picker#1210]
# Bug

app is crashing when trying to select the video from the gallery on the emulator. but worked if i record a video instead of browsing. 

on a real device, it nither works for browsing and recording.
**my code :**
`const options = {
      title: "Video Picker", 
      takePhotoButtonTitle: "Take Video...",
      mediaType: "video"
    };
    // @ts-ignore
    try {
      ImagePicker.showImagePicker(options, response => {
        if (response.uri) {
          this.setState({
            videoUrl: response.uri
          });
        }
      });
    } catch (error) {
      console.log(error)
    }`

### even try-catch not helped
i tried with try-catch but i didn't goes to the catch block.

### Carsholytics

> Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/27/ORIGINAL/NONE/1581774611 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F27/ORIGINAL/NONE/1581774611} }} to activity {com.yapstars/com.yapstars.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude

**Comment by Josin22** [comment]
same error

**Comment by eramudeep** [comment]
> 
> 
> same error

try on real device. and android >7
might help

**Comment by hiepnm** [comment]
same error

**Comment by Javimtib92** [comment]
same error here, for Android Q and it's due to the new way it handles files

**Comment by kamwoz** [comment]
same problem on Android 10

**Comment by vitorverasm** [comment]
Same problem on Android 10

**Comment by dev-pacific22** [comment]
Same error and Android 10 emulator
