### ISSUE TITLE
React Native Image Picker not working after building APK from android studio.

### ISSUE THREAD

**Issue by assadakramiintellect** [react-native-community/react-native-image-picker#1213]
Hi everyone.

In my dev environment, react-native-image-picker works perfectly but when I build APK from the android studio it does not launch my camera or access my gallery.

Any idea what might be the problem.

**Comment by Jeroentje61** [comment]
I am having the same issue.

**Comment by Jeroentje61** [comment]
@assadakramiintellect I solved the issue.
The problem for me was the fact that I added     
```
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
to my debug AndroidManifest.xml and not to my main AndroidManifest.xml.

Please add the permissions to your main AndroidManifest.xml and generate a new APK. Hopefully this will fix it for you. 

Related Issue: [Issue #845](https://github.com/react-native-community/react-native-image-picker/issues/845)

**Comment by assadakramiintellect** [comment]
@Jeroentje61 Thanks man you just saved my day. The issue has been resolved. Thanks again. 

**Closing this issue.**
