### ISSUE TITLE
App crashes when raw image (.dng) is picked up from the gallery.

### ISSUE THREAD

**Issue by kamlesh1000** [react-native-community/react-native-image-picker#1214]
**File Description:**
1. File Dimen: 4016*3008
2. File Size: 24.70 MB
3. File Type: .dng

### **React-native environment:**
**Packages**:
    "react-native": "0.61.2",
    "react-native-image-picker": "^1.1.0",
**System:**
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 2.42 GB / 7.92 GB
**Binaries:**
    Node: 12.3.1 
    Yarn: 1.16.0 
    npm: 6.9.0

**Comment by Cesar7123** [comment]
Same issue
