### ISSUE TITLE
Help needed: How can I upload the image using Axios?

### ISSUE THREAD

**Issue by TheMisir** [react-native-community/react-native-image-picker#1215]
# Question

I want to upload the picked image using Axios but I get `Network Error` without any additional error description. I researched and get that I did something wrong but did not found what is it?

Environment:

```
OS: Android 9
Device: Xiaomi Mi A1
App Stage: Development
React Native: 0.61
```

The code I'm trying to test is:

```js
var data = new FormData();
data.append('image', {
  uri: image.uri,
  type: image.type,
  name: image.fileName
});

var response = await axios.post('my-upload-endpoint', data);
```

Then I get `NetworkError` (also, the request is not received by the server too), 🤕 please help me if you know what I did wrong.
Thanks in advance!

**Comment by TheMisir** [comment]
Fixed, it was my mistake.

**Comment by login2tech** [comment]
what the issue was? I am also getting the same.

**Comment by TheMisir** [comment]
@login2tech I tried to send request using uninitialized Axios instance (without baseUrl defined).

```js
var api = axios.create({
  baseUrl: 'https://api.site.com/api/'
});
...
axios.post('upload', formData); // changing axios with api fixed my issue
```
