### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by issamabdelkrim** [react-native-community/react-native-image-picker#1216]
hello everyone 
After take a picture with camera my app crash in ios and android with one telephone witch version of android is 7 . 
In ios i have this error after i validate the picture "undefined is not an object (evaluating 'n.camera')" 
Can someone plz help me to fix this bug . 
Here my code 
   ImagePicker.launchCamera(
                                    {
                                      maxWidth: 1200, //speeds up compressImage to almost no time
                                      maxHeight: 1200,
                                      mediaType: "photo"
                                    },
                                    (res) => {

} )

**Comment by AmalaLiza** [comment]
@issamabdelkrim Please check this comment. This might help you :)
[Solution](https://github.com/react-native-community/react-native-image-picker/issues/1201#issuecomment-543795795)

**Comment by issamabdelkrim** [comment]
@AmalaLiza  i fixed the bug in ios it was a bug in my code . but i have problem with a phone Logitech ( android 7.0.0 ) app reload after record video or pick picture .

**Comment by JosManMx** [comment]
I have a similar issue with the lasts releases; this solved for me:

check the imports; if you have:

`import { showImagePicker } from 'react-native-image-picker';`

changed the import `import RNImagePicker from 'react-native-image-picker';`
and implement in this way: `RNImagePicker.showImagePicker(options, (response) => {})`

**Comment by issamabdelkrim** [comment]
@JosManMx always the same error 
When i logcat it show me this error : 
reactinstancemanager.ctor()

**Comment by cinder92** [comment]
same issue here, any other lib?
