### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by AmareshNeelgar** [react-native-community/react-native-image-picker#1220]
# Bug

App crashes after select and validate image or video.

Environment
Version 1.0.1

**Comment by JosManMx** [comment]
I have a similar issue with the lasts releases; this solved for me:

check the imports; if you have:

`import { showImagePicker } from 'react-native-image-picker';`

changed the import `import RNImagePicker from 'react-native-image-picker';`
and implement in this way: `RNImagePicker.showImagePicker(options, (response) => {})`

**Comment by cinder92** [comment]
@JosManMx your solution didn't work, same issue

**Comment by mferhatkeles** [comment]
hello @AmareshNeelgar, ı got same error and tried codes below and it worked for me. you can try it. hopefully it will work

///////these codes to pick image

` ImagePicker.showImagePicker({noData:true, mediaType:'photo'}, (response) => {
      console.log('Response = ', response);
    
      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        const source = { uri: response.uri };
    
        // You can also display the image using data:
        // const source = { uri: 'data:image/jpeg;base64,' + response.data };
    
        this.setState({
          avatarSource: response.uri,
        });
      }
    });`



////these codes to show ımage

` <Image source={{uri : this.state.avatarSource}} style={{height:50, width:100}} />`

**Comment by NestedLooper** [comment]
Add the missing permissions to your plist file. Info [here](https://github.com/react-native-community/react-native-image-picker/issues/1201#issuecomment-543795795).

**Comment by Anujmoglix** [comment]
App crash in react-native-cli: 2.0.1
react-native: 0.60.5
 "react-native-image-picker": "^2.3.0",

**Comment by bwaghmare** [comment]
I am facing a similar issue

https://stackoverflow.com/questions/65814849/react-native-app-crash-when-returning-from-camera-on-android
