### ISSUE TITLE
[Android] How to open gallery/camera immediately after accept permissions?

### ISSUE THREAD

**Issue by anniewey** [react-native-community/react-native-image-picker#1225]
# Question

How to open gallery/camera directly after accept camera and storage permissions? In Android, upon accepting permissions, the dialog dismissed and not showing gallery/camera. I need to tap again to launch the gallery/camera. I'm using `ImagePicker.launchCamera` and `ImagePicker.launchImageLibrary`.

**Comment by bmbmjmdm** [comment]
I'm not sure how you can do it directly from those calls if you don't have permission already, but one work around would be to add a Permissions check in your button click handler. That can check if you have the permissions already, prompting the user if you dont, and awaiting their response to then open the camera/image library. Or if you already have the permissions, skipping straight to opening the camera/image library.

**Comment by anniewey** [comment]
@bmbmjmdm yeah i'm using that workaround for now, just thinking if there's another better way using this library. thanks tho
