### ISSUE TITLE
iOS permissions not asked, and crash on ImagePicker being null

### ISSUE THREAD

**Issue by kyhnlbyrk** [react-native-community/react-native-image-picker#1227]
# Bug
on android everything is working smooth, but in ios permissions are not asked even though I added the permissions to the info.plist. Then, when I try to open the image picker the app crashes with the exception of null pointer. `ImagePicker.showImagePicker` in this line ImagePicker is null.. 
## Environment info

React native info output:

```bash
   React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
      Memory: 215.69 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.2 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 22.0.1, 23.0.1, 24.0.2, 26.0.0, 26.0.1, 27.0.3, 28.0.1, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

Library version: 0.28.0

## Steps To Reproduce

1. start a new project
2. install this library
3. call ImagePicker
4. run on ios 13
5. crash

Describe what you expected to happen:

1. Permissions should be asked
2. camera should open

## Reproducible sample code
`import ImagePicker from 'react-native-image-picker';` I inserted the library with this,
```bash   
const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true,
      },
      cancelButtonTitle: 'Kapat',
      takePhotoButtonTitle: 'Fotoğraf çek..',
      takePhotoButtonTitle: 'Fotoğraf çek..',
      chooseFromLibraryButtonTitle: 'Galeriden seç..',
      title: 'Seç'
    };

    ImagePicker.showImagePicker(options, response => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        this.uploadImage(response);

      }
    });
```

> *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: null is not an object (evaluating 'o.showImagePicker')', reason: 'Unhandled JS Exception: null is not an object (evaluating 'o.showImagePicker'), stack:
showImagePicker@809:546
value@940:2260
value@<null>:<null>

above is the exception I got

**Comment by kyhnlbyrk** [comment]
I just find out the problem. 

`react-native link` did not link the library, so the mage picker lib did not build with the app. Thats why I as getting null pointer exception because there was no lib.

What I did is manually add the library. 

If someone has encountered this problem try manually add the lib

**Comment by bellsenawat** [comment]
@kyhnlbyrk so what is your solution for this because I found this bug on my App too.

**Comment by danielle-Cman** [comment]
My solution is add privacy in Info.plist
```
<key>NSCameraUsageDescription</key>
	<string>Access to take a photo by camera</string>
<key>NSAppleMusicUsageDescription</key>
	<string>Access to pick a photo</string>
<key>NSPhotoLibraryUsageDescription</key>
	<string>Access to pick a photo</string>
```

**Comment by alishashaw439** [comment]
Correction : 
import * as ImagePicker from 'react-native-image-picker';
