### ISSUE TITLE
Installation clarification 

### ISSUE THREAD

**Issue by ilibilibom** [react-native-community/react-native-image-picker#1230]
Hi 
I'm new to react-native and mobile development. 
I'm trying to understand this Android  installation step: 

```
buildscript {...}
allprojects {...}

/**
  + Project-wide Gradle configuration properties
  */
ext {
    compileSdkVersion   = 27
    targetSdkVersion    = 27
    buildToolsVersion   = "27.0.3"
}
```

what should I edit here? 
I don't have: 
```
buildscript {...}
allprojects {...}
``` 

Also, in IOS installation, where do I edit this alert: 
```
$(PRODUCT_NAME) would like access to your photo gallery to change your profile picture
```

**Comment by niloufarMakhzani** [comment]
Hi 
For iOS you have to add NSPhotoLibraryUsageDescription in your info.plist and you can write whatever you want for the description.
