### ISSUE TITLE
launchImageLibrary is always returning error: "You don’t have permission."

### ISSUE THREAD

**Issue by jeevankumarkanuganti** [react-native-community/react-native-image-picker#1231]
# Bug
The package is returning error: "You don’t have permission." 
I had verified, the app has permission but still shows error.

Issue is with launchImageLibrary 

## Environment info
"react-native": "^0.59.10",
"react-native-image-picker": "^0.26.10",

**Comment by bjb118** [comment]
Did you figure out how to fix this?
