### ISSUE TITLE
Android app reloads without crash after taking picture

### ISSUE THREAD

**Issue by NikitaNeganov** [react-native-community/react-native-image-picker#1232]
# Bug

After taking a picture on android device, app relaunches without any errors.

Library version 0.28.1, install with pods.

### Important

As I've seen in #1192 this does only happen to Redmi phones, tested on Redmi 6A, Redmi 7. Seems to not have happened to Redmi 7 Note

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 583.77 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.19.2 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 23, 26, 28, 29
        Build Tools: 28.0.3, 29.0.0
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1
      react-native: 0.59.9
```

Library version: 0.28.1

## Steps To Reproduce

1. Launch the app
2. Open picker
3. Take a photo
4. Relaunch
...

Describe what you expected to happen:

1. Take a picture and then process it
2.

## Reproducible sample code

Image picker config
```
ImagePicker.showImagePicker(
      {
        title: label,
        storageOptions: {
          skipBackup: true,
          path: 'images',
          cameraRoll: true,
        },
        permissionDenied: {
          title: translate('auth_signUp_cameraField_title'),
          text: translate('auth_signUp_cameraField_description'),
          reTryTitle: translate('auth_signUp_cameraField_tryAgain'),
          okTitle: translate('auth_signUp_cameraField_cancel'),
        },
        mediaType: 'photo',
        quality: 0.8,
        noData: true,
        maxWidth: 2000,
        maxHeight: 2000,
      },
      handleFileChange,
    );
```

## Possible solutions

- largeHeap - didn't work
- android permissions - all set up, sometimes it doesn't relaunch, couldn't figure out if there's a pattern
- jetify - won't work, project also has stale libraries that won't support androidx even with jetifier

**Comment by tautvilas** [comment]
I have the smae problem. I get this error in logcat after taking the picture. Maybe it is related.

`2019-11-27 12:05:26.554 12666-12767/? E/ImageUtils: decodeOrientation() - Fail to access file /root/storage/emulated/0/Pictures/image-747bf7e8-65a5-4f02-bc03-42d16abb1cc4.jpg
    java.io.FileNotFoundException: /root/storage/emulated/0/Pictures/image-747bf7e8-65a5-4f02-bc03-42d16abb1cc4.jpg (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.oneplus.media.ImageUtils.decodeOrientation(ImageUtils.java:1665)
        at com.oneplus.camera.io.PhotoSaveTask.onPrepareMediaStoreValues(PhotoSaveTask.java:533)
        at com.oneplus.camera.io.MediaSaveTask.insertToMediaStore(MediaSaveTask.java:256)
        at com.oneplus.camera.io.PhotoSaveTask.insertToMediaStore(PhotoSaveTask.java:366)
        at com.oneplus.camera.io.FileManagerImpl$FileManageerThread$1.handleMessage(FileManagerImpl.java:515)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by tautvilas** [comment]
Related open issues: #1201 #1185 #1188 #1192

**Comment by tautvilas** [comment]
I digged a bit deeper and seems that the issue is related to memory issues on some devices. According this thread there might not be an easy fix https://stackoverflow.com/questions/10176550/android-system-stops-application-when-launching-media-intent

**Comment by tautvilas** [comment]
There is a nice discussion about the same issue in another lib here:

https://github.com/ivpusic/react-native-image-crop-picker/issues/955

It looks that the best solution offered there is to implement your own camera screen with interface and avoid native camera intent altogether.

**Comment by RodneyOnyi** [comment]
> I digged a bit deeper and seems that the issue is related to memory issues on some devices. According this thread there might not be an easy fix https://stackoverflow.com/questions/10176550/android-system-stops-application-when-launching-media-intent

I tried deleting items to clear memory then took the photo again, seems to work fine. This is such an inconvenience

**Comment by arifinoid** [comment]
Same here, this issue still occurs on low device android
