### ISSUE TITLE
open failed: EACCES (Permission denied) on Android 29 every time (I am certain it's setup properly) - works in Android 28

### ISSUE THREAD

**Issue by acoutts** [react-native-community/react-native-image-picker#1233]
## Environment info
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 2.16 GB / 61.90 GB
    Shell: 5.4.2 - /bin/zsh
  Binaries:
    Node: 13.2.0 - ~/.nvm/versions/node/v13.2.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v13.2.0/bin/npm
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 23.0.1, 25.0.0, 28.0.3, 29.0.0, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```
Library version: 
1.1.0

## Steps To Reproduce

```typescript
ImagePicker.launchImageLibrary(
  {
    title: "Select QR Code",
    storageOptions: {
      skipBackup: true,
      path: "images",
    },
    mediaType: "photo",
  },
  response => {
    console.log("Response = ", response)
    if (response.didCancel) {
      console.log("User cancelled image picker")
    } else if (response.error) {
      console.log("ImagePicker Error: ", response.error)
      Alert.alert("Error", response.error)
    } else {
      // process image here
    }
  },
)
```

The system permission dialogue is prompted and accepted. The proper permissions are without certain given. The app has the following in AndroidManifest:
```xml
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.READ_CONTACTS" />
```
But despite this the library returns a permission denied error every time like this:
```
/storage/emulated/0/DCIM/Camera/IMG_20191125_203629.jpg: open failed: EACCES (Permission denied)
```

Note: everything works as expected in the simulator but the permission error happens on a real device.

The simulator is running Android 28 and device is running Android 29 - is this an issue in the latest Android API version?

**Comment by acoutts** [comment]
Seems this is due to a change in Android 29 - found some more info in this stackoverflow post:

> [Starting with Android 11](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage) the storage permission is getting revoked and developers would need to consider alternative ways of accessing the storage they need either through [SAF](https://developer.android.com/guide/topics/providers/document-provider) or [Media Store](https://developer.android.com/reference/android/provider/MediaStore.Files). For the time being, you can carry on using what you’re using by adding the following in your manifest within the application tags:
> 
> android:requestLegacyExternalStorage="true"
> You might want to consider changing your minSDK to 19 and use getExternalFilesDir() to get a path that doesn’t require any permissions.

https://stackoverflow.com/questions/58430070/android-apiv29-filenotfoundexception-eacces-permission-denied


I was able to get react-native-image-picker working again by adding `android:requestLegacyExternalStorage="true"` to my `  <application ... >` tag in AndroidManifest.xml.

**Comment by Arjunmore6673** [comment]
for android:requestLegacyExternalStorage="true" 
you also need to upgrade compile SDK to 29
{
        buildToolsVersion = "29.0.0"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
}

**Comment by figureai** [comment]
see to here: [](https://developer.android.com/training/data-storage/use-cases)
```
<manifest ... >
<!-- This attribute is "false" by default on apps targeting
     Android 10 or higher. -->
  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
```

**Comment by Jackyaung** [comment]
@figureai this one doesn't work on my code, I added this line, and got a error :   failed processing manifest.

**Comment by sayem314** [comment]
@Jackyaung this is how it should be done

![Screenshot from 2020-10-09 22-02-27](https://user-images.githubusercontent.com/14138401/95605835-53e98480-0a7b-11eb-9070-3d8a41dca4a6.png)

![Screenshot from 2020-10-09 22-03-11](https://user-images.githubusercontent.com/14138401/95605849-5815a200-0a7b-11eb-8ef9-622bfdf36caa.png)

__* Note that this is a temporary solution. In SDK 30 or newer it won't work.__

![android diff](https://user-images.githubusercontent.com/14138401/95607179-31586b00-0a7d-11eb-9c8f-5c46d6bfaef5.png)

**Comment by HauLuu** [comment]
The thing is. I upgraded the target API to 29, added [android:requestLegecyExternalStorage="true"] to AndroidManifest.xml

Then I get the error requestLegecyExternalStorage not found. Have your guys ever run into this issue like me?

**Comment by lfoliveir4** [comment]
> see to here: https://developer.android.com/training/data-storage/use-cases
> 
> ```
> <manifest ... >
> 
>   <application android:requestLegacyExternalStorage="true" ... >
>     ...
>   </application>
> </manifest>
> ```

solved

**Comment by hdJerry** [comment]
> Seems this is due to a change in Android 29 - found some more info in this stackoverflow post:
> 
> > [Starting with Android 11](https://developer.android.com/training/data-storage/files/external-scoped#opt-out-of-scoped-storage) the storage permission is getting revoked and developers would need to consider alternative ways of accessing the storage they need either through [SAF](https://developer.android.com/guide/topics/providers/document-provider) or [Media Store](https://developer.android.com/reference/android/provider/MediaStore.Files). For the time being, you can carry on using what you’re using by adding the following in your manifest within the application tags:
> > android:requestLegacyExternalStorage="true"
> > You might want to consider changing your minSDK to 19 and use getExternalFilesDir() to get a path that doesn’t require any permissions.
> 
> https://stackoverflow.com/questions/58430070/android-apiv29-filenotfoundexception-eacces-permission-denied
> 
> I was able to get react-native-image-picker working again by adding `android:requestLegacyExternalStorage="true"` to my ` <application ... >` tag in AndroidManifest.xml.
> 
> But, this is only a temporary fix. I'm not experienced enough to submit a PR but hopefully this information helps someone who can upgrade the library for Android 29 and future releases.

It worked for me, Thanks.

**Comment by Michael-kyalo** [comment]
android:requestLegacyExternalStorage="true" 

doesn't work for me anyone with an alternative

**Comment by catalin3003** [comment]
> android:requestLegacyExternalStorage="true"
> 
> doesn't work for me anyone with an alternative

@Michael-kyalo check what @HauLuu suggested
https://github.com/react-native-image-picker/react-native-image-picker/issues/1233#issuecomment-711135457

It worked for me.

**Comment by siddharth-panda** [comment]
Setting `android:requestLegacyExternalStorage="true"` in the <application> tags inside  AndroidManifest.xml file works for me

**Comment by oskarhertzman** [comment]
I Recommend writing to .DocumentDirectyPath, it will only require media storage permissions, which eliminates the problem, example:

 ```
RNFS.readDir(RNFS.DocumentDirectoryPath).then(res => {

      const outputImage = YOUR_PATH_TO_IMAGE

      const newPath = `${RNFS.DocumentDirectoryPath}/Image.jpg`;

      RNFS.copyFile(outputImage, newPath)
        .then(() => {
          const finalPath = getPlatformURI(newPath);

          RNFS.exists(finalPath).then(() => {
            Share.open({ title, message, subject, url: finalPath });
          })
            .catch(err => console.log(err));
        })
        .catch(err => console.log(err));

    }).catch(err => console.log(err));
```

**Comment by josephgodwinkimani** [comment]
> Setting `android:requestLegacyExternalStorage="true"` in the tags inside AndroidManifest.xml file works for me

https://developer.android.com/about/versions/11/privacy/storage#maintain-compatibility-android-10
