### ISSUE TITLE
build error: package com.android.annotations does not exist

### ISSUE THREAD

**Issue by Liqiankun** [react-native-community/react-native-image-picker#1235]
# Question
After Linking react-native-image-picker. Run android project. Error shows up:
```
package com.android.annotations does not exist
import android.support.annotation.NonNull;
                                 ^
```
## Environment info

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 50.20 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.2
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.6.1 => 16.6.1 
    react-native: ^0.57.8 => 0.57.8 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native: 0.60.5
```
## Package.json
```
    "react": "16.6.1",
    "react-native": "^0.57.8",
    "react-native-image-picker": "^1.1.0",
```

**Comment by Liqiankun** [comment]
In my case, my android project doesn't migrate to AndroidX. My solution is converting `react-native-image-picker` back with reverse-jetify mode.
* npm install --save-dev jetifier
* npx jetify -r
* Set `react-native-image-picker`  `useAndroidX` and `enableJetifier` to false under `gradle.properties` file 
```
android.useAndroidX=false
android.enableJetifier=false
 ```

Here is about  `reverse-jetify` mode
>Maybe you are in the position where you must not migrate to AndroidX yet. But your libraries have started to migrate and they ship AndroidX native Java code.
You can convert them back with reverse-jetify mode.
Follow the instructions from above to convert to AndroidX, but add the -r flag to the npx jetify call.

**Comment by piyushrajput45** [comment]
react-native build error:- package android.support.annotation does not exist

Go to the terminal and open your project

Step 1- npm install jetifier

You can use yarn

Step 2- npx jetify

Step 3- npx react-native run-android
