### ISSUE TITLE
launchCamera and launchImageLibrary work only for the first time. 

### ISSUE THREAD

**Issue by wedusa** [react-native-community/react-native-image-picker#1236]
# Bug

`2019-11-28 18:03:32.900256+0400 myappname[515:59647] Warning: Attempt to present <UIImagePickerController: 0x159016c00> on <RCTModalHostViewController: 0x15a70ca30> whose view is not in the window hierarchy!`

## Environment info

React native info output:

    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.77 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 1.0.1

## Steps To Reproduce

1.Launch app
2.Try to take photo from camera/library - OK
3.Try to take photo from library/camera - camera open, but photo don't not change and library don't launch
4. Again try to take photo from camera/library - they don't launch!

## Reproducible sample code
```

 _onImageSelected(response) {
            if (response.didCancel) {
                console.log('User cancelled image picker');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            } else {
                console.warn(response.uri);
                api.postUserImage(response.uri).then((r) => {
                }).catch(e => console.warn(e))
                this.reloadOwnProfile()
            }
        }

    openNativeImageCamera(){
        ImagePicker.launchCamera(
          {
            quality: 1.0,
            allowsEditing: true,
            noData: true,
            storageOptions: {
                skipBackup: true,
                path: 'images',
            },
          },
      (response) => {this._onImageSelected(response);}
        );
    }

    openNativeImageLibrary(){
        ImagePicker.launchImageLibrary(
          {
            quality: 1.0,
            allowsEditing: true,
            noData: true,
            storageOptions: {
                skipBackup: true,
                path: 'images',
            },
          },
      (response) => {this._onImageSelected(response);}
        );
    }
```

**Comment by chai86** [comment]
Same issue. Sometimes I can select a picture from the library, sometimes it freezes and i can't select anything (e.g. album)

**Comment by bellsenawat** [comment]
@wedusa After you select images error will occurred and permission for access is show up right ?

**Comment by Rob117** [comment]
This is definitely 100% still happening. @chai86 Did you manage to resolve this?

**Comment by KristineTrona** [comment]
Same problem here

**Comment by marcoautiero** [comment]
Same problem here...very bad
