### ISSUE TITLE
Choosing image in library closes my app

### ISSUE THREAD

**Issue by kresogalic8** [react-native-community/react-native-image-picker#1237]
I followed your instructions for adding image picker, and when I open a image library, i choose the image and my app closes.

Here's the code I am using:

```
const takeShot = () => {
  ImagePicker.showImagePicker(options, response => {
    console.log('Response = ', response);

    if (response.didCancel) {
      console.log('User cancelled image picker');
    } else if (response.error) {
      console.log('ImagePicker Error: ', response.error);
    } else if (response.customButton) {
      console.log('User tapped custom button: ', response.customButton);
    } else {
      const source = {uri: response.uri};
      console.log(source);
    }
  });
};

**Comment by LuisRodriguezLD** [comment]
I am guessing iOS? Did you add the descriptions to your Info.plist?
```
<key>NSPhotoLibraryUsageDescription</key>
<string>$(PRODUCT_NAME) would like access to your photo gallery to change your profile picture</string>
<key>NSCameraUsageDescription</key>
<string>$(PRODUCT_NAME) would like to use your camera to change your profile picture</string>
```

**Comment by NikitaNeganov** [comment]
If it is android, does that look similar to #1201 #1185 #1188 #1192 #1232 ?

**Comment by vishalnarkhede** [comment]
@kresogalic8 I had the same issue. As recommended by @LuisRodriguezLD , steps given here fixed it for me - https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md#ios

**Comment by bellsenawat** [comment]
@vishalnarkhede After you edit info.plist what the next step I can't fixed this bug. Thanks :)

**Comment by tbsphpdev** [comment]
> @kresogalic8 I had the same issue. As recommended by @LuisRodriguezLD , steps given here fixed it for me - https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md#ios

The link you provided is not found!
