### ISSUE TITLE
Access Image from iColud and drive

### ISSUE THREAD

**Issue by gauravsbagul** [react-native-community/react-native-image-picker#1240]
How to access images from iCloud and google drive and photo library in ios and android.
I want to access images an videos from iCloud and google drive. 
`var options = {
			title: 'Capture Image',
			mediaType: 'image',
			path: 'image',
			quality: 1
		};
		ImagePicker.launchImageLibrary(options, response => {
console.log("TCL: CreatePostFeed -> selectImage -> response", response)
			if (response.didCancel) {
				console.log('User cancelled image picker');
			} else if (response.error) {
				console.log('ImagePicker Error: ', response.error);
			} else if (response.customButton) {
				console.log('User tapped custom button: ', response.customButton);
			} else {
					this.setState({
						imageUriArray: [...this.state.imageUriArray, response]
					});
				 
			}
		});
	}`

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-06 at 14 08 02](https://user-images.githubusercontent.com/25247251/70308738-eacd2b00-1831-11ea-8dfe-fc4aa4925188.png)

**Comment by Pavaneshpratap** [comment]
is there any way to get images from google drive ?
