### ISSUE TITLE
[Android]App crash when select a damaged png image

### ISSUE THREAD

**Issue by XingtianXin** [react-native-community/react-native-image-picker#1244]
# Bug
App always crash when you select a damaged png picture from the gallery.

## Environment info
Xiaomi 8  (Android: 9.0)
"react-native": "0.59.10",
"react-native-image-picker": "0.28.0",

React native info output:

 E AndroidRuntime: FATAL EXCEPTION: main
 E AndroidRuntime: Process: com.homecredit.hccn.hcpay.mapp.debug, PID: 12480
 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.miui.gallery.open/raw//storage/emulated/0/mapp/5a6abc2e-5a35-4c28-9144-b7ed2938fa71-dcb90fdc-3956-4fb5-9a6e-3846ca8a31ae.png typ=image/png flg=0x1 }} to activity {com.homecredit.hccn.hcpay.mapp.debug/com.adastragrp.hccn.hcpay.mapp.BaseRnActivity}: java.lang.NullPointerException: Attempt to read from field 'java.io.File CR.b' on a null object reference
 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4312)
 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4356)
 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6606)
 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.io.File CR.b' on a null object reference
 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:45)
 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:2)
 E AndroidRuntime: 	at com.facebook.react.C.a(ReactInstanceManager.java:32)
 E AndroidRuntime: 	at com.facebook.react.n.a(ReactActivityDelegate.java:17)
 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:1)
 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7368)
 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4308)
 E AndroidRuntime: 	... 9 more

Library version: "react-native-image-picker": "0.28.0"

## Steps To Reproduce
app-->select picture from gallery-->a damaged image whick display white in gallery--->app crash

1.
2.
...

Describe what you expected to happen:

1. App not crash, add some exception catch
2.

## Reproducible sample code
ImagePicker.launchImageLibrary(options, response => {
      handleImagePickerResponse(response, handleResponseCallback)
    })

**Comment by anniewey** [comment]
Any update on this issue?

**Comment by anniewey** [comment]
Is there any workaround for this issue?
