### ISSUE TITLE
Error TS2403

### ISSUE THREAD

**Issue by rollsroyc3** [react-native-community/react-native-image-picker#1254]
Curious if anyone has seen this error before?

https://github.com/react-native-community/bob/issues/18

Cross posting because its 2 days before Christmas and hoping to get some 👀

**Comment by rollsroyc3** [comment]
Ended up removing the "typescript" from the list of targets in package.json for `@react-native-community/bob` and that worked. Doubt its the correct long term solution though..

**Comment by frossi91** [comment]
Same issue here.  Suddenly started failing on bitrise right before Xmas break.  Haven't been able to get very far with it yet.
