### ISSUE TITLE
 It should now request permissions before displaying the picker view controller or camera. If permissions have not been granted, the module will return an `error` response. I'll leave it up to you to handle that error and instruct your users to go into settings to enable them. The errors will either be:

### ISSUE THREAD

**Issue by gopinathrpt** [react-native-community/react-native-image-picker#1255]
Hey there. Check out `v0.20.1` that I just published. It should now request permissions before displaying the picker view controller or camera. If permissions have not been granted, the module will return an `error` response. I'll leave it up to you to handle that error and instruct your users to go into settings to enable them. The errors will either be:
`error: Camera permissions not granted` or `error: Photo library permissions not granted`

_Originally posted by @marcshilling in https://github.com/react-native-community/react-native-image-picker/issues/253#issuecomment-230501797_

**Comment by AbdelkhalekESI** [comment]
@gopinathrpt 
Checkout your AndroidManifest.xml and see if it has these lines of code:
```

<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
