### ISSUE TITLE
华为p30调用相机权限显示英文

### ISSUE THREAD

**Issue by lxy910812** [react-native-community/react-native-image-picker#1257]
RN0.59.9版本，在华为P30手机调用相机权限提示英文，怎么解决

**Comment by SiJieMa** [comment]
same problem

**Comment by gitSirzh** [comment]
文档上有 permissionDenied 这个参数的配置
这是我对于英文的配置：
const options = {
            title: '请选择',
            cancelButtonTitle: '取消',
            takePhotoButtonTitle: '拍照',
            chooseFromLibraryButtonTitle: "相册",
            storageOptions: {
                skipBackup: true,
                path: 'images'
            },
           // 去除默认英文权限提示
            permissionDenied: {
                title: '提示',
                text: '请前往应用设置-权限-允许相机权限',
                reTryTitle: '前往设置',
                okTitle: '取消'
            },
        };
