### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by kumold** [react-native-community/react-native-image-picker#1259]
# Bug

In android, image picker asks permission even though it was granted before. And after granted, image picker does not show anything with console error " Permissions weren't granted". Tried in android 10 emulator.

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1. Ask permission before running image picker
2. Run image picker.
3. It asks permission again, and even allowed, it errors out that "no permission granted"
...

Describe what you expected to happen:

1. Do not ask permission, if it is already granted

**Comment by AbdelkhalekESI** [comment]
@kumold 
Checkout your AndroidManifest.xml and see if it has these lines of code:

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by deepankarsandy** [comment]
**ISSUE ON ANDROID 10 DEVICE**
exact response: `error: "/storage/emulated/0/DCIM/Camera/IMG_849.jpg: open failed: EACCES (Permission denied)"`

I've permission keys in Manifest file
`<uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

**Comment by samuelj1323** [comment]
Adding the android:requestLegacyExternalStorage="true" works, I took a wild guess and put it in the <application> part of the AndroidManifest.xml file. It works just fine. The Node.js terminal gives me a lot of text, but it seems to be working.

**Comment by lucaspdude** [comment]
I tried adding the requestLegacyExternalStorage thing in every way i can think of, but i didn't work.
```

<uses-permission android:name="android:requestLegacyExternalStorage="true""/>  doesn't build
<uses-permission android:name="android:requestLegacyExternalStorage='true'"/>  doesn't work
<uses-permission android:name="android:requestLegacyExternalStorage"/>  doesn't work
<uses-permission android:name="android:requestLegacyExternalStorage=true"/> doesn't work
```
Can anyone help me figure it out?

**Comment by negrudev** [comment]
> I tried adding the requestLegacyExternalStorage thing in every way i can think of, but i didn't work.
> 
> ```
> 
> <uses-permission android:name="android:requestLegacyExternalStorage="true""/>  doesn't build
> <uses-permission android:name="android:requestLegacyExternalStorage='true'"/>  doesn't work
> <uses-permission android:name="android:requestLegacyExternalStorage"/>  doesn't work
> <uses-permission android:name="android:requestLegacyExternalStorage=true"/> doesn't work
> ```
> 
> Can anyone help me figure it out?

Add it to `<application>` tag

**Comment by benjamin-daniel** [comment]
check out https://github.com/react-native-community/react-native-permissions and @deepankarsandy comment

**Comment by omeshkumarfso** [comment]
Add these both permission of read and write, to solve this issue

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />`

Add this below line in Application tag
`android:requestLegacyExternalStorage="true"`

**Comment by beauhsia** [comment]
Somehow I did everything described above (added the android:requestLegacyExternalStorage="true"), and added all of the required permissions, but my app still can't access my images on my device. Are there any other person experiencing the same thing? The picture of my AndroidManifest.xml file is attached. 
![image](https://user-images.githubusercontent.com/31454959/100160142-e1363c00-2e63-11eb-915b-e8c3e1b99aa9.png)

**Comment by gopikrishnagurram** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.awesomeproject">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />                                               
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>


Added  **android:requestLegacyExternalStorage="true"** to the application tag, still facing same issue. Please help me if anyone knows hot to fix

**Comment by SohaibKtb** [comment]
still the same error: {"errorCode": "permission"}

**manifest:**
```
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />

    <!-- Include this only if you are planning to use the microphone for video recording -->
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:requestLegacyExternalStorage="true">
```
package.json: 

```
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-image-picker": "^3.0.0",
```

**the error occures when I am calling this function:**
```
launchCamera(options, (e) => { console.log(e)
```

any solution?

**Comment by ravirajn22** [comment]
What `options` are you using?

**Comment by SohaibKtb** [comment]
@ravirajn22 
these are the options: 
```
let options = {
                includeBase64: true,
                quality: 0.5,
                videoQuality: 'high',
                mediaType: 'photo',
                saveToPhotos: true
            };
```

**Comment by ravirajn22** [comment]
From the docs

> Image/video captured via camera will be stored in temporary folder so will be deleted any time, so don't expect it to persist. Use saveToPhotos: true (default is false) to save the file in the public photos. saveToPhotos requires WRITE_EXTERNAL_STORAGE permission on Android 28 and below (You have to obtain the permission, the library does not).

So you have to obtain WRITE_EXTERNAL_STORAGE using built in react-native permissions or some third party library

**Comment by SohaibKtb** [comment]
@ravirajn22 Thank you, I got it.

**Comment by omeshkumarfso** [comment]
> Somehow I did everything described above (added the android:requestLegacyExternalStorage="true"), and added all of the required permissions, but my app still can't access my images on my device. Are there any other person experiencing the same thing? The picture of my AndroidManifest.xml file is attached.
> ![image](https://user-images.githubusercontent.com/31454959/100160142-e1363c00-2e63-11eb-915b-e8c3e1b99aa9.png)

if you are not using real device then try on real device. And clear cache before running. if still face problem send me the code and android version which you are using.

**Comment by caoruonan** [comment]
> > 我以某种方式完成了上述所有操作（添加了android：requestLegacyExternalStorage =“ true”），并添加了所有必需的权限，但是我的应用仍然无法访问设备上的图片。还有其他人遇到过同样的事情吗？随附了我的AndroidManifest.xml文件的图片。
> > ![图片](https://user-images.githubusercontent.com/31454959/100160142-e1363c00-2e63-11eb-915b-e8c3e1b99aa9.png)
> 
> 如果您使用的不是真实设备，请尝试使用真实设备。并在运行前清除缓存。如果仍然遇到问题，请向我发送您正在使用的代码和Android版本。

+1

**Comment by AugustoAleGon** [comment]
This should be open. As we know Android 11 is getting a new permission with a different way to access the files. Is there any update for this? https://support.google.com/googleplay/android-developer/answer/10467955

**Comment by minhchienwikipedia** [comment]
Any update about new permission for Android 11?

**Comment by MayoudP** [comment]
Nothing new ? Discussion also open here : https://github.com/react-native-image-picker/react-native-image-picker/discussions/1672

**Comment by ravirajn22** [comment]
- Version 2.x.x is not longer supported, please upgrade to 3.x.x. Version 3.x.x no longer requires any permission as it is on android. Read the docs carefully.

**Comment by MayoudP** [comment]
> * Version 2.x.x is not longer supported, please upgrade to 3.x.x. Version 3.x.x no longer requires any permission as it is on android. Read the docs carefully.

Alright, even if it's just moving the problem somewhere else, if I want to use image-picker correctly, I'll still have to use requestLegacyExternalStorage...

**Comment by ravirajn22** [comment]
@MayoudP no

**Comment by Sayanc2000** [comment]
Is there any way to solve this problem on an expo app, because the android manifest file isn't available in expo environment

**Comment by cybergears** [comment]
hello,
I am also facing the same problem.
When i add camera permission in AndroidManifest file  i get the following error

> This library does not require Manifest.permission.CAMERA, if you add this permission in manifest then you have to obtain the same.

i have added the following permissions 
 ```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>
```
and i have also tried adding 
`android:requestLegacyExternalStorage="true" `
inside <application />
when i remove 
`<uses-permission android:name="android.permission.CAMERA"/>`
i get 
`{" errorCode" : "permission"}`
i want to take the picture and save it on the public storage on my device. so i have added 
` saveToPhotos:true, `
in the options. but when i remove this 'saveToPhoto:true' the camera works but according to the documentation that image is stored in the temporary storage and will be removed anytime. 

do anyone have the solution to the this problem ? 
my version is ` "react-native-image-picker": "^4.3.0", `

Thankyou.

**Comment by kristijantomic** [comment]
You could try following:

```html
<!-- AndroidManifest.xml -->

<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" />
```

```js
// JavaScrip

 if (isAndroid) {
     const isGranted = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.CAMERA);

     if (isGranted) launchCamera(opts, handler);
     else {
         const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.CAMERA);

          if (granted === PermissionsAndroid.RESULTS.GRANTED) launchCamera(opts, handler);
          else openAlert();
     } 
} else {
  // iOS
  launchCamera(opts, handler);
}
```

It works, but yesterday i have got some bugs from production that some devices (Android 10) does not give access to photos. I have to investigate it further.

**Comment by imHarshBhatia** [comment]
Hi,

Is this anyone still facing this issue in 2025? Is it still mandatory to use the WRITE_EXTERNAL_STORAGE property in API Level 29? We are receiving error message for using this property from Google Play Console. How can this be resolved?
