### ISSUE TITLE
DurationLimit doesn't work in android

### ISSUE THREAD

**Issue by maysolanki** [react-native-community/react-native-image-picker#1260]

**Comment by maysolanki** [comment]
Ios app working very well , but when i'm try to android and pick video that time it pick whole length of video durationLimit doesn't work for me in android

my options:
const options =
{
    mediaType: 'video',
    videoQuality: 'high',
    allowsEditing: true,
    durationLimit: 30,
    thumbnail: true,
    takePhotoButtonTitle: null,
    title: 'Select Video',
    noData: true,
    maxWidth: 1000, 
    maxHeight: 1000, 
    storageOptions: {
        path: 'videos',
        skipBackup: true
    }
}

**Comment by peteroid** [comment]
`durationLimit` doesn't take effect on Android v2.3.1 on Android 9

**Comment by dhevendhiran-adt** [comment]
> `durationLimit` doesn't take effect on Android v2.3.1 on Android 9

Can you please elaborate on your answer. I am facing the same issue. DurationLimit is not working on any android devices.
Are there any other workarounds?
