### ISSUE TITLE
Have mixed as "mediaType" on android

### ISSUE THREAD

**Issue by niloufarMakhzani** [react-native-community/react-native-image-picker#1261]
# Feature Request

I want to use this library ro upload video or image. I've managed to do it every thing is working fine on iOS and android but there is an issue which is that I can't have access to take photo and record video on Android like iOS. 
I have managed to do this using a custom button like this:
```
   if (response.customButton) {
                ImagePicker.launchCamera(videoOption, response => {})
```

But I know that users don't like to see disabled button so I prefer to have them both on same screen.

**Comment by tareqdayya** [comment]
same issue here

**Comment by AdamGold** [comment]
Is there a solution?

**Comment by sanborN93** [comment]
having the same issue. Mediatype mixed is not working on android. I can only select photos.

**Comment by plus-** [comment]
for reference the issue is discussed here: https://github.com/react-native-community/react-native-image-picker/issues/759#issuecomment-444938268

**Comment by imAliAzhar** [comment]
It seems like android does not allow this behavior. See [this](https://stackoverflow.com/questions/44095236/start-camera-for-both-take-picture-or-record-video).

It's possible to open a camera app which will allow to shoot both picture and video but it won't be returned from the Intent. The image or video will just be stored in Gallery.

**Comment by marcodafonseca** [comment]
I am having this problem as well now. Will the mediaType "mixed" never be made available to Android?
