### ISSUE TITLE
IOS Dialog automatically closes after launching

### ISSUE THREAD

**Issue by ShahidNawazBaloch** [react-native-community/react-native-image-picker#1263]
### Description
I am using React-Native-Image-Picker to Select and Upload Files from my App, The issue i am facing that It is working in Android but in ios react-native-image-picker dialog automically closes after launching, therefore i cannot select files for upload

### How to repeat issue and example

import ImagePicker from 'react-native-image-picker';
import RNFetchBlob from 'react-native-fetch-blob';

var options = {
      title: 'Select Image',
      quality : 0.25,
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
    };
  ImagePicker.showImagePicker(options, response => {
      console.log('Response = ', response);

      RNFetchBlob.fs.stat(response.path)
      .then((stats) => {
        if (stats.size <= 5000000) {
          let source = response;
          let checkboxStates = {...this.state.checkboxStates}; 
          checkboxStates['image'] = true;

          this.setState({ imagePath: source, imageVisible: true, totalUploadSize: this.state.totalUploadSize + stats.size });   
          this.setState({checkboxStates});
        }
        else{
          toastMessage('Image should be less than 5 MB');
        }
      }).catch((err) => {});

    });

### Additional Information

* React Native version: 0.61.5
* Platform: IOS
* Development Operating System: Mac OS Mojave 10.14.2
* Dev tools: Xcode 10.14.2
* Device : IPad Pro (IOS 9)

**Comment by krunaldarji** [comment]
@ShahidNawazBaloch You need to add Gallery/Camera permission in info.plist file , add below lines inside your info.plist

<key>NSPhotoLibraryUsageDescription</key>
	<string>So you can upload images</string>
<key>NSCameraUsageDescription</key>
	<string>So you can upload image</string>

**Comment by akhileshsinha** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/issues/1573#issuecomment-757546103
