### ISSUE TITLE
How to lock screen orientation for Library Page ('Choose from Library option') ?

### ISSUE THREAD

**Issue by nazarap** [react-native-community/react-native-image-picker#1268]
- Lock device orientation. (Portrait Mode)
 - Open camera with ImagePicker.launchCamera() in Landscape mode
 - Open photo or press cancel. Application still work in Landscape mode but it's should return in Portrait

Expectation:
 - After Library page closing, application return to Portrait mode

**Comment by JuraSemenenko** [comment]
Same problem (

**Comment by Kishanjvaghela** [comment]
Any solution?
