### ISSUE TITLE
Disable Video Compression

### ISSUE THREAD

**Issue by packerfan626** [react-native-community/react-native-image-picker#1270]
I noticed there was another ticket on this that was closed a while back. But is there anyway to disable the video compression that happens in iOS? I noticed it runs so slow on longer videos and I need to be handling videos that are 90 seconds or less.

**Comment by jahn-brito** [comment]
any news regarding this?

**Comment by foufrix** [comment]
would like to know as well is this something needed or can be avoided ? 
I've seen that there is also a rencoding of the video from .mov to .mp4 to avoid any issue with apple regulation : https://developer.apple.com/softwarelicensing/quicktime/
Is this related ?
