### ISSUE TITLE
confuse about image image local size and upload size

### ISSUE THREAD

**Issue by qudianapp** [react-native-community/react-native-image-picker#1272]
# Question
in my project , i using react-native-image-picker to select image and then upload to server, there's my confuse:
at iOS platform , the photo store sandbox at : file:///var/mobile/Containers/Data/Application/1F51CFDC-3CA8-475D-8D12-9EB60569B654/Documents/images/98DB43A6-6179-46FB-821D-B85E648ACD55.jpg, the disk size of the image is **158K**(JPEG), however, the upload size is about **500K** ( get size from Charles),
the upload code:

```
 let formData = new FormData();
 let file = {uri: response.uri, type: 'multipart/form-data', name: 'image.png'};  
 formData.append("files",file); 

 fetch(uploadURL,{
            method:'POST',
            headers:{
                'Content-Type':'multipart/form-data',
            },
            body:formData,
        })
            .then((response) => response.json())
            .then((responseData)=>{
              
            })
            .catch((error)=>{console.error('error',error)});
```

**Comment by qudianapp** [comment]
seems like a react native bug: https://github.com/facebook/react-native/issues/27099

**Comment by AlexanderIgnacz** [comment]
Fixed by setting imageFileType: 'png' at options. Found this property from iOS native source code, which isn't updated at the documentation at this time.

**Comment by MayoudP** [comment]
Got the same, trying to upload with a pre-signed url on S3, and it appears that the upload size is increasing, so I'm keep having this error : `Your proposed upload exceeds the maximum allowed size`..
By any chance, did you succeed to fixe it ?
