### ISSUE TITLE
App is requesting permission after when i choose an image from the gallery in IOS

### ISSUE THREAD

**Issue by iqbalfaisal** [react-native-community/react-native-image-picker#1283]
# Bug

App is requesting gallery access permission after when i choose an image from the gallery in IOS

React native info output:

Library version: 2.2.1
React-Native version: 0.60.5
IOS: 13.3

**Comment by LaVielle** [comment]
I was having the same issue in v2.0.0:
user could open gallery and select and image without giving permission. After selecting, the permission Alert appears. Accepting or refusing permission had no effect: the picture could still be accessed and uploaded to backend or wherever. Very weird.

After updating to 2.3.0, the permission request is simply not shown, but I guess this is actually a feature and I'm fine with that :)
User is still presented permission request before opening camera.

I'm on RN 0.61.5
react-native-image-picker 2.3.0
iOS 12.4.4

**Comment by biduone** [comment]
@LaVielle   same issue 

react-native: 0.61.4
react-native-image-picker 2.3.0

**Comment by LaVielle** [comment]
@biduone I found a solution, described here: https://github.com/react-native-community/react-native-image-picker/issues/928#issuecomment-584784124

**Comment by iqbalfaisal** [comment]
any updates?

**Comment by vorasudh** [comment]
Workaround can be to manually ask for permissions before making a call to any `ImagePicker` method using [react-native-permissions](https://github.com/react-native-community/react-native-permissions)
