### ISSUE TITLE
return album name of the picked image in response

### ISSUE THREAD

**Issue by mmjd** [react-native-community/react-native-image-picker#1287]
Is it possible to return groupName or album name of the picked image as response. I am going to show image picker to user to select a photo from camera roll and then use react-native-cameraroll to show all images from the selected album in a grid.

**Comment by saintyusuf** [comment]
i need this solution too! i'd like to have info about asset album in response when assets are selected and when i will save them to gallery with react-native-camera-roll package, i need that album name...
