### ISSUE TITLE
react-native 0.61.5, not linking in android project

### ISSUE THREAD

**Issue by jackychanfox** [react-native-community/react-native-image-picker#1289]
Autolinking is not working

Manual linking is also not working

ver 0.28.0 not working too.

**Comment by nateblog** [comment]
Same issue as mine, no matter what I do my app crash because of this

**Comment by igormoraesdev** [comment]
@nateblog show error for us

**Comment by cullsin** [comment]
Hi,

For me, I am unable to open the Upload File itself in my android device. It is working fine in the android simulator.  Can you please suggest asap.
