### ISSUE TITLE
App crash when trigger launchCamera in Android

### ISSUE THREAD

**Issue by iqbalfaisal** [react-native-community/react-native-image-picker#1290]
# Bug

App crash when trigger launchCamera in Android 7.0 and 24 API

Library version: 2.3.0
React-native: 0.60.5

**Comment by guopeng1994** [comment]
+1

"react-native-camera": "3.15.1"
"react-native": "0.59.10"

**Comment by nateblog** [comment]
Same here, I installed the latest version of react-native-image-picker and the app crash just by running it.

"react-native": "0.61.5",
