### ISSUE TITLE
launchCamera not open the camera, and do nothing both iOS and Android

### ISSUE THREAD

**Issue by achimbaggins** [react-native-community/react-native-image-picker#1294]
# Bug
launchCamera not open the camera, and do nothing both iOS and Android, launchImageLibrary work properly

## Environment info

React native info output:

info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 401.33 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.1 AI-173.4819257
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Library version: 2.3.0

## Steps To Reproduce

1. upgrade from 2.2.1 to 2.3.0 

Describe what you expected to happen:

1. can open the camera

**Comment by risardi123** [comment]
To be noted I haven't try to reproduce. but as I expect the problem is from androidManifes,t.xml or config info.plist in ios. In android have you try to put this 
`<uses-permission android:name="android.permission.CAMERA" />`  and in ios 
```
<key>NSCameraUsageDescription</key>
<string>$(PRODUCT_NAME) would like to use your camera (For upload your photo)</string>

<key>NSPhotoLibraryUsageDescription</key>
<string>$(PRODUCT_NAME) would like access to your photo gallery (For Upload your photo)</string>

<key>NSPhotoLibraryAddUsageDescription</key>
<string>$(PRODUCT_NAME) would like to save photos to your photo gallery (For Upload your photo / adding image)</string>
```
I hope my answer is correct. Btw i used the 2.3.0 version and for me it's working properly

**Comment by achimbaggins** [comment]
thanks it works, :)
