### ISSUE TITLE
Camera Roll on iOS Simulator has a blank screen and cannot select any images

### ISSUE THREAD

**Issue by BC01719** [react-native-community/react-native-image-picker#1303]
# Bug

Camera Roll on iOS Simulator has a blank screen and cannot select any images

## Environment info
![Simulator Screen Shot - iPhone 11 - 2020-02-27 at 09 08 03](https://user-images.githubusercontent.com/29097404/75452705-beacdc00-5940-11ea-9d26-66146a2cc15e.png)
![Simulator Screen Shot - iPhone 11 - 2020-02-27 at 09 08 26](https://user-images.githubusercontent.com/29097404/75452706-beacdc00-5940-11ea-960f-3f3f293493ed.png)

Simulator iPhone 11 - 13.3

React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 174.88 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-26 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-google-places: 3.1.0
    react-native-photo-view: 1.5.2
    react-native-rename: 2.4.1
```

Library version: 2.3.1
"react-native-image-picker": "^2.3.1",

## Steps To Reproduce

1. Call ImagePicker.showImagePicker( ... ) from a button press
2. Tap on the Toast Menu Entry corresponding to the Camera Roll
3. View the Blank Screen of the Camera Roll (soft lock)

Describe what you expected to happen:

1. Call ImagePicker.showImagePicker( ... ) from a button press
2. Tap on the Toast Menu Entry corresponding to the Camera Roll
3. View the Camera Roll

## Reproducible sample code

```typescript
/**
 * Options for the image picker
 */
const options = {
  title: 'Choose from Library',
};

/**
  * Event handler for Image Selection area pressing
  */
handlePressImageSelector = () => {
  ImagePicker.showImagePicker(options, response => {
    if (response.didCancel) {
      console.log('User cancelled image picker');
    } else if (response.error) {
      this.setState({error: new Error(response.error)});
    } else if (response.fileSize > /* 25M */ 25 * 1024 * 1024) {
      this.setState({error: new Error('The chosen media is too large.')});
    } else {
      this.setState({image: response});
    }
  });
}

// inside render function
 <TouchableOpacity onPress={this.handlePressImageSelector}>
  <Text>select image</Text>
</TouchableOpacity>
```

**Comment by BC01719** [comment]
This was something that I had working previously with version "react-native-image-picker": "2.3.0" on Thu Feb 20, but then was broken when I upgraded to version 2.3.1. Downgrading did not fix the issue even after 
```bash 
rm -rf node_modules && yarn install && cd ios && pod repo update && pod install
```

**Comment by iaj8** [comment]
I am also experiencing this issue. On an iOS 13 simulator the Camera Roll shows a blank screen. However on Android 10 and iOS 12, the Camera Roll works perfectly on both simulators and devices.
