### ISSUE TITLE
When using ImagePicker.launchImageLibrary it is still asking permission after chose video from gallery.

### ISSUE THREAD

**Issue by ayciceksahin** [react-native-community/react-native-image-picker#1304]
# Bug
I am using `react-native-image-picker` for take video and choose video from gallery.  When using `ImagePicker.launchImageLibrary` it is still asking permission after chose video from gallery. 
But if i chose picture from gallery, there is no asking about permission as we expected.

## Environment info

React native info output:

```bash
    "react-native": "0.61.2",

```

    "react-native-image-picker": "^2.3.1.",

## Steps To Reproduce

1.  `ImagePicker.launchImageLibrary` for chosing video from gallery
2. ask permission after selected video.
...

Describe what you expected to happen:

1. I think it should be asking before selected video from gallery or never ask.

**Comment by Vitalik7** [comment]
same issue
