### ISSUE TITLE
How can i show the gallery button when the camera is open?

### ISSUE THREAD

**Issue by rafaelcavalcante** [react-native-community/react-native-image-picker#1309]
# How can i show the gallery button when the camera is open?

The design team where i work requested a different behavior from the camera and asked me a few questions. The only thing i couldn't answer – and also can't find in the documentation or in an issue with a reply – is how can i enable (or even if it's possible) to show the gallery button in the bottom side of the screen when i'm using the camera.

Here's two images below, the first one is from the in-app camera, the second is the default Android camera.

![in-app-camera](https://user-images.githubusercontent.com/405355/76252632-db41f180-6227-11ea-8a81-9bc3f67dfed7.jpg) 

![default-camera](https://user-images.githubusercontent.com/405355/76252609-d0875c80-6227-11ea-80e8-54c924d0beae.jpg)

I'm wondering how i can show the image gallery button (the one that's showing a cat in the example above.

Thanks in advance 🤗

**Comment by prescindivel** [comment]
any solution?

**Comment by mateussmohamed** [comment]
any solution or workaround?

**Comment by rafaelcavalcante** [comment]
No... i'm building a screen to handle [react-native-community/react-native-camera](https://github.com/react-native-community/react-native-camera) with custom buttons on top

**Comment by coolvasanth** [comment]
Any solution ??

**Comment by hungdev** [comment]
Any solution ??
