### ISSUE TITLE
进入相册选择照片，华为能看到视频，选择视频闪退

### ISSUE THREAD

**Issue by wulaizi** [react-native-community/react-native-image-picker#1313]
其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
华为手机进入相册，会同时看到视频和照片
需求:只选择照片，不需要选择视频
那么华为用户   选择视频就会发生闪退。

**Comment by KouSyurei** [comment]
I also encountered the same problem, including the selection of damaged images and GIF images will also, do you have a solution? @wulaizi

**Comment by wulaizi** [comment]
> 我也遇到了同样的问题，包括选择损坏的图像和GIF图像也会，您有解决方案吗？@wulaizi

暂时我也没找到解决的方法

**Comment by chuanhaisoft** [comment]
you maybe should set noData:true,

**Comment by R-yan** [comment]
> 其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
> 华为手机进入相册，会同时看到视频和照片
> 需求:只选择照片，不需要选择视频
> 那么华为用户 选择视频就会发生闪退。

请问解决了么 一样的问题

**Comment by R-yan** [comment]
> 其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
> 华为手机进入相册，会同时看到视频和照片
> 需求:只选择照片，不需要选择视频
> 那么华为用户 选择视频就会发生闪退。

部分小米手机也是如此

**Comment by R-yan** [comment]
> 其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
> 华为手机进入相册，会同时看到视频和照片
> 需求:只选择照片，不需要选择视频
> 那么华为用户 选择视频就会发生闪退。

经过看源码，找到了我觉得的问题所在，请问是否在自己的逻辑内配置了quality？如果是并且设置quality非1.0而是如0.8，0.9 ，那么在选取视频后一定会闪退，您可以将其注释掉（默认1.0），看一下，应该就不会再次闪退了！根据作者所述【quality： 0 to 1, photos only】 很明显不支持video
，设置为1.0并不会压缩，哪怕选取的是video，也不会执行其作用

**Comment by R-yan** [comment]
> 其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
> 华为手机进入相册，会同时看到视频和照片
> 需求:只选择照片，不需要选择视频
> 那么华为用户 选择视频就会发生闪退。

经过看源码，找到了我觉得的问题所在，请问是否在自己的逻辑内配置了quality？如果是并且设置quality非1.0而是如0.8，0.9 ，那么在选取视频后一定会闪退，您可以将其注释掉（默认1.0），看一下，应该就不会再次闪退了，个人感觉是视频

> > 其他安卓手机，进入相册选择照片是，只会看到照片的，而不会看到视频，
> > 华为手机进入相册，会同时看到视频和照片
> > 需求:只选择照片，不需要选择视频
> > 那么华为用户 选择视频就会发生闪退。
> 
> 经过看源码，找到了我觉得的问题所在，请问是否在自己的逻辑内配置了quality？如果是并且设置quality非1.0而是如0.8，0.9 ，那么在选取视频后一定会闪退，您可以将其注释掉（默认1.0），看一下，应该就不会再次闪退了！根据作者所述【quality： 0 to 1, photos only】 很明显不支持video
> ，设置为1.0并不会压缩，哪怕选取的是video，也不会执行其作用

 "react-native": "0.60.0",
"react-native-image-picker": "^2.3.1",

**Comment by Onespro** [comment]
这个兼容问题有处理好的吗
