### ISSUE TITLE
Xiaomi gallery app allows video selection that causes the ap chrash

### ISSUE THREAD

**Issue by t0mm4rx** [react-native-community/react-native-image-picker#1317]
Hi,
Here is my code, which is really simple:
```js
ImagePicker.showImagePicker(
      {
        noData: true,
        mediaType: 'photo',
      },
      response => { /* My stuff here */ }
);
```
It works perfectly on all my devices, but on a **Xiaomi phone with API 29**, the default gallery app still let the user choose a video, which make the app crash. **Is it possible to totally deactivate video selection ?**
Is it a bug in the Xiaomi gallery app ?

The bug occurs on a client phone so I don't have any crash logs.
Thanks !

**Comment by R-yan** [comment]
> 嗨，
> 这是我的代码，非常简单：
> 
> ```js
> ImagePicker。showImagePicker（
>       {
>         noData ： true，
>         mediaType ： “照片”，
>       }，
>       响应 => { / *我的东西在这里* / }
> ）;
> ```
> 
> 它可以在我的所有设备上完美运行，但是在**具有API 29**的**小米手机上**，默认的图库应用仍然允许用户选择视频，这会使该应用崩溃。**是否可以完全停用视频选择？**
> 这是小米图库应用程序中的错误吗？
> 
> 该错误发生在客户端电话上，因此我没有任何崩溃日志。
> 谢谢 ！

我的华为手机也是这样 设置为选取图片，却出现了视频 选取视频即闪退

**Comment by chenweigh** [comment]
I have same problem. huawei p30.
