### ISSUE TITLE
Error occurred when executing react-native link react-native-image-picker

### ISSUE THREAD

**Issue by spemed** [react-native-community/react-native-image-picker#1319]
+ Hello my dear friend,i am a student who using react-native for developing my graduation design and I found some problem when I used react-native compoment react-native-image-picker for selecting some photos from the local device
+ When I follow the docs and execute the command
```
   react-native link react-native-image-picker   
```
+ The waring message occurred  after doing it
```
    warn The following packages use deprecated "rnpm" config that will stop working from next release:
```
+ Could someone help me to solve this problem ?
+ this is my device message
```
   react-native-cli: 2.0.1
   react-native: 0.61.4
```
+ And I use Android emulator and the version of Android System is 9.0 x86

**Comment by Alarees** [comment]
react-native > 0.60 uses Autolink, so
1- react-native unlink react-native-image-picker
2- in `android/setting.gradle` at the bottom write
``` 
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
```
