### ISSUE TITLE
Save an image with a filename using ImagePicker.launchCamera

### ISSUE THREAD

**Issue by sheikx1221** [react-native-community/react-native-image-picker#1326]
### Description

I was trying to save an image using the API ImagePicker.launchCamera() but it seems it is not possible to provide an image filename, i needed to filter images based on user selection for that i need to save them with some sort of unique name, so that i can pick similar types of images after.

### Solution

It would be great to just pass it like a param and it automatically saves the image with the filename.

### Additional Information

* Expo version: 3.15.5
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android SDK 36

**Comment by Luccasoli** [comment]
Did you found any solution for your problem?
