### ISSUE TITLE
ImagePicker.launchCamera and launchImageLibrary do nothing

### ISSUE THREAD

**Issue by tapz** [react-native-community/react-native-image-picker#1327]
When I call ImagePicker.launchCamera or launchImageLibrary absolutely nothing happens. Is something missing from the readme as I copy-pasted the code example?

Samsung Galaxy S8+, Android 9
RN 0.62.0

**Comment by hancheng150** [comment]
Me too.   Samsung Galaxy S8, Android 9
RN 0.61.5

**Comment by tapz** [comment]
Works in iPhone X, but Cancel and Choose after taking a photo are not localized.

**Comment by tapz** [comment]
Does not work in Google Pixel 2, Android 10 either.

**Comment by yatoogamii** [comment]
Hey @tapz 

Can you send your code here ?

I have same issus with launchCamera and launchImageLibrary because i omitted option argument like showImagePicker. But launchCamera and launchImageLibrary methods need option argument (can be empty: {}).

I hope that can help you

**Comment by Atuldhaka** [comment]
launchCamera and launchImageLibrary do nothing, please explain how to use this as i have also tried passing empty options object  and also with some keys in options object.

**Comment by Atuldhaka** [comment]
I have resolved it by adding the proper permission in info plist and android manifest file. My bad.
