### ISSUE TITLE
Android upload video from library - no durationLimit even with allowsEditing set to true

### ISSUE THREAD

**Issue by cnairi** [react-native-community/react-native-image-picker#1328]
Library version : 0.28.0
react-native version : 0.59.3

Hi everyone,

I have an issue only with video uploaded from library, and only on Android devices (all of them).

Here are my options for the mediaPicker : 
	const optionsUploadAndroidCamera = {
		mediaType: 'video',
		noData: true,
		allowsEditing: true,
		videoQuality: 'high',
		storageOptions: {
			skipBackup: true,
		},
		durationLimit: 20
	};
and here is the way I pass them to it : 
ImagePicker.launchImageLibrary(optionsUploadAndroidLibrary)

The problem is the following : 
Even with option allowsEditing set to true, I can upload video larger than 20seconds, and I can't edit them.

Does somebody have a clue about this issue ?

Thanks a lot for your help.

**Comment by cokealmonacid** [comment]
did you find any solution on this?

**Comment by raindev32** [comment]
any solution on this ?

**Comment by HoangTrongKhanh** [comment]
any solution?
