### ISSUE TITLE
Bottom of screen flickers after ImagePicker resolves on iOS 13

### ISSUE THREAD

**Issue by jurelik** [react-native-community/react-native-image-picker#1329]
# Bug
Bottom of the screen flashes/flickers after the ImagePicker promise is resolved. Pay attention to the bottom of the screen in the following gif:
![image-picker bug](https://user-images.githubusercontent.com/43504530/78354547-f80de280-75a3-11ea-9f7d-ca4765ca1136.gif)

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 411.13 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.3.1

## Steps To Reproduce

1. Create a new react project and install react-native-image-picker
2. Add the code below to App.js
3. Run the app on iOS 13, press the test button and either load an image from the gallery or press cancel. After the ImagePicker promise is resolved the bottom of the screen will flicker as if something wants to pop up.

Describe what you expected to happen:

1. Smooth closing of the image picker component.

## Reproducible sample code
```
import React from 'react';
import {
  SafeAreaView,
  Button,
} from 'react-native';
import ImagePicker from 'react-native-image-picker';

export default function App() {
  return (
    <SafeAreaView>
      <Button onPress={() => ImagePicker.showImagePicker({}, res => {
        //Do nothing
      })} title='test' />
    </SafeAreaView>
  )
}
```

**Comment by lewazo** [comment]
Did you resolve this? I am also experiencing the same issue on iOS 13.

**Comment by lewazo** [comment]
In my case, it only happens after choosing a photo from library. When I cancel or when I take a photo directly it does not flicker.
