### ISSUE TITLE
'React/RCTBridgeModule.h' file not found      Help me!!!!!

### ISSUE THREAD

**Issue by namecjk** [react-native-community/react-native-image-picker#1330]
in Xcode Bug

"'React/RCTBridgeModule.h' file not found"

/Users/XXXXXXX/Desktop/React-native/Db_App/node_modules/react-native-image-picker/ios/ImagePickerManager.h:1:9: 'React/RCTBridgeModule.h' file not found

**Comment by chai86** [comment]
Have you tried to drag the file and put it under the corresponding project folder in XCode file navigator on the left hand side?
