### ISSUE TITLE
Unable to use tintColor

### ISSUE THREAD

**Issue by chai86** [react-native-community/react-native-image-picker#1332]
@levipro I'm using react-native-image-picker v0.27.0 as this is the most stable release on iOS i've found that works with my react-native v0.59.1

When i try:

```
const options = {
       mediaType: 'video',     //works!
       title: " ",                       //doesn't work
       durationLimit: 15,       //doesn't work
       tintColor: 'orange',     //Doesn't work
       cancelButtonTitle: 'GoBack',  //Doesn't work
      };
```

What are these options not working?

**Comment by drewpitchford** [comment]
Yes, came here looking for this. Tint color doesn't work.

**Comment by chai86** [comment]
I have issues with these options, but in general i'm unable to make any stylistic modifications with this module. For example, the 'compressing video' text, the white 'choose' and 'cancel' buttons, the blue compressing video loading bar. It's FIXED, when it should be editable

**Comment by remstos** [comment]
tintColor not working here as well. iOS 13.4 - RN 0.61.4 - rn-image-picker 2.3.1

**Comment by MayoudP** [comment]
Any update on this ? I also got the same pb from @remstos

**Comment by takdol** [comment]
Hi, not sure if I should create a new issue but this is somewhat related to `tintColor` as well. 

`tintColor` for me only works for the `ActionSheet` component, but when you go to the Camera Roll of the device, the `Back` and `Cancel` buttons are using the system default colors. 

I'm sort of on the same boat as @chai86
