### ISSUE TITLE
Image selection does not work on miui global 11.0.8 android 10

### ISSUE THREAD

**Issue by nes123** [react-native-community/react-native-image-picker#1334]
We get complains on production version that it is not possible to select an image in this specific phone. We dont have access to it and we dont see any error log. It seems that after the user select the image the "cancel" is triggered. 

Any ideas?

**Comment by aplattinum** [comment]
I can attest to this issue.  Upon trying to upload a photo to firebase storage with miui I am getting blocked because I dont have permissions.

**Comment by rawern** [comment]
this might be the same problem like #1350 because of the ScopedStorage on API >=  Android 10 (API 29)
