### ISSUE TITLE
Set aspect ratio from options for both android & ios

### ISSUE THREAD

**Issue by raajnadar** [react-native-community/react-native-image-picker#1335]
# Feature Request

Ability to add aspect ratio like `aspectRatio: [1,1]` throught options.

## Why it is needed

Will be helpful to get square shaped images or desired aspect ratio image for both Android & iOS.

**Comment by raajnadar** [comment]
No please

**Comment by CryptoDevWill** [comment]
So you are telling me there is no way to change the aspect ratio?
