### ISSUE TITLE
launchImageLibrary works only the first time

### ISSUE THREAD

**Issue by KristineTrona** [react-native-community/react-native-image-picker#1337]
# Bug

This issue has already been reported , however was closed without actually fixing it https://github.com/react-native-community/react-native-image-picker/issues/1236

using ``ImagePicker.launchImageLibrary()`` works only the first time, does not matter if the user chooses an image or dismisses the window - it is not possible to re-launch ImagePicker to choose an image again. 

## Environment info

System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 377.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

   react-native-image-picker: 2.3.1

**Comment by jtich** [comment]
Any luck resolving this issue? I'm also experiencing this on react-native 0.62.2.

**Comment by weinixuehao** [comment]
@KristineTrona @jtich 
Have you resolved this issue?

**Comment by KristineTrona** [comment]
@weinixuehao No, unfortunately I did not resolve it.
