### ISSUE TITLE
[Android] Camera image rotates 90 degress

### ISSUE THREAD

**Issue by krakzk** [react-native-community/react-native-image-picker#1338]
I aml facing this issue, where my images taken from camera are rotated by -90 or 270 , which i cant confirm as my original rotation comes as 0 and isVertical is true.
i have tried the 360 rotation passing, giving quality 0.99 etc. Sadly none of them worked.
The issue doesn't appear in case of images selected from gallery.

Version : 0.28.1
Rn version : 0.59.3
Android device: Redmi note 8
Version : android 9

**Comment by KrishyV** [comment]
I did manage to replicate it but only for selfies. The originalRotation from the response body is in fact 270 degrees. My proposed fix would be to import react-native-image-resizer and use the createResizedImage method to rotate the image by -90 degrees.

**Comment by krakzk** [comment]
@KrishyV I had tried that, but it would affect the images selected from the gallery, as the issue is not there for them. Did u have any identification for the above select scenario that the image is from camera

**Comment by KrishyV** [comment]
Yes, if you look at the URI from the Response body, it would differ if it is from Camera vs File System. You can do a `startsWith` on the URI to check if it is from taken from camera.

**Comment by krakzk** [comment]
@KrishyV Thank you... Was able to sort out an algorithm based on that

**Comment by krakzk** [comment]
If needed to resolve the issue without updating the version of your plugin, please change add the follwoing change in MediaUtils line 274
int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_UNDEFINED);

This had worked in devices, but emulator still shows error in my case
