### ISSUE TITLE
[Android] App crash when video is selected 

### ISSUE THREAD

**Issue by iqbalfaisal** [react-native-community/react-native-image-picker#1341]
# Bug
the app is crashing when trying to select the video from the gallery on the emulator. but worked if I record a video.

# Error
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/31/ORIGINAL/NONE/190558717 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F31/ORIGINAL/NONE/190558717} }} to activity {com.myApp/com.myApp.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
## Environment inf
"react": "16.8.6",
"react-native": "0.60.5",

Library version: 2.3.0

**Comment by harshit-prog** [comment]
same issue in my case

**Comment by Pyroboomka** [comment]
Same crash on emulator, but seems to work fine on actual device

**Comment by cb1993patel** [comment]
same issue in my case

**Comment by RahulkrishnanSpericorn** [comment]
I have same issue in both android and ios when i select a video

**Comment by abhisekpadhi** [comment]
Confirm it breaks. 

Here are 2 alternatives if your use case involves picking file - 
https://github.com/ivpusic/react-native-image-crop-picker
https://docs.expo.io/versions/v35.0.0/sdk/imagepicker/

**Comment by martppa** [comment]
Hi. It happens to with after downloading a test video from the internet and fails trying get geolocation java.lang.IllegalArgumentException: Invalid column latitude
at com.imagepicker.utils.RealPathUtil.getDataColumn(RealPathUtil.java:131)
        at com.imagepicker.utils.RealPathUtil.getRealPathFromURI(RealPathUtil.java:101)
        at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:659)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:436)

**Comment by lefrankleal** [comment]
no updates on this?

**Comment by martppa** [comment]
Hi @lefrankleal I ended using https://github.com/ivpusic/react-native-image-crop-picker. I recommend you using it as well.
