### ISSUE TITLE
[Android] After taking a photo or selecting a photo, the callback is not executed

### ISSUE THREAD

**Issue by hancheng150** [react-native-community/react-native-image-picker#1348]
react-native :0.61.5
react-native-image-picker:2.3.1

device:samsung S10

ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);
      if (response.didCancel) {
        console.log('User cancelled photo picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        this.refs.webViewRef.postMessage(JSON.stringify({
          "takePhoto": response.data,
          "fileSize": response.fileSize,
          "attcmentType": type
        }));
      }
    });

After I take a photo or select a photo, the callback does not execute。

**Comment by gurmeetsinghmalhotra** [comment]
Facing same issue

**Comment by anchaljain123** [comment]
Facing issue

**Comment by gurmeetsinghmalhotra** [comment]
@hancheng150 I am also using react-native : 0.61.5 and after seeing your comment I tried it on another project with "react-native": "0.62.2" and it worked perfectly. Can you try to upgrade your version and confirm the same that there is an issue with "0.61.5" specifically?

**Comment by hancheng150** [comment]
> @hancheng150 I am also using react-native : 0.61.5 and after seeing your comment I tried it on another project with "react-native": "0.62.2" and it worked perfectly. Can you try to upgrade your version and confirm the same that there is an issue with "0.61.5" specifically?

I did not try to update the RN version。This can solve my problem #383

**Comment by plus-** [comment]
I'm now facing this issue after upgrading from 0.61.4 to 0.62.2

**Comment by hanzoow** [comment]
same here react-native 0.59.9

**Comment by anchaljain123** [comment]
Add following code in MyActivity.java file
@Override
    protected void onActivityResult(int requestCode, int resultCode, @androidx.annotation.Nullable Intent data) { 
        mReactInstanceManager.onActivityResult(this,requestCode, resultCode, data);
    }

**Comment by hanzoow** [comment]
@anchaljain123 u mean add "mReactInstanceManager.onActivityResult(this,requestCode, resultCode, data);" in ?
How u can declare mReactInstanceManager?

**Comment by anchaljain123** [comment]
@hanzoow : I have created my own Activity.java file for react native, but you can simply use super() instead of mReactInstanceManager

**Comment by v0lume** [comment]
same issue

**Comment by v0lume** [comment]
@anchaljain123 sorry for tagging you, but can you provide full code example of your actiivity class? thanks!
