### ISSUE TITLE
Change API to use promises instead of callbacks

### ISSUE THREAD

**Issue by Bhullnatik** [react-native-community/react-native-image-picker#135]
React-native is slowly switching from callbacks to Promises (See [1](https://github.com/facebook/react-native/issues/4971), [2](https://github.com/facebook/react-native/pull/5512), [3](https://github.com/lwansbrough/react-native-camera/issues/168)), as Promises provide multiple advantages over callbacks ([async and await keywords](https://jakearchibald.com/2014/es7-async-functions/),...) plus  offering a common API.

This could be implemented easily in this module, I could look into it if that's something you would be interested in.

Cheers!

**Comment by yfuks** [comment]
That will be a great enhancement for sure

**Comment by marcshilling** [comment]
We'll need to build a JavaScript wrapper around the native components to accomplish this, correct?

**Comment by Bhullnatik** [comment]
@marcshilling Not really, React-native provides some interfaces usable in Java. For now this project is using [`Callback`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/Callback.java) but [`Promise`](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/bridge/Promise.java) is as much available.

I'd refer to recent native modules implementations like [DatePickerAndroid](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/modules/datepicker/DatePickerDialogModule.java#L118) to see how it works; the good thing is RN also automatically handles `Promise`s by returning them in the javascript method (see [JS implementation](https://github.com/facebook/react-native/blob/master/Libraries/Components/DatePickerAndroid/DatePickerAndroid.android.js#L64) and [async/await example](https://github.com/facebook/react-native/blob/master/Examples/UIExplorer/DatePickerAndroidExample.js#L49) of previous mentioned example) if it's the last parameter of the `@ReactMethod`.

The 'tricky' part would be to decide when to resolve/reject the promise (again `DatePickerAndroid` is a good example imo), and also that it would be a API breaking change in the next version of react-native-image-picker. Other than that it's easy to implement.

I would be more than happy to throw a PR together if you are still interested.

**Comment by marcshilling** [comment]
To avoid a breaking change, do you think you can make Promises the default, but fall back to the callback if it's provided? If so, would gladly accept a PR

**Comment by Bhullnatik** [comment]
That would be pretty easy with a JS wrapper:
```js
showImagePicker(options, callback) {
  if (callback === undefined || typeof callback !== 'function') {
     return ImagePickerManager.showImagePicker(options);
  } else {
     ImagePickerManager.showImagePicker(options).finally((result) => {
       callback(result);
     });
  }
}
```
but still would need some more coding to translate the corresponding value from the `Promise` to the callback as it would be hard to keep the same response.
That would also invoke a _breaking change_ for the import, from `const { ImagePickerManager } = React.NativeModules` to `import ImagePickerManager from 'react-native-image-picker'`

another way without JS wrapper would be to offer 2 methods in the module:
```java
@ReactMethod
showImagePicker(final ReadableMap options, final Promise promise) {
  ...
}

@ReactMethod
showImagePicker(final ReadableMap options, final Callback callback) {
 ...
}
```
and let React native decides which one to call depending on the function caller, but I'm not sure if it works.

For me fully switching to Promises with a major version bump doesn't seem too bad, but I can understand that's not a direction wanted.

**Comment by florianbepunkt** [comment]
is this still on the roadmap?

**Comment by marcshilling** [comment]
I personally don't mind the callbacks so I'm not in a rush to do this myself, but I've really just been waiting for a PR!
