### ISSUE TITLE
launchImageLibrary shows other options than Gallery

### ISSUE THREAD

**Issue by ahmetbicer** [react-native-community/react-native-image-picker#1360]
# Question
How can i disable other options when i use launchImageLibrary. You can see in this [link](https://prnt.sc/s8xblc) it shows other apps that can provide image or video like Mega or Google Photos i just want to show local gallery. Is this possible?

**Comment by lewatt23** [comment]
@ahmetbicer  please how did you solve the problem?

**Comment by ahmetbicer** [comment]
I didn't solved it. Since no one answered this question i looked for another solution and i found out that expo-image-picker is another option for picking images or videos from gallery. So i use expo-image-picker. But keep in mind that if you use expo-image-picker the selected file going to be copied to your apps cache folder. So it doesn't give you the actual uri for the file it copies to the cache and give you a uri from cache folder. In my use case it is totally fine i just manage the cache off the app with file system libraries. 

https://docs.expo.io/versions/latest/sdk/imagepicker/

**Comment by AlexCernik** [comment]
I have same problem, any solution?
