### ISSUE TITLE
After updating to RN 0.62 and Update the package, Android stopped working

### ISSUE THREAD

**Issue by barak109** [react-native-community/react-native-image-picker#1361]
# Bug

The package works great for me in the past, but after i was updating my RN to RN 0.62.2 this package stopped working for android.
I get all the data as in the past but i think that the data in the uri didn't save.
And i didn't get any error
-->

This is my code-

```
handleAddingPhoto = () => {
  ImagePicker.showImagePicker(options, async (response) => {
    if (response.didCancel) {
      console.log("User cancelled image picker");
    } else if (response.error) {
      console.log("ImagePicker Error: ", response.error);
    } else {
      ImageResizer.createResizedImage(response.uri, 400, 400, "JPEG", 80)
        .then(async (data) => {
          const data = {uri: response.uri, name: data.name};
          this.handleUploadPhoto(data);
        })
        .catch((err) => {
          console.log(err.message);
        });
    }
  });
};
```

## Environment info

    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

Library version:
   "react-native-image-picker": latest

## Steps To Reproduce

1. create new RN 0.62.2 Project
2.add react-native-image-picker
3.try to get to the image will fail in android and will success in IOS 

Describe what you expected to happen:
1.get the uri and see the image

**Comment by barak109** [comment]
Sorry the problem was in react-native 0.62 .
This solved my problem -
https://github.com/facebook/react-native/issues/28551#issuecomment-611085378

**Comment by longebane** [comment]
why did you close this issue, if it's still an issue and you only followed a workaround?
