### ISSUE TITLE
Return a HTTPS url rather than a File URL

### ISSUE THREAD

**Issue by ruthvikkonda** [react-native-community/react-native-image-picker#1363]
I need to pass a website url to my firebase authentication but currently the ImagePicker function returns a file URL. And there is no usable way for me to convert a file URL to a website url. So I was wondering if there was any way for imagepicker to return a website/HTTPS url. I'm not exactly sure how to do it or if there already exists a way but I thought I'd put this out there.

**Comment by RigoTheDev** [comment]
You first need to upload the image returned by the ImagePicker to a web service where you can retrieve the image back with an HTTPS url.

1. Get image from picker
2. Upload to web storage, can be your own web server or [Firebase's Cloud Storage](https://firebase.google.com/docs/storage)
3. Return the HTTPS url for that image, Firebase should have docs on this
4. Pass that URL to your Firebase Authentication

Hope that helps you out!
