### ISSUE TITLE
What is the unit of the fileSize from the response object?

### ISSUE THREAD

**Issue by hugoh59** [react-native-community/react-native-image-picker#1364]

**Comment by himanshupadia** [comment]
@hugoh59 
could you please let me know the type (bytes/kb/etc..) of fileSize that we are getting from selected or captured image?
It's really helpful for me as I am getting stuck on this?
Please help me, waste one day and still stuck.
Appreciate your help.

**Comment by qualitymanifest** [comment]
Based on what I've seen by comparing to a file I saved after uploading it, it's bytes.
