### ISSUE TITLE
incorrect dimensions?

### ISSUE THREAD

**Issue by avlonder** [react-native-community/react-native-image-picker#1365]
Hi,

I discovered that the width and height responded by ImagePicker.launchImageLibrary does not equal that of Image.getSize() on my Android device. This probably has something to do with PixelRatio, but I cannot figure it out.

**Comment by emmaielle** [comment]
is this related to the fact that images chosen dont use the original dimensions? For me they always get transformed to landscape, even if they are portrait

**Comment by avlonder** [comment]
My apologies. Apparently, the dimensions returned by react-native's Image.getSize() are incorrect for Android.
