### ISSUE TITLE
App crash when pick video is not screen recording 

### ISSUE THREAD

**Issue by hanzoow** [react-native-community/react-native-image-picker#1369]
# Bug report

## Summary
When I select a video from my gallery, except for the screen shot video, my application always crashes

## Environment info
Android

`react-native info` output:

```bash
# paste it here
```

Library version: x.x.x

## Steps to reproduce

1. Select a video from my gallery
2. After short time my App crashed

Describe what you expected to happen:

1. I could select my video and do my stuffs

**Comment by hanzoow** [comment]
i dont know how but right after i created this issue and it works LOL

**Comment by lefrankleal** [comment]
@hanzoow how did u resolved this?

**Comment by kuldip9060** [comment]
Facing same issue
