### ISSUE TITLE
[IOS] can't get thumbnail for IOS Video picker?

### ISSUE THREAD

**Issue by thongdinh** [react-native-community/react-native-image-picker#1370]
Hi all,

I use this library for Video picker it's work fine on Android with the uri for thumbnail when select the video in library or take new video but it not work on IOS for the thumbnail, the uri always return the path of video instead of the thumbnail of the video.

**Comment by user14045** [comment]
@thongdinh hi, did u find any solution?

**Comment by haridevks** [comment]
this issue is still there in iOS.
