### ISSUE TITLE
Multiple selection supported?

### ISSUE THREAD

**Issue by huaiguoguo** [react-native-community/react-native-image-picker#1371]
# Question

**Comment by mjamroz** [comment]
Before you open an issue

This library started as a basic bridge of the native iOS image picker, and I want to keep it that way. As such, functionality beyond what the native UIImagePickerController supports will not be supported here. Multiple image selection, more control over the crop tool, and landscape support are things missing from the native iOS functionality - not issues with my library. If you need these things, react-native-image-crop-picker might be a better choice for you.

**Comment by huaiguoguo** [comment]
> Before you open an issue
> 
> This library started as a basic bridge of the native iOS image picker, and I want to keep it that way. As such, functionality beyond what the native UIImagePickerController supports will not be supported here. Multiple image selection, more control over the crop tool, and landscape support are things missing from the native iOS functionality - not issues with my library. If you need these things, react-native-image-crop-picker might be a better choice for you.

thank you for your reply,   i am not trying to express that these's something wrong with your library;
you overreacting...

i  just  only open a Questions and help,   i am not open bug report,   
thank you!

**Comment by huaiguoguo** [comment]
thank you for your recommendation "react-native-image-crop-picker"

**Comment by mjamroz** [comment]
@huaiguoguo but i am not an author or this package. by accident i was on front page where i read that and few seconds later i noticed you're asking question in issues so i decided to copy & paste. probably better than waiting for an author to answer (assuming s/he would) ;-)

**Comment by huaiguoguo** [comment]
@mjamroz  thank you
