### ISSUE TITLE
Error: react-native-image-picker: NativeModule.ImagePickerManager is null.

### ISSUE THREAD

**Issue by juliasliu** [react-native-community/react-native-image-picker#1376]
I have been trying to figure out how to fix this error for several hours but I have not found a working solution yet. I have tried all the following steps listed in the error message, as well as running these lines of code that were suggested by other people in the issues thread:
1. `npm uninstall react-native-image-picker`
2. `npm install react-native-image-picker@0.28.0 --save`
3. `react-native link react-native-image-picker`

However, none of these methods worked for me. The more I try `pod install`, `react-native link`, and other commands in my react native project, the more I feel like my code is breaking. I am now even unable to run `yarn ios`, equivalent to `react-native run-ios`.

**A brief context and description of how to reproduce this error:**
- In my package.json, it says that I am using the version`"react-native-image-picker": "^2.3.1",`
- I did the following in order to clean my react native project and re-eject my expo app:
    1. Deleted both the ios and android directories in my root folder
    2. `expo eject`
    3. `yarn ios`
- Everything worked fine up to this point. **The app was running smoothly in the iOS simulator.**

- **However, I wanted to test my react native app on my real iOS device as well**, so I ran `expo start`, navigated to my browser to see the expo CLI, changed the Connection from LAN to Tunnel, opened the Expo Client app on my iPhone, clicked on the project to run it, and as soon as the JavaScript bundle was done loading, the error showed up in red below.

Is this an inherent problem with react-native-image-picker? I want to be able to build and run my app on my personal iOS device, but this error is blocking me. Should I be switching to a different react native module entirely?

```
Error: react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
• Run `react-native link react-native-image-picker` in the project root.
• Rebuild and re-run the app.
• If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
• Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker

<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:179783:20
loadModuleImplementation
    require.js:322:6
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:179691:60
loadModuleImplementation
    require.js:322:6
<global>
    New.js:20
loadModuleImplementation
    require.js:322:6
<global>
    BottomTabNavigator.js:17
loadModuleImplementation
    require.js:322:6
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123951:63
loadModuleImplementation
    require.js:322:6
<unknown>
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:123855:49
loadModuleImplementation
    require.js:322:6
<global>
    AppEntry.js:3
loadModuleImplementation
    require.js:322:6
guardedLoadModule
    require.js:201:45
global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:220633:4
```

**Comment by sagarokcredit** [comment]
The issue is still there

**Comment by yalcinozer** [comment]
Yep. Still there.

**Comment by PatrickTchoupe** [comment]
I still have this error
