### ISSUE TITLE
Remove / Add exif data from image.

### ISSUE THREAD

**Issue by dev7050** [react-native-community/react-native-image-picker#1379]
I want to let user to decide whether they want to remove exif data from image before upload. I have seen there's option to get exif in react-native-image-crop-picker and react-native-camera i.e "includeExif". Is there any way to do the same and removing/adding exif using this library.

Or any way to achieve same using any other third-party on client side.

Any help will be appreciated.

Thank You.

**Comment by shubhamoyorooms** [comment]
Hi @dev7050 did you find any solution for the same?

**Comment by dev7050** [comment]
Hello @shubhamoyorooms , yes you can do so with piexif as 
import piexif from 'piexifjs';
noexifbase64 = piexif.remove(your base-64 image);

**Comment by etczrn** [comment]
Thank you. You're my life saver!
And those who want to know how to use piexif-ts (including TypeScript), this might help you.

```typescript
import { remove, load } from "piexif-ts";

const reader = new Reader();
reader.onloadend = () => {
  const result = load(reader.result as string);
  console.log("result:", result); // to see the original exif data 
  const removed = remove(reader.result as string);
  console.log("after removed:", load(removed)); // now you can see all the exif data is gone.
};
reader.readAsDataURL(file);
```
