### ISSUE TITLE
Conditional rendering for custom button in options [] 

### ISSUE THREAD

**Issue by MayoudP** [react-native-community/react-native-image-picker#1381]
# Question

Hello folks, 
I tried to manage a conditional rendering for a custom button within the picker.
My options [] looks like this : 

```
const options = {
      title: title,
      takePhotoButtonTitle: condition ? title : null,
      chooseFromLibraryButtonTitle: condition ? title : null
      },
      ...
      customButtons: [{name:'title', title: title }],
    };
```

I tried condition like I used for `takePhotoButtonTitle` or `chooseFromLibraryButtonTitle` where both of them works well actually. But didn't manage to handle it for the `customButtons`field.

The only way to handle a conditional display for customButtons is to actually create a complete new object options without the field `customButtons` and manage the condition there : 
`ImagePicker.showImagePicker(condition ? options : options2WithoutCustomButton, ...` but not a huge fan to having to create a new options object just to handle this case. 

Any ideas ?

**Comment by 52-28** [comment]
Hello, same issue here, have you found a solution? I tried the one you suggest but it doesn't work ...

**Comment by hogrid** [comment]
Same here
