### ISSUE TITLE
How to create file from base64 data returned from response and upload to server that supports multipart/form only

### ISSUE THREAD

**Issue by drb1** [react-native-community/react-native-image-picker#1395]
"react-native": "0.61.5",
"react-native-image-picker": "2.3.3",
Both Platform

 const data = new FormData();
                data.append('file', {
                    uri: response.data,
                    type: response.type,
                    name: 'photo.jpeg',
                });

and upload the data to server but i get error Request part file not found,Please help to convert response to file format,atob and btoa is not wroking

**Comment by AvneeshD** [comment]
> "react-native": "0.61.5",
> "react-native-image-picker": "2.3.3",
> Both Platform
> 
> const data = new FormData();
> data.append('file', {
> uri: response.data,
> type: response.type,
> name: 'photo.jpeg',
> });
> 
> and upload the data to server but i get error Request part file not found,Please help to convert response to file format,atob and btoa is not wroking

Hi, did you find a solution to this?

**Comment by drb1** [comment]
change uri: response.data to response.uri

**Comment by yvza** [comment]
> change uri: response.data to response.uri

worked thanks 😁
