### ISSUE TITLE
[iOS] How to handle permission denied

### ISSUE THREAD

**Issue by jonolock91** [react-native-community/react-native-image-picker#330]
If the user specifies they don't want to allow for example camera access, can I bind an event to that? At the moment if I press deny, I'm presented with the camera screen filled black and the user has to press cancel to go back, preferably I'd like to not load the camera at all if they deny access.

If this is native behaviour I understand you're not willing to make further changes.

**Comment by marcshilling** [comment]
iOS or Android?

**Comment by jonolock91** [comment]
iOS, I haven't tested for Android to be honest.

**Comment by tomazahlin** [comment]
I was also thinking the same. Is there any way to check if permission was allowed or not by the user?

**Comment by marcshilling** [comment]
So, as you can see [here](https://github.com/marcshilling/react-native-image-picker/blob/f70713b954affafdc096bc25c312d1188954e55a/ios/ImagePickerManager.m#L250), it should return an error response if permissions were not granted. Are you guys seeing different results?

**Comment by sunkibaek** [comment]
@marcshilling I am not familiar with iOS platform but is there any way to simply ask for permissions again in iOS through the dialog box using react-native-image-picker?

**Comment by tomazahlin** [comment]
@sunkibaek I am not sure if you can ask through react-native-image-picker, but maybe you can consider using this - https://github.com/yonahforst/react-native-permissions ?

**Comment by sunkibaek** [comment]
@tomazahlin Yeah, I was just checking that out, too. Thanks!

BTW it seems it is not just possible to ask for the permission more than once in iOS.

**Comment by marcshilling** [comment]
@sunkibaek that is true - once they decline permissions, the best you can do is redirect them to the settings app to have them manually turn them on.

I'm not sure what the right way to handle this is. I feel like the way it is working now is correct and it should be up to the developer to handle declined permissions themselves.

**Comment by haitaoli** [comment]
I agree the permission denied error should be handled by caller. But the error should be returned in a structured way. Currently it's returned as an error string which is different between camera and photo library, and cannot be localized. Ideally the code should set another property in response object, or use a "status" enum property which has values such as "OK", "Cancelled", "Denied", "Unknown".

**Comment by marcshilling** [comment]
@haitaoli fair point. I'll think on this.

**Comment by dangnelson** [comment]
I agree with @tomazahlin, using https://github.com/yonahforst/react-native-permissions as a dependency seems to be the best course of action for iOS. Then use the react-native Alert component with the standard change permissions in settings message if permissions have already been denied.

**Comment by JoaoCnh** [comment]
I still think error codes should be returned. A lib should give me full control of how to handle situations like these. I have other libs (like react-native-camera) where I can do whatever my app requires (be it alert, redirect, whatever) when the user denied permissions. And even so we're at a point in this lib where permissionDenied works for Android and not on iOS. That's just not feasable for many.

I vote for the implementation of simple error codes being returned on the callback.

**Comment by Johan-dutoit** [comment]
It's fairly easy to get the status codes to the front end.
That being said, I'm not yet convinced that we need to split it them up, but I'm happy to be convinced otherwise.

What I'm currently thinking:

- App requests access to X (library/camera)
- iOS Permission check occurs
  - If first request, proceed as normal and request permission
  - If previously requested and permission still granted, skip permission request (don't need to request) 
  - If previously requested and permission **not** granted, skip permission request (can't request anyway)
- Plugin permission check occurs
  - If permission granted, show picker
  - If permission denied, call callback with current error message & permission status code**

** code will be a value of either 1(restricted)*** or 2(denied)***.  Both _AVAuthorizationStatus_ and _PHAuthorizationStatus_ use the same pattern.

*** Yet to decide if the plugin should return the int value (i.e. 1) or the string label (i.e. restricted).  Need to Take Android into consideration here.

Example of response:

```JS
{error: "Photo library permissions not granted", permissionStatus: 2}
```
or 

```JS
{error: "Camera permissions not granted", permissionStatus: "restricted"}
```

**Comment by JoaoCnh** [comment]
You could have error codes similar to what react-native-camera does. Like "READY", "PENDING_AUTHORIZATION" and "NOT_AUTHORIZED". With Typescript these are easy to track and make sure people use them accordingly and they convey purpose. Sending an error message is also nice.

**Comment by toro705** [comment]
This should not be stale. Working on it right now. 
In my case, on IOS:

The user declines camera, so i take the permission error and manually show the alert that redirects to setings. Until there we are all good. but i'm using storage too. Both permissions ar asked one after another. if i acept camera permission, but i do not accept the storage permission, the app wont return any error. It simply does nothing.
