### ISSUE TITLE
tintColor for ActionSheet

### ISSUE THREAD

**Issue by jonathanglasmeyer** [react-native-community/react-native-image-picker#337]
[ActionSheetIOS](https://facebook.github.io/react-native/docs/actionsheetios.html) supports tintColor. It'd be nice to be able to configure it for this library as well.

**Comment by marcshilling** [comment]
Would gladly accept a PR.

**Comment by winkelsdorf** [comment]
PR is open: https://github.com/react-native-community/react-native-image-picker/pull/898
