### ISSUE TITLE
Destructive custom button?

### ISSUE THREAD

**Issue by wcandillon** [react-native-community/react-native-image-picker#424]
@marcshilling Thank you so much for this amazing library!

I am using a custom button to remove a picture that is already set and I was wondering if there is a way to style a custom button as being a destructive button?

**Comment by marcshilling** [comment]
This is definitely possible. iOS has the concept of "destructive" and Android calls it "negative". We could easily look for a `style` key on the `customButtons` objects that get passed in. If you want to take a stab at a pull request that would be awesome, if not I will keep this open and try to get around to it eventually!

**Comment by wcandillon** [comment]
@marcshilling Thanks for the answers! I opened #431 but unfortunately I'm completely unfamiliar with native development.

**Comment by Jef-Jkn** [comment]
Is this already fixed in a way or is it still open?
