### ISSUE TITLE
iOS can open photo library ,but can't get photo

### ISSUE THREAD

**Issue by wwl901215** [react-native-community/react-native-image-picker#442]
i can use this successfuly in android.  but i can not get photo in ios ; In ios , i can open Photo Library;
can you help me ? i am newer to ios , i was learn android.

**Comment by wwl901215** [comment]
it seem that ImagePicker.showImagePicker(optins,callBack) don't work .  The callBack don't work.

**Comment by jackjunjiang** [comment]
me too,it is about ImagePickerManager.showImagePicker

**Comment by kayoubi** [comment]
+1, if I select "choose from library.." the application crashes

**Comment by marcshilling** [comment]
Everything working fine for me on iOS. Can you provide more detail about your issue?

**Comment by ksarna** [comment]
@jackjunjiang make sure you did the following. 

> For iOS 10+, Add the NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription (if allowing video) keys to your Info.plist with strings describing why your app needs these permissions

That was causing crash for me.

**Comment by pheye** [comment]
react-native: 0.41.2
react-native-image-picker: 0.26.2
xcode 8.2.1

I met the similar problem on ios, after pick photo from the photo library, it always get "`Can't find variable:response`" error.Then I tried to click the cancel button, the same error,too.Last, I tried 
to rename callback parameter name and result in the same error.So I guess it must stuck somewhere in the module itself.

```
 ImagePicker.showImagePicker(options, function(res) {  //rename response to res.
       console.log(res);                                                        
});
```

finally, I try to import `ImagePickerManager` from `NativeModules` directly, the problem gone.

**Comment by marcshilling** [comment]
@pheye the Example project works fine without using `ImagePickerManager` directly, so I'm not sure what you're doing wrong.
