### ISSUE TITLE
Thumbnail uri for the camera roll

### ISSUE THREAD

**Issue by philjoseph** [react-native-community/react-native-image-picker#457]
I do not find in the response object anyway to display the video thumbnail.I've just found out that [Aakash Sigdel](http://stackoverflow.com/users/1924443/aakash-sigdel) is suggesting that this is doable. Any idea?

**Comment by marcshilling** [comment]
I'm not sure how to do this off the top of my head. Would accept a PR.

**Comment by enieber** [comment]
It's is very cool to implementat in video response.

one example of implementation may be this:

```js

\\ config object

const optionsVideo = {
  Thumbnail: true,
  mediaType: 'video',  
}

\\ get video 

ImagePicker.launchCamera(optionsVideo, (response)  => {
    base64fromVideo = response.thumbnail
}) 
```

**Comment by nica0012** [comment]
Any news on this?
