### ISSUE TITLE
Duplicate image in folder Pictures

### ISSUE THREAD

**Issue by nhatchimai111** [react-native-community/react-native-image-picker#468]
![duplicate image](https://cloud.githubusercontent.com/assets/13510054/22770034/a87451d2-eebf-11e6-9709-4f64d6a7315b.png)

When I take photo then react-native-image-picker will create folder with 2 images same.

**Comment by finch001** [comment]
this happen to me  my device is android7.1.1

**Comment by rusfearuth** [comment]
@finch001 Could you check where first and second photos store? I guess why it could happen.

**Comment by finch001** [comment]
it seem that Duplicate image all store in /storage/emulated/0/Android/data/com.photodemo/files/Pictures @rusfearuth

**Comment by radjivF** [comment]
Any update on this one, I have the same problem in 2019 :'(

**Comment by suvro24** [comment]
Any update on this one? I am still facing this issue.

**Comment by username199327** [comment]
this also happened to the current app i'm working on, are there any updates on this?

**Comment by DmitryGlobalbit** [comment]
Hi, I'm having the exact same issue. Any update regarding this bug?

**Comment by imanshu1** [comment]
Still facing this issue in Motorola Phones

**Comment by lucasR23** [comment]
i am also still facing this issue but in redmi note 7

**Comment by AnurajDev** [comment]
This issue is still live!

**Comment by Kamony** [comment]
had similar issue,
resolved by setting another storage destination path with option 

`storageOptions: {
    cameraRoll: true
  }`

**Comment by devanshsadhotra25** [comment]
don't provide `storageOptions` and u won't see the issue
