### ISSUE TITLE
Android: App restart on come back from take photo

### ISSUE THREAD

**Issue by luisfuertes** [react-native-community/react-native-image-picker#471]
I am testing the app in a device with 1GB RAM and when app come back from take a photo, app restart. 

How can i prevent the app is closed while i take the photo?

**Comment by luisfuertes** [comment]
Ok, i had install react-native-image-picker v0.24.0 with rn v0.33.

When i downgrade to react-native-image-picker to 0.23.0, it works

**Comment by rusfearuth** [comment]
Do you take a photo with max size?

**Comment by luisfuertes** [comment]
Yes, this is my code:
```
let options = {
        quality: 1,
        mediaType: 'photo',
        cameraType: 'front',
        maxWidth: PixelRatio.getPixelSizeForLayoutSize(Commons.Constrains.max_picture_width), // photos only
        maxHeight: PixelRatio.getPixelSizeForLayoutSize(Commons.Constrains.max_picture_height), // photos only
        takePhotoButtonTitle: multiStrings.takePhoto,
        chooseFromLibraryButtonTitle: multiStrings.fromDevice,
      };

      ImagePicker.showImagePicker(options, (res) => {
        if (res.uri) {
          if (Platform.OS === 'ios') {
            var image = {isStatic: true , uri: res.uri.replace('file://', ''), data: 'data:image/jpeg;base64,' + res.data}
          }else{
            var image = {isStatic: true , uri: res.uri, data: 'data:image/jpeg;base64,' + res.data}
          }
          dispatch(registerActions.changePhoto(image))
        }
      });
```

**Comment by rusfearuth** [comment]
If I remember right, I saw that library rotates image by means rotating bitmap. It is potential please for OOM.
I can check it tomorrow.

**Comment by rusfearuth** [comment]
The ram size doesn't meter. Android gives some memory limit for run app. If you don't think about memory limit, you'll get problem with OOM or something like this.

**Comment by rusfearuth** [comment]
Hmm... There is fine... but might be able crash. I think what I can do for fix this bug and will send PR.

**Comment by rusfearuth** [comment]
@luisfuertes Could you give more information about photo size?

**Comment by luisfuertes** [comment]
@rusfearuth ofcourse:
My code:
Width: PixelRatio.getPixelSizeForLayoutSize(600)
Height: PixelRatio.getPixelSizeForLayoutSize(400)

In console log: 
Width:  1200
Height:  800

**Comment by rusfearuth** [comment]
@luisfuertes and could you give information about taken photo? I mean how many Mb and etc.

**Comment by rusfearuth** [comment]
@luisfuertes is it possible to get logcat output?

**Comment by IvanCaceres1** [comment]
Hello.

I'm using react native 0.42.0 (latest) with react 15.4.2 (latest) and react-native-image-picker 0.26.0 and i'm  experimenting the same issue but only when the app open first time.

regards.

**Comment by tanaka0x** [comment]
Sometimes I faced same issue with react-native-image-picker 0.26.1
I tried to find the cause from logcat, but I have not found it.

[logcat_when_restared.txt](https://github.com/marcshilling/react-native-image-picker/files/829340/logcat_when_restared.txt)

```
ImagePicker.showImagePicker({
      mediaType: 'photo'
    }, (response) => {
      if (response.didCancel) {
        this.setState({
          ...this.state,
          pickImageError: null
        })
        return
      }

      if (response.error) {
        this.setState({
          ...this.state,
          pickImageError: response.error
        })
        return
      }

      this.setState({
        ...this.state,
        pickImageError: null,
        book: {
          ...this.state.book,
          iconUrl: response.uri
        }
      })
    })
```

**Comment by rexjrs** [comment]
any updates on this?

**Comment by rexjrs** [comment]
This happens to me on Android 7.1.1 

Google Pixel

**Comment by rexjrs** [comment]
CAM_ActivityCloser: WARNING: Activity was artificially finished: CameraActivityController: Intent completed with a valid result. Closing activity.

**Comment by haitaoli** [comment]
The camera intent launches the camera app, so your own app now runs in the background. An Activity should be able to handle restarts, which can happen in many scenarios including orientation change. I don't think this is something `react-native-image-picker` can control.

**Comment by hosembafer** [comment]
I have this problem too, is there more progress? What to do, wait or switch to another package? And if anyone know the details of problem, can you explain?

**Comment by haitaoli** [comment]
Android can decide to close background activities for various reasons including low memory. When the app is switched back to foreground, the activity is re-created using the serialized state data. Your app has to handle this state change. Unfortunately the pointer to react-native-image-picker module cannot be serialized. So the image picker result gets lost. There isn't an easy solution right now. :( If it's caused by orientation change, there is a way to avoid restarting activity: 
https://stackoverflow.com/questions/4568558/how-to-avoid-restarting-activity-when-orientation-changes-on-android

**Comment by dgurns** [comment]
Any update on this?

Has anyone been able to successfully take photos on Android without app restarting?

**Comment by deepeshkarkee** [comment]
There is a high chance that this is not a React Native issue, rather that of your phone(Only Android) settings. Try this:
1. Go to Settings > Developer options.
2. Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
3. Disable it IF it's enabled. (If its disabled, then this solution is not for you)
4. Try running the file upload now. It should work.


****** Description: 
  - Don't keep activities - destroys every activity as soon as the user leaves it.
  - React native image picker opens system's file system using React-native-fs. 
 - At this point your  RN app becomes a background app, which is destroyed by the setting in step 3. 
 - This is the case with all apps that use native file systems. Thats the reason some apps like facebook, messanger, whatsapp etc have their own native filesystem.

Happy coding

**Comment by nateReiners** [comment]
RN 55.4 Android 8.0.0 This happens for me after I make an apk and install that on my phone but it doesn't happen when I build to my real device (connected via usb) with react-native run-android. odd

**Comment by ishita-kothari** [comment]
Hello,
My react native app restarts when I click photo and then click on the tick button to get the response about my photo clicked. Can anyone please help
RN: 0.55.4
react-native-image-picker: 0.26.10
android/build.gradle: classpath 'com.android.tools.build:gradle:3.1.0'

**Comment by ivanarielcaceres** [comment]
Good Morning!
It happens to me when I use expo locally. Once I publish works perfectly to upload images and take a picture. It must be some phone settings.

**Comment by deepeshkarkee** [comment]
Hi Ishita,
Did you do as I suggested above?

Regards,
Dipesh Karki
Mumbai, India
Ph: +91 9920735197
Skype: deepeshkarkee

**Comment by VicEsquivel** [comment]
@ivanarielcaceres Hey hello, what do you mean by publish? When you assemble a release apk this doesnt happen but it does in debug apk releases?

Because it is happening to me when I assemble a debug apk and fresh new install it. In some devices during the first run it crashes and the whole app is restarted under the message of OutOfMemory

**Comment by ivanarielcaceres** [comment]
Hello @VicEsquivel, yes. 
When i publish the apk using expo publish, it's works perfectly!
But when i trying to debug locally the app crash the first time. It's something weird issue, maybe something about phone permissions.

**Comment by mohitsingh90** [comment]
> Hello,
> My react native app restarts when I click photo and then click on the tick button to get the response about my photo clicked. Can anyone please help
> RN: 0.55.4
> react-native-image-picker: 0.26.10
> android/build.gradle: classpath 'com.android.tools.build:gradle:3.1.0'



> Hello,
> My react native app restarts when I click photo and then click on the tick button to get the response about my photo clicked. Can anyone please help
> RN: 0.55.4
> react-native-image-picker: 0.26.10
> android/build.gradle: classpath 'com.android.tools.build:gradle:3.1.0'

I also having the same problem please provide the solution if you have.

**Comment by DavitVosk** [comment]
Could anyone solve this problem?

**Comment by Return-1** [comment]
Still facing this

**Comment by Flouwrian** [comment]
> There is a high chance that this is not a React Native issue, rather that of your phone(Only Android) settings. Try this:
> 
> 1. Go to Settings > Developer options.
> 2. Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
> 3. Disable it IF it's enabled. (If its disabled, then this solution is not for you)
> 4. Try running the file upload now. It should work.
> 
> ****** Description:
> 
> * Don't keep activities - destroys every activity as soon as the user leaves it.
> * React native image picker opens system's file system using React-native-fs.
> * At this point your  RN app becomes a background app, which is destroyed by the setting in step 3.
> * This is the case with all apps that use native file systems. Thats the reason some apps like facebook, messanger, whatsapp etc have their own native filesystem.
> 
> Happy coding

I had this issue and this solved it for me

**Comment by wengkitt969696** [comment]
I facing this issue on older android devices. The app restart itself after I select image from the gallery. Anyone have any solution other than this ?

> There is a high chance that this is not a React Native issue, rather that of your phone(Only Android) settings. Try this:
> 
> Go to Settings > Developer options.
> Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
> Disable it IF it's enabled. (If its disabled, then this solution is not for you)
> Try running the file upload now. It should work.
> ****** Description:
> 
> Don't keep activities - destroys every activity as soon as the user leaves it.
> React native image picker opens system's file system using React-native-fs.
> At this point your RN app becomes a background app, which is destroyed by the setting in step 3.
> This is the case with all apps that use native file systems. Thats the reason some apps like facebook, messanger, whatsapp etc have their own native filesystem.
> Happy coding

This is what happening to me: 
![ezgif com-optimize](https://user-images.githubusercontent.com/33577934/87136695-6f9f8c00-c2ce-11ea-850d-ec6e56ebd4de.gif)

**Comment by HugoGresse** [comment]
Can we re-open the issue? as stated in the linked Expo issue, this is still happenning on newer Sony Xpera model, without any developer option enable.

**Comment by komelabbbas** [comment]
Could anyone solve this problem ??
plz help if anyone already find solution
