### ISSUE TITLE
i cant open select from library after removing camera permission

### ISSUE THREAD

**Issue by talalmajali** [react-native-community/react-native-image-picker#515]
Hello, 
Thank you for this great module,
But i'm facing an issue, i only need to access the library without camera, so i have only removed camera permission from AndroidManifest (WRITE_EXTERNAL_STORAGE still there), after that i couldn't manage to open the library, 
and when i ignored these lines of code: ImagePickerModule:265
if (!permissionsCheck(currentActivity)) {
  return;
}
it worked,
any help ?

**Comment by rusfearuth** [comment]
Hi. I see your case.
Year, you can use it like this.

Thank you. It'll be implemented in the next releases.

Please will not close this issue until it's done from my side.

**Comment by nikhilag** [comment]
Is there any update on this issue? I need a way to just select a picture from gallery instead of relying on camera.
I don't want to add a privacy policy for our app since we don't really need the camera.
