### ISSUE TITLE
undefined is not an object(evaluating 'ImagePickerManager.showImagePicker'

### ISSUE THREAD

**Issue by gzfgeh** [react-native-community/react-native-image-picker#522]
"react": "^15.4.2",
    "react-native": "^0.42.0",
    "react-native-image-picker": "^0.24.1"

**Comment by gzfgeh** [comment]
chooseHeadPic(){
        let options = {
            title: "b",
            takePhotoButtonTitle: '拍照',
            chooseFromLibraryButtonTitle: '相册',
            cancelButtonTitle: "a",
        };

        ImagePicker.showImagePicker(options, (response) => {
            if (response.didCancel) {
                ToastAndroid.show("用户取消", ToastAndroid.SHORT);
            } else if (response.error) {
                ToastAndroid.show("出错了", ToastAndroid.SHORT);
            } else if (response.customButton) {
                ToastAndroid.show("用户点击", ToastAndroid.SHORT);
            } else {
                let source = { uri: response.uri };

                // You can also display the image using data:
                // let source = { uri: 'data:image/jpeg;base64,' + response.data };

                this.setState({
                    avatarSource: source.uri
                });

                this.uploadFile(response.uri, response.fileName);

            }
        })
    }

**Comment by gzfgeh** [comment]
![Uploading image.png…]()

**Comment by Coramo** [comment]
same issues in react-native-image-picker@0.26.2 and react-native@0.42.3

**Comment by rusfearuth** [comment]
@gzfgeh Hi! How did you import `ImagePicker`? Could you show that line?

**Comment by qiangxinyu** [comment]
@gzfgeh  clean  ios/build  and android/build

**Comment by gzfgeh** [comment]
let ImagePicker = require('react-native-image-picker'); and i clean ios/build and android/build  ,
but the same error, i have the error three days

**Comment by qiangxinyu** [comment]
```
  YiLiPeiUser git:(master) npm install react-native-image-picker@latest --save


YiLiPeiUser@0.0.1 /Users/qiangxinyu/Desktop/YiLiPeiUser
└── react-native-image-picker@0.26.2

➜  YiLiPeiUser git:(master) ✗ react-native link
Scanning 562 folders for symlinks in /Users/qiangxinyu/Desktop/YiLiPeiUser/node_modules (4ms)
rnpm-install info Linking react-native-image-picker android dependency
rnpm-install info Android module react-native-image-picker has been successfully linked
rnpm-install info Linking react-native-image-picker ios dependency
rnpm-install info iOS module react-native-image-picker has been successfully linked
rnpm-install info Android module react-native-splash-screen is already linked
rnpm-install info iOS module react-native-splash-screen is already linked
➜  YiLiPeiUser git:(master) ✗ cd ios
➜  ios git:(master) ✗ rm -rf build
➜  ios git:(master) ✗ cd ..
➜  YiLiPeiUser git:(master) ✗ cd android
➜  android git:(master) ✗ rm -rf build
➜  android git:(master) ✗ ls
app               build.gradle      gradle            gradle.properties gradlew           gradlew.bat       keystores         settings.gradle
➜  android git:(master) ✗ cd ..
➜  YiLiPeiUser git:(master) ✗ react-native run-android
```

That is what i did

you can create new object try,

**Comment by encorex** [comment]
same here.....

**Comment by cseelus** [comment]
Tried all version from 0.24.0 up to the current master, always getting `undefined is not an object (evaluating 'ImagePickerManager.showImagePicker')`

**Comment by fanzhiri** [comment]
looking for answer

**Comment by marcshilling** [comment]
Generally this error means you've failed to properly link the native library. I'd recommend walking through the manual installation instructions in the README (don't use react-native link)

**Comment by fanzhiri** [comment]
My problem has been resolved . react-native link is good , after that , go to the project dir ios/ double click the project file {xxx}.xcodeproj , click the {Build and run the current scheme } button , and then close the Xcode , run the command react-native run-ios , that is ok . thanks marcshilling .

**Comment by cosydney** [comment]
I'm having a similar issue.

I followed the Readme from react-native-image-picker with both manual and automatic linking (tried both separately).

When I launch simulator from terminal using react-native run-ios I get the error. When launching from Xcode it works fine, I can access the CameraRoll picker no problem.

Here are the versions I'm using:

```"react-native": "0.43.3",
"react-native-image-picker": "^0.26.3",```

I saw a similar thread here [stackoverflow](http://stackoverflow.com/questions/40018381/undefined-is-not-an-objectevaluating-imagepickermanager-showimagepicker) and it seems I'm not the only one having this issue.

Thank you for helping.

The full error:
```
undefined is not an object (evaluating 'ImagePickerManager.showImagePicker')

showImagePicker
    index.js:28:30
selectPhotoTapped
    CamPick.js:31:32
touchableHandlePress
    TouchableOpacity.js:126:45
_performSideEffectsForTransition
    Touchable.js:746:34
_receiveSignal
    Touchable.js:664:44
touchableHandleResponderRelease
    Touchable.js:433:24
invokeGuardedCallback
    ReactErrorUtils.js:30:9
executeDispatch
    EventPluginUtils.js:99:42
executeDispatchesInOrder
    EventPluginUtils.js:127:20
executeDispatchesAndRelease
    EventPluginHub.js:37:46
forEachAccumulated
    forEachAccumulated.js:30:16
processEventQueue
    EventPluginHub.js:227:8
runEventQueueInBatch
    ReactEventEmitterMixin.js:18:35
handleTopLevel
    ReactEventEmitterMixin.js:38:25
<unknown>
    ReactNativeEventEmitter.js:113:8
perform
    Transaction.js:149:24
batchedUpdatesWithControlledComponents
    ReactGenericBatching.js:51:26
_receiveRootNodeIDEvent
    ReactNativeEventEmitter.js:111:40
receiveTouches
    ReactNativeEventEmitter.js:200:8
__callFunction
    MessageQueue.js:244:47
<unknown>
    MessageQueue.js:108:26
guard
    MessageQueue.js:46:4
callFunctionReturnFlushedQueue
    MessageQueue.js:107:10```

**Comment by sidd607** [comment]
I am facing the same issue. I am building app using CRNA

**Comment by aahmed19** [comment]
+1 on create react native app

**Comment by aaronhma** [comment]
Where should I install the react-native-image-picker properly?

**Comment by denghejun** [comment]
+1

**Comment by pacozaa** [comment]
+1

**Comment by yummyelin** [comment]
I fixed by add NSPhotoLibraryUsageDescription, NSCameraUsageDescription keys to Info.plist, [manually link](https://github.com/react-community/react-native-image-picker#manual-installation)
