### ISSUE TITLE
Memory consumption grows largely when using maxWidth/maxHeight options

### ISSUE THREAD

**Issue by jozan** [react-native-community/react-native-image-picker#523]
I see something like 30-40 MB more memory allocations when using cropping options. This is quite a bummer for lower end devices which I'd like to support. Now I just have to deal with full size image and it's a bit issue as well since I'm uploading it to the server.

Are there any plans to try to reduce memory consumption in the future releases?

And by the way, cool library. Huge thanks for maintainers/contributors! 👍

**Comment by rusfearuth** [comment]
@jozan I can say that You'd get OOM in some other cases ;) like this #471 
I'm working on it

**Comment by jozan** [comment]
Right. Thanks for the reply. Looking forward to solution. :)

**Comment by maggialejandro-rp** [comment]
@rusfearuth  Any updates on this issue? Thanks for the work
