### ISSUE TITLE
IOS: Cannot Dowload Photo

### ISSUE THREAD

**Issue by GuelorEmanuel** [react-native-community/react-native-image-picker#524]
Does anyone know how to resolve the following issue, getting an alert message "There was an error downloading this photo from your iCloud Photo Library. Please try again"

**Comment by vivekshah-zymr** [comment]
@GuelorEmanuel  I am facing the same issue. Have you found any solution?

**Comment by ferostar** [comment]
Same here. Any clues?

**Comment by vivekshah-zymr** [comment]
@ferostar, Haven't found any solution. Please let us know if you have any update.

**Comment by VivekSharma-zymr** [comment]
Cannot pick the iCloud photo from the gallery in iOS.

**Comment by skyforeverGE** [comment]
I believe this lib almost dead
