### ISSUE TITLE
image is not converting to base64

### ISSUE THREAD

**Issue by shaikhussian** [react-native-community/react-native-image-picker#525]
Hai,
  When i try to convert the image to base64 it is not showing the correct base64 format. Here is the line of code i used for base64 conversion
`let source = { uri: 'data:image/jpeg;base64,' + response.data }`
But it not showing correct base64 image

**Comment by gbenga504** [comment]
I am also having the same issue.  When I try to get the base64 encode of images.  I get undefined returned

**Comment by gbenga504** [comment]
Solved mine already,  the line of code is correct. Try console logging your result from dataURI to make sure that dataURI actually exists.  And make sure that you don not have data of response object pointing to null or undefined and finally make sure no middleware is intercepting and performing an operation

**Comment by ShanthiSenguttuvan** [comment]
Me too used the same let source = { uri: 'data:image/jpeg;base64,' + response.data }
 and got error  bad base-64

**Comment by yasserzubair** [comment]
Can anybody help me on this? Can't get this to work. the string does not convert to image.

**Comment by ShanthiSenguttuvan** [comment]
Use fs module to create image,
import ImagePicker from 'react-native-image-picker';
var fs=require('fs');
ImagePicker.showImagePicker(options, (response) => {
fs.writeFile(Location, response.data, 'base64', function(err) {
          if(err){
                  console.log('Error', err);
          }
          else{
                 console.log('file created');
          }
   });
});

**Comment by yasserzubair** [comment]
I solved the problem myself. You need to do 
`let source = 'data:image/jpeg;base64,' + response.data`
instead of 
`let source = { uri: 'data:image/jpeg;base64,' + response.data }`

**Comment by DavitVosk** [comment]
Any success?
