### ISSUE TITLE
Error: react-native-image-picker:processReleaseResources

### ISSUE THREAD

**Issue by Nygma297** [react-native-community/react-native-image-picker#531]
```
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-picker:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log

BUILD FAILED
```

Any Suggestions?

**Comment by rusfearuth** [comment]
@Nygma297 RN version? React-native-image-picker version? Android build configs?

**Comment by Nygma297** [comment]
@rusfearuth shows this in package.json
```    "react-native": "0.42.0",
    "react-native-image-picker": "^0.26.2",
```

**Comment by Nygma297** [comment]
Any Help? @rusfearuth

**Comment by rusfearuth** [comment]
@Nygma297 hmm... Strange. I've been trying to repeat...

**Comment by Ashu-Shah** [comment]
After install this packege @Nygma297 @rusfearuth i am also getting this error.

**Comment by Nygma297** [comment]
Are You using Windows @Ashu-Shah ?

**Comment by Ashu-Shah** [comment]
yes i am using windows 10.

**Comment by Nygma297** [comment]
Do you have a mac/linux/ubuntu?

**Comment by Ashu-Shah** [comment]
@Nygma297 No i dont have. there is no solution for windows???

**Comment by Nygma297** [comment]
I had to link it using mac @Ashu-Shah but I couldn't pinpoint a solution for windows!

**Comment by Ashu-Shah** [comment]
@Nygma297 I got the solution from [here](https://github.com/marcshilling/react-native-image-picker/issues/221).

**Comment by SalviShahzad** [comment]
I am using macOS 10.13.2 facing the same problem. any solution?

**Comment by kapil708** [comment]
I am using macOS 10.13.2 facing the same problem. any solution?

**Comment by giriallada** [comment]
I'm using linux mint.Any solution?

**Comment by MadGeorge** [comment]
MacOS 10.13.5 same exception

**Comment by RajaSaravanan** [comment]
https://github.com/react-community/react-native-image-picker/issues/882
It worked!

**Comment by platonish** [comment]
Faced the same issue, solved it using the solution linked by @RajaSaravanan. Here's the gist: add the following lines to the bottom of your `android/build.gradle`: 
```gradle
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26 // <-- match this to your project's compileSdkVersion
                buildToolsVersion '26.0.3' // <-- match this to your project's buildToolsVersion
            }
        }
    }
}
```

the project's `compileSdkVersion` and `buildToolsVersion` are available under `ext {...}`

**Comment by NickOpen** [comment]
It's works for me @RajaSaravanan , thanks ：）

**Comment by goldnetonline** [comment]
Hi All,

Conformed @platonish solution worked as of September 4 2018.

Thanks mate.

**Comment by jmsbrett** [comment]
@platonish you are awesome.

**Comment by jordangrant** [comment]
@platonish props to you sir, thank you so much!

**Comment by casper123** [comment]
> Faced the same issue, solved it using the solution linked by @RajaSaravanan. Here's the gist: add the following lines to the bottom of your `android/build.gradle`:
> 
> ```groovy-gradle
> subprojects {
>     afterEvaluate {project ->
>         if (project.hasProperty("android")) {
>             android {
>                 compileSdkVersion 26 // <-- match this to your project's compileSdkVersion
>                 buildToolsVersion '26.0.3' // <-- match this to your project's buildToolsVersion
>             }
>         }
>     }
> }
> ```
> 
> the project's `compileSdkVersion` and `buildToolsVersion` are available under `ext {...}`

This doesn't work for me, is there anything else i can try ?

**Comment by jmsbrett** [comment]
@casper213
Make sure your compileSdkVersion and buildToolsVersion match your project, if they do try running these cleaning the gradle wrapper file with commands:

mac/linux:
cd android
./gradlew clean

windows: 
dir android
./gradlew clean
