### ISSUE TITLE
Compatibility with Android 4.4.4 (KitKat)

### ISSUE THREAD

**Issue by WajeehZantout** [react-native-community/react-native-image-picker#533]
The latest version crashes the gallery after confirming an image took with the camera. I used v.0.22.13, it worked.

**Comment by firdausious** [comment]
Same here.. I'm using same code as the example, but it crash immediately

I'm using :
- Node v. 7.7.1
- RN : 0.42.0

**Comment by rusfearuth** [comment]
@firdausious Have you used Android emulator or real device?

**Comment by firdausious** [comment]
@rusfearuth I've tested both on 
Device (Xiaomi Red Mi 2 - Android 4.4.4) and 
Emulator (Genymotion Nexus 7 - Android 5.0.0) has the same error (crash)

Using : 
- Node v.7.7.1
- RN v.0.42.0
- with Macbook Pro

**Comment by WajeehZantout** [comment]
@firdausious Use react-native-image-picker v.0.22.13 instead. It worked on that version

**Comment by a113f** [comment]
Android 4.4 cano't emulated react-native... error: unable to load script from assets "index.android.bundle"...
