### ISSUE TITLE
Android cameraRoll gives: Error moving image to camera roll

### ISSUE THREAD

**Issue by MilosR** [react-native-community/react-native-image-picker#545]
On Android, cameraRoll option won't work, following error appears on console, the com.xxx is the name of my package:

``
ImagePicker Error: Error moving image to camera roll: /app_images/Android/data/com.xxxxx/files/Pictures/image-953bd538-17e5-4976-8a0e-c6146c099799.jpg: open failed: ENOENT (No such file or directory)
``

If i an pick option to load image from gallery everything works as expected. Here is how image picker is initiated:

```
import ImagePicker from 'react-native-image-picker';

...

var options = {
    title: 'Select image',
    noData: true,
    storageOptions: {
        skipBackup: true,
        cameraRoll: true,
    }
};

...

ImagePicker.showImagePicker( options, (response) => {
    console.log(response);   // response.error contains message above
});
```

In android manifest i have added following permissions

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Android 6.0.1 CM13 (Samsung Galaxy S4)
RN v0.42.3
react-native-image-picker - develop with #516

**Comment by rusfearuth** [comment]
@MilosR Could you describe algorithm for reproducing that bug?

**Comment by MilosR** [comment]
Changing the line line of onActivityResult
`final File oldFile = new File(uri.getPath());`

to
`final File oldFile = new File(getRealPathFromURI(uri));`

fixes the problem for for me.

path with uri.getPath():
`/app_images/Android/data/com.xxxxx/files/Pictures/image-953bd538-17e5-4976-8a0e-c6146c099799.jpg`

path with getRealPathFromURI(uri):
`/storage/emulated/0/Android/data/com.xxxxx/files/Pictures/image-953bd538-17e5-4976-8a0e-c6146c099799.jpg`

So that was a cause of ENOENT (No such file or directory).

Also, uri returned in response object in case of library pick have` content://` prefix, don't know why and now with cameraRoll  it will have `file://`, that should be uniformed, probably the better option is `file://`.

I saw that you are doing some refactoring, maybe you have already resolved this issues, but i wanted to mention just in case.

**Comment by rusfearuth** [comment]
@MilosR I've pushed PR with fixing of current problem. You may check it.

**Comment by demogar** [comment]
Any update on this PR? Looking forward on implementing this fix on my code.
