### ISSUE TITLE
can't see options

### ISSUE THREAD

**Issue by rishiankush** [react-native-community/react-native-image-picker#546]
I am not able to see the options when background color is white or transparent.
There is no such property to add color option.

Here is the screenshot:
![screen shot 2017-04-09 at 7 37 07 am](https://cloud.githubusercontent.com/assets/25289937/24834043/a8cac510-1cf7-11e7-857a-3de378e27eec.png)

**Comment by marcshilling** [comment]
I'm not sure how this is possible. Are you using `UIApperance` anywhere in your iOS code to style action sheets?

**Comment by rishiankush** [comment]
No, I am just using the simple example code you have provided. Please check my code below:
```
selectPhotoTapped() {
    let context = this;

    const options = {
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      allowsEditing: true,
      storageOptions: {
      skipBackup: true
       }
    };

    ImagePicker.showImagePicker(options, (response) => {
    if (response.didCancel) {
      console.log('User cancelled photo picker');
    }
    else if (response.error) {
      console.log('ImagePicker Error: ', response.error);
    }
    else if (response.customButton) {
      console.log('User tapped custom button: ', response.customButton);
    }
    else {
      let source = {};
      if (Platform.OS === 'android')
        source = {uri: response.uri, isStatic: true};
      else
        source = {uri: response.uri.replace('file://', ''), isStatic: true};
      context.setState({imageSource: source});
      context.updatePhoto();
    }
    });
  }
```

**Comment by stief510** [comment]
I am having this problem on Android, the links are white

**Comment by jaredrhodes** [comment]
Having the same issue on Android. Changing `android/src/main/res/layout/list_item.xml:8` to `android:textColor="#000000"` fixes it but definitely isn't the real solution. Wondering where that value might be getting set incorrectly or overwritten elsewhere.

**Comment by jaredrhodes** [comment]
Found a fix for my situation. Added a Splash Screen and in `YOURPROJ/android/app/src/main/res/values/styles.xml` I needed:
```xml
<style name="SplashTheme" parent="Theme.AppCompat.Light.NoActionBar">
```
instead of
```xml
<style name="SplashTheme" parent="Theme.AppCompat.NoActionBar">
```

**Comment by Mrityunjay2903** [comment]
I am having this problem on Android, the links are white on "react-native-image-picker": "^2.3.4" version

**Comment by Mrityunjay2903** [comment]
add this line into your project_name\android\app\src\main\res\values\styles.xml
inside style tag 
 <item name="android:textColorAlertDialogListItem">#000000</item>
i hope it will fix your Problem in Android
