### ISSUE TITLE
Android storageOptions does not seem to be implemented for videos

### ISSUE THREAD

**Issue by ericvillemure** [react-native-community/react-native-image-picker#551]
reading the documentation it seems like if I use the following settings the file will be saved in a 'private' folder
```javascript
  ...
  storageOptions: {
    cameraRoll: false,
  },
```

Unfortunately, it only seems to work for pictures and not videos.  I would like the videos taken from my app to not appear in the 'public' library

I have not tested it in iOS

**Comment by rusfearuth** [comment]
@ericvillemure Is it Android bug?

**Comment by rexjrs** [comment]
var options = {
  title: 'Select meal image',
  storageOptions: {
    skipBackup: true,
    cameraRoll: true,
  },
  quality: 0.8,
  mediaType: 'photo',
  maxHeight: 2000,
  maxWidth: 1000
};

I'm on Android. I set cameraRoll to true but cannot find the images in the gallery or photos app after taking a picture.

**Comment by ranjitpandit** [comment]
@ericvillemure I'm seeing the same issue. Even if I set the cameraRoll to 'false, videos recorded using the module are always getting saved on the Android cameraRoll. Were you able to find a fix?

**Comment by rickcha** [comment]
I ran into the same issue. On Android, it always saves to the global DCIM folder regardless of the value I set for storageOptions.cameraRoll. On iOS, it works well.

**Comment by dolphinflow86** [comment]
Same issue here on Android.

**Comment by 0xcodezero** [comment]
Videos on Android are shown in the gallery despite the value of storageOptions!. It works as expected in iOS.

**Comment by petergaultney** [comment]
Can confirm that this happens consistently on Android and not iOS.

Worse, some Android galleries seem to retain references to those videos even after they've been  moved to somewhere else on the filesystem. It's quite confusing.

**Comment by vinay93** [comment]
Any updates on this issue would be appreciated.
I am able to save photos in the custom folder but no luck with storing videos it always gets stores in 0/DCIM/Camera
