### ISSUE TITLE
Android API 19 - ImagePickerModule.java:732

### ISSUE THREAD

**Issue by ptfly** [react-native-community/react-native-image-picker#552]
### Description

It's crashing when trying to "Take a Picture" under Android API 19.
I'm getting a red screen without an error message but stating the issue location: 
`ImagePickerModule.java:732` which corresponds to `path.mkdirs();` 

It's happening on an emulator and on a real device!

Screenshot: https://cloud.githubusercontent.com/assets/1925966/24944081/1f5664b6-1f62-11e7-9b72-dc0c9cb2c194.png

### How to repeat issue and example

Build on emulator set to run Android API 19, and try to take a picture with the following code:
`const options = {
            quality:1,
            noData:true,
            mediaType:'photo',
            allowsEditing:false
};
ImagePicker.launchCamera(options, (response) => console.log(response));` 

### Solution

Some investigation around the ability to create newly captured file in that specific directory, may be it does't exists on that Android version by default?! 

### Additional Information

* React Native version: 0.43.0
* Platform: Android API 19
* Development Operating System: MacOS

**Comment by rusfearuth** [comment]
@ptfly Please use ISSUE TEMPLATES! I've added that for describing bug!

**Comment by ptfly** [comment]
@rusfearuth ok, sorry for that :)

**Comment by rusfearuth** [comment]
@ptfly please correct your issue description with this template:

```
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android
```

I've added it to avoid asking routine questions.

**Comment by ptfly** [comment]
@rusfearuth Done, you can delete all comments bellow the original issue to keep it clean :)

**Comment by rusfearuth** [comment]
@ptfly Tnx )

**Comment by aarontrank** [comment]
This is a KitKat permissions issue (KitKat is funky).  Resolvable by adding following code in ImagePickerModule before calling: currentActivity.startActivityForResult(cameraIntent, requestCode);

Added this block of code at line 269:

```
    // Workaround for Android bug.
    // grantUriPermission also needed for KITKAT,
    // see https://code.google.com/p/android/issues/detail?id=76683
    if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
      List<ResolveInfo> resInfoList = reactContext.getPackageManager().queryIntentActivities(cameraIntent, PackageManager.MATCH_DEFAULT_ONLY);
      for (ResolveInfo resolveInfo : resInfoList) {
        String packageName = resolveInfo.activityInfo.packageName;
        reactContext.grantUriPermission(packageName, cameraCaptureURI, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
      }
    }
```
