### ISSUE TITLE
IPad will have an error

### ISSUE THREAD

**Issue by liyangwood** [react-native-community/react-native-image-picker#556]
error message
 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [PUUIAlbumListViewController shouldAutorotate] is returning YES'

when only use for IPad and make the app orientation is landscape left and landscape right.

**Comment by haitaoli** [comment]
@liyangwood This answers your question: http://stackoverflow.com/questions/25090167/set-shouldautorotate-to-false-with-photolibrary
It's a limitation in iOS UIImagePickerController. You have to enable portrait mode in your app.
