### ISSUE TITLE
File type null

### ISSUE THREAD

**Issue by vzhen** [react-native-community/react-native-image-picker#557]
Here is the response. Is the file itself problem or the module?
```
data: "LONG_STRING"
fileName: "IMG_1576 (1).png"
fileSize: 1073263
height: 1136
isVertical: true
originalRotation: 0
path: "/storage/emulated/0/Download/IMG_1576 (1).png"
type: null
uri: "content://media/external/images/media/36"
width: 640
```

Version
"react": "16.0.0-alpha.6",
"react-native": "0.43.2",
"react-native-image-picker": "^0.26.2",

Devices
Windows 7 64bits
Android emulator 7.1.1

**Comment by alecbennett** [comment]
This looks like it is related to #744 and is likely due to the space in the file name.  In the short term, until a fix is available, I added a 'null' check and use react-native-file-type to do a quick check on 'response.path', which correctly returns the file type/ext.

**Comment by vzhen** [comment]
Ok, thanks for the suggestion.

**Comment by ankitwandx** [comment]
Looks like not just space in the file name is causing this issue:

fileName: "DSCN0905.JPG"
fileSize: 3171851
height: 3456
isVertical: true
originalRotation: 0
path: "/storage/emulated/0/bluetooth/DSCN0905.JPG"
timestamp: "2018-05-31T12:43:14Z"
**type: null**
uri: "content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2Fbluetooth%2FDSCN0905.JPG"
width: 4608

**Comment by chgsilva** [comment]
any updates on this? 

same issue here

**Comment by ankitwandx** [comment]
I am using react-native-file-type to get the filetype if this returns NULL

**Comment by chgsilva** [comment]
i am using the same workaround for a while, thanks.

**Comment by omererbil** [comment]
i have resolved this issue by
```
  ImagePicker.launchImageLibrary(options, (response) => {

    if (response.didCancel) {
    } else if (response.error) {
    } else if (response.customButton) {
    } else {
      if(response.type==null){
        response.type='image/jpeg'
        response.fileName='image'

      }
      }
  });
}
```

**Comment by deCodeIt** [comment]
> i have resolved this issue by
> 
> ```
>   ImagePicker.launchImageLibrary(options, (response) => {
> 
>     if (response.didCancel) {
>     } else if (response.error) {
>     } else if (response.customButton) {
>     } else {
>       if(response.type==null){
>         response.type='image/jpeg'
>         response.fileName='image'
> 
>       }
>       }
>   });
> }
> ```

This will only work if the choosen file type is either JPEG or JPG, not for PNG and others
