### ISSUE TITLE
NullPointerException while cancel

### ISSUE THREAD

**Issue by rayshih** [react-native-community/react-native-image-picker#559]
### Description

Found fatal exception which recorded by crashlytics. Here is the log

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
       at com.imagepicker.ResponseHelper.invokeResponse(ResponseHelper.java:76)
       at com.imagepicker.ResponseHelper.invokeCancel(ResponseHelper.java:63)
       at com.imagepicker.ImagePickerModule.doOnCancel(ImagePickerModule.java:187)
       at com.imagepicker.ImagePickerModule$2.onCancel(ImagePickerModule.java:173)
       at com.imagepicker.utils.UI$3.onCancel(UI.java:88)
       at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

Seems like there is a chance that "cancel" be triggered twice, but the `callback` is null in the second time.

### How to repeat issue and example

Don't know how to repeat.

### Solution

Add null check before the invocation. Maybe add events that inform JS realm that there is an error.

### Additional Information

* React Native version: 0.42
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio 2.3

**Comment by kashyapp** [comment]
This crash is most likely from the permission explaining dialog. There are code paths where `this.callback` is set _after_ the permissions check. And the permissions dialog invokes `doOnCancel` if the user cancels it.

**Comment by kbeckmann** [comment]
I've seen a bunch of this one in production as well. React native 0.43.3 and react-native-image-picker 0.26.3 (plus an unrelated patch).

I can reproduce it by repeatedly pressing the button in my app that calls ImagePicker.showImagePicker() and then as fast as possible press "cancel" on the native dialog that pops up. Can trigger it after around 2-3 tries.

**Comment by kbeckmann** [comment]
I haven't tried to find the root cause but if you need a quick patch you can add a null-check and set the callback to null. This works around the issue for me at least. It feels a bit dirty and there is probably a cleaner way to solve it.

ImagePickerModule.java:
```
  public void doOnCancel()
  {
+   if (callback != null) {
      responseHelper.invokeCancel(callback);
+     callback = null;
+   }
  }
```

**Comment by hugski** [comment]
same crash, hopes to fix the bug.

**Comment by kbeckmann** [comment]
This project seems abandoned. @hugski I recommend you to fork and apply my patch manually.
