### ISSUE TITLE
how to change the color of the takePhotoButtonTitle, chooseFromLibraryButtonTitle

### ISSUE THREAD

**Issue by loodsite** [react-native-community/react-native-image-picker#560]
### Description

How to change the color of the takePhotoButtonTitle, chooseFromLibraryButtonTitle to "red", e.g?
I managed to change the background color, the color of the title and cancel button with code below.
![dialog-buttons-color](https://cloud.githubusercontent.com/assets/27905975/25309745/5eee62ba-27d5-11e7-9ac4-6e2b9634c230.png)

### Source code

`<resources>

    
    <style name="DefaultExplainingPermissionsTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
	      
        <item name="android:background">#eeeeee</item>

        
        <item name="android:textColor">#000000</item>

        
        <item name="android:textColorPrimary">#ff0000</item>

        
        <item name="colorAccent">#4dcaba</item>
    </style>

</resources>
`

### Solution

Add option buttonTitleColor.

### Additional Information

* React Native version: 0.43.1
* Platform: Android
* Development Operating System: Linux

**Comment by imarem** [comment]
Hi @loodsite 

How have you done to customize the dialog as well? I'm trying to do the same and I can't adapt it.

Could you show me how you import the customize in the theme?

Thanks for advance!

**Comment by colorfulberry** [comment]
@imarem  @loodsite  How do you solve it with the end?

**Comment by colorfulberry** [comment]
github.com +### Directly Launching the Camera or Image Library + + To Launch the Camera or Image Library directly (skipping the alert dialog) you can + do the following: + 
```javascript + // Launch Camera:
 ImagePicker.launchCamera(options, (responseType, response) => { // Same code as in above section! + });
// Open Image Library: +
 ImagePicker.launchImageLibrary(options, (responseType, response) => { + // Same code as in above section! + }); 
 ```

Then you can custom the selecor.

**Comment by imarem** [comment]
@colorfulberry Exactly. Using each of the options separately.

;)

**Comment by colorfulberry** [comment]
@imarem Yeah,  you are correct.

**Comment by salimbutex** [comment]
Hi guys,
I am having same issue, in my case, text color is white... I tried 
<style name="DefaultExplainingPermissionsTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
        
        <item name="colorAccent">#000000</item>

        
        <item name="android:textColorPrimary">#000000</item>

        
        <item name="android:background">#dddddd</item>
    </style>

I am getting out put like 
https://image.prntscr.com/image/6CCuT8wqQ4S7Lw7xlHR4jg.png

look here, text color is white. although I did not set any whote...
I tried to use buttonTitleColor as option. did not work.

RN Version : 4.1
"react-native-image-picker": "^0.26.7",

thanks for any response.

**Comment by adamivancza** [comment]
This seems to be an undocumented feature but actually you can customize theme in two ways:
* Create a theme.xml inside android/app/src/res/values folder and create a style named `DefaultExplainingPermissionsTheme`. Example: https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/res/values/themes.xml
* You can also pass your own theme to the constructor of the package. You just need to replace `new ImagePickerPackage()` with `new ImagePickerPackage(R.style.MyCustomTheme).
For example: https://github.com/react-community/react-native-image-picker/blob/develop/Example/android/app/src/main/java/com/example/MainApplication.java#L29
Reference: https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/java/com/imagepicker/ImagePickerPackage.java#L24

**Comment by salimbutex** [comment]
great thanks for your response bro... 
I just need to change text color...
android:textColorPrimary or android:textColor... nothing works...

**Comment by Hektar90** [comment]
If someone is still looking for an answer:

I added to my AppTheme

`<item name="android:textColorAlertDialogListItem">YOUR_COLOR</item>`

**Comment by mo-ah-dawood** [comment]
My fix is to create a layout called list_item.xml it will override the default one

> `<?xml version="1.0" encoding="utf-8"?>
<TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@android:id/text1"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:textAppearance="?android:attr/textAppearanceMedium"
    android:textColor="@color/primary_light"
    android:fontFamily="@font/tajawal"
    android:gravity="center_vertical"
    android:paddingTop="15dp"
    android:paddingBottom="15dp"
    android:paddingLeft="25dp"
    android:paddingRight="25dp"
    android:ellipsize="marquee"
    />` 


>\android\app\src\main\res\layout\list_item.xml

**Comment by rajendersha** [comment]
I am still facing same issue as mentioned by @selimonline. 

Tried almost every solution but not able to change the text color of take photo.. and choose from library... buttons.

Please help!

**Comment by mbernardes19** [comment]
Just for the record if anyone else faces this issue again in the future: update the lib to 3.xx because from that version on there's no `showImagePicker` to show the modal, just the `launchCamera` and `launchImageLibrary` methods, therefore you can make your own modal or actionsheet and call those methods from them.
