### ISSUE TITLE
react-native-image-picker not working in android 7.0

### ISSUE THREAD

**Issue by AndrewJikun** [react-native-community/react-native-image-picker#561]
react-native-image-picker not working in android 7.0.

**Comment by rusfearuth** [comment]
@AndrewJikun we have special template for issue. Will you be so kinds as to use it?

**Comment by rheilgm** [comment]
same as mine, but its only restarting right after clicking "Take Photo..." option
something like `android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/image-048cc0c7-97a7-4b01-a673-d2cc884a5124.jpg exposed beyond app through ClipData.Item.getUri()`

**Comment by mesbahsabur** [comment]
Works for me... On a Galaxy S8.
I do get  an app crash when I use 'Take Photo' and then use 'react-native-camera' (of visa versa). Crash does not occur on simulator (Android 6) or on iOS.

**Comment by Calvin92** [comment]
@mesbahsabur The same .  simulators are OK but Android device crashed..   So  how did you fix it?

**Comment by mesbahsabur** [comment]
@Calvin92 I haven't yet. But I got a reply on the community facebook page that they have started testing this library on devices. Hope there is a quick fix. Otherwise, I may use  react-native-crop-picker for the time being.

**Comment by Calvin92** [comment]
@mesbahsabur Oh,  thank u.  Such being the case, I will try to user `react-native-crop-picker` .

**Comment by faceach** [comment]
is this issue fixed? @AndrewJikun

**Comment by santhosh77h** [comment]
Is this issue fixed?

**Comment by santhosh77h** [comment]
Update app it will solve this issue

**Comment by GopiKrishna10** [comment]
hi Guys,
i am still facing a issue when I take the picture and press OK button the app get restarted.in all mobiles like redmi note4 and moto g2. am trying to resolve from one day. am not able to solve this can u please help me thanks in advance 

i update the version react-native-image-picker from 0.26.3 to 0.22.9. app getting like "unfortunately app has stopped" showing pop up like this.

config

"react-native": "^0.42.3",
"react-native-image-picker": "0.22.9"
db is firebase

options are

var options = {
title: 'Select Avatar',
quality: 0.6,
storageOptions: {
skipBackup: true,
path: 'images'
}
};

**Comment by WhoJave** [comment]
Any solutions on crash

**Comment by SudoPlz** [comment]
Actually that issue is a duplicate of https://github.com/react-community/react-native-image-picker/issues/732

**Comment by deepeshkarkee** [comment]
**Possible Solution:**

There is a high chance that this is not a React Native issue, rather that of your phone(Only Android) settings. Try this:

Go to Settings > Developer options.
Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
Disable it IF it's enabled. (If its disabled, then this solution is not for you)
Try running the file upload now. It should work.
****** Description:

Don't keep activities - destroys every activity as soon as the user leaves it.
React native image picker opens system's file system using React-native-fs.
At this point your RN app becomes a background app, which is destroyed by the setting in step 3.
This is the case with all apps that use native file systems. Thats the reason some apps like facebook, messanger, whatsapp etc have their own native filesystem.
Happy coding

**Comment by Shahzadkhan99** [comment]
same problwm with me when i upload file from image picker the app crash,

**Comment by Aubynj** [comment]
Well try to downgrade react-native-imagepicker from v0.28.0 to v0.27.0

**Comment by aacassandra** [comment]
I encountered the same problem, and I managed to overcome it. this is actually just a matter of licensing. not much different from "Ionic". we need to add this in AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.example">

    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

```

**Comment by Michaelvons** [comment]
Solved !!

After installing the package, open your android project for Gradle to build (~43 minutes for me. maybe network). Stop the metro server, uninstall the previous app in your emulator, run `npm install` and finally run `npx react-native run-android `. This should work.

**Comment by surendrasourcesoft** [comment]
I am facing same https://github.com/react-native-community/react-native-image-picker/issues/561#issuecomment-297229488 issue in android.

**Comment by mosheFuks** [comment]
I was facing the same issue when trying to open the camera on Android 7. This solution works for me: 
const writeStorageGranted =
          (await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          )) === PermissionsAndroid.RESULTS.GRANTED;
This code goes on the code when you ask for the granted permissions.

Image Picker version: 4.10.0
