### ISSUE TITLE
Works Great on iPhones 5 & 6, but Crashes on iPhone 7

### ISSUE THREAD

**Issue by sheprdinc** [react-native-community/react-native-image-picker#562]
Image Picker Version: 0.26.2
My RN Version: 42

Devices Test on:
iPhone 5/5s: works always
iPhone 6/6+: works always
iPhone 7: "Choose from Library" works always, but "Take Photo" crashes the app (always)
iPhone 7+: "Choose from Library" works always, but "Take Photo" crashes the app (always)

**Comment by Liqiankun** [comment]
What is the IOS version of them?

**Comment by Liqiankun** [comment]
What are their ios versions? if iPhone 7 running iOS 10.You need add the `NSPhotoLibraryUsageDescription`, `NSCameraUsageDescription`, and `NSMicrophoneUsageDescription` (if allowing video) keys to your `Info.plist` with strings describing why your app needs these permissions.

**Comment by zengyanzi** [comment]
I added already, but my iPhone 6 crashed as well.
React native version is 41
image picker version is "^0.26.3",
iOS is 10.3.1
Thanks a lot

**Comment by dhawanheena26** [comment]
Any update on this issue?

**Comment by GuillaumeMunsch** [comment]
For me the keys are called "Privacy - Camera Usage Description" for the camera and "Privacy - Photo Library Usage Description" for the Library.
Check is the issue doesn't come from the simulator itself that doesn't have any camera.

**Comment by dhawanheena26** [comment]
I missed "Privacy - Microphone Usage Description" in info.pilist , added that and it worked .
Thanks a lot :)
