### ISSUE TITLE
Permissions weren't granted on Android

### ISSUE THREAD

**Issue by enguerranws** [react-native-community/react-native-image-picker#563]
I'm testing an app which is using react-native-image-picker on my Android devices. It's working on iOs, not on Android.

Here's what I've done:
```
export function getImageFromLibrary () {

  let options = {
    quality: 1.0,
    maxWidth: 500,
    maxHeight: 500,
    storageOptions: {
      skipBackup: true
    }
  };

  return dispatch => {

    dispatch(requestImageFromLibrary())

    return ImagePicker.showImagePicker(options, (response) => {

      let responseObj = {};

      if (response.didCancel || response.error) {
          responseObj = {
            success: false,
            errorMessage: response.error,
            uri: response.uri
          };
          dispatch(receiveImageFromLibraryErr(responseObj));
      }

      else {

        responseObj = {
          success: true,
          uri: response.uri
        };
        dispatch(receiveImageFromLibrary(responseObj));
        // let source = { uri: 'data:image/jpeg;base64,' + response.data };


      }

    });
  }

}
```
```
<TouchableOpacity onPress={this.props.getImageFromLibrary}>
            <Text>Choose picture</Text>
</TouchableOpacity>
```
Here's what happen:
- I can tap the Choose picture
- it opens the "Select a photo" menu
- whether I tap Take photo or Choose from library, it logs an error "Permissions not granted" 

I uninstalled the app / reinstalled it, checked my application permissions in Android settings, but it never ask me for more permissions.

What do I miss? Should I use another module, like https://github.com/yonahforst/react-native-permissions?

**Comment by kevinmcampos** [comment]
Any lucky on this?

Checkout your AndroidManifest.xml and see if it has these lines of code:

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

This library already handle Android permissions, you don't need any other permission library for use it.

**Comment by cshen4** [comment]
I'm having the same problem and my AndroidManifest.xml looks like this: 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.CAMERA" />build

    <uses-sdk
        android:minSdkVersion="19"
        android:targetSdkVersion="25" />
`...`

**Comment by jeremyeaton89** [comment]
Having similar problem after upgrading from React Native 0.39.2 to 0.50.3, where on Android, any selection from #showImagePicker yields error: Permissions weren't granted

**Comment by josephmagara** [comment]
Because your targetSdkVersion is 25, you need to request for permission from the user during runtime. 
Checkout these docs for more info [https://developer.android.com/training/permissions/requesting.html](Requesting Permission during Runtime). 
There are also a number of libraries that help with handling the process of requesting permissions during runtime.

**Comment by jeremyeaton89** [comment]
Thanks for the info @josephmagara. Looks like adding `android:targetSdkVersion` to uses-sdk, everything worked again :)

**Comment by josephmagara** [comment]
@jeremyeaton89 You're welcome :)

**Comment by jeremyeaton89** [comment]
Sorry, @josephmagara, i'm actually still having issues. posted naive, temp solution https://github.com/react-community/react-native-image-picker/pull/758

but, keep getting denied `WRITE_EXTERNAL_STORAGE`. noticed it's not required for sdk >= 19 so made small patch/workaround for now

**Comment by AdamChrist** [comment]
+1 same problem

**Comment by codegoblins** [comment]
Make sure your `uses-permission` declaration in `AndroidManifest.xml` isn't:

```
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
    tools:node="remove"
/>
```

Although it may look like the this line grants you permissions, `tools:node="remove"` deletes the required permissions if included from another library. See [here](https://developer.android.com/studio/build/manifest-merge.html) for more details.

You want:

```
<uses-permission
    android:name="android.permission.WRITE_EXTERNAL_STORAGE"
/>
```

**Comment by bikalay** [comment]
I added 
```
<uses-permission-sdk-23 android:name="android.permission.CAMERA"/>
<uses-permission-sdk-23 android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
and it works for me

**Comment by basheerkohli** [comment]
Got to this file Your Project Name\android\app\build.gradle"
and change the  targetSdkVersion to 23 and above.Then u can see by default the run time permissions are not enabled in the app settings.

**Comment by foo4foo** [comment]
> I added
> 
> ```
> <uses-permission-sdk-23 android:name="android.permission.CAMERA"/>
> <uses-permission-sdk-23 android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> ```
> and it works for me

@bikalay Thank you !

**Comment by dakkafex** [comment]
Still existing issue, all applicable  permissions are granted but when using the imagepicker(either library or camera) I still get the error back with "permissions weren't granted"

**Comment by Rikinp5** [comment]
I am facing the same issue, tried adding 
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
but it still shows permission denied

**Comment by Martyneris** [comment]
I still have this issue when trying to use `ImagePicker.showImagePicker` 

"react-native": "0.64.2"
"react-native-image-picker": "^1.1.0"

In Android manifest I have tried both examples - removing the CAMERA and WRITE_EXTERNAL_STORAGE permissions and adding them with <uses-permission-sdk-23

In all cases I get {error: "Permissions weren't granted"}
