### ISSUE TITLE
.3gp video format freezes app when selected by image picker

### ISSUE THREAD

**Issue by larryranches** [react-native-community/react-native-image-picker#570]
When selecting a .3gp video format video from the ios camera roll, the app freezes. There is no hard crash that happens nor can it hit any logs within the ImagePicker.launchImageLibrary() promise that returns the file information.

* React Native version: 0.43.3
* Platform: IOS
* Development Operating System: MacOS

**Comment by zachrnolan** [comment]
+1 having the same issue

**Comment by GeoffreyPlitt** [comment]
Note that this is one of the most popular video formats on mobile
