### ISSUE TITLE
Android device always OOM

### ISSUE THREAD

**Issue by JimmyDaddy** [react-native-community/react-native-image-picker#572]
### Description
 
Some Android device with low ram always crash because of OOM

### Solution
I edited the source code at `MediaUtils.java`,function `getResizedImage` with the code below:
```
try {
      photo = BitmapFactory.decodeFile(realPath, options);
    } catch (OutOfMemoryError e) {
      System.out.print(e.getMessage());
      while(photo == null) {
        System.gc();
        System.runFinalization();
        photo = BitmapFactory.decodeFile(realPath, options);
      }
    }
```
and 
```
try {
      scaledphoto = Bitmap.createBitmap(photo, 0, 0, photo.getWidth(), photo.getHeight(), matrix, true);
    } catch (OutOfMemoryError e) {
      System.out.print(e.getMessage());
      while(scaledphoto == null) {
        System.gc();
        System.runFinalization();
        scaledphoto = Bitmap.createBitmap(photo, 0, 0, photo.getWidth(), photo.getHeight(), matrix, true);
      }
    }
```
It will resolve my problem. Do you have a better solution for this? Can you fix it?

**Comment by haitaoli** [comment]
@JimmyDaddy try this: https://github.com/react-community/react-native-image-picker/pull/565. The reason I didn't merge the change is because it might lower the resized image quality if device has enough memory to load the full resolution image.
