### ISSUE TITLE
On denying permissions for first time and trying to allow it again it shows ReTry?

### ISSUE THREAD

**Issue by sahil290791** [react-native-community/react-native-image-picker#575]
### Description

On denying permissions for first time and trying to allow it again it shows ReTry. 
I was expecting it to ask for permission again, instead of showing ReTry and sending the user to app settings screen.

After going through other apps with camera permission, there it asks for permission from within the app to access camera and does not send the user outside of the app to `settings -> apps`.

### How to repeat issue and example

Install a new app. 
- Click on camera icon
- deny permissions
- click on camera icon again
- it shows to retry

### Solution

How can i get the same dialog for allowing the user to allow camera and gallery access instead of sending them to settings page.

### Additional Information

* React Native version: 0.42.3
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio 2.2.3

**Comment by MihailDemchenko** [comment]
Use this solution.
https://github.com/react-community/react-native-image-picker/issues/330
