### ISSUE TITLE
[iOS] fileName is not the same as actual file name?

### ISSUE THREAD

**Issue by mesbahsabur** [react-native-community/react-native-image-picker#576]
### Description

When I pick a photo from the Library, the response.fileName is not the same as the file name in response.uri. When I take  a photo, there is no response.fileName at all. I have storageOptions enabled, as well as storageOptions.waitUntilSaved.

I can't use response.uri to save the photo to local storage, because of this reason: [Link](http://aplus.rs/2013/never-save-absolute-file-paths-in-your-ios-app/)

So I use this to return the actual file name: 
```
        let source = response.uri;
        
        if (Platform.OS === 'ios') {
          var subsource = source.substr(source.length - 40)
        }
```
Then, I use react-native-fs to generate a dynamic uri to the file.

### Example response object (this is when I pick from Library)

```
fileName:"IMG_0637.JPG"
fileSize:3016009
height:1500
isVertical:false
latitude:52.34070833333333
longitude:4.676461666666667
origURL:"assets-library://asset/asset.JPG?id=7DC370EF-5937-4AF6-A6E8-E8016D348568&ext=JPG"
timestamp:"2017-04-23T12:21:45Z"
uri:"file:///var/mobile/Containers/Data/Application/A7F68ABA-DD58-4123-ACFD-AF1596A3EE62/Documents/AD69F6C9-4E1F-45C1-BEC9-06FA1180A29A.jpg"
width:2000
```

### Solution

Something like response.uriFileName that matches the file name in uri would be ideal.

### Additional Information

* React Native version: 0.43.3
* React Native Image Picker version: 0.26.3
* Platform: iOS
* Development Operating System: macOS

**Comment by cosmith** [comment]
Thank you for this issue! My files were disappearing for no apparent reason, but in fact I was rebuilding after every run, so the local URI was obsolete.

I agree that having `response.uriFileName` or similar would be a good idea.

**Comment by burennto** [comment]
Both `storageOptions.cameraRoll` AND `storageOptions.waitUntilSave` need to be true in order for captured media to have fileName and timestamp.

This is mentioned in #394 and I've submitted #658 to update the README.

**Comment by jojomillenium** [comment]
I have the same issue on iOS (Android all good), when taking from Library, with 
```js
storageOptions: {
    path: 'myPath',
    waitUntilSaved: true,
    cameraRoll: true,
    skipBackup : true
},
```
fileName returned is still like : ```IMG_0002.jpg``` and the uri has a filename like ```DFE43C-C0C3-4534-B3E0-C895BA7DD5A1.jpg```

- "react-native": "0.57.8",
- "react-native-fs": "^2.13.2",
- "react-native-image-picker": "^0.28.0"

**Comment by Biplovkumar** [comment]
Still smae issue in  "react-native-image-picker": "^1.1.0",

**Comment by SwathyPA** [comment]
Same here

**Comment by omar-fk** [comment]
same here
