### ISSUE TITLE
Got Crashed on Open library/camera in iPad and my app only in landscape mode

### ISSUE THREAD

**Issue by sw-tt-keyurprajapati** [react-native-community/react-native-image-picker#587]
**Crash Log Reason:**

*** Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [PUUIAlbumListViewController shouldAutorotate] is returning YES'

If any specific solution available.

**Comment by aprihodko** [comment]
Do not block the orientation in project settings

**Comment by rstr74** [comment]
Had this problem also in when compiled for IOS 10, and then found out that you can use a popup representation by changing UIModalPresentationCurrentContext to UIModalPresentationPopover in  ImagePickerManager.m. 

This seems to work for the case you only have landscape mode enabled in Deployment Info section at app target options.

You can change the file ImagePickerManager.m in  Libraries/RNImagePicker.xcodeproj folder in your xcode project. (beware that this file is linked to the react-native-image-picker node_module. So when you update npm modules beware that your changes can be undone).

in ImagePickerManager.m seach for UIModalPresentationCurrentContext and you find this code:

**original**
```objective-c
    self.picker.modalPresentationStyle = UIModalPresentationCurrentContext;
    self.picker.delegate = self;

    // Check permissions
    void (^showPickerViewController)() = ^void() {
        dispatch_async(dispatch_get_main_queue(), ^{
            UIViewController *root = RCTPresentedViewController();
            [root presentViewController:self.picker animated:YES completion:nil];
        });
    };
```

and than change it to something like this:

**modified**
```objective-c
  
    self.picker.modalPresentationStyle = UIModalPresentationPopover;
    self.picker.delegate = self;

    // Check permissions
    void (^showPickerViewController)() = ^void() {
        dispatch_async(dispatch_get_main_queue(), ^{
            UIViewController *root = RCTPresentedViewController();
            [root presentViewController:self.picker animated:YES completion:nil];
            CGRect sourceRect = CGRectMake(root.view.frame.size.width/2-200, root.view.frame.size.height/2 - 300, 400, 400);
            
            self.picker.popoverPresentationController.sourceRect = sourceRect;
            self.picker.popoverPresentationController.sourceView = root.view;
        });
    };
```

**Comment by sw-tt-keyurprajapati** [comment]
@tysoncadenhead and @rstr74 
Thank You :)
Both solution individually woking fine.
