### ISSUE TITLE
React/RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by CC10559** [react-native-community/react-native-image-picker#591]
my react-native version is 0.44.0,also have this problem,what can i do,i try many ways to solve it,but not work,help me

**Comment by namecjk** [comment]
in Xcode Bug

"'React/RCTBridgeModule.h' file not found"

/Users/XXXXXXX/Desktop/React-native/Db_App/node_modules/react-native-image-picker/ios/ImagePickerManager.h:1:9: 'React/RCTBridgeModule.h' file not found
