### ISSUE TITLE
Accessing both Photos and Videos on Android

### ISSUE THREAD

**Issue by matthewfbenjamin** [react-native-community/react-native-image-picker#597]
### Description

Cannot access both Videos and Photos in the Android Gallery.

### Solution

Make it behave similarly to iOS with the 'mixed' type on the mediaType option

**Comment by jesperlndk** [comment]
Did anyone pick this one up yet?

**Comment by Noitidart** [comment]
Thanks @jesperlndk for linking this.

I think to get this feature, we need to land this code - https://github.com/react-community/react-native-image-picker/issues/759#issuecomment-353969584

I'm not sure how to get this code in, I'm not a good java/android guy. Would be awesome if the java/android guys out there can help land it.

**Comment by DavitVosk** [comment]
Any success on this?

**Comment by raquelcalado** [comment]
Any progress or news about it?
