### ISSUE TITLE
Ios 9 cannot open library or take photo 

### ISSUE THREAD

**Issue by dylanschirino** [react-native-community/react-native-image-picker#600]
Hi ! Is there an issue about ios 9 version which cannot open or take a picture ?

It work fine on ios 10 version but not under :/

**Comment by dylanschirino** [comment]
Bug fixed with enter in the info.plist on display name bundle :"YourNameApp" and the issues is solved ! Not understand exactly why but why not haha

**Comment by Nasirilahi** [comment]
@dylanschirino  Thanks, It also worked for me. and I also wasted my whole day finding the solution and finally this worked for me
