### ISSUE TITLE
Can't present view controller in iOS when the view controller of RN is pushed from a navigation controller.

### ISSUE THREAD

**Issue by yinanwang1** [react-native-community/react-native-image-picker#601]
The HXMyViewController added the rootView of RN and it is pushed from a navigation controller, as follow:
```
HXMyViewController *vc = [[HXMyViewController alloc] init];
    vc.view = self.rootView;
    
    [self.navigationController pushViewController:vc animated:YES];
```
In the react-native-image-picker framework, the RCT_EXPORT_METHOD(showImagePicker:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback) function in the ImagePickerManager.m file,
```
UIViewController *root = [[[[UIApplication sharedApplication] delegate] window] rootViewController];
        while (root.presentedViewController != nil) {
            root = root.presentedViewController;
        }
[root presentViewController:self.alertController animated:YES completion:nil];
```
The value of root is a UINavigationController, so invoke the presentViewController:animated: function don't display the alert controller.

**Comment by muzammil-triffort** [comment]
Any update on this ?
