### ISSUE TITLE
iOS: use QiNiu SDK upload a photo, need a fileName from response, but response do not back the fileName!

### ISSUE THREAD

**Issue by hanweixing** [react-native-community/react-native-image-picker#605]
version: 0.26.3
When i use this version, and i can not get the fileName. Then i open Xcode to debug, find that the usage of the foudation <Photos/Photos.h> used in react-native-image-picker maybe causes something wrong.
I find that these codes(in function `- (NSString * _Nullable)originalFilenameForAsset:(PHAsset * _Nullable)asset assetType:(PHAssetResourceType)type`) below went wrong:
`NSArray<PHAssetResource *> *pickedAssetResources = [PHAssetResource assetResourcesForAsset:asset];`
 pickedAssetResources became nil, so 
`if (error) {
                            NSLog(@"Error while saving picture into photo album");
                        } else {
                            // when the image has been saved in the photo album
                            if (assetURL) {
                                PHAsset *capturedAsset = [PHAsset fetchAssetsWithALAssetURLs:@[assetURL] options:nil].lastObject;
                                NSString *originalFilename = [self originalFilenameForAsset:capturedAsset assetType:PHAssetResourceTypePhoto];
                                self.response[@"fileName"] = originalFilename ?: [NSNull null];
                                // This implementation will never have a location for the captured image, it needs to be added manually with CoreLocation code here.
                                if (capturedAsset.creationDate) {
                                    self.response[@"timestamp"] = [[ImagePickerManager ISO8601DateFormatter] stringFromDate:capturedAsset.creationDate];
                                }
                            }
                            self.callback(@[self.response]);
                        }`
then `self.response[@"fileName"] = originalFilename ?: [NSNull null];` became nil.

So i have to set the parameter "fileName"in QiNiu SDK to a fixed value, like "123" in random and so on.

So i hope that someone can solve this problem, that's all.

**Comment by cloudsafe** [comment]
你可以用正则表达式获取文件名和mimeType我是这么做的。
