### ISSUE TITLE
Image Picker always go to response.didCancel in Android < 5

### ISSUE THREAD

**Issue by gabrielcandiag** [react-native-community/react-native-image-picker#606]
### Description

I'm using the library in my project, is working great in iOS and also in Android > 5, when i try to use the library in a Android version lower than 5 the response is always bringing **response.didCancel = true**, even if you press on **chooseFromLibraryButton** or **takePhotoButton**, so it never bring the data with the image. 

### How to repeat issue and example

    ImagePicker.showImagePicker(options, (response) => {
	      console.log('Response = ', response);

	      if (response.didCancel) {
              // Always enter here
	        console.log('User cancelled photo picker');
	      }
	      else if (response.error) {
	        console.log('ImagePicker Error: ', response.error);
	      }
	      else if (response.customButton) {
	        console.log('User tapped custom button: ', response.customButton);
	      }
	      else {
	        this.setState({ image : 'data:image/jpeg;base64,' + response.data });
	        this.postImage(this.state.image);
	      }
	    });

### Additional Information

* React Native version: 0.41.2
* Platform: Android
* Development Operating System: MacOS

**Comment by buskerone** [comment]
Same issue here. Can't find a fix for this.

**Comment by nexon** [comment]
Same issue here. Is a weird one.

**Comment by dgurns** [comment]
Any luck figuring this out? I'm getting it on Android 5.1.1, only when I do not have a default photo application set. If I do have a default photo application already set, then it works fine.

**Comment by gabrielcandiag** [comment]
In my case was an issue with the "launchMode" that is on the Android Manifest, that was causing that the activity in charge of selecting the pictures wasn't working. I fixed changing the launchMode to this:

android:launchMode="singleTop"

And with that it works.
