### ISSUE TITLE
only partial response data when using launchCamera

### ISSUE THREAD

**Issue by mbelgrader** [react-native-community/react-native-image-picker#607]
I need to get the height and width or at least isVertical of the video.
It is only in the response when picking from the gallery. 
When using launchCamera, I only get the video path.

Is there a way to get this information when launching the camera directly?

**Comment by angusmccloud** [comment]
@mbelgrader any luck with this? I've found (at least on android where the rotation matters) that the only data I get in the response is: height, timestamp, uri, and data - none of the other attributes described in the documentation.
