### ISSUE TITLE
GPS Location not available

### ISSUE THREAD

**Issue by claudioviola** [react-native-community/react-native-image-picker#608]
I'm working on Android device (Nexus 5) and I didn't receive any GPS from both: library and camera.

This is my options:
` const options = {
            title: 'Pick Picture',
            storageOptions: {
                skipBackup: true,
                path: 'images'
            }
        };`

In AndroidManifest I have follow settings:

`
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
`

This is the returned data when I try to take a picture:
`
data:"data of my picture"
fileName:"image-9dff3348-dbcc-4757-83a3-16e0c3e990db.jpg"
fileSize:1538608
height:3264
isVertical:true
originalRotation:0
path:"/storage/emulated/0/Pictures/image-9dff3348-dbcc-4757-83a3-16e0c3e990db.jpg"
type:"image/jpeg"
uri:"content://com.myapp.provider/app_images/Pictures/image-9dff3348-dbcc-4757-83a3-16e0c3e990db.jpg"
width:2448
`

How can I check if location services are enabled for the app?
Do I'm wronging somethings?
Thank you!

**Comment by haitaoli** [comment]
@claudioviola I suspect GPS metadata is stripped when image is resized. Could you try picking a small image while giving large `maxWidth` and `maxHeight` values?

**Comment by claudioviola** [comment]
@haitaoli thanks for support!
I followed your suggestion and I setted maxWidth: 8000, maxHeight: 8000, but unfortunately
I still don't see any Gps data in file...
Any idea?

Thanks again!

**Comment by sofianegargouri** [comment]
I'm having the same issue. I got all the picture data, except the location. 
Location services are allowed in the settings and service is available.

**Comment by maureentsakiris** [comment]
I'm having a similar issue on iOS 11. If I launch the camera through ImagePicker, the GPS data is not available. I do, however, receive GPS data if I 'pick' an image from the Photo Library taken with the standalone Camera App. 

These are my camera options (though the defaults didn't work either): 

`const options = { cameraType: 'back', mediaType: 'photo', quality: 0.8, noData: true,  allowsEditing: false }`

**Comment by rashmimhatre100** [comment]
Any breakthrough regarding GPS data??

**Comment by rashmimhatre100** [comment]
Added maxWidth : 8000 and maxHeight : 8000 to options and also keep your mobile settings, system app=>camera => Save location info **ON**. Now one can get lat/lng, also address is available in metadata.

      browseFile = ()=>{
      var ImagePicker = require('react-native-image-picker');
      var options = {
        quality       : 1,
        mediaType    : "photo",
        cameraType  : "back",
        allowsEditing : true,
        noData          : true,
        maxWidth      : 8000, 
        maxHeight     : 8000,
      };
      
      ImagePicker.showImagePicker((response) => {
        console.log('response: ', response);
        console.log('response latitude: ', response.latitude);
        console.log('response longitude: ', response.longitude);
      });
  }

     'response=> ', { height: 4208,
     width: 2368,
     type: 'image/jpeg',
     fileName: 'image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
     longitude: 73.93666076660156,
     path: '/storage/emulated/0/Android/data/com.assureidbackoffice/files/Pictures/image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
     timestamp: '2018-06-12T11:03:41Z',
     uri: 'content://com.assureidbackoffice.provider/app_images/Android/data/com.assureidbackoffice/files/Pictures/image-a58aedd4-bf19-467d-b872-e9a7c26ce0bd.jpg',
     data: 'image data',
     originalRotation: 0,
     latitude: 18.5183048248291,
     isVertical: true,
     fileSize: 3250731 }

**Comment by gtsluk** [comment]
when I use ImagePicker.launchCamera to take photo in IOS 11. The location metadata is lose. is it possible to pass the location information and by the option ?

**Comment by haifahrul** [comment]
@rashmimhatre100 Sometime get the GPS location and sometime not getting.

Any one can help?

**Comment by pankti1210** [comment]
@rashmimhatre100 i tried with the same solution but its not working..
