### ISSUE TITLE
Undefined is not an object (evaluating 'ImagePickerManager.showImagePicker') on Android

### ISSUE THREAD

**Issue by Kiarash-Z** [react-native-community/react-native-image-picker#609]
### Description

Hello I'm trying to use react native image picker but I get this error. I import that by require js and I have no problem with logging 
`console.log(ImagePicker.showImagePicker)`
it would show:
`function showImagePicker(options, callback) {
    if (typeof options === 'function') {
      callback = options;
      options = {};
    }
    return ImagePickerManager.showImagePicker(babelHelpers.extends({}…`
but when i call that as a function i get undefined is not an object.
note that i'm using wix react native navigation and my MainActivirt `extends `splashActivity and as it have written in Readme ( If MainActivity is not instance of ReactActivity, you will need to implement OnImagePickerPermissionsCallback to MainActivity )
my MainActivity is like code below
### How to repeat issue and example
```
import com.reactnativenavigation.controllers.SplashActivity;
import com.imagepicker.permissions.OnImagePickerPermissionsCallback;
import com.facebook.react.modules.core.PermissionListener;

public class MainActivity extends SplashActivity implements OnImagePickerPermissionsCallback {
  private PermissionListener listener;
  @Override
  public void setPermissionListener(PermissionListener listener)
  {
    this.listener = listener;
  }

  @Override
  public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults)
  {
    if (listener != null)
    {
      listener.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }
    super.onRequestPermissionsResult(requestCode, permissions, grantResults);
  }
}
```

### Additional Information

* React Native version:0.44.0
* Platform: Android
* Development Operating System: Windows

**Comment by qiudaoermu** [comment]
I also have this problem

**Comment by haitaoli** [comment]
`undefined is not an object` is happening in javascript code. Are you passing in valid `options` and `callback` parameters?

**Comment by saltas888** [comment]
Hi, you need to follow the instructions on Readme. You get this error because either you haven't link the project in to yours Android project either you did it but you didn't re-build it

**Comment by wff-** [comment]
@Kiarash-Z  Have you solved your problem?

**Comment by denghejun** [comment]
I got the same issue!

**Comment by dobiedad** [comment]
I just got this issue. It seems you need to rebuild after linking. Just call `react-native run-ios/android` after calling `react-native-link`

**Comment by pacozaa** [comment]
+1

**Comment by nak1b** [comment]
Inside your MainApplication.java file and search for `protected List<ReactPackage> getPackages() {`. You should find two declaration of this method. Add` new ImagePickerPackage()` in the second declaration.

**Comment by Thadeu** [comment]
I also have problem.

**Comment by Tony1106** [comment]
What I did to solve that problem is: 
1. Delete all the file of ImagePicker in NodeModule
2. Reinstall the package: npm install react-native-image-picker@latest --save
3. Shutdown completely the simulation.
4. Re-open the simulation again.
5. And it works now....
Good luck!!!

**Comment by Daneyl** [comment]
It's not working for me(in iOS) in any of the above given solutions.
Please help me out...
I have:
-restarted simulator after installing library
-followed manual instructions to link in iOS

**Comment by qiudaoermu** [comment]
just check the version






------------------ 原始邮件 ------------------
发件人: "Daneyl"<notifications@github.com>;
发送时间: 2018年6月27日(星期三) 晚上9:48
收件人: "react-community/react-native-image-picker"<react-native-image-picker@noreply.github.com>;
抄送: "北京-小白"<793385821@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [react-community/react-native-image-picker] Undefined is not anobject (evaluating 'ImagePickerManager.showImagePicker') on Android (#609)




It's not working for me(in iOS) in any of the above given solutions.
 Please help me out...
 I have:
 -restarted simulator after installing library
 -followed manual instructions to link in iOS

**Comment by thedanielforum** [comment]
I was struggling with this problem as well, so here is what worked for me.
I am using [wix/react-native-navigation](https://github.com/wix/react-native-navigation) routing, so my MainApplication is not the default config, hence the normal config didn't work.

Turns our I needed to add `new ImagePickerPackage()` to `createAdditionalReactPackages()`.

Here is my complete working MainApplication.java file: [gist: MainApplication.java](https://gist.github.com/thedanielforum/31288f514900bd71edde114c9939dbd1)

**Comment by abhishek-here** [comment]
You need to rebuild the project after installing and linking the react-native-image-picker using react-native run-android or using android studio

**Comment by Digant312** [comment]
I also faced the same issue in Android. It was linking issue, solved with below steps.
https://github.com/react-native-community/react-native-image-picker/blob/HEAD/docs/Install.md
