### ISSUE TITLE
How to resize or scale before converting to base64

### ISSUE THREAD

**Issue by yasserzubair** [react-native-community/react-native-image-picker#614]
### Description
Whenever I capture an image or choose from gallery, I want to resize it before converting to base64 uri and then get the base 64 uri of the resized image.

**Comment by haitaoli** [comment]
@yasserzubair check out `maxWidth` and `maxHeight`: https://github.com/react-community/react-native-image-picker#options

**Comment by VivekVithlani** [comment]
@yasserzubair in this document I have not found maxWidth, maxHeight document,
Can you please let me know If I set `maxWidth:500` then image filter with size <= 500 (does not display image more then 500 px width.) or when I select Image then the image will convert width 500px.
