### ISSUE TITLE
Android 4.4.4 Samsung S3 take photo Restart APP/拍照或选择照片重启

### ISSUE THREAD

**Issue by Evan-Future** [react-native-community/react-native-image-picker#615]
Android 4.4.4
RN：v0.44.3
React-native-image-picker ：v0.26.3
Add permission：
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

Question description：
Choose to take pictures or albums to select a photo, APP directly restart automatically, this phenomenon is occasional, but the number of more. Sometimes you can normally take pictures and select photos. Higher 5.0 or higher Android version does not have this problem. Is it not enough memory? This was not the case before the RN and image-picker versions were not upgraded.

问题描述：
选择拍照或者相册选择一张照片后，APP直接自动重启了，这种现象属于偶发，但是次数较多。有时是可以正常完成拍照和选择照片。更高的5.0以上的Android版本没有这种问题。难道是内存不够？之前没有升级RN和image-picker版本之前没有出现过这种现象。

**Comment by MossP** [comment]
I've just noticed this also but haven't looked any further to ensure it's not an error at my end yet.

**Comment by MossP** [comment]
Did you add the permissions to `AndroidManifest.xml`? That's what was missing for me.
```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by haitaoli** [comment]
This could be caused by low memory. Does the phone with lower Android version have less memory? You can try selecting large and small photos to verify.

**Comment by huangdou0204** [comment]
@MossP  yes， I've added it and forgot to write it。

**Comment by huangdou0204** [comment]
@haitaoli OK， thx！

**Comment by gregol** [comment]
i have the same issue on android 4.1 and 4.4, on android 6.0 works fine

**Comment by Clowning** [comment]
On Android 7.0 it's not working...

**Comment by cloudsafe** [comment]
@huangdou0204 怎么加的文件大小限制

**Comment by JsonRuby** [comment]
add `largeHeap=true` in mainfest.xml

**Comment by Clowning** [comment]
@JsonRuby Where in the manifest ?

**Comment by Clowning** [comment]
Hot to fix:

Make sure you are using gradle 2.2.x:

 classpath 'com.android.tools.build:gradle:2.2.3'
Add this in your app gradle:

android {
...
defaultConfig {
...
vectorDrawables.useSupportLibrary true
...
}

**Comment by dgurns** [comment]
largeHeap=true did not work for me

RN: 0.44.2
Tried a bunch of different versions of react-native-image-picker, all of them had the same problem. Take photo on Android device > Confirm > App restarts.

However, choosing a photo from the library works fine.

**Comment by Rewieer** [comment]
Adding largeHeap = true on the Manifest is not the solution, it just labels your application as ressource gready, therefore making android giving you potentially more memory for your heap, or quite the contrary making it a good candidate for memory release on low memory condition.

I also face the same problem, still did not figure out how to fix it

**Comment by SudoPlz** [comment]
Actually that issue is a duplicate of https://github.com/react-community/react-native-image-picker/issues/732

**Comment by yuzhi27** [comment]
对于华为，在拍照后，触发下状态栏（往下滑动，点击状态栏），再点击确认，APP重启
