### ISSUE TITLE
Error: {Name} has stopped, open app again

### ISSUE THREAD

**Issue by theLallanTop** [react-native-community/react-native-image-picker#618]
* App crashes without an error after selecting image from album or clicking camera.

### Description

> It had been worked properly but suddenly start giving error. App crash line of console.log('Camera open'), only this line print in debug. 
>**ImagePicker.showImagePicker(options, (response) not responding anything.** 

### How to repeat issue and example

```
import ImagePicker from 'react-native-image-picker';

onPressUploadProfileImageButton = () => {
    console.log('Camera open');
    this.setState({ isDone: true });
    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        this.setState({ isDone: false });
      	console.log('camera picture did cancel');
      }
      else if (response.error) {
        this.setState({ isDone: false });
        console.log('camera picture did error');
      }
      else {
        console.log('camera picture else condition');
        this.setState({ isDone: false });
        let source = { uri: response.uri };
        console.log('source ===>>', source);
        let sourceData = { uri: `data:image/jpeg;base64,${response.data}`, isStatic: true, data: response.data };
				this.setState({ file:sourceData.data });
        this.setState({
          avatarSource: source
        });
      }
    });
};

```
>AndroidManifest.xml 

 ```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> 
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

### Additional Information

* React Native version: "0.41.0"
* react-native-image-picker@latest
* Platform:  iOS, Android Both
* Development Operating System: MacOS
* Dev tools: Xcode 8.3.2 and Android Studio 2.3 , iOS 10 or Android SDK version more than 7.1

All step of [installation](https://github.com/react-community/react-native-image-picker#install)

**Comment by duyleduc** [comment]
I have the same error but when I re-open the app and take picture, it works ! (on debug and on prod too)

**Comment by Clowning** [comment]
Same for me ...

**Comment by luisreiskeys** [comment]
same for me ...

**Comment by NainalChauhan** [comment]
Same for me, first time it is having ANR(Application not responding) in android and that's why the app crashed. I am not able to find any way to resolve this.
