### ISSUE TITLE
How to make it work using CRNA Template?

### ISSUE THREAD

**Issue by carlo-fontanos** [react-native-community/react-native-image-picker#620]
Hi, newbie in react native here.

I'm sure your plugin works great when installed on a non-CRNA installation, but I have an app made up of CRNA, I was wondering if your plugin currently supports it?

I've tried installing your plugin on my CRNA app, but i'm getting `undefined is not an object (evaluating 'imagepickermanager....` 

I couldn't do your manual installation steps from the README.MD because CRNA template doesn't have  `android` and `ios` folders.

**Comment by XeCtvi** [comment]
+1
