### ISSUE TITLE
Can't set cancelButtonTitle to null or empty string in android.

### ISSUE THREAD

**Issue by xuchenchenBoy** [react-native-community/react-native-image-picker#625]
When i write:

    const options = {
	    title: null,
	    cancelButtonTitle: '',
    };

    onOpenImgPicker() {
	  ImagePicker.showImagePicker(options, (response) => {
	      let { uri, fileName, } = response;
	      this.uploadQiniu(uri, fileName);	   	 
	  });
    }

And  error: 
     Atempt to read from field 'java.lang.String com.imagepicker.utils.ButtonsHelper Item.title' on a null object reference.

**Comment by guopeng1994** [comment]
me to ,same question
RN:0.47
picker:0.26.7

**Comment by vdlindenmark** [comment]
me to, same question but then for iOS... Didn't trigger any error.

**Comment by charmtiger** [comment]
me to ,same question

**Comment by fantasy525** [comment]
same question,RN:0.57.5 picker:0.27.1

**Comment by vdlindenmark** [comment]
Bots........ It's still an issue ;-)

**Comment by tudiantuan** [comment]
me to ,same question
RN: 0.60.0
picker: 1.1.0

**Comment by Johan-dutoit** [comment]
You are free to submit a PR.
