### ISSUE TITLE
[Android] App crash on release

### ISSUE THREAD

**Issue by duyleduc** [react-native-community/react-native-image-picker#626]
My app works perfectly on debug but does not on release, 
it causes : "App crahsed, open again" after taking a photo. 
Sometimes, application is blocked after displaying the taken photo on imageview.

App works on Ios device. 

Android version 7.0
My options: 
var options = {
  title: 'something goes here',
  maxWidth: 1024,
  maxheight: 1024,
  quality: 0.85,
  fileSize: 3145728,
  storageOptions: {
  }
};

**Comment by Clowning** [comment]
Same for me !

**Comment by LironeG** [comment]
Any update?

**Comment by duyleduc** [comment]
In my cas, it was an out of memory error, so I changed the code in Java but I don't make a pull request.

**Comment by Clowning** [comment]
@duyleduc  Can you share it ? please

**Comment by duyleduc** [comment]
@Clowning My code is in gist here: https://gist.github.com/duyleduc/4a5df3a04e15db229c6fe32de4d61a83
