### ISSUE TITLE
Nothing happens on Android 7

### ISSUE THREAD

**Issue by enguerranws** [react-native-community/react-native-image-picker#630]
Hi, 

I'm almost sure I read something about my issue before, but here it is: 
- on React Native 0.43.3
- using last react-native-image-picker version
- on my Android devices (Nexus 5x, Android 7 and Nexus 7, Android 6)
- I can open the "Select a Photo" modal
- whether a touch Take photo... or Choose from Library, it closes the modal but triggers no callback. 

>     ImagePicker.showImagePicker(options, (response) => {
> 
>       let responseObj = {};
>       console.log(response);
>       if (response.didCancel || response.error) {
>           responseObj = {
>             success: false,
>             errorMessage: response.error,
>             uri: response.uri,
>             data: response.data,
>             path: response.path
>           };
>           dispatch(receiveImageFromLibraryErr(responseObj));
>       }
> 
>       else {
> 
>         responseObj = {
>           success: true,
>           uri: response.uri,
>           data: response.data,
>           path: response.path
>         };
>         dispatch(receiveImageFromLibrary(responseObj));
>         // let source = { uri: 'data:image/jpeg;base64,' + response.data };
> 
> 
>       }
> 
>     });

Here's how I did that, it works well in iOs, not on my Android (physical) device. My console.log() returns nothing when I click on Take photo... or Choose from Library, but it returns `{didCancel: true}` when I choose Cancel on the modal.

Any idea on what's happening here?

**Comment by enguerranws** [comment]
For the record, I solved it using: https://github.com/react-community/react-native-image-picker/issues/373#issuecomment-257964787

I was missing:
```
<uses-feature android:name="android.hardware.camera" android:required="false"/>
<uses-feature android:name="android.hardware.camera.autofocus" android:required="false"/>
```
In AndroidManifest.xml

**Comment by enguerranws** [comment]
Should those two lines be added to the documentation (Android>Manual installation)?

**Comment by dasm30** [comment]
Not working for me, same android versions, did link and manual installation and still no callback and app crashes after a few seconds.

**Comment by LongYue9608** [comment]
Me to,Select the camera or library, and do not trigger the callback method,Have you solved it?
@dasm30

**Comment by dasm30** [comment]
@LongYue9608 I Can't remember if I found a solution or ended up using another library /:

**Comment by mauroporrasp** [comment]
@LongYue9608 I solved it using https://docs.expo.io/versions/latest/sdk/imagepicker
