### ISSUE TITLE
iOS 11 - NSPhotoLibraryAddUsageDescription required

### ISSUE THREAD

**Issue by cosmith** [react-native-community/react-native-image-picker#632]
### Description

Just a heads up for anyone trying to use this lib on iOS11 - you need to add `NSPhotoLibraryAddUsageDescription` in your Info.plist (see https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html)

### How to repeat issue and example

The app will crash on iOS 11 if you don't add `NSPhotoLibraryAddUsageDescription` with a message explaining why you need access to the photos.

### Additional Information

* React Native version: all
* Platform: iOS 11
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by DJNgoma** [comment]
The above didn't work for. Had to use ```NSPhotoLibraryUsageDescription``` instead on my end.

**Comment by cosmith** [comment]
To be clear I had to use both `NSPhotoLibraryUsageDescription` as specified in the readme and the new `NSPhotoLibraryAddUsageDescription`.

There is a small bug too where it will ask for permission twice (once for read access and once for write access).

**Comment by DJNgoma** [comment]
Makes sense. Currently only using it for reading, but won't hurt to add it in for writing purposes in the future.

**Comment by OPNinja** [comment]
I've added both NSPhotoLibraryUsageDescription and NSPhotoLibraryAddUsageDescription but my app still isn't asking the user for permission.  Does it matter what value (i.e., what text) you add to the plist?

**Comment by cosmith** [comment]
No, I don't think it matters.

**Comment by eric8words** [comment]
I got the same issue that app still not asked for permission. Any one can help ?

**Comment by wawilliams003** [comment]
I was having the same issue with one of my app, after upgrading to Xcode 9 ios 11. I have used both NSPhotoLibraryUsageDescription and NSPhotoLibraryAddUsageDescription, this worked for me.

**Comment by esutton** [comment]
I added both **NSPhotoLibraryUsageDescription** and **NSPhotoLibraryAddUsageDescription** and now users must respond to two prompts and allow each one.  This annoys users.

>There is a small bug too where it will ask for permission twice (once for read access and once for write access).

@cosmith You said this is a bug that asks permission twice, one for each permission?  

A bug in **react-native-image-picker** ?

[NSPhotoLibraryUsageDescription and NSPhotoLibraryUsageDescription.](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW73)

![screen shot 2017-10-03 at 10 29 34 am](https://user-images.githubusercontent.com/6115047/31133674-d1bf7a2e-a825-11e7-9e3c-bdcb148028ff.png)

Thanks for a great library!

**Comment by MoOx** [comment]
I am getting issue with `NSPhotoLibraryAddUsageDescription`. The weird part is that I can't reproduce on my simulator nor iPhone. I found this issue via Sentry.
Anyway, hope that adding the proper key into the info.plist will fix it.

**Comment by StewartGillen** [comment]
This crash does not happen in sim, only on device.

**Comment by tirrorex** [comment]
@esutton any idea where is it coming from in react-native?
I assume since react-native supports a lot of ios versions this is related but i couldn't find the culprit.
I have this issue also on another repo but i think this should be a react-native issue
