### ISSUE TITLE
get geoLocation info from meta data of image

### ISSUE THREAD

**Issue by bkniya** [react-native-community/react-native-image-picker#634]
I can get geoloacation info when i upload a photo via phone cam, but i can't get geoloacation info when i upload a photo via app cam on IOS.(do not have any problem in android)
Also i can't get geolaocation info while adding a photo from gallery which is taken by app cam.

**Comment by dancomanlive** [comment]
what is the difference between phone cam and app cam?

**Comment by bkniya** [comment]
I think so there's no difference between two cam. The problem may be while saving photo, it doesn't write geolocation info in image meta tag.
