### ISSUE TITLE
IOS8: image fileName is undefined

### ISSUE THREAD

**Issue by fschai89** [react-native-community/react-native-image-picker#640]
### Description
The fileName for response object is undefined or null on IOS8.1, 

### How to repeat issue and example
Use IOS8.1 device and select any image, try to log its response object filename but undefined.

### Solution
I this is the get filename method in the ios not compatible with IOS8.

### Additional Information

* React Native version: 0.45.1
* Platform: IOS 8.1
* Development Operating System: MAX OS Sierra

**Comment by MaxToyberman** [comment]
see this PR https://github.com/react-community/react-native-image-picker/pull/709

**Comment by soubhik-mondal-bitcanny** [comment]
@MaxToyberman i got this issue in iOS 11 as well.

**Comment by fengyibo** [comment]
i got this issue in iOS 11 as well too.

**Comment by Jimmy-CC** [comment]
I got this issue too, any help needs to merge this pr?

**Comment by RoWaiR** [comment]
Is any solution known?

**Comment by charpeni** [comment]
What are the reproduction steps on iOS 11?

Is the issue is still there on iOS 12?

**Comment by filipsuk** [comment]
Still issue on iOS 12
