### ISSUE TITLE
App disappear (not crash) when launcher box appear 

### ISSUE THREAD

**Issue by sandropoluan** [react-native-community/react-native-image-picker#643]
**This is what i get**.
![videotogif_2017 07 15_01 26 25](https://user-images.githubusercontent.com/11922251/28223450-134573de-68fe-11e7-854c-67ca4a20a3a9.gif)

**But i want the launcher is in front of the app like this**.
![screenshot_2017-07-15-01-43-49-247_android](https://user-images.githubusercontent.com/11922251/28223978-0b43c77e-6900-11e7-8f63-7bd67ad4929d.png)

What do I miss?

RN 0.44
react-native-image-picker 0.26.3
Tested on Xiaomi Redmi Note 2

**Comment by bsonntag** [comment]
I'm having the same issue. The current activity is temporarily hidden when opening the library or the camera.
I'm using `ImagePicker.launchImageLibrary` and `ImagePicker.launchCamera`.

RN 0.40
react-native-image-picker 0.26.7

**Comment by sandropoluan** [comment]
@bsonntag ,Did you already have the solution ?
