### ISSUE TITLE
[Android] Video Duration Limit option and videoQuality not working

### ISSUE THREAD

**Issue by OrangeYi** [react-native-community/react-native-image-picker#644]
### Description
Video Duration Limit option and videoQuality not working

Test on pixel and nexus6 have below issues:
The camera just not stop until I press the stop button and the size of 2s video is 10m. It means that the videoquality option is not working.

### How to repeat issue and example
 options = {
          chooseFromLibraryButtonTitle: null,
          videoQuality: 'low',
          durationLimit: 5,
          title: '',
          takePhotoButtonTitle: 'Take video...',
          mediaType: 'video',
      };

* React Native version: 0.46
* Platform: Android
* Development Operating System: MacOS

**Comment by DaniyarJakupov** [comment]
Can confirm, have the same issue with durationLimit option

**Comment by skatego** [comment]
same here, videoQuality does not work,

* "react-native": "0.50.4",
* "react-native-image-picker": "0.26.7",
* Platform: Android

**Comment by rizkisunaryo** [comment]
Any update on this?

**Comment by alisa-hui** [comment]
same here, durationLimit does not work,

"react-native": "0.48.4",
"react-native-image-picker": "0.26.7",
Platform: Android
