### ISSUE TITLE
Take camera picture without confirmation "Save" button - Android

### ISSUE THREAD

**Issue by shukerullah** [react-native-community/react-native-image-picker#647]
### Description

I would like to take picture with without confirmation button on Android.

### Solution
Use "android.intent.extra.quickCapture"
```
Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
intent.putExtra("android.intent.extra.quickCapture",true);
```

| option        | iOS           | Android  | Info |
| ------------- |:-------------:| -----:|-----:|
| quickCapture| - | OK | Quick Capture, without confirmation button |

### Additional Information
[stackoverflow](https://stackoverflow.com/a/38371325/5315786)

**Comment by ZaidSameer** [comment]
Where to put this code?

**Comment by shukerullah** [comment]
for Video
```
// File ImagePickerModule.java#238
cameraIntent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
cameraIntent.putExtra("android.intent.extra.quickCapture",true);
```

for Image
```
// File ImagePickerModule.java#248
cameraIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
cameraIntent.putExtra("android.intent.extra.quickCapture",true);
```

> This works on NEXUS device only

**Comment by hiralp19** [comment]
cameraIntent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);
cameraIntent.putExtra("android.intent.extra.quickCapture",true);

this is not working for some other devices, how to handle that?

**Comment by tibbe** [comment]
I ran into this today as well. Our app has its own preview screen (that supports doodling) and we don't want two confirmation screens in a row. Could we add this to the `Options` object? Seems pretty straightforward.
