### ISSUE TITLE
[Defect] Black background added for transparent images

### ISSUE THREAD

**Issue by ethan605** [react-native-community/react-native-image-picker#651]
### Description

For `allowsEditing` set to `true`, every images picked from library with alpha channel will be black backgrounded:

![01](https://user-images.githubusercontent.com/1215541/28853164-db3d2270-7758-11e7-8296-6953f1ca6820.png)
![03](https://user-images.githubusercontent.com/1215541/28853167-df5cf042-7758-11e7-875f-235d8c775891.png)
![04](https://user-images.githubusercontent.com/1215541/28853196-090ea430-7759-11e7-9b51-dca19e3a828a.png)

When editing is disabled, images have white background as expected:

![02](https://user-images.githubusercontent.com/1215541/28853194-05bb560c-7759-11e7-874b-4f0a3d82609d.png)

### How to repeat issue and example

Here is my options passed to `ImagePicker.showImagePicker()` as first argument:

```javascript
{
  allowsEditing: true,
  cameraType: 'front',
  maxHeight: 512,
  maxWidth: 512,
  mediaType: 'photo',
  storageOptions: { path: 'images', skipBackup: true },
  title: null,
}
```

### Solution

No solutions proposed yet.

### Additional Information

* React Native version: `react-native@0.46.4`
* Platform: iOS (not tested on Android)
* Development Operating System: `macOS Sierra 10.12.5`
* Dev tools: Xcode 8

**Comment by agates4** [comment]
Did you find a workaround for this?

**Comment by nica0012** [comment]
Have you figured out this issue? I cant seem to remove the white backgrounds from png image. It was black until I removed the editing - now its white...

**Comment by TommyHarty** [comment]
Hi @nica0012 - did you manage to figure this out?

**Comment by nica0012** [comment]
@TommyHarty I sure did, instead or using `response.uri`, simply use `response.origURL`.

**Comment by TommyHarty** [comment]
@nica0012 - my app crashes when I use `response.origURL`

**Comment by nica0012** [comment]
@TommyHarty if I remember correctly I think it may only work on IOS.

**Comment by felipegouveiae** [comment]
I have found the same issue here for ios 13 black theme. The image list ls also dark and transparent.

**Comment by douglasjunior** [comment]
Problem still persists on Android.

**Comment by douglasjunior** [comment]
I discovered the problem. When using "maxHeight" or "maxWidth", the image is converted from PNG to JPEG, causing the transparent area to be converted to black.

Is there any way to keep the image in PNG?

**Comment by odyodyodys** [comment]
Any updates on this?
