### ISSUE TITLE
[Android] Image rotated 90 degrees

### ISSUE THREAD

**Issue by woodpav** [react-native-community/react-native-image-picker#655]
I am using `ImagePicker.showImagePicker` to take a photo. iOS outputs a correctly orientated image. On Android, the image is rotated 90 degrees. I am taking a picture using a Google Pixel API 25 Simulator. The simulator is in portrait mode. 

This is the relevant part of `response`

    {
      height: 480,
      isVertical: true,
      originalRotation: 0,
      width: 640
    }

`isVertical: true` but the `height` and `width` are switched (so rotated 90 degrees). 

Related #199 #388

**Comment by galeto** [comment]
Im algo having this problem only when I take a picture... from gallery works fine

**Comment by awitherow** [comment]
We are also having this problem on Samsung Galaxy S7 Edge.

**Comment by galeto** [comment]
the camera and the app should not adjust the orientation. it should be done by the server

https://beradrian.wordpress.com/2008/11/14/rotate-exif-images/

Im using rails as backend and dragonfly to process images, so to fix that I just did:
https://mensfeld.pl/2015/07/ruby-dragonfly-gem-auto-orient-all-the-images/

**Comment by awitherow** [comment]
I don't think your backend/server stuff is related to this @galeto ? instead we need to look at why Android is doing this.

**Comment by xiaoleiooo** [comment]
photos right, rotate 90 when use camera

**Comment by awitherow** [comment]
We are experiencing this issue on a Samsung Galaxy S7 Edge phone running Android 7.0 with Kernel version 3.18.14-11528205.

**Comment by awitherow** [comment]
@yfuks @marcshilling I have noticed you were looking into this PR which might be related https://github.com/react-community/react-native-image-picker/issues/199

I was wondering if you have any thoughts on this issue?

We are experiencing this on our application with React-Native `0.46.4`, React `16.0.0-alpha.12` and React-Native Image-Picker `0.26.3` on devices such as `Samsung Galaxy S7 Edge phone running Android 7.0 with Kernel version 3.18.14-11528205.`

**Comment by awitherow** [comment]
@yfuks @marcshilling any thoughts?

**Comment by marcshilling** [comment]
@awitherow I'm not super familiar with the Android side of the repo/am not actively maintaining this anymore. I'd be happy to help get a pull request merged if there is one.

**Comment by konradkierus** [comment]
@awitherow we've observed the similar behavior on Samsung Galaxy S7 but I don't think this is a bug.
Please note that image is rotated but it has proper EXIF data, if you try to open it on GIMP (for example) then it will ask you if you want to have the image opened as it is or take EXIF data into consideration. And EXIF data may contain information about image orientation (rotation).
All image browsers, including web browsers, should take EXIF data into consideration and from my observations they do.
Unless this is something else and you lost somewhere the EXIF data, for example during resizing the image or creating a thumbnail of it on the backend, it depends on your use case.

**Comment by JonoH** [comment]
As a work around I'm using [this](https://github.com/bamlab/react-native-image-resizer) library to rotate the image 90 degrees if the originalRotation prop exists and has a value of 90.

**Comment by Monte9** [comment]
@JonoH your solution works for me. Although one thing to note is that when taking images with the front camera (selfie), the rotation is  270. 

Hence here is what I ended up with in case it helps someone:
```
const IMAGE_PICKER_OPTIONS = {
  title: 'Select a photo',
  mediaType: 'photo',
  noData: true
}

ImagePicker.launchCamera( IMAGE_PICKER_OPTIONS, response => {
  const { error, uri, originalRotation } = response

  if ( uri && !error ) {
    let rotation = 0

    if ( originalRotation === 90 ) {
      rotation = 90
    } else if ( originalRotation === 270 ) {
      rotation = -90
    }

    ImageResizer.createResizedImage( uri, 800, 600, "JPEG", 80, rotation ).
      then( ( { uri } ) => {
        this.setState( { uri } )
      } ).catch( err => {
        console.log( err )

        return Alert.alert( 'Unable to resize the photo', 'Please try again!' )
      } )
  } else if ( error ) {
    console.log( "The photo picker errored. Check ImagePicker.launchCamera func" )
    console.log( error )
  }
} )
```

**Comment by JonoH** [comment]
Good catch @Monte9. Thanks for sharing!

**Comment by Odywan55** [comment]
Hello, have the same issue, only from camera image is rotated , but response from camera and gallery is the same (((
response from camera : 
<img width="1015" alt="screen shot 2017-11-24 at 10 58 30" src="https://user-images.githubusercontent.com/13364000/33202818-9229bfe6-d106-11e7-91ac-684637d8cfd5.png">
response from galary : 
<img width="1395" alt="screen shot 2017-11-24 at 11 00 03" src="https://user-images.githubusercontent.com/13364000/33202855-ae044614-d106-11e7-8c70-37b558637904.png">

Android 5.1
"react-native": "0.50.3",
"react-native-image-picker": "^0.26.7",

**Comment by projetedt** [comment]
@JonoH @Monte9 guys you made my day that work perfectly.

**Comment by Maddoc42** [comment]
@Monte9 that works great for photos taken by the camera! Does this also work for you when selecting the same image via the gallery?

Tested with a LG G2 and I am seeing inconsistent behaviour when picking the same (!) image with either gallery or camera. With the above code rotation is correct when picking via camera, but rotated when coming from the gallery. `originalRotation` is `90` in both cases, URI differs though.

Does anybody else have this issue?

For completeness:

- Result via camera:
```json
{
 "originalRotation": 90,
 "uri": "content://[app-id]/app_images/Android/data/[app-id]/files/Pictures/image-3dc109f0-71f9-4f15-acc1-d9342e8c67a9.jpg"
}
```
- Result via gallery
```json
{
 "originalRotation": 90,
 "uri": "content://media/external/images/media/25653"
}
```

**Comment by tirtaabimanyu** [comment]
I'm having the same issue as @Maddoc42 
@Monte9 's solution works for taking a picture via camera but failed when selecting from the gallery. Tested with my Samsung S7 Edge.

**Comment by josenaves** [comment]
I'm also having this issue. It seems to be related with Android 6.x devices.
Tested on a LGV520 tablet and MotoX2 phone.

**Comment by hubertli1991** [comment]
Hope this helps. Setting `rotation: 360` worked for me.

Image-picker's "original" / default image config causes this bug.

Overriding the default config is not so straight forward because this library ignores some image configurations (https://github.com/react-community/react-native-image-picker/blob/694fa1de5cf4a3dce8e135054c3831fba85e3880/android/src/main/java/com/imagepicker/media/ImageConfig.java#L139).

So, if you only set `rotation: 0`, the image on Android will get rotated 90 degrees because image-picker will continue to use the default image config. If, however, you set `rotation: nonZeroInteger`, image-picker will respect your configuration -- setting rotation to 360 will preserve the orientation. If you don't set `rotation` and just set `quality: 0.99` (I would not suggest doing this), image-picker will also respect your config -- not rotate and reduce the quality by 0.01.

**Comment by carlwelchdesign** [comment]
setting rotation to 360 is the simplest solution. Thanks @hubertli1991

**Comment by ganlub** [comment]
I went with @hubertli1991 proposal for Android (as selfies are giving 270 of `originalRotation`), and so far it seems to be properly working. Prior to that I was checking on the backend if the width was bigger than the height and if so rotating -90.

Is it there any official workaround/progress for this issue? On the API's reference `originalRotation`, #199 is mentioned but this issue is far more useful.

**Comment by malonguwa** [comment]
@hubertli1991 @carlwelchdesign  hey~ are you guys talking about setting rotation to 360 to solve the issue by using react-native-image-resizer library or this react-native-image-picker ?

**Comment by NainalChauhan** [comment]
setting rotation to 360 is not working for me in case of front camera

**Comment by franzoo** [comment]
Setting rotation: 360 does not solve the problem. Im using a Samsung S10+

**Comment by krakzk** [comment]
I am still facing this issue, where my images taken from camera are rotated by -90 or 270 , which i cant confirm as my original rotation comes  as 0 and isVertical is true. 
i have tried the 360 rotation passing, giving quality 0.99 etc. Sadly none of them worked.
The issue doesn't appear in case of images selected from gallery.

Version : 0.28.1
Rn version : 0.59.3

Similar to @Odywan55 mentioned issue.

**Comment by KrishyV** [comment]
> I am still facing this issue, where my images taken from camera are rotated by -90 or 270 , which i cant confirm as my original rotation comes as 0 and isVertical is true.
> i have tried the 360 rotation passing, giving quality 0.99 etc. Sadly none of them worked.
> The issue doesn't appear in case of images selected from gallery.
> 
> Version : 0.28.1
> Rn version : 0.59.3
> 
> Similar to @Odywan55 mentioned issue.

I have been trying to replicate this issue before removing this fix from my codebase. I've recently upgraded from 0.28 to the latest (2.3.1). Perhaps try upgrading your version? It is over 1.5 years outdated.

**Comment by krakzk** [comment]
@KrishyV I cannot updagradw my RN version right away, so i would need to get this done with the current version

**Comment by BSThisarasinghe** [comment]
> @JonoH your solution works for me. Although one thing to note is that when taking images with the front camera (selfie), the rotation is 270.
> 
> Hence here is what I ended up with in case it helps someone:
> (**react-native-image-picker** + **react-native-image-resizer**)
> 
> ```
> const IMAGE_PICKER_OPTIONS = {
>   title: 'Select a photo',
>   mediaType: 'photo',
>   noData: true
> }
> 
> ImagePicker.launchCamera( IMAGE_PICKER_OPTIONS, response => {
>   const { error, uri, originalRotation } = response
> 
>   if ( uri && !error ) {
>     let rotation = 0
> 
>     if ( originalRotation === 90 ) {
>       rotation = 90
>     } else if ( originalRotation === 270 ) {
>       rotation = -90
>     }
> 
>     ImageResizer.createResizedImage( uri, 800, 600, "JPEG", 80, rotation ).
>       then( ( { uri } ) => {
>         this.setState( { uri } )
>       } ).catch( err => {
>         console.log( err )
> 
>         return Alert.alert( 'Unable to resize the photo', 'Please try again!' )
>       } )
>   } else if ( error ) {
>     console.log( "The photo picker errored. Check ImagePicker.launchCamera func" )
>     console.log( error )
>   }
> } )
> ```

Hi I had to add one more condition like this to make it work.
   ```
 let rotation = 0;
                        if (response.originalRotation === 90) {
                            rotation = 90;
                        } else if (response.originalRotation === 180) {
                            rotation = 180;
                        } else if (response.originalRotation === 270) {
                            rotation = -90;
                        }

```

But, is there a way to identify whether user chose camera or gallery. Because I don't want to apply above conditions if it is from the gallery.

**Comment by Nilaamanandhar** [comment]
there is no any original rotation in new version of react native image picker what can be done to rotate

**Comment by yamila-fraiman** [comment]
Rotation is not available anymore. Any other solution?

**Comment by martintanbit** [comment]
I was able to solve this by passing `maxWidth` and `maxHeight` to the camera options.

```
const opts: CameraOptions = {
  mediaType: 'photo',
  includeBase64: true,
  presentationStyle: 'fullScreen',
  maxWidth: 1080,
  maxHeight: 1080,
  quality: 1.0,
};
const res = await launchCamera(opts);
```

**Comment by rajashekar-shatrix** [comment]
Hi @Monte9 
I was stuck with same 90 degrees rotation issue in latest react native image picker 

"react": "18.2.0",
"react-native": "0.72.4",
"react-native-image-picker": "^5.6.1",

In latest version response is not returning "originalRotation" key.

can you help me what could be the solution for latest version of react native image picker ?

**Comment by zjkuang** [comment]
This is a snippet in my code which fixes the rotation issue.

(Android native module)

@ReactMethod
> public void correctImageRotation(final String uriString, final Promise
> promise) {
>   String uriStringStripped = uriString.replaceFirst("file://", "");
>   ReadableMap result = _checkImageRotation(uriStringStripped);
>   if (!result.getString("result").equals("done")) {
>     promise.resolve(result);
>     return;
>   }
>   int orientation = result.getInt("orientation");
>   float correctionDegree = 0;
>   if (orientation == ExifInterface.ORIENTATION_ROTATE_90) {
>     correctionDegree = 90;
>   } else if (orientation == ExifInterface.ORIENTATION_ROTATE_180) {
>     correctionDegree = 180;
>   } else if (orientation == ExifInterface.ORIENTATION_ROTATE_270) {
>     correctionDegree = 270;
>   } else {
>     String message = String.format("Unrecognized orientation: %d",
> orientation);
>     Log.d("correctImageRotation", message);
>     WritableMap response = Arguments.createMap();
>     response.putString("result", "nop");
>     response.putString("message", message);
>     promise.resolve(response);
>     return;
>   }
>   _rotateImage(uriString, correctionDegree, promise);
> }
>


> // Returns
> //  -1: exception
> //  ExifInterface.ORIENTATION_*
> //   - ORIENTATION_FLIP_HORIZONTAL = 2;
> //   - ORIENTATION_FLIP_VERTICAL = 4;
> //   - ORIENTATION_NORMAL = 1;
> //   - ORIENTATION_ROTATE_180 = 3;
> //   - ORIENTATION_ROTATE_270 = 8; // <------ front camera (selfie)
> //   - ORIENTATION_ROTATE_90 = 6; // <------ back camera (main)
> //   - ORIENTATION_TRANSPOSE = 5;
> //   - ORIENTATION_TRANSVERSE = 7;
> //   - ORIENTATION_UNDEFINED = 0;
> ReadableMap _checkImageRotation(String uriString) {
>   //
> https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a
>   ExifInterface exif = null;
>   try {
>     exif = new ExifInterface(uriString);
>     int orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION,
> ExifInterface.ORIENTATION_UNDEFINED);
>     Log.d("correctImageRotation", String.format("orientation: %d",
> orientation));
>     WritableMap result = Arguments.createMap();
>     result.putString("result", "done");
>     result.putInt("orientation", orientation);
>     return result;
>   } catch (IOException e) {
>     Log.e("correctImageRotation", String.format("checkImageRotation()
> exception. %s", e.getLocalizedMessage()));
>     WritableMap result = Arguments.createMap();
>     result.putString("result", "exception");
>     result.putString("message", e.getLocalizedMessage());
>     return result;
>   }
> }
>


> void _rotateImage(String uriString, Float degrees, Promise promise) {
>   new Thread(() -> {
>     Uri photoURI = Uri.parse(uriString);
>     Bitmap bitmap = null;
>     try {
>       bitmap =
> MediaStore.Images.Media.getBitmap(reactContext.getContentResolver(),
> photoURI);
>       Matrix matrix = new Matrix();
>       matrix.postRotate(degrees);
>       Bitmap rotated = Bitmap.createBitmap(bitmap, 0, 0,
> bitmap.getWidth(), bitmap.getHeight(), matrix, true);
>       OutputStream os =
> reactContext.getContentResolver().openOutputStream(photoURI);
>       rotated.compress(Bitmap.CompressFormat.JPEG, 100, os);
>       os.flush();
>       os.close();
>       WritableMap response = Arguments.createMap();
>       response.putString("result", "done");
>       response.putString("message", String.format("Rotated %.0f degrees
> for correction.", degrees));
>       promise.resolve(response);
>     } catch (Exception e) {
>       Log.e("correctImageRotation", String.format("correctImageRotation()
> exception. %s", e.getLocalizedMessage()));
>       WritableMap response = Arguments.createMap();
>       response.putString("result", "exception");
>       response.putString("message", e.getLocalizedMessage());
>       promise.resolve(response);
>     }
>   }).start();
> }
