### ISSUE TITLE
Take photo from camera crashes app

### ISSUE THREAD

**Issue by zhenkaGo** [react-native-community/react-native-image-picker#664]
I get this error in xCode with 0.26.3 release, when I try to use a photo taken by the camera.

`2017-08-09 12:45:58.067658+0300 Stories[781:144006] 781: CFNetwork internal error (0xc01a:/BuildRoot/Library/Caches/com.apple.xbs/Sources/CFNetwork/CFNetwork-811.5.4/Foundation/NSURLProtocol.mm:183)
2017-08-09 12:45:58.068418+0300 Stories[781:144006] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x18274afe0 0x1811ac538 0x18262c2d8 0x182638030 0x10026b4b8 0x100294240 0x10160da50 0x10160da10 0x10161b2e8 0x101611634 0x10161b810 0x10161d630 0x10161d39c 0x18180b100 0x18180acac)
libc++abi.dylib: terminating with uncaught exception of type NSException`

`if ([imageURL.scheme caseInsensitiveCompare:@"assets-library"] == NSOrderedSame) {
    assetID = [imageURL absoluteString];
    results = [PHAsset fetchAssetsWithALAssetURLs:@[imageURL] options:nil];
 }`

@[imageURL]  is nil

**Comment by galeto** [comment]
+1
On Android, Im getting this error:
`CameraService: connectLegacy: camera HAL module version 100 doesn't support connecting to legacy HAL devices!
An error occurred while connecting to camera 0: -38 (Function not implemented)`

**Comment by galeto** [comment]
Im think that the problem with android is the camera api version:
this plugin uses the deprecated API:
https://developer.android.com/reference/android/hardware/Camera.html

https://developer.android.com/reference/android/hardware/camera2/package-summary.html
