### ISSUE TITLE
Crashes on Ios

### ISSUE THREAD

**Issue by ferminmoli** [react-native-community/react-native-image-picker#667]
Once I open image picker on an Ipad or an Iphone, the app closes.

**Comment by farhanmannan** [comment]
The app will instantly crash if you haven't got a "Privacy - Camera Usage Description" in your Info.plist requesting permissions to use the camera

**Comment by ferminmoli** [comment]
Yes, I have those permissions. I've just figured out that if I wrap the image picker launcher inside an event crashes. I'm trying to figure out what's happening.

**Comment by dgurns** [comment]
Having the same issue here. Works fine on simulator, crashes immediately on device upon taking a photo or choosing from library.

**Comment by zaka29** [comment]
+1

**Comment by klinkov** [comment]
+1

**Comment by Chrischuck** [comment]
+1

**Comment by lukez10** [comment]
+1

**Comment by luck2011** [comment]
+1

**Comment by huangdou0204** [comment]
+1 same issue

**Comment by zainmusani** [comment]
You need to add 

`<key>NSPhotoLibraryUsageDescription</key>
<string>This app requires access to the photo library.</string>
<key>NSCameraUsageDescription</key>
<string>This app requires access to the camera.</string>`

in _Info.plist_ file to fix this issue

**Comment by rickcha** [comment]
+1

**Comment by rickcha** [comment]
I found that the accessing photo permission is not set and it never asked on iOS 11. I solved my issue by asking the photo permission before I use the ImagePicker component.

Try this one: https://github.com/yonahforst/react-native-permissions

**Comment by kyoyadmoon** [comment]
ref: https://github.com/react-community/react-native-image-picker#ios

> For iOS 10+, Add the NSPhotoLibraryUsageDescription, NSCameraUsageDescription, and NSMicrophoneUsageDescription (if allowing video) keys to your Info.plist with strings describing why your app needs these permissions. Note: You will get a SIGABRT crash if you don't complete this step

**Comment by devagul93** [comment]
@ferminmoli did you figure out a solution?

**Comment by KangYoosam** [comment]
+1

**Comment by rohitpareek147** [comment]
@ferminmoli was you found any solution or reason behind this crash

**Comment by SirPhemmiey** [comment]
Any fix for this please?

**Comment by toannh0104** [comment]
I've crashed for the first time to ask permission to access library, then It worked, but cannot understand why?

**Comment by GuoZhiQiang** [comment]
+1

**Comment by yogavigneshwaran** [comment]
> You need to add
> 
> `<key>NSPhotoLibraryUsageDescription</key> <string>This app requires access to the photo library.</string> <key>NSCameraUsageDescription</key> <string>This app requires access to the camera.</string>`
> 
> in _Info.plist_ file to fix this issue
Thank you very much. It works for me :)

**Comment by nitingrewal** [comment]
+1 , same issue

**Comment by russelRajitha** [comment]
same issue in iphone 7 (ios 12.2).`NSCameraUsageDescription`,`NSPhotoLibraryUsageDescription`,`NSPhotoLibraryAddUsageDescription`, permitions already added in info.plist.

**Comment by antonmyrberg** [comment]
+1. Should not be stale.

**Comment by deep-link** [comment]
i tried it too and it has same issue. i checked the logcat and i saw that after get response from intent sent, react app get killed.then its starting as app has been closed.

**Comment by DenitzOps** [comment]
+ 1 app crashing when adding image just taken from camera

**Comment by Mitdd9707** [comment]
> You need to add
> 
> `<key>NSPhotoLibraryUsageDescription</key> <string>This app requires access to the photo library.</string> <key>NSCameraUsageDescription</key> <string>This app requires access to the camera.</string>`
> 
> in _Info.plist_ file to fix this issue

I am adding this permission in Info.plist still launchImageLibrary in debugging and releasing mode crash..
Any fix for this please?

**Comment by Seamus1989** [comment]
+1

**Comment by SohaibKtb** [comment]
+1, also gallery is not opening

**Comment by samiksha-syn** [comment]
i am facing same issue on real tablet. working fine on simulator. No solution find yet

**Comment by ZuzooVn** [comment]
+1

**Comment by vishaltanna** [comment]
I had setup all permission then also it's causing crash when I am trying to open it very first time.

Version is 1.1.0

Error : object cannot be nil (key: type)

In pod -> ImagePickerManager
Line : 379

[self.response setObject:mimeType forKey:@"type"];

Please help me to resolve this crash as it's suddenly start crashing and client chasing me for delivering app by resolving this issue.

**Comment by FayyazAliKhan1** [comment]
I am facing the problem when I open Image picker and selects an image the image picker closed & my screen freezes. 
The problem which I am facing is only in production, in development every thing is fine
Any one please

**Comment by mariia-kiliushina** [comment]
+1 
though have all key/string in my Info.plist, it just quits unexpectedly

<img width="747" alt="image" src="https://user-images.githubusercontent.com/95544709/198961278-2bdbb5ff-0752-45db-8694-4b8d87303484.png">
<img width="863" alt="image" src="https://user-images.githubusercontent.com/95544709/198961413-bd9af6be-f2fb-4023-a7fc-e12c12095842.png">

  is this issue just ignored or sth?

**Comment by erickgtzh** [comment]
any update on this?

**Comment by lucsoftsl** [comment]
Any update?
