### ISSUE TITLE
Getting absolute path on Android

### ISSUE THREAD

**Issue by PhillipWinder** [react-native-community/react-native-image-picker#671]
Is it possible to get the absolute path of a picture on Android?

Expo ImagePicker for example returns a path for the picked image like this: 

- "file:///data/user..."

This path can be used to upload the image to a server using content-type "multipart/form-data" in the post request.

However in react-native-image-picker I can only get

- "/storage/emulated/0/DCIM/Camera/IMG_20170820_200313.jpg" ("path")
or
- "content://media/external/images/media/15376" ("uri")

from the response object. 

I cannot seem to upload these files via a multipart/form-data request to a server. I guess I need the absolute path ("file:///data/user...") - how can I get this path?

Kind regards

**Comment by PhillipWinder** [comment]
solved:

adding "file://" in front of "/storage/...." so it becomes "file:///storage..." did the trick

**Comment by JohnHour89** [comment]
Hi, may I know how you get the file path of it? Thank you

**Comment by shahidjabbar** [comment]
@JohnHour89 its in response.path

**Comment by RohanGada** [comment]
This question and the response saved my day, Thank you @PhillipWinder

**Comment by thucld** [comment]
useful for me, thank you!

**Comment by vrush96** [comment]
Can anyone tell me how to get path of image from gallery on text view when selected image from gallery with full code sorry i am a newbie in android...

**Comment by SupriyaKalghatgi** [comment]
@PhillipWinder Your suggestion dd'nt work for me

**Comment by mohsinnaqvi110** [comment]
How do I convert this 
"content://media/external/images/media/15376" ("uri")"
to some absolute path like this 
"file:///storage..."  ("path")

 without ejecting my app? Is there something provided by expo!!!!

**Comment by sandeepsinghs** [comment]
Is there any lib with the help of that we can get the absolute path of a document. 

I have tried with different lib but not succeed to upload the file.
