### ISSUE TITLE
Nothings happens after pressing Take-photo or Choose-from-library, even no errors

### ISSUE THREAD

**Issue by marsonmao** [react-native-community/react-native-image-picker#673]
### Description

As title, nothing happens when I pressed Take-photo or Choose-from-library.
However the Cancel button is effective, the `if (response.didCancel)` block is entered.
I also tried to provide a callback function to `options` of `ImagePicker.showImagePicker(options`, the Cancel logic is still effective, but there shows no error.

### Additional Information

* React Native version: 
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-config": "^0.2.1",
    "react-native-device-info": "^0.10.0",
    "react-native-drawer": "^2.3.0",
    "react-native-image-picker": "^0.26.4",
    "react-native-maps": "^0.15.3",
    "react-native-material-ui": "^1.12.0",
    "react-native-vector-icons": "^4.3.0",
```
* Platform: Android 6
* Development Operating System: Windows 7
* Dev tools: I'm forcing my Android SDK to ver 23 with this config
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 23
                buildToolsVersion '23.0.1'
            }
        }
    }
}
```
Any suggestion or guess will be appreciated, thanks!

**Comment by AlmogRnD** [comment]
+1 I'm having the same issue only happing on Andriod

**Comment by Bvirgo** [comment]
+1 I'm having the same issue only happing on Andriod

**Comment by marsonmao** [comment]
Wow, seems I'm not alone. So anyone got clues?

I've traced the code a little bit, and read the function `launchCamera` in `android/src/main/java/com/imagepicker/ImagePickerModule.java`; since there's no error output, the flow should executes perfect include this final line `currentActivity.startActivityForResult(cameraIntent, requestCode);`, then nothing happens. 
So what does that mean? The `startActivityForResult` failed without error? I'm not sure.

Hope somebody could give some hint, thanks!

**Comment by AlmogRnD** [comment]
It working for me now, something with my build I belive

**Comment by nqthuan303** [comment]
@AlmogRnD what did you do to fix this issue?

**Comment by AlmogRnD** [comment]
I just updated react, did a clean build and rebuild

**Comment by marsonmao** [comment]
@AlmogRnD Would it be possible to share the clean & rebuild command? Thanks!

**Comment by nqthuan303** [comment]
@AlmogRnD ok, thank you so much.

**Comment by AlmogRnD** [comment]
I do it straight inside Xcode or android studio

**Comment by nqthuan303** [comment]
it's working for me now. Do this step to fix this issue

5. Add the required permissions in AndroidManifest.xml:

<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by pewh** [comment]
@nqthuan303 already follow that & still not work :/

**Comment by smk524198002** [comment]
I have the same problem on android. How to solve it ? Please Tell me. Thanks~

**Comment by minmaxflow** [comment]
@smk524198002 You can refer  https://github.com/react-community/react-native-image-picker/issues/539

**Comment by skeie** [comment]
For us the native-navigation from airbnb did not override the `onActivityResult` method. So if it doesn't work for you, you probably have a library which doesn't override the `onActivityResult` and passes it through.

**Comment by Rathawut-l** [comment]
I faced the same problem and got the solution from #803. Hope this helps!

**Comment by MewX** [comment]
You saved my day @nqthuan303 Thanks! I didn't even notice the react-native link did not add the permissions automatically!
