### ISSUE TITLE
taking a picture return a corrupted image

### ISSUE THREAD

**Issue by hmenzagh** [react-native-community/react-native-image-picker#681]
### Description

I'm trying to upload my image to a backend server using the uri & form-data and I always get corrupted files when the picture does not come from the camera roll. I can't get it to work.

everything works fine when i upload from the camera roll ...

### How to repeat issue and example

source code is very standard and needs no posting.

### Additional Information

on iOS && everything is up-to date and working fine ..
sending my file through a redux observable Epic && RxJS's Ajax function with a POST method (image in the body).

Thanks ..

**Comment by inventsys** [comment]
Same problem here!

**Comment by vriyeit** [comment]
Did anyone solve this? I am currently experiencing this now

**Comment by thiagobako** [comment]
any of you guys solved this? i'm experiencing it with a video!
