### ISSUE TITLE
Take photo crashes app

### ISSUE THREAD

**Issue by bahadircivelek** [react-native-community/react-native-image-picker#685]
When i try to take photo from camera crashes app... Problem in this line 

Uri contentUri = FileProvider.getUriForFile(context, context.getPackageName() + ".provider", result);

in RealPathUtil file.. and mobile center crash report is : Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.

**Comment by abartolo** [comment]
I am also getting this issue. @bahadircivelek any workaround?

**Comment by rickcha** [comment]
I also ran into this issue. After a fresh installation, when I try to take a photo or record a video, it asks me permission whether I am going to allow access to my photo album, which is great. However, after recording, when I press "Use Photo / Video", it crashes.

**Comment by rickcha** [comment]
I found that the accessing photo permission is not set and it never asked. I solved my issue by asking the photo permission before I use the image-picker component.

Try this one: https://github.com/yonahforst/react-native-permissions

**Comment by gengjiawen** [comment]
I think the cause is Android FileProvider, we need to fix the code in this repo. https://stackoverflow.com/questions/43175014/possible-to-use-multiple-authorities-with-fileprovider.
