### ISSUE TITLE
[Android] error: 'can\'t find current Activity'

### ISSUE THREAD

**Issue by smk524198002** [react-native-community/react-native-image-picker#688]
ImagePicker.launchCamera(options, (response) => {
                console.log(response);

})
log : error: 'can\'t find current Activity'

* React Native version: 0.41.0
* Platform: Android 5.0
* Development Operating System: MacOS
* Dev tools:  Android Studio 2.2

**Comment by kleytonlopes** [comment]
I'm having the same problem. Can you solve it? Thank you!

**Comment by Zapopozapopo** [comment]
Same
