### ISSUE TITLE
[Android] Issue with Release Build. Tag <provider> attribute authorities has invalid character '$'.

### ISSUE THREAD

**Issue by jaysig** [react-native-community/react-native-image-picker#690]
### Description

I am trying to generate an APK file using ./gradlew assembleRelease. It stops after BundledResourcesHashRelease with Task :react-native-fetch-blob:compileReleaseJavaWithJavac. The package it before compileRelease changes each time. The error is the following

react-native-image picker/android/build/intermediates/manifests/aapt/release/AndroidManifest.xml:12: Tag <provider> attribute authorities has invalid character '$'.

It says this went wrong
Execution failed for task ':react-native-image-picker:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Works fine in debug mode but does not compile a release candidate

### Additional Information

* React Native version: [0.44.3.]
* Platform: [Android]
* Development Operating System: [MacOS]
* Dev tools: [AS 3.0]

**Comment by jaysig** [comment]
To fix this I had to change the line in question 12 to android:authorities="APPLICATION_ID.provider". I don't know if this is the best practice though?

**Comment by mounlion** [comment]
I have same issue

**Comment by Purnadi12** [comment]
I've same issue. can work in debug mode very well, but no in release mode.
Trying to modify  Android_Manifest file for "android:authorities" value, but after build apk process, the system re-replace with "$" key again and again. 

Any help is very appreciated. Thanks

**Comment by andres-torres-marroquin** [comment]
I solved this following https://github.com/react-community/react-native-image-picker/issues/882#issuecomment-405255785
