### ISSUE TITLE
Windows UWP support

### ISSUE THREAD

**Issue by rclark98** [react-native-community/react-native-image-picker#702]
Is there a plan to support Windows UWP?

**Comment by Roopal78** [comment]
Is there a plan to support Windows UWP and MACOs App in react-native ?

**Comment by juanky201271** [comment]
There are people out there wondering this same thing and without any answer, I would really appreciate some kind of information about it. Thanks so much in advance.

**Comment by Invius** [comment]
It would amazing to have support for this
