### ISSUE TITLE
demo run ios simulator Cannot read property 'showImagePicker' of undefined

### ISSUE THREAD

**Issue by giantss** [react-native-community/react-native-image-picker#712]
![4b15568f-0b81-45ee-bdf3-815eb81edae6](https://user-images.githubusercontent.com/13778798/32369860-fa3365ba-c058-11e7-80c9-ae0c7e9213b7.png)

**Comment by wfxphoebus** [comment]
again, react-native run-ios

**Comment by mymai91** [comment]
i try run react-native run-iso but the issue always happens

**Comment by wvicioso** [comment]
I just ran into this issue. Turns out react-native link wasn't actually adding this package to my project. I had to manually add the library in xcode followed by rebuilding the project

**Comment by mymai91** [comment]
yah, correct, I retry with manually set up. It fixed

**Comment by Bytesu** [comment]
@wfxphoebus work for me ,tks
