### ISSUE TITLE
App crash with error: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by pzawadzki82** [react-native-community/react-native-image-picker#713]
### Description
After invoking mutliple times ImagePicker.showImagePicker() my react-native based app crashed with the following error: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. Stack tracke is attached below:

```
com.facebook.react.bridge.CallbackImpl.invoke CallbackImpl.java:30
com.imagepicker.ResponseHelper.invokeResponse ResponseHelper.java:76
com.imagepicker.ResponseHelper.invokeCustomButton ResponseHelper.java:56
com.imagepicker.ImagePickerModule.invokeCustomButton ImagePickerModule.java:497
com.imagepicker.ImagePickerModule$2.onCustomButton ImagePickerModule.java:193
com.imagepicker.utils.UI$1.onClick UI.java:66
android.support.v7.app.AlertController$AlertParams$3.onItemClick AlertController.java:1045
android.widget.AdapterView.performItemClick AdapterView.java:310
android.widget.AbsListView.performItemClick AbsListView.java:1145
android.widget.AbsListView$PerformClick.run AbsListView.java:306
android.widget.AbsListView$3.run AbsListView.java:3903
android.os.Handler.handleCallback Handler.java:739
android.os.Handler.dispatchMessage Handler.java:95
android.os.Looper.loop Looper.java:148
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run MessageQueueThreadImpl.java:194
java.lang.Thread.run Thread.java:818
```

### How to repeat issue and example
Click many times on e.g buttom that invokes ImagePicker.showImagePicker()

### Solution
Currently no idea how ti fix it

### Additional Information

* React Native version: 0.48.3
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android Studio and Atom

**Comment by cma00000** [comment]
I have similar problem. Try to ask [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid.html#request) before imagePicker (Camera and Write External). Example:

```
import { PermissionsAndroid } from 'react-native';

async requestCameraPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        'title': 'Cool Photo App Camera Permission',
        'message': 'Cool Photo App needs access to your camera ' +
                   'so you can take awesome pictures.'
      }
    )
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("You can use the camera")
    } else {
      console.log("Camera permission denied")
    }
  } catch (err) {
    console.warn(err)
  }
}
```

**Comment by john1jan** [comment]
i am also facing the same issue


```
FATAL EXCEPTION: mqt_native_modules
Process: com.nextbillion.groww.next, PID: 5185
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
at com.imagepicker.ResponseHelper.invokeResponse(ResponseHelper.java:76)
at com.imagepicker.ResponseHelper.invokeCancel(ResponseHelper.java:63)
at com.imagepicker.ImagePickerModule.doOnCancel(ImagePickerModule.java:211)
at com.imagepicker.ImagePickerModule$2.onCancel(ImagePickerModule.java:192)
at com.imagepicker.utils.UI$3.onCancel(UI.java:89)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1364)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by TranHanHieu** [comment]
Did you have a solution?

**Comment by guiyom19** [comment]
Same here. Any idea ?
The thing occurs only the first time we take a picture : the App crashes the first time and from the second, it works.
I have these lines in my AndroidManifest : 
<uses-feature android:name="android.hardware.camera" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.hardware.camera.autofocus" />

A sample of the code :
render() {
        return (
 ....
<TouchableOpacity onPress={this.displayImagePicker.bind(this)}>
...
);

displayImagePicker() {
        ImagePicker.showImagePicker(this.state.options, (response) => {
...
}

**Comment by HaiTaoWang123** [comment]
Have you solved this problem? I have the same problem now, can you give me some solutions to solve this error, thank you!

**Comment by kp20white** [comment]
@cma00000 thanks for the suggestion.  

I ended up using the [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid) module to request _multiple_ permissions before invoking **ImagePicker.showImagePicker**.  Here's a slightly different example from the one @cma00000 listed above if anyone's interested:

```

    import { PermissionsAndroid } from 'react-native'

...

    try {
      const grants = await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.CAMERA,
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
      ])

      const cameraGrant = grants[PermissionsAndroid.PERMISSIONS.CAMERA]
      if (cameraGrant === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use the camera')
      } else {
        console.log('Camera permission denied')
        return false
      }

      const storageGrant = grants[PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE]
      if (storageGrant === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can use store photos and videos')
      } else {
        console.log('Storage permission denied')
        return false
      }
    } catch (err) {
      console.warn(err)
      return false
    }

...

   ImagePicker.showImagePicker(options, responseFn)

```

**Comment by Under-Warz** [comment]
same error here but it look likes it's happening on close. Here is a stacktrace of the error

```
java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    CallbackImpl.java:28 com.facebook.react.bridge.CallbackImpl.invoke
    ResponseHelper.java:76 com.imagepicker.ResponseHelper.invokeResponse
    ResponseHelper.java:63 com.imagepicker.ResponseHelper.invokeCancel
    ImagePickerModule.java:201 com.imagepicker.ImagePickerModule.doOnCancel
    ImagePickerModule.java:182 com.imagepicker.ImagePickerModule$2.onCancel
    UI.java:89 com.imagepicker.utils.UI$3.onCancel
    Dialog.java:1480 android.app.Dialog$ListenersHandler.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:154 android.os.Looper.loop
    MessageQueueThreadImpl.java:192 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:762 java.lang.Thread.run
```

**Comment by rohit75** [comment]
Facing the same issue.. any solution???

**Comment by yuheidapperapps** [comment]
I can reproduce this by calling showImagePicker twice.

The issue is callback from second call replaced the first one, therefore when both dialog of them have been pressed, it will called twice.

If you put `ImagePicker.showImagePicker` in `onPress` and use double tap the button it is possible that `ImagePicker.showImagePicker` will be called twice.

My workaround is add a flag to stop it being called again until the dialog is dismissed.

**Comment by nihp** [comment]
I am getting this error. Any solution for this?

**Comment by duyk16** [comment]
I also get this issue. Any solution here?

**Comment by MustafaZouari** [comment]
iam also facing this problem,,any good solutions..

**Comment by mohit23x** [comment]
> This callback type only permits a single invocation from native code

This comes when the user has clicked the image picker button in your app multiple times, and the second sheet gives this error and app crashes.
My solution was to not call the `launchCamera` or `launchImageLibrary` when the picker is already open.
Used a `ref` to track whether picker was open or not.

```
const isPickerOpen = useRef(false);

const handleCamera = () => {
  if(isPickerOpen.current) return;

  isPickerOpen.current = true;

  launchCamera(options, () => {
    isPickerOpen.current = false;
    // ...
  })
}

```

**Comment by h1nson** [comment]
you may called the callback method multiple times.
