### ISSUE TITLE
[Android-emulator] diamond operator is not supported in -source 1.6

### ISSUE THREAD

**Issue by GitHubTracey** [react-native-community/react-native-image-picker#721]
### Description
I recently upgraded ReactNative in my app... from 0.44.3 to 0.50.0. I am now unable to open the app in the simulator in Android Studios. The error I receive is: 

> //Users/mydir/Projects/myproj/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/utils/ButtonsHelper.java
>>List<String> result = new LinkedList<>();
>
> error: diamond operator is not supported in -source 1.6
> (use -source 7 or higher to enable diamond operator)
>
> Execution failed for task ':react-native-image-picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details

same messages appear for:
> imagepicker/utils/PermisionUtils.java
>> final WeakReference<ImagePickerModule> reference = new WeakReference<>(module);

> imagepicker/utils/UI.java
>> final WeakReference<ImagePickerModule> reference = new WeakReference<>(module);

### How to repeat issue and example
I upgraded the react-native version, along with the react-native-image-picker version, I did an npm clean -xfd in my folder, readded the local.properties file for android, and I removed the .gradle/caches folder from my app, and then reopened android studios. I was then requested to update the android studio tool from 23.? to 26.0.2. I can no longer build emulator from android studios.

### Solution
I don't know what is wrong - I have limited experience with Android Studios, and java

### Additional Information

* React Native version: 0.50.0
* react-native-image-picker version: 0.26.7
* Platform: Android - building to phone with react-native run-android is fine, but I am unable to run emulator, I currently do not have any issues with iOS (either emulator or phone)
* Development Operating System: MacOS
* Dev tools: Android Studio 3.0, build tools version: 26.0.2

Previously, we were using: 
>        classpath 'com.android.tools.build:gradle:2.2.3'
however the latest version of Android studios requires 
>        classpath 'com.android.tools.build:gradle:3.0.0'

This seems to be where the issue may be coming from... Ideally I'm looking for a push in the right direction - I am not experienced enough with Android studios to know if this is a bug or an implementation error.

when I revert back to 2.2.3, then it suddenly doesn't allow usage of google(), nor can it find the buildToolsVersion.

**Comment by njflabs** [comment]
from what I understand, LinkedLists<> (with the  diamond operator), came out in java 7. I think that Android does not yet support java 7. so, you either have to rewrite the classes using LinkedList<> or try to get java 7 working on Android. Its seems to be an issue with java projects and Android compatibility.
