### ISSUE TITLE
How to select only jpeg file only and not .gif files ?

### ISSUE THREAD

**Issue by TonyFrancis** [react-native-community/react-native-image-picker#722]
I am trying to work add only jpeg files but .gif are getting in.
Need to remove them.
Can you help me.
I tried mediaType: 'photo',

**Comment by drakerehfeld** [comment]
bump~~

**Comment by LouisLeung** [comment]
same problem , anyone know how to fix?

**Comment by hagenssd** [comment]
still 2023 same issue!

**Comment by anurag-bansals** [comment]
I am facing same problem. Any fix ?
