### ISSUE TITLE
LaunchImageLibrary doesn't launch image picker after multiple uses

### ISSUE THREAD

**Issue by kyledmellander** [react-native-community/react-native-image-picker#728]
### Description

launchImageLibrary() seems to only return a response 1 time on IOS. It works as it should, opens up the library and then returns a selected image. After the first successful image, trying to launch the library again doesn't work. The response never arrives, image picking library never opens.

### How to repeat issue and example
    const options = {
      mediaType: 'photo',
      quality: 0.7,
      noData: Platform.OS !== 'ios',
    };

    console.log(options); // This prints

    ImagePicker.launchImageLibrary(options, results => {
      console.log(results); // This gets called once, doesn't work afterwards, image library never 
      opens.
      ... 
    }

### Additional Information

* React Native version: 0.45.1
* Platform: iOS
* Development Operating System: Mac
* Dev tools: XCode 9.1, IOS 11.1

**Comment by ChristiaanHaas** [comment]
Same issue here, since I updated to iOS 11

**Comment by kyledmellander** [comment]
I was also on iOS 11. Wasn't able to solve this issue, but react-native-image-crop-picker seemed to do the trick for me.

**Comment by mreda7** [comment]
I have the same problem also

**Comment by ChristiaanHaas** [comment]
Current workaround is to use `ImagePicker.showImagePicker(...)` on iOS in stead of `ImagePicker.launchImageLibrary(...)`.

**Comment by gaoxuan-haxibiao** [comment]
I'm the same problem

**Comment by jcurtis** [comment]
I get the same issue no matter which function I used @ChristiaanHaas 

It appears to be an issue with this bit of code: 

```
    void (^showPickerViewController)() = ^void() {
        dispatch_async(dispatch_get_main_queue(), ^{
            UIViewController *root = RCTPresentedViewController();
            [root presentViewController:self.picker animated:YES completion:nil];
        });
    };
```

`RCTPresentedViewController` does return a view but calling `presentViewController` doesn't appear to be doing anything after it's been called once before. Maybe it's something to do with how it's cleaned up after it's closed? Not sure I'm no iOS expert.

**Comment by jcurtis** [comment]
`react-native-image-crop-picker` appears to have the exact same issue. I'm running RN 0.54.0.

**Comment by RZulfikri** [comment]
any solution ?

**Comment by mateuspiresl** [comment]
This was happening to me when I had an update in the component right after calling `launchImageLibrary`. When I call it from a button click, it works, but when I call from a modal that is dismissed after calling it, the picker does not open or opens for a second and gets hidden.

**Comment by badri-sartania** [comment]
I have same problem. `launchImageLibrary` doesn't trigger show image library for second time.

**Comment by tobzilla90** [comment]
I had same problem on iOS (didn't test android yet)
for me it work to set the permissions in the Info.plist maually:

open Info.plist under ios/YOUR_PROJECT_NAME and add:
```
<dict>
...
<key>NSPhotoLibraryUsageDescription</key>
    <string>YOUR_REASON_FOR_USING_USER_PHOTOS_HERE</string>
    <key>NSCameraUsageDescription</key>
    <string>YOUR_REASON_FOR_USING_USER_CAMERA_HERE</string>
</dict> 
```

on android you can add permissions in the Manifest.xml. You will need the following (as I said didn't test if there is a issue on andorid) 
```
<uses-permission android:name="android.permission.CAMERA" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by sergeylaptev** [comment]
@mateuspiresl was right! The closing modal causes this issue. I have a custom action sheet which is implemented via Modal, and when I call `launchImageLibrary` and close modal at the same time, library gets opened only for the first time (and callback is getting invoked only once as well). Then I need to restart the app to be able to open gallery one more time. To fix this I have simply delayed launching gallery until modal will get closed, and everything works like a charm!

**Comment by SamuelGuNUAA** [comment]
@sergeylaptev Thanks, just close modal and give a little delay which works on IOS (No such issue on my Android)
