### ISSUE TITLE
Support for updated Android Studios Gradle Plugin 3.0.0

### ISSUE THREAD

**Issue by GitHubTracey** [react-native-community/react-native-image-picker#729]
### Description
Please allow for an updated version of Android Studios & Gradle. In my current project, I have:
in my build.gradle: 
com.android.tools.build:gradle:3.0.0
and in gradle-wrapper.properties:
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

### How to repeat issue and example
Create any app, upgrade your android studios Gradle Plugin to version 3.0.0

### Solution
update react-native-image-picker\android\build.gradle
> change line 16 from 
`classpath 'com.android.tools.build:gradle:2.2+'`
to 
`classpath 'com.android.tools.build:gradle:2+'`
remove line 24
`buildToolsVersion "25.0.2"`

** I will try to submit a PR later this evening...

### Additional Information

* React Native version: 0.44.3, though I had the same issue with 0.50.0 (we are working on upgrading react native in a separate ticket)
* Platform: [Android]
* Development Operating System: MacOS
* Dev tools:Android Studio version 3.0, Android SDK version 26.0.2

**Comment by aayushanand99** [comment]
hey @GitHubTracey did you submit the pr?I still cannot see the changes in the project

**Comment by GitHubTracey** [comment]
hey @aayushanand99 , I got distracted with some bug fixes. I'll do my best to take a look at it again this afternoon. 

Cheers!

**Comment by GitHubTracey** [comment]
I have a PR Ready, but I am unable to push to origin. Any hints would be great! 
Permission to react-community/react-native-image-picker.git denied to GitHubTracey.
> I have added  my SSH key to github (which allowed me to download the files), but am unable to submit the PR.
@marcshilling

**Comment by aayushanand99** [comment]
Hey, Are you trying to push to master branch? Create a local branch and
push it to remote then submit a pr from your branch to master

**Comment by GitHubTracey** [comment]
I used ash to download the repo, then switched to develop, then created a local branch and attempted to push to remote. That’s where it told me I was unauthorized for my account. It didn’t prompt for a passcode or anything though... maybe I missed something? I haven’t had to use SSH to commit before. Any hints would be welcome.

**Comment by GitHubTracey** [comment]
*ssh

**Comment by Spetastian** [comment]
@GitHubTracey Did you fork the repo before cloning it locally with SSH?

**Comment by GitHubTracey** [comment]
@spetastian, no, I don’t think I did. That’s a good point. It has been some time since I have tried to add to a someone else’s repo.

**Comment by Spetastian** [comment]
@GitHubTracey Its an expected behavior that you are not authorized to someone elses repo like this. If you want to contribute to the code you should first fork this repo so you have your own version of it on your own GitHub account. 
Then you that fork locally on your computer: `git@github.com:GitHubTracey/react-native-image-picker.git`. 

Then you create a branch locally just like you did and implement your changes. After that you push your own branch to your own fork which you have full access to.

Then you go to the original repo here and create a pull request and notify one of the admins of the original repo here in this issue.

**Comment by GitHubTracey** [comment]
Thank-you for the very detailed instructions! Much appreciated!

**Comment by socialcode-rob1** [comment]
Has this been done?  
Issue still open.

**Comment by GitHubTracey** [comment]
Wow. I am so embarrassed. I completely forgot about this ticket. Here is a PR:
https://github.com/react-community/react-native-image-picker/pull/952
You can do it manually, or just add this PR and then users won't need to go in and manually change it for themselves.

@Spetastian How do I find out who is the admin? It took me an hour to do this because I've been using bitbucket for so long I forgot how to do "all the things" in github. Yikes!
