### ISSUE TITLE
Attempt to Invoke Interface Method 'boolean com.facebook.react.brige.ReadableMap.hasKey(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by mr-bat** [react-native-community/react-native-image-picker#730]
My code works fine on iOS, the trouble begins in Android. Whatever I do, I face this error:
<img width="271" alt="screen shot 2017-11-16 at 17 37 08" src="https://user-images.githubusercontent.com/16259723/32895321-e4d508f8-caf4-11e7-9b16-7337070e3996.png">

This is how I invoke image picker:
```
uploadFile() {
		ImagePicker.launchImageLibrary(null, (response)  => {
			console.log('Response = ', response);
```
### Solution
You shouldn't set option to null as it will cause the error. You better use an empty object {} instead.
Adding some robustness can help other developers not to encounter this error.

react-native-cli: 2.0.1
react-native: 0.46.3
react-native-image-picker 0.26.7
Android
MacOS

**Comment by trinhvanvinh** [comment]
i have bug the same. how to fix ?

**Comment by Musigwa** [comment]
i have the same issue running the geolocation map app with react-native expo version 53.0.0

anyone to help???

**Comment by vah7id** [comment]
+

**Comment by aloptrbl** [comment]
**help i'm also have this issue**

**Comment by dooboolab** [comment]
People who are having same issue as above,

```
ImagePicker.launchImageLibrary(null, (response)  => {
			console.log('Response = ', response);
```

from above code, you should not pass the `null`. I've experienced this and solved it with giving option correctly. Something like below.

```
const options = {
  storageOptions: {
    skipBackup: true,
    path: 'images'
  }
};
```

**Comment by pvsong** [comment]
Same issue

**Comment by anniewey** [comment]
Using the same workaround as @dooboolab but the error still persist

**Comment by xfry** [comment]
@mr-bat  I got the same error using: React Native Geolocation, and your solution works for me. here some information about my environment.

```
 Environment:
  OS: Windows 10
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4
```

Thanks you man!

**Comment by derren7532123** [comment]
@xfry can you provided the soluction on it ? i also got this issue with
// Attempt to invoke interface method 'boolean abi27_0_0.com 'facebook.react.bridge.readablemap.getstring(java.lang.string) on a null object reference //

**Comment by griosb** [comment]
same problem, please
![image](https://user-images.githubusercontent.com/37642967/81181644-60206180-8f72-11ea-870c-c793b9edce63.png)

**Comment by fatsoflo** [comment]
just had this problem and I went into the `Options.java` file (inside android > src) to see what I could've been missing. for any key that says options.getString, my `options` work ONLY AFTER adding in all the keys with either an empty string or actual argument.

this is my final options which im using with v3.3.4, no longer getting this error

const options = {
  title: 'Select Image',
  cameraType: "back",
  maxWidth: 256,
  maxHeight: 256,
  noData: true,
  mediaType: 'photo',
  includeBase64: true,
}

**Comment by arhambutt11** [comment]
**how to fix this Error** 

"attempt to invoke interface method boolean com swmansion reanimated layout reanimation native methods holder is layout animation enable () on a null object reference"

**Comment by neeleshyadav253** [comment]
Do not pass null to the image picker options. Always pass a valid object (e.g., {}) even if no options are needed.

Initialize pickerOptions with safe default values, including keys like:

cropping: true

mediaType: 'photo'

compressImageQuality: 0.8

width and height (for example, 100x100 as fallback)

Conditionally override width and height only after the base object is created. For example:

if (activeImageType === 'profile') {
  pickerOptions.width = 300;
  pickerOptions.height = 300;
}
Ensure all keys expected by the native module are present to prevent hasKey() crashes on Android.

Use defensive coding if values are dynamic:

pickerOptions.width = typeof customWidth === 'number' ? customWidth : 300;
Do not allow undefined or missing values in required option fields, as this causes native Android code to crash.
