### ISSUE TITLE
Taking a picture with storageOptions.path has no effect

### ISSUE THREAD

**Issue by Selman555** [react-native-community/react-native-image-picker#731]
I am trying to take a picture with the camera providing storageOptions like this:

```
        const options = {
            cameraType: 'back',
            mediaType: 'photo',
            storageOptions: {
                cameraRoll: false, // Don't save photos to the camera roll
                path: "/data/data/com.testapp/itemfiles"
                skipBackup: true, // No need to backup to iClould
            },
        };

        ImagePicker.launchCamera(options, (response) => {
            if (response.didCancel) {
                console.log('User cancelled image picker');
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            }
            else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            }
            else {
                let source = {uri: response.uri};
            }
        });
```

Pretty standard stuff, I suppose.
The problem I'm having is that the options don't seem to have any effect
The path doesn't change and the file is saved in the camera roll instead.
I have confirmed that the path does exist.

The URI in the response looks like this:

> uri: 'content://com.reportit.provider/app_images/Pictures/image-a3fbe51e-94d8-4564-855c-464ed0d8f0ff.jpg',

The logs mention this as well:

> W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
> I/TAG: Finished scanning /storage/emulated/0/Pictures/image-5e89bc4d-0f11-4e83-bf37-5283ae39f425.jpg

What am I doing wrong? How can I save pictures to the path I specified?

### Additional Information

* React Native version: 0.48.3
* Platform: Android (5.0.2 device and 7.0 emulator)
* Development Operating System: MacOS
* Dev tools: Android Studio, PhpStorm

**Comment by Selman555** [comment]
I've made a local change to MediaUtils.java:

```
        final File path = ReadableMapUtils.hasAndNotNullReadableMap(options, "storageOptions")
            && ReadableMapUtils.hasAndNotEmptyString(options.getMap("storageOptions"), "path")
            ? new File(reactContext.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), options.getMap("storageOptions").getString("path"))
            : (!forceLocal ? Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
                          : reactContext.getExternalFilesDir(Environment.DIRECTORY_PICTURES));

        // ORIGINAL CODE
        //final File path = ReadableMapUtils.hasAndNotNullReadableMap(options, "storageOptions") && !forceLocal
        //        ? Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
        //        : reactContext.getExternalFilesDir(Environment.DIRECTORY_PICTURES);
```

Now I can pass a folder like this:

```
            storageOptions: {
                cameraRoll: false,
                path: 'itemfiles',
                skipBackup: true, // No need to backup to iCloud
            },
```

And the path in the response is 

> "/storage/emulated/0/Android/data/com.app/files/Documents/itemfiles/image-ee46fd5a-e669-4038-a14a-a08df67e0345.jpg"

But cameraRoll: false is still ignored...

**Comment by nathan-K-** [comment]
Hello,

I'm not in charge of this repo, but I guess with some minor changes it can be turn into a PR so this option (storageOptions.path) can be used with Android too !

**Comment by Vishal-Lakkapathri** [comment]
Any solution for this? I'm facing the same issue!!

**Comment by nathan-K-** [comment]
Yes, my PR.
You can apply the modifications in your npm package ... it's ugly, but should work.

**Comment by nathan-K-** [comment]
Well, feel free to adapt the code, the doc is quite good ! ([here for android](https://developer.android.com/training/data-storage/files))

**Comment by jpdesignerrio** [comment]
I'm having another problem also related to that. Both using the original method and using the method proposed by Selman555, two image files are generated. One (smaller) comes in the URI response, but the other (much bigger in Mb) I did not even know of the existence until I opened the destination folder of the images! 

The image returned by the code is something like: `image-a442467f-3713-4fba-8404-d5df999ff1bb.jpg`
The other, identical to that, is: `image-d626da27-a482-4670-8945-d2f2a67377b3.jpg`

After submit to server I deleted the original image, but the other image isn't possible, because it's name is not known by the code.

**Comment by jpdesignerrio** [comment]
Hello! I finally did it! (tested only in Android)

Options:
```
const options = {
        title: 'Photo Capture',
        chooseFromLibraryButtonTitle: null,
        cameraType: 'back',
        mediaType: 'photo',
        noData: true,
        cameraRoll: false,
        
        storageOptions: {
          skipBackup: true,
          path: 'tmp_files'
        },
      };

```
If you want base64 image, do this:
```
ImagePicker.launchCamera(options, (response) => {
        if (response.error) {
          console.error(response.error);
        } else if(!response.didCancel) {
          RNFS.readFile(response.uri, "base64").then(based => {
            // binary data
            _this.setState({
              photoUri: response.uri, //photo URI
              photoData: based, //base 64
            });
          });
        }
      });
```
So... Delete the file:
```
var file = _this.state.photoUri.split('///').pop();
    console.warn("File to DELETE: " + file);

    const filePath = file.substring(0, file.lastIndexOf('/'));
    console.warn("File Path: " + filePath);

    RNFS.readDir(filePath)
      .then(files => {
        for(let t of files) {
          RNFS.unlink(t.path);
        }

      })
      .catch(err => {
        console.error(err)
      });
```

I used this modification too, but I don't know exactly if it's make part of success or not:

> I've made a local change to MediaUtils.java:49:
> 
> ```
>         final File path = ReadableMapUtils.hasAndNotNullReadableMap(options, "storageOptions")
>             && ReadableMapUtils.hasAndNotEmptyString(options.getMap("storageOptions"), "path")
>             ? new File(reactContext.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), options.getMap("storageOptions").getString("path"))
>             : (!forceLocal ? Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
>                           : reactContext.getExternalFilesDir(Environment.DIRECTORY_PICTURES));
> 
>         // ORIGINAL CODE
>         //final File path = ReadableMapUtils.hasAndNotNullReadableMap(options, "storageOptions") && !forceLocal
>         //        ? Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES)
>         //        : reactContext.getExternalFilesDir(Environment.DIRECTORY_PICTURES);
> ```
