### ISSUE TITLE
JPEG uri returned for PNG files

### ISSUE THREAD

**Issue by borisyankov** [react-native-community/react-native-image-picker#741]
### Description

Picking a PNG image from the library returns a `name` of `something.png` but a `uri` of `path/name.jpeg` and the format of the image is actually `jpeg`.

I am missing some option or is this a bug?

### Additional Information

* React Native version: 0.50.4
* Platform: iOS 11
* Development Operating System: MacOS

**Comment by delia-m** [comment]
I have similar issue
in ios 10.3.2
pick png file (in ios, screenshot is png)
uri: jpg
uri, origURL: png

```
fileName:  "IMG_5698.PNG"
fileSize: 94205
height: 500
isVertical: true
origURL: "assets-library://asset/asset.PNG?id=4612F135-DBC9-4004-895E-05CC91F35CF2&ext=PNG"
timestamp: "2017-12-04T09:17:19Z"
uri: "file:///var/mobile/Containers/Data/Application/D3C30F67-238F-47DA-99E2-CBF06B99C5A4/Documents/DDBE4915-B667-4BE1-A8F1-1100C88399C0.jpg"
width: 281
```

**Comment by tirtaabimanyu** [comment]
having the same issue with ios, any solution?

**Comment by asifvora** [comment]
Yes you have need to changes in ios library file.
if (imageURL && [[imageURL absoluteString] rangeOfString:@"ext=GIF"].location != NSNotFound) {
                fileName = [tempFileName stringByAppendingString:@".gif"];
            }
            else if ([[[self.options objectForKey:@"imageFileType"] stringValue] isEqualToString:@"png"] || [[[self.options objectForKey:@"imageFileType"] stringValue] isEqualToString:@"PNG"] || [[imageURL absoluteString] rangeOfString:@"ext=PNG"].location != NSNotFound || [[imageURL absoluteString] rangeOfString:@"ext=png"].location != NSNotFound) {
                fileName = [tempFileName stringByAppendingString:@".png"];
            }
            else {
                fileName = [tempFileName stringByAppendingString:@".jpg"];
            }

**Comment by salahalsaleh1993** [comment]
First add imageFileType: 'png' in your options like this:
const options = {
    imageFileType: 'png'
};

Then change this line in ImagePickerManager.m:
if ([[[self.options objectForKey:@"imageFileType"] stringValue] isEqualToString:@"png"])
to this:
if ([[self.options objectForKey:@"imageFileType"] isEqualToString:@"png"])

* it appears twice in the file not once

Hope this helps

**Comment by AlMel3000** [comment]
I use unchanged file with
https://github.com/react-community/react-native-image-picker/issues/872#issuecomment-404439605

**Comment by blackburnian** [comment]
This is still an issue for me with v1.1.0. https://github.com/react-native-community/react-native-image-picker/pull/1099 fixes it for me.
