### ISSUE TITLE
Spaces in filename cause 'null' file type

### ISSUE THREAD

**Issue by simonas88** [react-native-community/react-native-image-picker#744]
### Description

When selecting an image, I expect to receive an object containing file data and file type (mime) among other things. If the file name of the selected image contains spaces, the object returned by the image picker has `null` as the type property.

### How to repeat issue and example

Just attempt to to select an image that has spaces in its name and log the lib's output.

### Additional Information

* React Native version: `0.47.0`
* Platform: tested on `Android`
* Development Operating System: test on `Mac` and `Windows`
* Dev tools: Chrome for debugging

**Comment by alecbennett** [comment]
This still occurs on react native 0.50.3+ and looks like its library specific.  I posted a quick workaround in #557 until this can be fixed.
