### ISSUE TITLE
my application crash when choose an image from gallery taken before i have installed the application

### ISSUE THREAD

**Issue by yosraab** [react-native-community/react-native-image-picker#749]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

--- Delete everything above this line ---

### Description

Explain what you did, what you expected to happen, and what actually happens.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by yosraab** [comment]
RN: 0.49.1
react-native-image-picker: 0.26.7
react :16.0.0-beta.5

**Comment by Mimicx** [comment]
Same issue, did u find a solution about this problem ?

**Comment by yosraab** [comment]
yes, i just removed the plygin "react-native-image-picker" and reinstalled
it .

2017-12-14 20:46 GMT+01:00 Luis Manuel | Mimicock <notifications@github.com>
:

**Comment by SirPhemmiey** [comment]
No fix on this?

**Comment by bosz** [comment]
Facing same issue. Please, anybody facing similar issue help. I tried @yosraab 's solution of removing and reinstalling the plugin but it didn't solve the problem. 

The app crashes at the point which you select **Choose from gallery** (to select a photo from the gallery)
