### ISSUE TITLE
Front Camera Mirror Photo

### ISSUE THREAD

**Issue by projectn3xt** [react-native-community/react-native-image-picker#750]
### Description

When I take photo using my front camera I recive a mirror photo

### How to repeat issue and example
 selectPhotoTapped() {

const options = {
      title: 'Selecionar Imagem',
      takePhotoButtonTitle: 'Tirar foto',
      chooseFromLibraryButtonTitle: 'Escolher da galeria',
      quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      //console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
       // let source = { uri: response.uri };
       // You can also display the image using data:
       let source = { uri: 'data:image/jpeg;base64,' + response.data };
        this.setState({
          profilePic: source
        });
      }
    });

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: 0.47.2
* Platform: Android
* Development Operating System: Mac High Sierra
* Dev tools: Visual Studio Code

**Comment by adamivancza** [comment]
I don't think this is a bug. iOS default camera app works the same way. https://www.quora.com/Why-are-selfie-pictures-mirror-images-while-rear-camera-images-are-not
