### ISSUE TITLE
Both permissions must be granted for Android Take Photo or Choos from Library

### ISSUE THREAD

**Issue by dennisgann** [react-native-community/react-native-image-picker#752]
### Description

On Android, when calling ImagePicker.showImagePicker it shows the default dialog prompting user to choose between Take Photo or Choose from Library. When either is clicked it will request permissions for BOTH camera and library access, this is not intuitive for the user.
The expected functionality would be that on pressing "Take Photo" only camera permissions would be checked and vice versa for "Choose from library". Only one permission prompt should be shown at a time, NOT both in succession.

The flow on iOS works perfectly.

This issue is related to #717.

### How to repeat issue and example

To reproduce simply call ImagePicker.showImagePicker on Android and choose one of the options, you will notice both permission prompts show up in succession.

### Solution

Only show relevant permissions prompt. Instead of checking if both have been granted, only check the required one. 

### Additional Information

* React Native version: 0.50.3
* Platform: Android
* Lib Version: 0.26.7

**Comment by haitaoli** [comment]
@dennisgann If I understand the code correctly, the camera mode also required writing to storage. After a picture is taken with the camera app, it needs to written to some file that your app can read. Camera permission for "choose from library" might be unnecessary.

**Comment by dennisgann** [comment]
@haitaoli Thanks for your response. When using the image picker camera it shouldn't need access to the media library, the photo is not saved. Rather it is stored on the device temporarily. Other apps such as Facebook messenger, Slack, etc. also don't have this behavior. The issue stems from the code in this library. We should also strive for consistency across platforms.
