### ISSUE TITLE
Both permissions are asket to  Choose from Library #752

### ISSUE THREAD

**Issue by mreda7** [react-native-community/react-native-image-picker#753]
On Android, when calling trying to open gallery , the library asks . for two permissions 'camera' and 'external storage' , 
but it works well on ios

--- Delete everything above this line ---

### Description

the library must ask only for one permission

### How to repeat issue and example

To reproduce this issue call ImagePicker.launchImageLibrary on Android .

### Solution

ask only for external storage permission 

### Additional Information

Platform: Android
Lib Version: 0.26.7

**Comment by Eldavid** [comment]
It is still problem in 0.28.1

**Comment by chris-muller** [comment]
This is an issue in `2.3.0`, I feel like this isn't a minor issue, for apps that don't need camera access, is makes your app seem like it's invading the user's privacy to be asking for access to things it doesn't need.

Additionally, if the user rejects the camera permission (which is perfectly reasonable given the situation) the photo library request will fail.
