### ISSUE TITLE
Mixed photo/video support on android

### ISSUE THREAD

**Issue by Noitidart** [react-native-community/react-native-image-picker#759]
### Description

When I launch the camera with `mediaType` set to photo, it shows the "video" icon but i cannot select it. I was hoping to be able to toggle between the two. I am only able to show "video" or "photo" is it possible to add support for "mixed" on android?

**Comment by Noitidart** [comment]
We see in this screenshot I launched it with `mediaType` of `video`. The "photo" icon is visible here at bottom but I am not able to press it. It seems the work is already done for "mixed" mode we just need a slight tweak. Any ideas please?

![screenshot_2017-12-25-21-30-23](https://user-images.githubusercontent.com/6372489/34348260-544ed1e0-e9be-11e7-8279-ee81c7600c92.png)

**Comment by Noitidart** [comment]
It seems the trick is to use the intent of `MediaStore.INTENT_ACTION_STILL_IMAGE_CAMERA` per https://stackoverflow.com/a/30041238/1828637

**Comment by haitaoli** [comment]
@Noitidart Thanks for the investigation. Do you mind submitting a PR?

**Comment by Noitidart** [comment]
@haitaoli thanks for the positivity and hope here! I tried to hack at it. I changed the intent constant to this, but it was not giving a "ok/cancel" to return the file data/path to my app. I'm a very novice, never did java/android much. May you/others please help out?

**Comment by Donhv** [comment]
@Noitidart How can show and select video and images in android?

**Comment by Noitidart** [comment]
@Donhv I couldn't figure it out. :(

**Comment by Donhv** [comment]
@Noitidart I suggest use image-coper-picker to mixed photo/videos.

**Comment by jesperlndk** [comment]
I believe #597 describes what is needed for this library.

**Comment by Donhv** [comment]
@jesperlndk it only use for ios

**Comment by totoo74** [comment]
What about playing with the custom buttons?
```javascript
const options = {
    title: 'Select the perfect view',
    storageOptions: {
        skipBackup: true,
        path: 'images'
    },
    customButtons: [
        {name: 'video', title: 'Take Video...'},
        {name: 'video_library', title: 'Choose Video from library...'},
    ],
    maxWidth: 1920,
    maxHeight: 1080,
    noData: true
};
const optionsVideo = {
    storageOptions: {
        skipBackup: true,
        path: 'movies'
    },
    noData: true,
    mediaType: 'video'
};

ImagePicker.showImagePicker(options, (response) => {
    if (response.didCancel) {
        console.log('User cancelled image picker');
    } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
    } else if (response.customButton === 'video') {
        ImagePicker.launchCamera(optionsVideo, (response)  => {
            //do what you want with the video
        });
    } else if (response.customButton === 'video_library') {
        ImagePicker.launchImageLibrary(optionsVideo, (response)  => {
            //do what you want with the video
        });
    } else {
        //do what you want with the picture
    }
});
```

**Comment by Noitidart** [comment]
@totoo74 - the problem is not on the picker part. It's once we have entered the image/video taker, we want the "picker" like interface there as well to swap from video back to image, and vice versa.

**Comment by hoscarcito** [comment]
I will appreciate some highlights here too!

**Comment by DavitVosk** [comment]
Could anyone find a solution? mediaType: "mixed" does not work on Android for me too

**Comment by Noitidart** [comment]
@DavitVosk I never found a solution.

**Comment by DavitVosk** [comment]
@Noitidart as per documentation `mixed` option is not available for Android... But I want to find a proper way to make it work as we do for IOS

**Comment by Noitidart** [comment]
@DavitVosk yes `mixed` is not available per the docs, this is known. Please see my comment above for direction in which solution lies - https://github.com/react-native-community/react-native-image-picker/issues/759#issuecomment-353969584 - it relies on modifying the native code.

**Comment by DavitVosk** [comment]
I hope package owners will handle this mismatch. This issue is open already a year 👎

**Comment by NaveedNoor92** [comment]
@DavitVosk  if you can try the react-native-image-crop component because the current( react-native-image-picker ) one also has a mime issue with the format of the video.

**Comment by cyphereza** [comment]
I kinda implemented a solution (not sure if it is up to standards) for multiple select and mixed image and photo. It is available on my repo (https://github.com/cyphereza/react-native-image-picker). And not sure if I should PR this as I am fairly new to contributing in public repos.

**Comment by marcodafonseca** [comment]
I am having this problem as well now. Will the mediaType "mixed" never be made available to Android?

**Comment by areedev** [comment]
zzz
