### ISSUE TITLE
Module '"react-native-image-picker"' has no default export.

### ISSUE THREAD

**Issue by chjwrr** [react-native-community/react-native-image-picker#768]
typescript

import ImagePicker from 'react-native-image-picker';

error TS1192: Module '"react-native-image-picker"' has no default export.

why.......

**Comment by AndrejKolar** [comment]
Add to tsconfig.json:

 `"allowSyntheticDefaultImports": true`

**Comment by challme28** [comment]
@AndrejKolar do you know how could I ignore it on flowtype?

**Comment by ideyuta** [comment]
@challme28 How about here?
```js
import * as ImagePicker from 'react-native-image-picker';
```
