### ISSUE TITLE
How to Add Image On top of the other image

### ISSUE THREAD

**Issue by fithaN** [react-native-community/react-native-image-picker#770]
### Description

How to Add Image On top of the other image

### How to repeat issue and example

This is how i would like to achieve
![img_0072](https://user-images.githubusercontent.com/33620488/34748305-fe712262-f5ef-11e7-8fc5-eed93865eebe.jpg)

### Solution

Suggest a solution 

### Additional Information

* React Native version: [react-native@0.51.0]
* Platform: [both]
* Development Operating System: [ MacOS]
* Dev tools: [ Xcode Version 10.0]

**Comment by azharrizkip** [comment]
I think you can use zIndex
