### ISSUE TITLE
How am gonna test this type of promise

### ISSUE THREAD

**Issue by NawazKhanMd** [react-native-community/react-native-image-picker#772]
am familiar with
```
 someFunction().then(()=>{
//some code 
})
```
Dunno how to test or mock this one, Pls help..... 👍 

```
ImagePicker.showImagePicker(options, response => {
            alert(JSON.stringify(response))
            return (response);
        })
```

**Comment by NonsenseJudge** [comment]
Try putting the ImagePicker.showImagePicker inside of your OnPress event from a button.

**Comment by fafnir0007** [comment]
handleButton = () =>{
ImagePicker.showImagePicker(options, response => {
            alert(JSON.stringify(response))
            return (response);
        })}

<button onPress={this.handleButton}/>

**Comment by schmijos** [comment]
Isn't the question, how to stub the function and how to test the callback? Because I am asking this myself right now and Google showed me this question.
