### ISSUE TITLE
iOS - Compilation error 

### ISSUE THREAD

**Issue by mzafer** [react-native-community/react-native-image-picker#773]
### Description

After installing the module and running "react-native run-ios" I am getting a lot of warning/errors  like below, any thoughts why I am seeing this ?

In module 'Photos' imported from /Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:5:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHPhotoLibrary.h:15:28: note: 'PHAuthorizationStatus' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, PHAuthorizationStatus) {
                           ^
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:551:26: note: enclose 'PHAuthorizationStatusNotDe
termined' in an @available check to silence this warning
    } else if (status == PHAuthorizationStatusNotDetermined) {
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:552:10: warning: 'PHPhotoLibrary' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
         ^~~~~~~~~~~~~~
In module 'Photos' imported from /Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:5:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHPhotoLibrary.h:36:55: note: 'PHPhotoLibrary' has been explicitly marked partial here
PHOTOS_CLASS_AVAILABLE_IOS_TVOS(8_0, 10_0) @interface PHPhotoLibrary : NSObject
                                                      ^
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:552:10: note: enclose 'PHPhotoLibrary' in an @available check to silence this warning
        [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
         ^~~~~~~~~~~~~~
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:552:48: warning: 'PHAuthorizationStatus' is only available on iOS 8.0 or newer [-Wunguarded-availability]
        [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
                                               ^~~~~~~~~~~~~~~~~~~~~
In module 'Photos' imported from /Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:5:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHPhotoLibrary.h:15:28: note: 'PHAuthorizationStatus' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, PHAuthorizationStatus) {
                           ^
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:552:48: note: enclose 'PHAuthorizationStatus' in an @available check to silence this warning
        [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
                                               ^~~~~~~~~~~~~~~~~~~~~
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:553:27: warning: 'PHAuthorizationStatusAuthorized' is only available on iOS 8.0 or newer [-Wunguarded-availability]
            if (status == PHAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In module 'Photos' imported from /Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:5:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/System/Library/Frameworks/Photos.framework/Headers/PHPhotoLibrary.h:15:28: note: 'PHAuthorizationStatus' has been explicitly marked partial here
typedef NS_ENUM(NSInteger, PHAuthorizationStatus) {
                           ^
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:553:27: note: enclose 'PHAuthorizationStatusAuthorized' in an @available check to silence this warning
            if (status == PHAuthorizationStatusAuthorized) {
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m:685:16: warning: implicit boolean conversion of Objective-C object literal always evaluates to true [-Wobjc-literal-conversion]
        return @NO;
        ~~~~~~ ^~~
59 warnings and 3 errors generated.



** BUILD FAILED **


The following build commands failed:

	CompileC /Users/mzafer/projects/app/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/react-native-image-picker.build/Objects-normal/x86_64/ImagePickerManager.o /Users/mzafer/projects/app/node_modules/react-native-image-picker/ios/ImagePickerManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)





### Additional Information

* React Native version:0.51.0
* Platform: iOS, Android
* Development Operating System: MacOS
* Dev tools: iOS11.0

**Comment by basir** [comment]
I have this issue. please fix it.
