### ISSUE TITLE
not comptabile with MI devices?

### ISSUE THREAD

**Issue by shimil2017** [react-native-community/react-native-image-picker#774]
--- Delete everything above this line ---

### Description
When you user try to pick image in MI devcices it showing user cancelled photo picker.whcih is not present in any other devices

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by maomeiqi** [comment]
Solve it？
