### ISSUE TITLE
undefined is not a function (evaluating '(0, _reactNativeImagePicker2.default)')

### ISSUE THREAD

**Issue by zfiratselim** [react-native-community/react-native-image-picker#778]
### Description

Error react-native-image-picker. Library is es5 my script is es6 
![26942869_1592043620844323_1218263587_n](https://user-images.githubusercontent.com/30474437/34911197-29b33364-f8d6-11e7-9ab8-a4ca79976960.png)

My library edit. 
![2018-01-14 02-55-02 ekran goruntusu](https://user-images.githubusercontent.com/30474437/34911205-5d68bda0-f8d6-11e7-923c-032a20ce0e75.png)

### Additional Information
* React version: 16.0.0-alpha.12
* React Native version: 0.51.0
* Platform: Android
* Development Operating System: Linux
* Dev tools: Android SDK 24

**Comment by martinepic** [comment]
@zfiratselim do you generated the build again?

**Comment by moogman** [comment]
Try running `react-native link`

**Comment by radreamer** [comment]
same on iOS, project rebuild doesn't help

**Comment by chai86** [comment]
Same issue on iOS, no resolution even in 2019???

**Comment by riyaz1620390** [comment]
```
@Nullable
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.asList(
      .........
      new ImagePickerPackage()   // <-- add this to your application class people!
    );
  }
```
