### ISSUE TITLE
[Camera Crash]: Incompatibility with react-native-camera 0.13.0?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-image-picker#780]
### Description

When I use the "Take Photo" option to open the camera on Android and snap a picture, the app immediately crashes. This happens when `react-native-camera` is also installed in the project at version `0.13.0`. If I downgrade `react-native-camera` to `0.12.0`, everything works again.

### How to repeat issue and example

1. `npm install --save react-native-camera`
2. Boot up the Android version of the app
3. Try to snap a photo using this library

### Solution

Identify what's causing this incompatibility?

### Additional Information

* React Native version: `0.52.0`
* Platform: Android
* Development Operating System: macOS
* Dev tools: Android studio 3.0.1
* react-native-image-picker: `0.26.7`

**Comment by hkung77** [comment]
I too was experiencing this issue. I think it's related to #762. I was getting the same errors.

**Comment by udfalkso** [comment]
I had this issue in emulator, but camera works ok on real device.

**Comment by prakashbrili** [comment]
React-native-camera 0.13.0 for android have an issue, and it supports 0.9.5 version in Android
