### ISSUE TITLE
crashing issue after uploading image from gallery 

### ISSUE THREAD

**Issue by atchuthsai468** [react-native-community/react-native-image-picker#781]
If i  upload an image from gallery it Redirecting to Homepage
 picking photos from gallery or taking a photo from camera without showing any error and  restarts the app 

  i'm using react-native-image-picker module 
i tried to store image in firebase database 

* React Native version: 0.46.4
* Platform: both
* Development Operating System:  MacOS, 
* Dev tools:Android Studio navigation crash for Android

**Comment by haitaoli** [comment]
If your device is low on memory when gallery app launches, Android may stop your activity then restore it after gallery app finishes. It may look like a restart. Unfortunately we haven't found a solution to restore a React Native module state yet.

**Comment by atchuthsai468** [comment]
Now what i have to do, how to fix this problem

**Comment by martinepic** [comment]
I have the same problem - version android 6.0 API 23

**Comment by atchuthsai468** [comment]
No problem with my device gallery still I'm getting error
