### ISSUE TITLE
Implicit boolean conversion of Objective-C object literal always evaluates to true

### ISSUE THREAD

**Issue by ayushiSharma22** [react-native-community/react-native-image-picker#783]
### Description

I upgraded my react-native version to 0.43.0. And ran my app in xcode 9.2 but i get this error: "Implicit boolean conversion of Objective-C object literal always evaluates to true" on line 685: -> statement: "return @NO;"

### How to repeat issue and example

Run Xcode 9.2 and received this warning "Implicit boolean conversion of Objective-C object literal always evaluates to true" in File ImagePickerManager.m

### Additional Information

* React Native version: [0.43.0]
* Platform: [iOS]
* Development Operating System: [MacOS]
* Dev tools: [Xcode]

**Comment by ajfigueroa** [comment]
Were you running the example app or did you install this as a dependency in an existing application?
