### ISSUE TITLE
Automatic install on Android misses permissions setup

### ISSUE THREAD

**Issue by greenais** [react-native-community/react-native-image-picker#787]
RN 50.4
RNIP- latest

As per topic - linking misses adding 

===================================

uses-permission android:name="android.permission.CAMERA" 
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"

===================================

necessary strings to AndroidManifest.xml, they still should be added manually.
This probably should be reflected in docs.

**Comment by Austyns** [comment]
There is a part titled IMPORTANT NOTE in https://github.com/react-community/react-native-image-picker#automatic-installation which says ```You'll still need to perform step 4 for iOS and steps 2 and 5 for Android of the manual instructions below.``` From the Readme file on automatic installation
