### ISSUE TITLE
Cannot access Videos in device

### ISSUE THREAD

**Issue by Thanmai-C** [react-native-community/react-native-image-picker#789]
Hi,
I am using react-native-image-picker to access the images AND videos on the device, but i am able to access the images. But NOT the videos.

test device: Nexus 5X (Android 8.0)
RN version: 0.46.4
react-native-image-picker: ^0.26.3

**Comment by ProteanDev** [comment]
I currently got this issue with iOS
see #793 

Not solutions yet as of the moment I posted this comment though...

**Comment by ProteanDev** [comment]
@Thanmai-C did you solved this?

**Comment by Thanmai-C** [comment]
No I didn't find any solution for it on Android.
But works well on iOS

**Comment by ProteanDev** [comment]
@Thanmai-C I wasn't having issues with Android, but how did you made it work with iOS Videos?

**Comment by Thanmai-C** [comment]
U can use the mediaType property as 'mixed',  check the docs.
How do u access both images and videos on Android?

**Comment by ProteanDev** [comment]
Still getting this error:
`[discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}`

I use `react-native-get-real-path` for android, then pass the resulting file path to `react-native-fs`'s  readFile() method

**Comment by slickdev** [comment]
CameraRoll isn't retrieving videos anymore for me on iOS 11.2. My app was working fine and after the 11.2 update was released I started receiving bug reports that they can't see any of their videos.

**Comment by ProteanDev** [comment]
@slickdev yeah I'm also getting that error with iOS 11.2+

**Comment by slickdev** [comment]
@ProteanDev I think it's because iOS deprecated the Assets Library Framework since iOS 9 and now are using Photos Framework... not sure what the best solution for this would be. If you come up with any ideas let me know!

**Comment by ProteanDev** [comment]
@slickdev you might be right. Someone had to do a PR for that to fix this package.

**Comment by CubixTagon** [comment]
@slickdev did you got any solution?

**Comment by slickdev** [comment]
@CubixTagon it appears to be working properly for me now. Are you still experiencing this issue after updating all dependencies?

**Comment by CubixTagon** [comment]
yes @slickdev. I am using latest version i.e 0.26.7. But still facing this issue.

**Comment by ajaykumar97** [comment]
@slickdev What are the dependencies you talking about?

**Comment by LongicornYu** [comment]
I'm experiencing same issue. @slickdev , can you share what dependencies should be updated? Thanks

**Comment by DavitVosk** [comment]
Guys as per documentation (https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md), `mediaType` can't be `mixed` for Android. Could anyone find a solution to make both work on Android as well as it does now on IOS?

**Comment by pmella16** [comment]
if you need access to video from the gallery you can add this code in /node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java


line 338
      libraryIntent = new Intent(Intent.ACTION_PICK,
      MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
      libraryIntent.setType("image/* video/*");

**Comment by DavitVosk** [comment]
@pmella16 your proposed solution did not work unfortunately

**Comment by hossamnasser938** [comment]
@pmella16 Your solution worked for me. Thank you

**Comment by Mohamedghaly140** [comment]
still having this issue even if i use mixed for mediaType
