### ISSUE TITLE
Where my images is uploaded ?

### ISSUE THREAD

**Issue by Johnba1988** [react-native-community/react-native-image-picker#791]
I tried to do this example and it worked , but I don't know where my images uploaded ? I want to choose the folder of upload .

**Comment by wvicioso** [comment]
i dont think you image is actually being uploaded into the your directory. When using this libraey, I only save the base64 string to the components `state`. if I wanted to persist the image I would save it in an external api or use AWS S3 storage

**Comment by kilaniba** [comment]
Thank you for your help.

**Comment by laksh1010** [comment]
@wvicioso hi mate can i know how you upload the images taken by react-native-image-picker to aws s3 bucket ? im also kinda in same situation

**Comment by brunokunace** [comment]
@wvicioso i try to use base64 and save on database, but the base64 always getting error. i try to use the base64 on another site, but the code is wrong.

@Johnba1988 on Android saves on picture folder, on root
