### ISSUE TITLE
Custom Image Library header style

### ISSUE THREAD

**Issue by sandywk** [react-native-community/react-native-image-picker#792]
### Description

I want to customize the style of the head when I use Image Library. How should I do it?

### How to repeat issue and example

> // Open Image Library:
ImagePicker.launchImageLibrary(options, (response)  => {
  // Same code as in above section!
});

### Solution

I don't know

### Additional Information

* React Native version: 0.51.0
* Platform: iOS and Android
* Development Operating System: MacOS
* Dev tools: Xcode 9.2

**Comment by Choco-milk-for-u** [comment]
did you find a solution?
