### ISSUE TITLE
[iOS] Loading Video via Response URI - NOT WOKRING

### ISSUE THREAD

**Issue by ProteanDev** [react-native-community/react-native-image-picker#793]
### Description

Getting this Error with Xcode:

[discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}

And I am NOT able to get the Video File via source

### How to repeat issue and example

With This
let source = { uri: response.uri }

Using this:
storageOptions: {
		cameraRoll: true,
		waitUntilSaved: true,
		skipBackup: true,
		path: 'videos'
	}

### Solution

I honestly got no idea why I CAN save yet NOT being able to retrieve. 

### Additional Information

* React Native version: 0.52.0
* Platform: iOS
* Development Operating System: MacOS High Sierra
* Dev tools: Xcode 9.2 (9C40b), iOS 11.2.5

**Comment by ProteanDev** [comment]
Hello? Please help... :(

**Comment by ProteanDev** [comment]
Anybody?

**Comment by ProteanDev** [comment]
Help! Help! Help!

**Comment by ProteanDev** [comment]
So you guys just gonna wait till this post get's so inactive before you help or what?

**Comment by valeryq** [comment]
Same troubles, guys. But with images and only on IOS when permission popup showing first time.

**Comment by fendorio** [comment]
+1 getting this on this repo, and can't select videos using react-native-image-crop-picker on IOS 11 either..... bumer!

**Comment by EnzoVezzaro** [comment]
got this problem with images, any solution yet?
