### ISSUE TITLE
How to reduce quality image after select ?

### ISSUE THREAD

**Issue by Johnba1988** [react-native-community/react-native-image-picker#796]
### Description
I want after select a photo from the device library reduce quality of image before post it in database.

### How to repeat issue and example

Here is my code , what I expect to solve my proble:
`ImagePicker.showImagePicker(options, response => {`
     ` if (response.didCancel) {`
      `  console.log("User cancelled image picker");`
      `} else if (response.error) {`
        `console.log("ImagePicker Error: ", response.error);`
     ` } else if (response.customButton) {`
        `console.log("User tapped custom button: ", response.customButton);`
   `   } else {`
        `let source = { uri: response.uri };`
        

### Additional Information

* React Native version:"0.52.0"
* Platform: [ both]
* Development Operating System: [Windows]
* Dev tools: [ Android SDK version]

**Comment by minhphung210** [comment]
https://github.com/bamlab/react-native-image-resizer
maybe help you

**Comment by prakas25** [comment]
you can change the quality in the 'option' that you are sending to 'showImagePicker' as
const options = {
  quality: 0.5,
  ...
}

**Comment by bhanuka96** [comment]
` File image = await ImagePicker.pickImage(source: ImageSource.gallery,imageQuality: );`
