### ISSUE TITLE
Can i know how to remote upload the selected image to some server / CDN

### ISSUE THREAD

**Issue by laksh1010** [react-native-community/react-native-image-picker#798]
hi thanks for the great plugin. please can anyone help me on how to remote upload the selected image via camera or gallery to remote server or cdn that i have access to

im in a learning RN... thanks for the understanding.

**Comment by taqi457** [comment]
`const makeForm = (response) => {
 let data = new FormData();
 data.append('title', name);
 data.append("file", {
    response.uri,
    response.name,
    response.type
  });
 return data;
}
`
where the response is what you get from the image-picker.
You can just use simple fetch or any other http-client and send the photo to your server as a POST with content-type header as multi-part form.

**Comment by jimji1005** [comment]
```
export const uploadPhoto = (url , photo_uri) => {

    const data = new FormData();

    data.append('photo', {
        uri: photo_uri,
        type: 'image/png',
        name: 'photo'
    });

    //build payload packet
    var postData = {
        method: 'POST',
        headers: {
            'Content-Type': 'multipart/form-data',
            'somevar': 'whatever you want to pass'
        },
        body: data,
    }

    return fetch(url, postData)
        .then((response) => response.json())
        .then((responseJson) => {

            console.log('responseJson',responseJson);
            return responseJson;

        })
        .catch((error) => {
            
            console.log('error',error);

        });

}
```

**Comment by Mohammad-Khalid23** [comment]
**"react-native": "0.56.0"**
**"react-native-image-picker": "github:gengjiawen/react-native-image-picker#bugfix/android_photo_crash"**
**For android**
   
I called the function on any event to upload image
 openImagePicker = (img) => {
        console.log(img, "Image picker function")
        var options = {
            title: 'Select Avatar',
            customButtons: [
                { name: 'fb', title: 'Choose Photo from Facebook' },
            ],
            storageOptions: {
                skipBackup: true,
                path: 'images'
            }
        };
        ImagePicker.showImagePicker(options, (response) => {
            console.log('Response = ', response);

            if (response.didCancel) {
                console.log('User cancelled image picker');
            }
            else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            }
            else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            }
            else {
                let source = { uri: response.uri };
                const imageData = new FormData();
                imageData.append('name', 'image');
                imageData.append('image', {
                    uri: response.uri,
                    type: response.type,
                    name: response.fileName,
                    data: response.data
                });
                //here you can call api and send the image data in data of api ,in uploadImage I called the api
                this.props.actions.uploadImage(imageData).then(response => {
                 console.log(response,"response of upload image");
                }, (err) => {
                    console.log(err, "error of upload image")
                })
            }
        });
    }

**Comment by JonathanRufino** [comment]
@Mohammad-Khalid23 You just saved my life. Thank you so much :smile:

**Comment by danielzzz** [comment]
when I try to use form data the  file field is being sent as [Object object] (String) instead of actual object
what might be the reason for that?

```
const data = new FormData();


  //process file upload
  if (comment.attachment) {
    let file = {
      data: comment.attachment.data,
      name: comment.attachment.fileName,
      type: comment.attachment.type,
      uri:
        Platform.OS === 'android'
          ? comment.attachment.uri
          : comment.attachment.uri.replace('file://', ''),
    };
    data.append('attachment', {file});
  }
```

**Comment by danielzzz** [comment]
ok, it was a setting in react-native-debbugger to track network requests. it makes formdata unusable for file uploading

**Comment by DhawanRachakonda** [comment]
@danielzzz how did you fix that?, even I am facing same issue. Did you generate SDK and test?

**Comment by DhawanRachakonda** [comment]
You need to update FLIPPER_VERSION of gradle.properties to FLIPPER_VERSION=0.39.0. Afetr that it worked for me.
After you update you have to clean gradle, else it wont work. Here are links which found me helpful:
https://stackoverflow.com/questions/61046007/form-post-with-file-attach-throws-network-error-react-native-react-native-im
https://github.com/facebook/flipper/issues/993#issuecomment-619823916

**Comment by dawiddydlinski** [comment]
> You need to update FLIPPER_VERSION of gradle.properties to FLIPPER_VERSION=0.39.0. Afetr that it worked for me.
> After you update you have to clean gradle, else it wont work. Here are links which found me helpful:
> https://stackoverflow.com/questions/61046007/form-post-with-file-attach-throws-network-error-react-native-react-native-im
> [facebook/flipper#993 (comment)](https://github.com/facebook/flipper/issues/993#issuecomment-619823916)

Thanks for your answer! I was trying to upload an image with formData, but I had never-ending loading with Axios. Updating  FLIPPER_VERSION helped me yay!

**Comment by ksielyov** [comment]
Not working ALL

**Comment by reboss** [comment]
Doing this: 
```javascript
 imageData.append('image', {
    uri: response.uri,
    type: response.type,
    name: response.fileName,
    data: response.data
});
```
Does not work.  It doesn't even send the network request when I try to append an object.  But if I append it as a string, for example:
```javascript
 imageData.append('image', JSON.stringify({
    uri: response.uri,
    type: response.type,
    name: response.fileName,
    data: response.data
}));
```
Then it will send the request, but it breaks for obvious reasons.  Why is `FormData` not allowing me to append an object?

**Comment by banjo09** [comment]
@reboss you are a real boss. God bless you. Amen

**Comment by alielmajdaoui** [comment]
One issue that is not related to the frontend is Nginx, make sure it doesn't respond with `413 Request Entity Too Large` error. If it is, try to add `client_max_body_size 50M` into the `http` section of your nginx.conf file.
