### ISSUE TITLE
Camera is not opening after react-native upgrade from 0.47.2 to 0.52?

### ISSUE THREAD

**Issue by nichesoftgh04** [react-native-community/react-native-image-picker#803]
### I updated my react-native version from 0.47.2 to 0.52. Before this updation ImagePicker was opening camera fine and was taking pictures. But after this updation camera is not opening and it says 'ImagePicker Error:  Couldn't get file path for photo' and camera is not opening. 

What could possibly go wrong with this upgrade?

**Comment by daanoz** [comment]
Kinda got it working, but just by step-by-step debugging the issue... No guarantee it will work for everyone. 

Add this in your `android/app/src/main/AndroidManifest.xml`
``` 
<manifest xmlns:tools="http://schemas.android.com/tools"
                 ...>
 ...
  <application>
   ....
    <provider
      android:name="android.support.v4.content.FileProvider"
      android:authorities="${applicationId}.provider"
      android:exported="false"
      android:grantUriPermissions="true">
      <meta-data
        tools:replace="android:resource"
        android:name="android.support.FILE_PROVIDER_PATHS"
        android:resource="@xml/provider_image_picker_paths" />
    </provider>
  </application>
</manifest>
```

And add a file in the resources dir `android/app/src/main/res/xml/provider_image_picker_paths.xml`
```
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="files"  path="/" />
</paths>
```

**Comment by tugorez** [comment]
@daanoz  I can confirm it works, thank you very much

**Comment by MewX** [comment]
Thanks, but unfortunately, didn't work in my case

**Comment by rahul120292** [comment]
i added this lines under res folder .and camera got worked 
 <files-path name="shared" path="."/>
    <external-path name="shared" path="."/>
    <external-files-path name="shared" path="."/>
    <root-path name="root" path="."/>

**Comment by rahul120292** [comment]
i added this lines under res folder .and camera got worked
    <files-path name="shared" path="."/>
    <external-path name="shared" path="."/>
    <external-files-path name="shared" path="."/>
    <root-path name="root" path="."/>

**Comment by barinascode** [comment]
remove this code

> android/app/src/main/AndroidManifest.xml

```
 <provider
        android:name="androidx.core.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/provider_image_picker_paths" />
      </provider>
```
