### ISSUE TITLE
Multiple dex files defined Android studio error. 

### ISSUE THREAD

**Issue by mjk22071998** [react-native-community/react-native-image-picker#804]
When I add functionality on my app i-e getting system date and time on an activity it work perfectly but when I do same on fragments (because i want to add some more functionalities) It give following error

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/design/widget/CoordinatorLayout$1;

Actually I want to ask what are these DEX files and how multiple DEX files are are defined

**Comment by mjk22071998** [comment]
And I am not using Coordinator layout in any of my classes and layouts

**Comment by GustavoPMSilva** [comment]
Don't know if it will help you but when I updated the compileSdkVersion, buildToolsVersion and com.android.support packages to 27 (is was 26) the error stopped

**Comment by mjk22071998** [comment]
Thanks

**Comment by vanikalai** [comment]
Information:Gradle tasks [:app:assembleDebug]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;
Error:com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lnet/sqlcipher/database/SQLiteDebug$PagerStats;
Information:BUILD FAILED in 30s
Information:15 errors
Information:0 warnings
Information:See complete output in console




Hi 
Can you help me to resolve this,
I am getting this error only at Runtime.

**Comment by cinder92** [comment]
same issue here
