### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ThomWright** [react-native-community/react-native-image-picker#805]
Is a new version scheduled to be released soon?

We're suffering from problems which are fixed by #727 which has been merged, but not released yet.

We'd really appreciate this getting released soon :slightly_smiling_face:

**Comment by MrHubble** [comment]
@ThomWright have you tried using the master branch? 

Inside your `package.json` you replace `"react-native-image-picker": "^0.26.4"` with `"react-native-image-picker": "git+https://git@github.com/react-community/react-native-image-picker"`

Then run `yarn upgrade react-native-image-picker` or the relevant npm command.

**Comment by ThomWright** [comment]
Thanks for the suggestion @MrHubble - we've already pinned our dependency to a commit hash, but ideally we'd like to use a proper release.
