### ISSUE TITLE
Unexpected rotation and 'isVertical' values on Android

### ISSUE THREAD

**Issue by embpdaniel** [react-native-community/react-native-image-picker#807]
### Description

Hi, I feel I am seeing unexpected values for `originalRotation` and `isVertical`.

I get `originalRotation` as `0` for landscape counter-clock-wise rotated, and also for portrait (right-side up).

I get `isVertical` set to `true` on every orientation except when I hold the phone upside down.

Expected:

I expected `originalRotation` to have different values while on portrait, and while rotated to landscape counter-clockwise, as they are different orientations. To note, I get values if phone is upside down (`originalRotation:720`) and if rotated clock-wise (`originalRotation:180`)

I expected `isVertical` to be `false` on landscape orientations.

I am taking photos on a real device (LG Stylo), using the back camera.

### How to repeat issue and example

1. Invoke Picker
2. Take a picture with camera
3. Log the response from the picker once image is selected

### Solution

Assuming this is a bug (hoping I'm not just not understanding how it SHOULD work), read the Exif data properly when image is loaded.

### Additional Information

* React Native version: 0.52.0
* Platform: Android
* Development Operating System: MacOS Sierra 10.12.6
* Dev tools: VS Code, Android SDK Tools 26.1.1
* Device: LG Stylo, Android 6.0

**Comment by DavitVosk** [comment]
Could you solve this problem?

**Comment by embpdaniel** [comment]
@DavitVosk This was a while ago, but I don't believe I was able to fix it. At the time I went with [react-native-image-resizer](https://github.com/bamlab/react-native-image-resizer) and [react-native-exif](https://github.com/francisco-sanchez-molina/react-native-exif) to get this working. Hope that helps
