### ISSUE TITLE
mysql value not null

### ISSUE THREAD

**Issue by lebog** [react-native-community/react-native-image-picker#809]
hello
someone can help me?

i create a table in mysql and i put one column NOT NULL
but when i insert a null data in this column it's inserted in the column as an empty data without return an error...i want error be returned because i insert a null value in a not null columns
that is how i create my table:
CREATE TABLE tab (
idm int(11) NOT NULL,
cln varchar(12) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
here i insert data:
INSERT INTO tab (idm, cln) VALUES
(1, null);

and i found result like this : INSERT INTO tab (idm, cln) VALUES
(1, "");
instead to return an error.

I work under lunix(ubuntu)

**Comment by jimji1005** [comment]
is this off topic or what
