### ISSUE TITLE
How to get video file size?

### ISSUE THREAD

**Issue by tjsaini007** [react-native-community/react-native-image-picker#810]
Hello Team, 
I am working on a project in which there is a requirement of **video size**. Please tell me how to get the video size using your library?

Current RN versions:
"react": "16.0.0",
"react-native": "0.51.0",
"react-native-image-picker": "^0.26.7"

Thanks.

**Comment by nextdooroldwang** [comment]
same

**Comment by ducanhmai205** [comment]
+1

**Comment by sqlninja** [comment]
+1

**Comment by nicoara** [comment]
+1

**Comment by hanishcodebrew** [comment]
@tjsaini007  use this 

 ```
RNFetchBlob.fs.stat(path)
                    .then((stats) => { 
                        this.setState({
                            videoSize: stats.size
                        });
                    })
                    .catch((err) => { })
```

**Comment by samuelmataraso** [comment]
any solution for this?

**Comment by ZaikinaEvgeniya-2** [comment]
RNFetchBlob.fs.stat(path) not working for IOS for me, but works fine for Android
