### ISSUE TITLE
Could not invoke ImagePickerManager.showImagePicker on Android

### ISSUE THREAD

**Issue by zasyadev** [react-native-community/react-native-image-picker#815]
### Description
I m trying to call `ImagePicker.showImagePicker(options, (response) => {})`, onPress, but it gives me the following error(in image). I have configured the library properly. Why is it happening? 

![screenshot_1521710985](https://user-images.githubusercontent.com/30326446/37763128-3cc8f662-2de4-11e8-9eed-5cc0a6d172b9.png)

If I call 
```
ImagePicker.launchCamera(options, (response)  => {
});
```
it works fine,
but showImagePicker is not being invoked.

```
<TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
                    {/* {avatar} */}
                    { this.state.ImageSource === null ? avatar :
                    <Image style={styles.proImageStyle} source={this.state.ImageSource} />
                    }
 </TouchableOpacity>
```

```
selectPhotoTapped() {
        const options = {
            quality: 1.0,
            maxWidth: 500,
            maxHeight: 500,
            storageOptions: {
                skipBackup: true
            }
        };

ImagePicker.showImagePicker(options, (response) => {
            console.log('Response = ', response);
            if (response.didCancel) {
              console.log('User cancelled photo picker');
            } else if (response.error) {
              console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
              console.log('User tapped custom button: ', response.customButton);
            } else {
              const source = { uri: response.uri };
              // You can also display the image using data:
              // let source = { uri: 'data:image/jpeg;base64,' + response.data };
              this.setState({
                ImageSource: source
              });
            }
        });
    }
```

### Additional Information

* React Native version: 0.53.3
* react-native-image-picker": "^0.26.7
* Platform:  Android
* Development Operating System:  Windows

**Comment by Monte9** [comment]
I ran into this issue as well. It was throwing this exact error:

<img src="https://user-images.githubusercontent.com/7840686/39539929-07a432e4-4df6-11e8-9d81-ae9f4cacd031.jpg" width="300" />

**And I fixed it by adding this to my `android/build.gradle` file:**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext {
    compileSdkVersion = 26 // Or what version you want (latest is recommended)
    buildToolsVersion = '26.0.2' // same thing
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}
```

Hope this helps someone. 👍

**Comment by kkusanagi** [comment]
Nop, it won't work. any solution?

**Comment by andreykrugliak** [comment]
updating to support-v4 and appcompat-v7 helps me: 
```
com.android.support:appcompat-v7:27.1.1
com.android.support:support-v4:27.1.1
```

**Comment by lamnh96** [comment]
thankyou, it works

**Comment by Muntaqeem** [comment]
> updating to support-v4 and appcompat-v7 helps me:
> 
> ```
> com.android.support:appcompat-v7:27.1.1
> com.android.support:support-v4:27.1.1
> ```

My gradle is 4.4 and this doesn't work. Can anyone give any solution? I've already upgraded to the latest version which is 0.28.0. It still shows the same error.

**Comment by Muntaqeem** [comment]
> updating to support-v4 and appcompat-v7 helps me:
> 
> ```
> com.android.support:appcompat-v7:27.1.1
> com.android.support:support-v4:27.1.1
> ```

This one works..Thanks

**Comment by kaytee319** [comment]
@Muntaqeem where to make these changes??

**Comment by jayan2019** [comment]
@andreykrugliak Thank you so-much, it works 🙏🏻
@kaytee319  Update insight `android/app/build.gradle`
```js
dependencies {
    ....
    compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}" // or 27.1.1
    compile "com.android.support:support-v4:${rootProject.ext.supportLibVersion}" // or 27.1.1
    .....
}
```

**Comment by itsChirag** [comment]
> updating to support-v4 and appcompat-v7 helps me:
> 
> ```
> com.android.support:appcompat-v7:27.1.1
> com.android.support:support-v4:27.1.1
> ```

this solution works for me Thank you !
