### ISSUE TITLE
Add support for iOS 11 UIImagePickerController permissions change

### ISSUE THREAD

**Issue by ajfigueroa** [react-native-community/react-native-image-picker#818]
### Description

In iOS 11, the `UIImagePickerController` is more sandboxed now meaning that asking for permission to access a photo is no longer required as it is a separate process.

To copy the excerpt from this SO [answer](https://stackoverflow.com/a/46594741/1631577) from rickster:
```
In iOS 11, UIImagePickerController runs as a separate process from your app. That means:

1. Your app can't see the user's whole Photos library — it gets read-only access just 
for whichever asset(s) the user chooses in the image picker.
2. Because of (1), your app doesn't need the standard privacy authorization for Photos 
library access. The user explicitly chooses a specific asset (or multiple) for use in your 
app, which means the user is granting your app permission to read the asset(s) in question.
```

### How to repeat issue and example

For the below scenarios, build on an iOS 11 device.

### Scenario 1
1. Launch image picker via `Select a Photo` and tap `Choose from Library...`
2. Verify that the iOS native permission prompt appears asking for access to Photos
3. This shouldn't appear anymore

### Scenario 2
1. Launch image picker via `Select a Photo` and tap `Choose from Library...`
2. Verify that the iOS native permission prompt appears asking for access to Photos
3. Tap `Cancel`
4. Observe nothing happens
5. This shouldn't affect whether the image picker appears for iOS 11

### Solution

To address this issue, we just need to limit the permissions request to pre-iOS 11 devices for image picker single image selection only

### Additional Information

* React Native version: 0.40.0
* Platform: iOS
* Development Operating System: MacOS
* Dev tools:  Xcode 9.2, iOS 11 SDK

**Comment by QuentinWangWJJ** [comment]
Hi, is that mean we no longer need to add NSPhotoLibraryAddUsageDescription and NSPhotoLibraryUsageDescription in info.plist? Thanks!
