### ISSUE TITLE
App crashes on limited memory devices

### ISSUE THREAD

**Issue by herlarb** [react-native-community/react-native-image-picker#822]
### Description
The app crashes when the user attempts to load images from gallery when using memory limited devices
### How to repeat issue and example
1.  Deploy an application  using the react-native-image-picker module on  a memory limited device
2. Attempt to load images for selection in gallery
3. Observe

Expected Result
App should not crash even when loading image gallery on memory limited devices

Actual Result
App crashes when the user attempts to load images from gallery on memory limited device

### Additional Information

* React Native version: [0.54.0]
* Platform: [Android]
* Development Operating System: [Windows]
* Dev tools: [Android Studio version:2.3.3, Android 4.4  ] 
https://gist.github.com/herlarb/736982fc5122565731b4d1e92b903d4d

**Comment by MaxEerdhuijzen** [comment]
+1

**Comment by shivanimonga94** [comment]
+1

**Comment by bharadwajsampath** [comment]
+1
On most of the devices , taking multiple pictures using the camera , causes
`java.lang.OutOfMemoryError: Failed to allocate a 38340876 byte allocation with 16777216 free bytes and 31MB until OOM at dalvik.system.VMRuntime.newNonMovableArray(Native Method)`

**Comment by swadhin-** [comment]
+1

**Comment by danielpgauer** [comment]
+1

**Comment by bakhaa** [comment]
+1
