### ISSUE TITLE
How to use video compression

### ISSUE THREAD

**Issue by yz-xlame** [react-native-community/react-native-image-picker#827]
The video shot is too big, how to compress

**Comment by Ding95** [comment]
use the option 'videoQuality'

**Comment by nicoara** [comment]
Hi, 
I was using Whatsapp ant it compresses video phenomenally, from 40 mb to 5 mb (85% reduction) while keeping good quality. 
I am wondering if I can achieve similar results with this library. 

I have tried to use the compression for a 40 mb video using image-picker, and the compression takes a whole few minutes. I cannot add this to production. 
My goal is to have a video after compression of under 10 mb, while waiting for about 10 seconds for the compression. How large can the original video be?

My options are: 
```
    const options = 
      {
        mediaType: 'video',
        videoQuality: 'high',
        durationLimit: 10,
        takePhotoButtonTitle: null, //'Take video...', //bug at taking video with camera so far 27/10/2018
        title: 'Select Video',
        //noData,maxWidth and maxHeight shorten time for ImportPhoto to return image
        noData: true,
        maxWidth: 1000, //speeds up compressImage to almost no time
        maxHeight: 1000, //speeds up compressImage to almost no time
        storageOptions: {
          path: 'videos',
          skipBackup: true
        }
      }
    ImagePicker.showImagePicker(options, response => {

```
Thanks!

**Comment by nicoara** [comment]
anyone?!

**Comment by yz-xlame** [comment]
@nicoara I solved it at the time, thank you for your reply.

**Comment by DavitVosk** [comment]
This package does not have an option to compress video on Android. How did you solve the problem?

**Comment by DavitVosk** [comment]
@yz-xlame how did you solve it?

**Comment by oliverdomandtom** [comment]
@yz-xlame How did you solve it?

**Comment by iguilhermeluis** [comment]
@yz-xlame How did you solve it?
