### ISSUE TITLE
[Android] Allow only using one permission rather than both

### ISSUE THREAD

**Issue by buoyad** [react-native-community/react-native-image-picker#828]
### Description

When using `Choose from library...` on Android, the imagePicker requests both library and camera permissions and returns an error if either isn't granted. This (rightfully) raises privacy concerns from users, who may only want to grant permissions for one of them. 

### How to repeat issue and example

Use `Choose from library...` on android, allow library permissions but not camera permissions; ImagePicker returns `response.error`.

### Solution

[This function](https://github.com/react-community/react-native-image-picker/blob/develop/android/src/main/java/com/imagepicker/ImagePickerModule.java#L539) already is provided with a `requestCode` corresponding to which permission we're asking for. The function should predicate which permission it requests / checks for on what this is set to.

### Additional Information

* React Native version: 0.54.3
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android studio 2.3.3

**Comment by fearmear** [comment]
Check out [my fork](https://github.com/fearmear/react-native-image-picker). It splits permission requests and has other small fixes.

**Comment by Kvazios** [comment]
Same problem. No error output, so have no idea whats going wrong

**Comment by jsha** [comment]
@fearmear would you be interested in submitting the "split permission requests" part of your fork as a PR? I would find it very useful.

**Comment by jacquesdev** [comment]
Related issue https://github.com/react-native-community/react-native-image-picker/issues/765

**Comment by jsha** [comment]
This issue still affects me.

**Comment by jacquesdev** [comment]
Agreed it should be re-opened

**Comment by chengsam** [comment]
I think it should be fixed asap..

**Comment by MaximusBaton** [comment]
Several PR's fixing this issue are on a waiting list for a pretty much long period. I don't believe this issue is gonna be fixed here in master, so better you create your own fork and step over.

https://github.com/react-native-community/react-native-image-picker/pulls

**Comment by jsha** [comment]
I would still like to see this fixed.

**Comment by jsha** [comment]
This issue is still important to me.

**Comment by jpudysz** [comment]
+1

**Comment by jsha** [comment]
I am still interested in this issue.

**Comment by jsha** [comment]
I'm still interested in seeing this bug fixed.

**Comment by jsha** [comment]
Would someone mind reopening this issue?
