### ISSUE TITLE
lost GIF's "fileName,origURL,timestamp" in iOS

### ISSUE THREAD

**Issue by 12343954** [react-native-community/react-native-image-picker#829]
### Description

When set `options.allowsEditing= false,` //保留gif格式
the JSON result lost GIF's "fileName,origURL,timestamp" in iOS

Not check it on Android yet !

### Solution & Fixed it
Add these code in 'ImagePickerManager.m' line: 326

```
NSString *timestamp = [[ImagePickerManager ISO8601DateFormatter] stringFromDate:[asset valueForProperty:ALAssetPropertyDate]];
[gifResponse setObject:[rep filename]               forKey:@"fileName"];
[gifResponse setObject:[imageURL absoluteString]    forKey:@"origURL"];
[gifResponse setObject:timestamp                    forKey:@"timestamp"];
```

![image](https://user-images.githubusercontent.com/1804003/38597277-3e8bda0a-3d89-11e8-8ff1-0f2fa6c579d9.png)

**Comment by oneroundseven** [comment]
+1

**Comment by phungnlg** [comment]
+1
