### ISSUE TITLE
A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by shuanglongpei** [react-native-community/react-native-image-picker#830]
### Description
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-image-picker'.
      > Could not resolve all dependencies for configuration ':react-native-image-picker:classpath'.
         > Could not resolve com.android.tools.build:gradle:2.2.+.
           Required by:
               rnDemo:react-native-image-picker:unspecified
            > Could not resolve com.android.tools.build:gradle:2.2.+.
               > Failed to list versions for com.android.tools.build:gradle.
                  > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
                     > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'.
                        > Connect to 127.0.0.1:1080 [/127.0.0.1] failed: Connection refused: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

### How to repeat issue and example
I follow the API instructions to set Android.But when I use 'react-native run-android',then the above exception will appear.Please tell me how to solve,thanks

### Additional Information
* React Native version: 2.0.1
* Platform: Android
* Development Operating System: Windows
* Dev tools: android-studio-ide-173.4670197-windows.exe

**Comment by shuanglongpei** [comment]
When I install react-native-image-picker.

**Comment by shuanglongpei** [comment]
When I install react-native-image-picker:
WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by shuanglongpei** [comment]
ok.The problem has been solved.I forgot to install android-21 and android-22

**Comment by sajaddp** [comment]
@shuanglongpei 
Do you mean "android-21" and "android-22" must be installed to solve the problem?

**Comment by PrimeObjects** [comment]
Because firebase need higher version of Gradle, so I changed gradle-wrapper.properties. 
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

and now the image-picker failed during build. 
Similar error with additional line 
Deprecated Gradle features were used  in this build

**Comment by shuanglongpei** [comment]
@sajaddp 
Yes

**Comment by shuanglongpei** [comment]
@PrimeObjects 
Above 2.x or later can be right, do not understand Android, but solve the problem of react-native

**Comment by akamahesh** [comment]
well my project was running fine..
this error just occurred from no where.
How i solved it?
I just enabled Gradle offline work ...it worked like a charm

**Comment by houssem23000** [comment]
@akamahesh how did u enable it?

**Comment by chachora** [comment]
@houssem23000 For e.g., `./gradlew assembleRelease --offline
`

**Comment by tusharhadawale** [comment]
@chachora   open android studio 
configure ->project defaults -> settings ->Build, Execution, Deployment -> Build Tools ->Gradel 

Just enable offline work in this 

Start new CMD. It will work.

or 


File | Settings | Build, Execution, Deployment | Build Tools | Gradle 

go to above path
