### ISSUE TITLE
（Android 7.1.0） When i choese take a photo the APP Flashback without any log 

### ISSUE THREAD

**Issue by purrck** [react-native-community/react-native-image-picker#832]
When i choese take a photo the APP flashback without any log ;
i install it follow the step the github show  ,i can choese use atlas to choese the picture ，it will work ,but
choese take photo going wrong
so i was so doubt  ，could someboby answer me ?

![_20180413151858](https://user-images.githubusercontent.com/24643608/38721813-2f24cf62-3f2e-11e8-9ff4-cb9a903ac03f.png)
![_20180413151924](https://user-images.githubusercontent.com/24643608/38721815-2f7672b8-3f2e-11e8-8f48-757536a43f65.png)

**Comment by philions** [comment]
Did you include "<uses-permission android:name="android.permission.CAMERA" />"?
