### ISSUE TITLE
Why this library handles images on the main thread, this can cause a lot of problems.

### ISSUE THREAD

**Issue by SmartLeeQ** [react-native-community/react-native-image-picker#834]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

### Description

Why do I need to put the picture taken by the photo or gallery into the main thread? Both iOS and Android are handled in the same way. This will cause many problems.

**Comment by jpodpro** [comment]
all the reasonable issues are getting marked as stale. who is maintaining this?
