### ISSUE TITLE
App crash after clicking 'Take photo' (Android)

### ISSUE THREAD

**Issue by appli-intramuros** [react-native-community/react-native-image-picker#836]
### Description

Hello,

Some Android devices (samsung A5, Android 7.0) crash just after clicking "Take photo" in the dialog box. (Choose picture from library works well.)

Please find the crash logs:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
       at com.imagepicker.ImagePickerModule.parseOptions(ImagePickerModule.java:707)
       at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:233)
       at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:206)
       at com.imagepicker.ImagePickerModule$2.onTakePhoto(ImagePickerModule.java:162)
       at com.imagepicker.utils.UI$1.onClick(UI.java:54)
       at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:807)
       at android.widget.AdapterView.performItemClick(AdapterView.java:343)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1664)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:4075)
       at android.widget.AbsListView$10.run(AbsListView.java:6557)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:762)
```

### How to repeat issue and example

Here is the source code I use to open the image picker dialog:
```
const photoOptions = {
      title: '',
      cancelButtonTitle: 'Annuler',
      takePhotoButtonTitle: 'Prendre une photo...',
      chooseFromLibraryButtonTitle: 'Choisir une photo...',
 };

showImagePicker(photoOptions, response => {
      if (!response.didCancel && !response.error && !response.customButton) {
        const imageSource = {
          uri: response.uri,
          name: response.fileName ? response.fileName : 'image.JPG',
          type: 'image/jpg',
        };

        this.setState({ imageSource });
      }
 });
```

### Solution

The null pointer appears here in the image-picker source code (ImagePickerModule.java):
```
private void parseOptions(final ReadableMap options) {
  noData = false;
  if (options.hasKey("noData")) {    **<==== HERE, options is null, but I can figure out why !?**
    noData = options.getBoolean("noData");
  }
  imageConfig = imageConfig.updateFromOptions(options);
  pickVideo = false;
  if (options.hasKey("mediaType") && options.getString("mediaType").equals("video")) {
    pickVideo = true;
  }
  videoQuality = 1;
  if (options.hasKey("videoQuality") && options.getString("videoQuality").equals("low")) {
    videoQuality = 0;
  }
  videoDurationLimit = 0;
  if (options.hasKey("durationLimit")) {
    videoDurationLimit = options.getInt("durationLimit");
  }
}
```

Is it possible to add a NPE check on options variable ?

Thanks.

### Additional Information

* React Native version: 0.54.2
* React Native Image Picker version: 0.26.7
* Platform: Android
* Development Operating System: MacOS High Sierra 10.13.4
* Dev tools: Android Studio

**Comment by scriptgb** [comment]
+1

This solution didn't apply for me, but can help someone else.

Go to Settings > Developer options.
Scroll Down till you find "Don't keep activities". Usually it should be under "App" heading.
Disable it IF it's enabled. (If its disabled, then this solution is not for you)
Try running the file upload now. It should work.

**Comment by skyforeverGE** [comment]
I am facing this situation as well

**Comment by skyforeverGE** [comment]
@appli-intramuros : I think I find out the problem, because your android application provider authorities doesn't mach with this lib {applicatinId}.provider.

you have change change to some like this below
```      <provider
          android:name="android.support.v4.content.FileProvider"
          android:authorities="<your app package name>.provider"
          android:exported="false"
          android:grantUriPermissions="true"
          tools:replace="android:authorities">
          <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/filepaths"
              tools:replace="android:resource"/>
      </provider>```

**Comment by appli-intramuros** [comment]
@skyforeverGE I don't get the point. Can you detail your solution ?

**Comment by appli-intramuros** [comment]
@skyforeverGE I precise that I don't have provider defined in my AndroidManifest.xml. I have to add one ?

**Comment by skyforeverGE** [comment]
@appli-intramuros: try adding a provider under your AndroidManifest

**Comment by skyforeverGE** [comment]
@appli-intramuros : btw, add one line ```<uses-feature android:name="android.permission.BLUETOOTH" />```, that's what I found also

**Comment by appli-intramuros** [comment]
@skyforeverGE sorry for late reply. I added the file provider to my manifest. But I can't test now because I don't reproduce the issue on my phone. The issue was reported by my crashlytics. So I will let you know if the error still occurs after deploying the new version of my app on the play store.
Thanks.

**Comment by skyforeverGE** [comment]
@appli-intramuros : don't forget ```<uses-feature android:name="android.permission.BLUETOOTH" />```, this lib needs

**Comment by appli-intramuros** [comment]
@skyforeverGE  I can't figure out why this lib is needed ?!

**Comment by skyforeverGE** [comment]
@appli-intramuros : me, neither.

**Comment by scriptgb** [comment]
I already tried all those solutions and none of them works for me when I run on Moto G3 device. In other devices, it's run properly.

**Comment by skyforeverGE** [comment]
@appli-intramuros : sorry, I don't have that modal of device.

**Comment by Sunkari16** [comment]
+1

We are also facing the same issue

**Comment by agrass** [comment]
Any solution with this issue?  I'm getting this is some devices.

**Comment by firdaussoberi** [comment]
> Any solution with this issue? I'm getting this is some devices.

Same. react-native-image-library 1.0.2 . RN 0.60.4  . adb logcat don't reveal any exception. It's weird.

**Comment by radonejr** [comment]
i was in the same situation .after take picture and confirm the app crashes even i get response 

i think there's a plugin who is crash the app in my case was react-native-location-enabler 
i wish it will help someone

**Comment by hienhodeveloper** [comment]
I'm crying. Have everyone fixed it??

**Comment by thuynt99** [comment]
I Migration to v3 and i crash app in android when i use launchCamera. Pls, Have any solution to fix it????

**Comment by vinaydanaraddi** [comment]
if the issue is with app restarting,
go to settings and select your app & set the fullScreenMode true. This fixed the app restart on Redmi Devices

**Comment by Felipe-G-Melo** [comment]
Did anyone manage to solve the problem? I have the same error on redmi note 12.
