### ISSUE TITLE
android crash when I click 'take a photo'

### ISSUE THREAD

**Issue by unionTime** [react-native-community/react-native-image-picker#838]
`
"react-native-image-picker": "^0.26.7"
"react-native": "0.48.3"
 android:6.0
`

### Solution

carsh and error When I click 'take a photo'
but It worked successfully before（and now choosing a photo is fine）

I try any means that Issues about same problem, but these weren't work!
### Additional Information

![smartselectimage_2018-04-24-17-36-28](https://user-images.githubusercontent.com/19386499/39184095-ca067e8a-47f4-11e8-9490-aa3b5c7e5281.png)

------------------------ Solution ------------------
`Build.VERSION.SDK_INT < 21 `
change is
`Build.VERSION.SDK_INT < 24`
I have updated the SDK!!!!

**Comment by skyforeverGE** [comment]
@unionTime : look at this one, see if it can help

**Comment by hungdt-ibl** [comment]
can you tell more detail about your solution ?

**Comment by jzhw0130** [comment]
Same problem, any solution? thx

**Comment by skyforeverGE** [comment]
@hungdt-ibl and @jzhw0130 : plz look at https://github.com/react-community/react-native-image-picker/issues/836, and see if it can help

**Comment by jzhw0130** [comment]
@skyforeverGE 
Sure, it works prefect. Thanks a lot.
