### ISSUE TITLE
cancelButton  disappear on ipad.

### ISSUE THREAD

**Issue by chenweigh** [react-native-community/react-native-image-picker#840]
<img width="631" alt="2018-04-25 11 12 01" src="https://user-images.githubusercontent.com/15101298/39224371-a57ec01a-4879-11e8-9ebc-b51af3adf293.png">

what is wrong?

**Comment by Ruanyang2015** [comment]
me Too @chenweigh @pedro @ligaz @nevir

**Comment by chenweigh** [comment]
@Ruanyang2015 I gave up using it and wrote a component myself.
