### ISSUE TITLE
application account creation in device in react native

### ISSUE THREAD

**Issue by Viveksmart93** [react-native-community/react-native-image-picker#843]
--- Delete everything above this line ---

### Description

I am building an app in react-native in which I need to implement contact synchronization with device for that I need to create app account in device.

### How to repeat issue and example

Your explanation here and source code or link

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by Louies89** [comment]
I think you are very new to github.
This question is irrelevant at this place. You have to ask in the react-native library, where it does contact synchronization or ask in StackOverflow.
