### ISSUE TITLE
How to get the video duration

### ISSUE THREAD

**Issue by nextdooroldwang** [react-native-community/react-native-image-picker#844]

**Comment by nikopolidi** [comment]
@DalalAbadi @nextdooroldwang durationLimit works onlt for video recording. Is there any option to filter videos when choosing one from library?

**Comment by dhevendhiran-adt** [comment]
> set video duration on option like this : durationLimit: 40

durationLimit is only working for iOS. Is there any way to get duration of the selected video from the gallery?

**Comment by relivetech** [comment]
facing same problem, did any one get any library for duration.

**Comment by dhevendhiran-adt** [comment]
> facing same problem, did any one get any library for duration.

Currently, they are not supporting android to set up the video duration. We found [https://www.npmjs.com/package/rn-media-meta](url) . After capturing video we can get the duration using this library. It is not an alternative. But somewhat it helps based on the requirements.
