### ISSUE TITLE
How to extract the key frame from the video?

### ISSUE THREAD

**Issue by fazeelCGI** [react-native-community/react-native-image-picker#846]
--- Delete everything above this line ---

### I am using this library for photo and video purpose. I am recording the video of 10 seconds. I need to find the keyframe of video from the response object of video. Is there any property available for key frame extraction?
Example:  
`ImagePickers.showImagePicker(options, (response) => {
      console.log('Response = ', response);
      console.log('timestamp = ', response.timestamp);
      console.log('uri = ', response.uri);
      

      if (response.didCancel) {
        console.log('User cancelled video picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        this.setState({
          videoSource: response.uri
        });
      }
    });`
how to extract the key frame of video from response object.

### Additional Information

* React Native version: [0.50.3]
* Platform: [iOS, Android]
* Development Operating System: [developing on MacOS]
* Dev tools: [Xcode: 9.3, Android Studio: 3.1]

**Comment by pierroo** [comment]
I might be late to the party; but did you ever find a solution to this @fazeelCGI ?
