### ISSUE TITLE
application/octet-stream.

### ISSUE THREAD

**Issue by sajaddp** [react-native-community/react-native-image-picker#850]
Hello,

There is a question which I like to raise: Imagine, a user wants to upload a picture and it is a big size, the type of will be `application/octet-stream`. Therefore, it is not useful for us because, by this format, we can not understand whether it is a picture or not. 
I mean perhaps the file will not be a picture, it may be a kind of audio type: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

Is there any way to solve this case? What is your suggestion?

**Comment by rgamaesilva** [comment]
same problem here. I cant get my uploaded file to the correct format
