### ISSUE TITLE
Documentation of noData configuration option - practical effects

### ISSUE THREAD

**Issue by jkdf2** [react-native-community/react-native-image-picker#853]
The `noData` configuration option is explained as:

> If true, disables the base64 data field from being generated (greatly improves performance on large photos)

But what does this mean, practically? It sounds like something that you would want to default to `true` and switch to `false` if you have some specific need for the `.data` field, but the fact that it defaults to `false` makes me think there's something more to it than meets the eye based on the current description.

Under what contexts would you *not* want to set `noData: true`?

**Comment by antoinerousseau** [comment]
`noData` should indeed be set to `true` by default... (or `data: false` would be better)

and then users wanting a `base64` version of their image would need to activate this, not the other way around.
