### ISSUE TITLE
native module imagepickermodule tried to override imagepicker module for module name imagepickermanager

### ISSUE THREAD

**Issue by kariasbolster** [react-native-community/react-native-image-picker#856]
I got this error when i tried to run in samsung s7 real device. How can I resolve this?

**Comment by GuillaumeMunsch** [comment]
Hi!

I just resolved the same issue.

I'm pretty sure you have this line twice into your `MainApplication.java`:
```new ImagePickerPackage(),```

Maybe you also ran `react-native link` twice.

Fixed it for me ;)
