### ISSUE TITLE
Multiple calling of imagepicker crashes the app

### ISSUE THREAD

**Issue by rf1804** [react-native-community/react-native-image-picker#864]
### Description

OnPress of a function i call Image Picker but during testing i found that if you press it more than 5-7 times simultaneously it crashes the App (I found it on Android)
### How to repeat issue and example

Just call ImagePicker.showImagePicker function again and again (It is like tapping multiple times TouchableOpacity in it's OnPress it calls ImagePicker funtion)

### Solution

I think Image Picker should be like promise based or like await, till the operations does not completed it should not invoke again

### Additional Information

* React Native version: 0.55.2
* react-native-image-picker: 0.26.10
* Platform: Android (I tested on Android only)
* Development Operating System: MacOs

**Comment by gabrielberlanda** [comment]
+1
