### ISSUE TITLE
java.lang.OutOfMemory when trying to pick too big image

### ISSUE THREAD

**Issue by blitzerpl** [react-native-community/react-native-image-picker#870]
### Description

I have tried to pick an image which has size about 15MB and the application has stopped. In the logs I have found java.lang.OutOfMemory exception. This error occurs only on some devices (with less RAM memory).

Logs:
06-13 08:58:15.013 16865 18295 I FaceThreadPoolExecutor: [FACE] afterExecute FutureTask
06-13 08:58:15.133 18010 18020 W art     : Suspending all threads took: 15.472ms
06-13 08:58:15.143 18010 18020 I art     : Background partial concurrent mark sweep GC freed 7(240B) AllocSpace objects, 2(11MB) LOS objects, 12% free, 107MB/123MB, paused 16.243ms total 51.342ms
06-13 08:58:15.333 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.333 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.333 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.343 18010 18010 I art     : Alloc partial concurrent mark sweep GC freed 6(192B) AllocSpace objects, 1(15MB) LOS objects, 14% free, 91MB/107MB, paused 414us total 11.714ms
06-13 08:58:15.343 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.353 18010 18010 I art     : Alloc concurrent mark sweep GC freed 6(12KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 413us total 12.347ms
06-13 08:58:15.353 18010 18010 I art     : Forcing collection of SoftReferences for 46MB allocation
06-13 08:58:15.353 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.373 18010 18010 I art     : Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 415us total 11.468ms
06-13 08:58:15.373 18010 18010 W art     : Throwing OutOfMemoryError "Failed to allocate a 49233492 byte allocation with 16777216 free bytes and 36MB until OOM"
06-13 08:58:15.373 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.373 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.373 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.383 18010 18010 I art     : Alloc partial concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 412us total 8.403ms
06-13 08:58:15.383 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.393 18010 18010 I art     : Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 413us total 11.563ms
06-13 08:58:15.393 18010 18010 I art     : Forcing collection of SoftReferences for 46MB allocation
06-13 08:58:15.393 18010 18010 I art     : Starting a blocking GC Alloc
06-13 08:58:15.403 18010 18010 I art     : Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 410us total 11.547ms
06-13 08:58:15.403 18010 18010 I art     : Starting a blocking GC HomogeneousSpaceCompact
06-13 08:58:15.433 18010 18010 I art     : HomogeneousSpaceCompact marksweep + semispace GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 14% free, 91MB/107MB, paused 31.821ms total 31.821ms
06-13 08:58:15.433 18010 18010 W art     : Throwing OutOfMemoryError "Failed to allocate a 49233492 byte allocation with 16777216 free bytes and 36MB until OOM"
06-13 08:58:15.433 18010 18010 D AndroidRuntime: Shutting down VM
06-13 08:58:15.433 18010 18010 E AndroidRuntime: FATAL EXCEPTION: main
06-13 08:58:15.433 18010 18010 E AndroidRuntime: Process: com.stairsandroidapp, PID: 18010
06-13 08:58:15.433 18010 18010 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 49233492 byte allocation with 16777216 free bytes and 36MB until OOM
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:185)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:63)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.util.Base64.encodeToString(Base64.java:456)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.imagepicker.ImagePickerModule.getBase64StringFromFile(ImagePickerModule.java:689)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.imagepicker.ImagePickerModule.updatedResultResponse(ImagePickerModule.java:534)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:442)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:692)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:126)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:7137)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:4916)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4963)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.ActivityThread.access$1600(ActivityThread.java:221)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1848)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:158)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7224)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-13 08:58:15.433 18010 18010 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-13 08:58:15.443   860  1593 W ActivityManager:   Force finishing activity com.stairsandroidapp/.MainActivity
06-13 08:58:15.443   860  1593 D FocusedStackFrame: Set to : 0

### How to repeat issue and example

1. Download an image with high resolution (about 15 MB size).
2. Try to pick up an image with ImagePicker.

### Solution

In my opinion the best solution will be to add some limitations for resolution or image size in options.

### Additional Information

* React Native version: 0.55.3
* Platform: Android 6.0.1
* Phone: Samsung Galaxy S5 (SM-G900F)
* Development Operating System: Windows 10 with Visual Studio Code

**Comment by tututututututu** [comment]
+1

**Comment by Mahaswami** [comment]
Can you add a sample of your Plugin init code? For example of NoData option is set to true the entire file content would not be fetched into RAM. It is quite possible that NoData is false.

**Comment by xiaonull** [comment]
![Uploading Image 1.png…]()

**Comment by xiaonull** [comment]
![image 1](https://user-images.githubusercontent.com/20394030/46194302-9aa43000-c333-11e8-9000-dc9c0ae8a4ce.png)

let options = {
	title: '选择图片',
	cancelButtonTitle: '取消',
	takePhotoButtonTitle: '照相机',
	chooseFromLibraryButtonTitle: '图库',
	mediaType: 'photo',
	noData: true,
	quality: 1,
	allowsEditing: true,
	storageOptions: {
		skipBackup: true,
		path: 'images'
	}
};
