### ISSUE TITLE
Error when display returned image: Android - 'com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String'

### ISSUE THREAD

**Issue by McMainsLiam** [react-native-community/react-native-image-picker#893]
### Description

I am trying to use the image picker to choose an image and then display it on the next screen. It works fine on iOS, but after I choose the image on Android and try to display it, I get an error: `com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String`

![alt text](http://liam.mcmains.net/react_native_error.png)

#### Here is my code to get the image
```
getPhoto() {
    ImagePicker.showImagePicker(options, (response) => {
      if (response.didCancel) {
        console.log('User cancelled image picker')
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error)
      }
      else {
        let source = { uri: 'data:image/jpeg;base64,' + response.data }
    
        Actions.nextScreen({source: source})
      }
    });
  }
```

#### And my code to display the image on the next screen
```
<Image source={this.props.source} style={styles.photo}></Image>
```

### Solution

I would love some help to figure out why this error is occuring. Thank you! 

### Additional Information

* React Native version: react-native: 0.55.4
* Platform: android
* Development Operating System: MacOS
* Dev tools: android emulator - react-native run-android

**Comment by ragamufin** [comment]
@spiritman110 I had exactly the same problem and you saved me a lot of time looking for the source of the issue. Thanks a million!

**Comment by hwde** [comment]
Thanks, saved me my time too, this one helped me: [https://github.com/wassgha/react-native-fullwidth-image/issues/4](https://github.com/wassgha/react-native-fullwidth-image/issues/4)

**Comment by LeftTeh** [comment]
> ## Edit:
> I just figure the problem out. It was not an issue with react-native-image-picker but rather a function I was calling to get the size of the image:
> 
> ```js
> Image.getSize(this.props.source, (width, height) => {
>     // some code
> });
> ```
> 
> I took this code and it seems to be working fine now. You can close issue out.

Hi, I'm having this exact same issue, may you explain your answer to me? I'm a little unclear as to how it works (very new to RN)

**Comment by hwde** [comment]
An Image supports different **source=** types, see [here](https://facebook.github.io/react-native/docs/images).

If you request the size of an image by getSize, **this.props.source** is either of type string, i.e. if you create an image like:

`<Image source={require('./my-icon.png')} />;`

or an object, with key/values, at least **uri**:

`<Image source={{uri: 'app_icon'}} style={{width: 40, height: 40}} />`

which could also be written as (to make it more clearly):

```
let mySource = {uri: 'app_icon'};
...
<Image source={mySource} style={{width: 40, height: 40}} />
```
