### ISSUE TITLE
App Crashes for ios

### ISSUE THREAD

**Issue by LongicornYu** [react-native-community/react-native-image-picker#903]
2018-07-28 23:08:16.498589-0400 PillMemo[811:238905] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}

When first time running the app on a real device, it pops up asking for permission for photo gallery, and the photo gallery shows successfully.

However, when trying to select from photo gallery for a second time, nothing happens and for the third time, above errors occurred. The photo gallery pops then disappears right away.

I have added the following in info.plist
        <key>NSPhotoLibraryAddUsageDescription</key>
	<string>PillMemo would like to save photos to your photo gallery</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>PillMemo would like access to your photo gallery</string>

What am I missing? Thanks

**Comment by linoleum00** [comment]
I'm having the same problem, did you get to solve it somehow @LongicornYu ? or did you find an alternative library? 
Thanks

**Comment by sundariragavan** [comment]
In iPhone 6+ when tap on the camera icon. The app is getting crashed.Any one have the same issue.please let me know and how to solve this issue. In iPhone 6 is working fine.

**Comment by EnzoVezzaro** [comment]
Any news???

**Comment by LongicornYu** [comment]
I managed to make it work by adding a ‘sleep’ to it and after that it works perfectly.

Let me know if you guys need a code example

**Comment by linoleum00** [comment]
Yes please, that would be awesome.
Thanks @LongicornYu

**Comment by LongicornYu** [comment]
@linoleum00 Here you go.
`_pickImage = async () => {
    this._toggleModal();

    setTimeout(() => {
      ImagePicker.openPicker({
        width: 300,
        height: 300,
        cropping: true,
        cropperCircleOverlay: true,
      }).then((imageObj) => {
        this._handleImagePicked(imageObj);
      })
      .catch((error) => {
        console.log('onPickPhotoPress error')
        console.log(error)
      })
    }, 500)

  };
`

**Comment by cinder92** [comment]
having same issue @LongicornYu solution didn't work iOs 13
