### ISSUE TITLE
Take photo and crash

### ISSUE THREAD

**Issue by kutirie** [react-native-community/react-native-image-picker#904]
If in android use Take photo, app is crash.
![image](https://user-images.githubusercontent.com/25860657/43398501-b25f315e-9421-11e8-8a0d-657c04c11220.png)

I'm installed from guide in readme, and AndroidManifest, etc...

Android 5+ worked, without crash.

**Comment by ggunti** [comment]
Same behaviour at me. If I take a photo and then select "OK", it crashes
