### ISSUE TITLE
Crop images taken from camera

### ISSUE THREAD

**Issue by DavitVosk** [react-native-community/react-native-image-picker#906]
### Description

I want to crop the images before sending it to the server. Is there any option in this package to handle cropping? Thanks 

### How to repeat issue and example

Take the image with `RNImagePicker.launchCamera()` and you will see that cropping option is not available

* React Native version: ^0.55.3
* Platform: IOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by DavitVosk** [comment]
I can't use here `react-native-image-crop-picker` package, since it does not support `mixed` media types

**Comment by jwrubel** [comment]
The README is very specific - it says this package doesn't handle any processing of the media. I've been using it for over a year and I haven't seen them even consider adding anything like this. I don't think it will be an option for you, unfortunately.

**Comment by DavitVosk** [comment]
Thanks @jwrubel. I ended up using `react-native-image-crop-picker` package where there is `ImagePicker.openCropper({})` prop. So I called that prop in the response of `react-native-image-picker` package... And as a result, I could take the picture and then resize it when needed. Hope this could help anyone. But it will be great to include cropping option into this package

**Comment by HarshitMadhav** [comment]
@DavitVosk  how did you managed the imports though? Can you share the code?

**Comment by mtebele** [comment]
> @DavitVosk how did you managed the imports though? Can you share the code for the same?

`import ImagePicker from 'react-native-image-picker'
import ImageCropPicker from 'react-native-image-crop-picker'

ImagePicker.showImagePicker(options, response => {

      if (response.didCancel) return

      ImageCropPicker.openCropper({
        path: response.uri,
        width: deviceWidth,
        height: 200,
        includeBase64: true,
      }).then(cropped => {
        // save it
      })`

Hope this helps!
