### ISSUE TITLE
No callback on Android

### ISSUE THREAD

**Issue by pinkyblue** [react-native-community/react-native-image-picker#908]
My Project is an Android App mixed with ReactNative ,I can open the camera and gallery, but can't receive callback, it does work in another ReactNative Projet,I want to know what reason it is, is MainActivity must be extends ReactActivity ?or other reasons ? hope for your reply

**Comment by khanhhaduc** [comment]
Did you make any progress on this?

**Comment by tranlam181** [comment]
same issue, I followed steps and setup correctly.
When click button, it can open dialog to Take Photo, or Chosse from library, but nothing happen when I click
console log was: Response =  {error: "Cannot launch photo library"}, Response =  {error: "Cannot launch camera"}

**Comment by claudioviola** [comment]
The same for me

react-native-cli: 2.0.1
react-native: 0.55.4
react-native-image-picker: ^0.26.10


I see the modal for choosing options, then I select an options and in the console log I see only the log regarding the custom button, the others log doesn't arrive, neither the console log of the response at the beginning.

**Comment by claudioviola** [comment]
I added in AndroidManifest.xml these 2 permissions lines 

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

I think that these 2 lines should be added when we run `react-native link`....

Hope it's helpfull

**Comment by daniel1214** [comment]
试试这个
[https://github.com/daniel1214/Assets/blob/develop/%E6%88%AA%E5%9B%BE/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-09-07%20%E4%B8%8B%E5%8D%882.10.07.png](url)

**Comment by daniel1214** [comment]
试试这个
[image](https://github.com/daniel1214/Assets/blob/develop/%E6%88%AA%E5%9B%BE/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-09-07%20%E4%B8%8B%E5%8D%882.10.07.png)

**Comment by xifumengmengda** [comment]
yes ,i have the same issue,i can choose camera and gallery,but cannot choose library ,and and run as well on other device. who solve it?thanks

![guximi](https://user-images.githubusercontent.com/16473366/50390396-c89de280-0771-11e9-9df3-60ad00fd8116.png)

**Comment by Nidhi-Gandhi** [comment]
I face this kind of issue after installing react-native-fbsdk. I mistakenly add onActivityResult as below which causes an issue in my app. 
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
Normal behaviour of app was It's ask for permission shows popup for Take a photo(camera) or choose from library, I could able to open gallery and choose a picture. But I didn't get response objet. It never goes into response callback after choosing an image.
The solution is: 
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }
I know it's bit not relevant to your issue but might be help others.

**Comment by mahesh-agrawal** [comment]
same issue happening now. i upgraded to rn 0.60.6 and this issue started. not sure how to fix. all setup is same and did everything possible but no solution.

**Comment by luiey** [comment]
I having this issue too with error on Metro: `ImagePicker Error:  Cannot launch photo library` which surprise me on at first development, I can open gallery and select image on my android device pc. And past few days, it suddenly cannot open gallery to select image.

Tried both `showImagePicker` and `launchImageLibrary` but no success

**Comment by mayur-bhandari** [comment]
#1405

**Comment by mayur-bhandari** [comment]
I am also facing this issue on react-native@0.63.2 and react-native-image-picker@2.3.3. I am getting an error: `ImagePicker Error: Cannot launch photo library`.
