### ISSUE TITLE
在android模拟器中可以正常选择图片，打包后点击选择图片却没有反应

### ISSUE THREAD

**Issue by yy6597988** [react-native-community/react-native-image-picker#915]

**Comment by EvanMaFYH** [comment]
the same issue
解决了吗大兄弟

**Comment by yy6597988** [comment]
> the same issue
> 解决了吗大兄弟

最后我用form-data的形式提交了，没有转换成base64

**Comment by EvanMaFYH** [comment]
@yy6597988 我都没法打开相册或者摄像头在release模式下，最后右转用了react-native-image-crop-picker

**Comment by yy6597988** [comment]
> @yy6597988 我都没法打开相册或者摄像头在release模式下，最后右转用了react-native-image-crop-picker

这种在本地对图片进行base64的都会有个问题，占用内存很大，在性能比较差的手机上经常闪退
