### ISSUE TITLE
ReferenceError: Can't find variable: ImagePicker

### ISSUE THREAD

**Issue by tinmar33** [react-native-community/react-native-image-picker#916]
Hi,

It's working fine on my iPad, but on my Android tablet, when i tried to launch my app, I've got a "ReferenceError: Can't find variable: ImagePicker".
I tried to manually install react-native-image-picker, but it doesn't works. 
I also tried to unlink and link again the package and I can't find any solution.

My Tablet is on Android 4.4.4

Any solution ?

**Comment by wzup** [comment]
same 
https://github.com/react-community/react-native-image-picker/issues/957
https://github.com/react-community/react-native-image-picker/issues/962
https://github.com/react-community/react-native-image-picker/issues/963
