### ISSUE TITLE
Be able to cancel cropping when the user wants to

### ISSUE THREAD

**Issue by DavitVosk** [react-native-community/react-native-image-picker#919]
### Description

Hi there. One more time thanks for a great package. 

I use `allowsEditing: true` option to enable image cropping in IOS. Sometimes when image height is much higher than the height of the space of image cropping, I want to avoid cropping and let the image as it is. Is there an option to cancel cropping from the screen of cropping?

### How to repeat issue and example

Just use `allowsEditing: true` option and you will see that there is no any option to cancel the cropping and let the image as it is

### Solution

N/A

### Additional Information

* React Native version: ^0.55.3
* Platform: IOS
* Development Operating System: MacOS
* Dev tools: Xcode

**Comment by mengpeilee** [comment]
+1

**Comment by nica0012** [comment]
This is very neccessary

**Comment by arnaudambro** [comment]
Issue not resolved, and much needed !
