### ISSUE TITLE
 You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### ISSUE THREAD

**Issue by faheem121** [react-native-community/react-native-image-picker#921]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at registerRootComponent.js:35.
    in ExpoRootComponent (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)

My Code is:

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  PixelRatio,
  TouchableOpacity,
  Image,
} from 'react-native';
 
import ImagePicker from 'react-native-image-picker';
 
class ImagePickerProject extends React.Component {
  
    state = {
 
      ImageSource: null,
    
    };
  
    selectPhotoTapped() {
      const options = {
        quality: 1.0,
        maxWidth: 500,
        maxHeight: 500,
        storageOptions: {
          skipBackup: true
        }
      };
  
      ImagePicker.showImagePicker(options, (response) => {
        console.log('Response = ', response);
  
        if (response.didCancel) {
          console.log('User cancelled photo picker');
        }
        else if (response.error) {
          console.log('ImagePicker Error: ', response.error);
        }
        else if (response.customButton) {
          console.log('User tapped custom button: ', response.customButton);
        }
        else {
          let source = { uri: response.uri };
  
          // You can also display the image using data:
          // let source = { uri: 'data:image/jpeg;base64,' + response.data };
  
          this.setState({
 
            ImageSource: source
 
          });
        }
      });
    }
  
    render() {
      return (
        <View style={styles.container}>
 
          <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
 
            <View style={styles.ImageContainer}>
 
            { this.state.ImageSource === null ? <Text>Select a Photo</Text> :
              <Image style={styles.ImageContainer} source={this.state.ImageSource} />
            }
 
            </View>
 
          </TouchableOpacity>
 
        </View>
      );
    }
  
  }
  
  const styles = StyleSheet.create({
 
    container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FFF8E1'
    },
 
    ImageContainer: {
      borderRadius: 10,
      width: 250,
      height: 250,
      borderColor: '#9B9B9B',
      borderWidth: 1 / PixelRatio.get(),
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#CDDC39',
      
    },
 
  });
 
AppRegistry.registerComponent('ImagePickerProject', () => ImagePickerProject);

**Comment by faheem121** [comment]
this issue is solve by putting export default but i got another issue
undefined is not an object (evaluating 'ImagePickerManager.showImagePicker')
Please Help

**Comment by terence612** [comment]
react-native link seems doesn't work. I met the same problem as you do when I was using `react-native link`
Try to install it manually and my problem solved.

**Comment by CajetanRodrigues** [comment]
Same issue

**Comment by kambleaa007** [comment]
issue is still there never fixed
