### ISSUE TITLE
error: Camera not available on simulator

### ISSUE THREAD

**Issue by KingAmo** [react-native-community/react-native-image-picker#923]
take photo or select from library works in android, select photo works in iOS too, but take photo does not work in iOS, when i press take photo , nothing happens, and just console has a log: 'error: camera not available on simulator'

**Comment by rdougan** [comment]
This is because there is no camera on the simulator...

**Comment by KingAmo** [comment]
@rdougan but when i use react-native-camera, the simulator can show a fake camera

**Comment by senorincognito** [comment]
react-native-camera directly accesses the camera preview and when that fails is able to simulate that with a randomly generated view. 

react-native-image-picker simply tells the system to open its Camera app which obviously fails when a device or simulator can't do that. To counteract this error this plugin would have to create and show a custom view just for the iOS simulator. This is just too much trouble.

**Comment by KingAmo** [comment]
@senorincognito i see , thanks a lot

**Comment by hari3110** [comment]
its "Fill Free" not Fell free

**Comment by aniruddhbhamare** [comment]
Take photo or select works fine in android , select photo works in iOS too, but take photo does not work in iOS , when i press take photo , nothing happens, and just console has a log: 'error: camera not available on simulator'

**Comment by waqaramjad** [comment]
@hari3110  are you doing KOMEDY here  ?
