### ISSUE TITLE
set Options  cameraType: 'front', but it did not work. why?

### ISSUE THREAD

**Issue by tangtang11** [react-native-community/react-native-image-picker#927]

**Comment by tangtang11** [comment]
help me please.  Thank you!

**Comment by hieupaul** [comment]
Any body has idea for this issue?

Still happens on 0.26.10

**Comment by winardis** [comment]
i'm using version 1.1.0 the cameraType: 'front' doesnt seem to work, it just follow the previous camera position i've set on the native camera (stock camera app)

**Comment by dilipchandima** [comment]
I'm facing this issue with v4.1.1. any solution?

**Comment by rrsalian16** [comment]
I'm also facing the same issue. Any solution ?
