### ISSUE TITLE
Getting error "Response =  {error: "Couldn't get file path for photo"}"

### ISSUE THREAD

**Issue by himanshusharma9400** [react-native-community/react-native-image-picker#928]
### Description
I have used a library named 'react-native-mauron85-background-geolocation' along with 'react-native-image-picker' in my app, when I add 'react-native-mauron85-background-geolocation'  dependencies and link it my camera doesn't open when i click 'take photo' button and gives an error 'Response =  {error: "Couldn't get file path for photo"}' in log but gallery is opening successfully, and when I remove all dependencies of  'react-native-mauron85-background-geolocation' then everything works fine.

### How to repeat issue and example

My code is :
export default class App extends React.Component {

  state = {
    avatarSource: null,
    videoSource: null
  };

  selectPhotoTapped() {
    quality: 1.0,
      maxWidth: 500,
      maxHeight: 500,
      storageOptions: {
        skipBackup: true
      }
    };

    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled photo picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        let source = { uri: response.uri };

        // You can also display the image using data:
        // let source = { uri: 'data:image/jpeg;base64,' + response.data };
        console.log('ye hua abhi')
        this.setState({
          avatarSource: source
        });
      }
    });
  }

  selectVideoTapped() {
    const options = {
      title: 'Video Picker',
      takePhotoButtonTitle: 'Take Video...',
      mediaType: 'video',
      videoQuality: 'medium'
    };

    ImagePicker.showImagePicker(options, (response) => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled video picker');
      }
      else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      }
      else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      }
      else {
        this.setState({
          videoSource: response.uri
        });
      }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <TouchableOpacity onPress={this.selectPhotoTapped.bind(this)}>
          <View style={[styles.avatar, styles.avatarContainer, {marginBottom: 20}]}>
          { this.state.avatarSource === null ? <Text>Select a Photo</Text> :
            <Image style={styles.avatar} source={this.state.avatarSource} />
          }
          </View>
        </TouchableOpacity>

        <TouchableOpacity onPress={this.selectVideoTapped.bind(this)}>
          <View style={[styles.avatar, styles.avatarContainer]}>
            <Text>Select a Video</Text>
          </View>
        </TouchableOpacity>

        { this.state.videoSource &&
          <Text style={{margin: 8, textAlign: 'center'}}>{this.state.videoSource}</Text>
        }
      </View>
    );
  }
}

Link to library of react-native-mauron85-background-geolocation: https://github.com/mauron85/react-native-background-geolocation#http-locations-posting

### Solution

I want to link both the libraries successfully without an issue

### Additional Information

* React Native version: [0.56.0]
* Platform: [Android]
* Development Operating System: [MacOs]
* Dev tools: [Android SDK version : 27] navigation crash for Android

**Comment by kapil708** [comment]
did u found any solution i get same issue ?

**Comment by himanshusharma9400** [comment]
@kapil708 : Yeah I made it work, I changed the buildToolsVersion to 27.0.3 and supportLibVersion to 27.1.0 and added the latest version of both the plugins/libraries and it is working now.  My build.gradle now is:
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "27.1.0"
    googlePlayServicesVersion = "11.8.0"
    androidMapsUtilsVersion = "0.5+"
    gradle3EXPERIMENTAL = "yes"
    oreoEXPERIMENTAL = "yes"
}
Tell me if it works....:)

**Comment by kapil708** [comment]
not working.
i do all things
1. clear project
2. npm install
3. uninstall & install 

it give same error.

did there any steps to set this.

**Comment by kapil708** [comment]
still not working

**Comment by himanshusharma9400** [comment]
Can u give the following information:
Error, android version of testing device, your react-native version 
also test it in a real device
and if all doesn't work start a new project with all latest version of react-native and latest version of both the libraries/plugins and use code of image picker example:
**https://github.com/react-community/react-native-image-picker/tree/master/Example**
and for background-geolocation just link the library using react-native link
(I also did the same and after adding both, my camera wasn't opening when I clicked on 'Select a photo' but it camera was opening when I clicked 'Select a video' camera was opening)

**Comment by kapil708** [comment]
any other image picker to use

**Comment by himanshusharma9400** [comment]
Yes there are but they are a bit more complicated and have more issues, this is the most stable one....You can try **https://github.com/ivpusic/react-native-image-crop-picker**, but I recommend you to try above method and any other possible way to make it work

**Comment by kapil708** [comment]
don't know k=how to solve this issue i am stuck from 2 days in it

**Comment by kapil708** [comment]
give me your email id so i will send you my source code if you can give some help.

**Comment by atulmy** [comment]
Anyone able to solve this issue?

**Comment by brycepavey** [comment]
I had the same issue, if you're project already has filepaths.xml under app/res/xml like mine does (which was added as part of react-native-share) you need to add the following path config (taken from this PR https://github.com/react-community/react-native-image-picker/pull/951/commits/307a278f8cdd287e50015a8a252e74ad93b5ac76)
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <...any existing config...>
    <files-path name="shared" path="."/>
    <external-path name="shared" path="."/>
    <external-files-path name="shared" path="."/>
    <root-path name="root" path="."/>
</paths>
```

**Comment by llitfkitfk** [comment]
@brycepavey thx
It worked

**Comment by rahul120292** [comment]
@brycepavey  thank man . worked your solution.

**Comment by Subway19** [comment]
@brycepavey I was wondering how the feature got broken in my app. thanks so much for the solution.

**Comment by marcosbenevides** [comment]
@brycepavey works beautifully 😄

**Comment by Vidyack** [comment]
@jose2007kj , You can get file path using response.uri

**Comment by edilsonlm217** [comment]
I just got a solution for this problem.
When installing react-native-image-picker you have to add bellow lines to android/app/src/debug/AndroidManifest.xml in order to get permission to access device's camera and storage.

Don't know why but for some reason when you call ImagePicker.launchCamera by app it doesn't ask for sotrage permission. That's why it can't get file path for photo.

To make it run you got to allow storage permisson manually in your device or emulator.

In case you don't know how to do that follow the steps described in the link: https://phandroid.com/2019/07/18/how-to-change-app-permissions-android-m/

**Comment by PragyanD33p** [comment]
@brycepavey  What if I don't have that filepaths.xml file? How to do that?

**Comment by AmrAlmagic** [comment]
please, check this [comment](https://github.com/react-native-community/react-native-image-picker/issues/874#issuecomment-578238305)

**Comment by LaVielle** [comment]
As @AmrAlmagic points out in his [comment](https://github.com/react-native-community/react-native-image-picker/issues/874#issuecomment-578238305), this is actually a permission issue. No need to add extra stuff in the native android files.

All you need is to request and get `CAMERA` and `WRITE_EXTERNAL_STORAGE` permissions **before** calling `launchCamera`:

```JavaScript
const getImageFromCamera = async () => {
  if (Platform.OS === 'android') {
    try {
      await PermissionsAndroid.requestMultiple([
        PermissionsAndroid.PERMISSIONS.CAMERA,
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      ])

      const permissionCamera = await PermissionsAndroid.check('android.permission.CAMERA')
      const permissionWriteStorage = await PermissionsAndroid.check('android.permission.WRITE_EXTERNAL_STORAGE')

      if (!permissionCamera || !permissionWriteStorage) {
        return {
          error: 'Failed to get the required permissions.'
        }
      }
    } catch (error) {
      return {
        error: 'Failed to get the required permissions.'
      }
    }
  }
  return ImagePicker.launchCamera(options, response => response)
}
```

**Comment by haqisaurus** [comment]
I found this problem too on android 10 this is my setting i used
"react-native-image-picker": "^2.3.1",
ImagePicker.showImagePicker(
            {
                title: 'Choose Image',
                maxWidth: 1000,
                maxHeight: 1000,
                quality: 0.7,
                mediaType: 'photo',
                storageOptions: {
                    skipBackup: true,
                    path: 'Pictures/myAppPicture/', //-->this is neccesary
                    privateDirectory: true
                }

            },
            response => {
                console.log(response);
                
            },
        );
also adding 
filpaths.xml like someone told above
**BUT I still have problem when open androi gallery because it access denied, althought I I have add permission to read file on manifest.xml**
thanks I hope it help

**Comment by syedamirali14** [comment]
> I had the same issue, if you're project already has filepaths.xml under app/res/xml like mine does (which was added as part of react-native-share) you need to add the following path config (taken from this PR [307a278](https://github.com/react-native-community/react-native-image-picker/commit/307a278f8cdd287e50015a8a252e74ad93b5ac76))
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <paths xmlns:android="http://schemas.android.com/apk/res/android">
>     <...any existing config...>
>     <files-path name="shared" path="."/>
>     <external-path name="shared" path="."/>
>     <external-files-path name="shared" path="."/>
>     <root-path name="root" path="."/>
> </paths>
> ```



> external

i don't have any file like this

**Comment by hautran96** [comment]
it not working with android 10 :(( help me

**Comment by muhammadaqibkhan** [comment]
For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
`{
storageOptions: {
privateDirectory: true
} }` 
In my case private directory serves the purpose.

build.gradle settings:

`ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 17
        compileSdkVersion = 29
        targetSdkVersion = 29
        supportLibVersion = "28.0.0"
        renderscriptVersion = 21
    }`  

Lib Version:
"react-native-image-picker": "2.3.1"

**Comment by shixiaoquan** [comment]
> For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> `{ storageOptions: { privateDirectory: true } }`
> In my case private directory serves the purpose.
> 
> build.gradle settings:
> 
> `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> 
> Lib Version:
> "react-native-image-picker": "2.3.1"

it worked for me on android 10 
after  add  "{ storageOptions: { privateDirectory: true } }", I can open camera ,but i can't choose photo from gallery

**Comment by shixiaoquan** [comment]
> > For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> > `{ storageOptions: { privateDirectory: true } }`
> > In my case private directory serves the purpose.
> > build.gradle settings:
> > `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> > Lib Version:
> > "react-native-image-picker": "2.3.1"
> 
> it worked for me on android 10
> after add "{ storageOptions: { privateDirectory: true } }", I can open camera ,but i can't choose photo from gallery

I can access photo in gallery now, this is solution 
add  android:requestLegacyExternalStorage="true" to my <application ... > tag in AndroidManifest.xml.

**Comment by hautran96** [comment]
> For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> `{ storageOptions: { privateDirectory: true } }`
> In my case private directory serves the purpose.
> 
> build.gradle settings:
> 
> `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> 
> Lib Version:
> "react-native-image-picker": "2.3.1"

it worked, thank you so much, i love you

**Comment by muhammadaqibkhan** [comment]
> > > For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> > > `{ storageOptions: { privateDirectory: true } }`
> > > In my case private directory serves the purpose.
> > > build.gradle settings:
> > > `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> > > Lib Version:
> > > "react-native-image-picker": "2.3.1"
> > 
> > 
> > it worked for me on android 10
> > after add "{ storageOptions: { privateDirectory: true } }", I can open camera ,but i can't choose photo from gallery
> 
> I can access photo in gallery now, this is solution
> add android:requestLegacyExternalStorage="true" to my <application ... > tag in AndroidManifest.xml.

Seems like a solution, but in my case If Camera & External Permissions were granted, I'd no issue
PermissionsAndroid.PERMISSIONS.CAMERA
PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE (were asked)
You might try with asking for these permissions first and then go on with the library functions. Hope this works as well.

**Comment by muhammadaqibkhan** [comment]
> > For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> > `{ storageOptions: { privateDirectory: true } }`
> > In my case private directory serves the purpose.
> > build.gradle settings:
> > `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> > Lib Version:
> > "react-native-image-picker": "2.3.1"
> 
> it worked, thank you so much, i love you

Pleasure and no problem, love you too !!!

**Comment by ibrahnerd7** [comment]
> android:requestLegacyExternalStorage="true"

This was helpful.  I appreciate

**Comment by devprakashbinary** [comment]
> I had the same issue, if you're project already has filepaths.xml under app/res/xml like mine does (which was added as part of react-native-share) you need to add the following path config (taken from this PR [307a278](https://github.com/react-native-community/react-native-image-picker/commit/307a278f8cdd287e50015a8a252e74ad93b5ac76))
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <paths xmlns:android="http://schemas.android.com/apk/res/android">
>     <...any existing config...>
>     <files-path name="shared" path="."/>
>     <external-path name="shared" path="."/>
>     <external-files-path name="shared" path="."/>
>     <root-path name="root" path="."/>
> </paths>
> ```

pls include this line also in your AndroidMenifest.xml

**Comment by gabrielfrancodias** [comment]
solved joiining @muhammadaqibkhan and @shixiaoquan answers. ty

**Comment by ivanfeliciano9** [comment]
> For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> `{ storageOptions: { privateDirectory: true } }`
> In my case private directory serves the purpose.
> 
> build.gradle settings:
> 
> `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> 
> Lib Version:
> "react-native-image-picker": "2.3.1"

It works!! Thank you.

**Comment by athaisyah** [comment]
`const takeImageHandler = () => {
    const options = {
      title: 'Select Image',
      storageOptions: {
        privateDirectory: true,
        skipBackup: true,
        // path: 'Image_test_',
      },
    };

    ImagePicker.launchCamera(options, (res) => {
      console.log('Response ===>', res);
      if (res.didCancel) {
        console.log('User cancelled image picker');
      } else if (res.error) {
        console.log('Image Picker Error: ', res.error);
      } else {
        console.log('response', JSON.stringify(res));
        let source = {uri: res.uri};
        console.log(source);
        // setPickedImage(image.source);
        setPickedImage({
          image: {source},
        });
        // props.onImageTaken(image.uri);
      }
    });
  };`

Lib Version: react-native-image-picker: '2.3.4'
It does working! Thanks

> For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> `{ storageOptions: { privateDirectory: true } }`
> In my case private directory serves the purpose.
> 
> build.gradle settings:
> 
> `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> 
> Lib Version:
> "react-native-image-picker": "2.3.1"

**Comment by thuynt99** [comment]
> For now passing following storage option, seemed to have fixed launchCamera on Android 10 for me.
> `{ storageOptions: { privateDirectory: true } }`
> In my case private directory serves the purpose.
> 
> build.gradle settings:
> 
> `ext { buildToolsVersion = "29.0.2" minSdkVersion = 17 compileSdkVersion = 29 targetSdkVersion = 29 supportLibVersion = "28.0.0" renderscriptVersion = 21 }`
> 
> Lib Version:
> "react-native-image-picker": "2.3.1"

It's so good. Thank you very much!

**Comment by surajl11** [comment]
but if I choose a video from the gallery to upload in android ,its getting me a relative path of the video which is not uploading, this is only happening in android ,in iOS its giving me the absolute path

**Comment by siddharth-kt** [comment]
> but if I choose a video from the gallery to upload in android ,its getting me a relative path of the video which is not uploading, this is only happening in android ,in iOS its giving me the absolute path ,please help

any solution bro ?
