### ISSUE TITLE
Stop Images from being saved to Default Camera Roll. Let users (developers that use the package) decide to enable or disable that.

### ISSUE THREAD

**Issue by vemulanishanth** [react-native-community/react-native-image-picker#941]
### Description

I tried to invoke show camera method. After that took a picture from camera interface.
I expected to be returned a camera blob information without it being saved into default camera roll or DCIM folder.
I Donot want any information that is recorded from my app to move outside it.

The image is being saved to default camera roll. I donot want to do extra work of moving the image to application's internal document folder.

### How to repeat issue and example

```
ImagePicker.showImagePicker(options, async response => {
      // console.log("Response = ", JSON.stringify(response));

      if (response.didCancel) {
        console.log("User cancelled image picker");
        // DO NOTHING
      } else if (response.error) {
        console.log("ImagePicker Error: ", response.error);
        // TODO: error handling
      } else if (response.customButton) {
        console.log("User tapped custom button: ", response.customButton);
        // TODO: Custom Button handling
      } else {
        switch (Platform.OS) {
          case "android":
               if (responsePath.indexOf(RNFS.ExternalDirectoryPath) >= 0) {
                 //  if the image is from temporary directory i.e. image is taken from launchCamera within the applicationmove it to document directory
                 await RNFS.moveFile(responsePath, filePath);
               } else {
                 //  if the image is from external location or performed action os choose from Library move it to document directory
                 await RNFS.copyFile(responsePath, filePath);
               }
               break;
          . . .
         }
      }
})
```
when options has storageoptions property set to undefined or doesnot have the property assigned at all, you will find that when image is captured within the application a copy resides in DCIM folder which is not needed.
I am unable to delete the image from within the application.

### Solution

** Unknown

### Additional Information

* React Native version: 0.55.4
* Platform: Android
* Development Operating System: Windows and Mac
* Dev tools: Visual Studio Code and Android Studio

**Comment by NguyenQuangVinh123** [comment]
Anyone can fixed that ?

**Comment by llitfkitfk** [comment]
https://github.com/react-community/react-native-image-picker/issues/928#issuecomment-438526153

**Comment by augustocbx** [comment]
I'm trying to resolve this problem too

**Comment by lbelavoir** [comment]
Duplicate of #986

**Comment by j0nd0n7** [comment]
Facing the same problem, It get worse if you request smaller sizes than the max resolution.
I get 3 copies!! (on Android):
- /Pictures -> original size
- /Pictures -> resized
- /DCIM/Camera -> original size

It seems so strange this issue is around since 2017 having even a pull request to address it.
 
What is blocking the merge or solution to this undesired storage wasteful behaviour?

**Comment by agrass** [comment]
Hi, how u guys solved this??  I alway got the path with DCIM, and I'm using another folder.

**Comment by vemulanishanth** [comment]
Please reopen the issue as it is not solved.

**Comment by marcoavazquez** [comment]
Someone resolve this? I have the same problem, 
I only need the base64 data but the picture is saved in the cameraroll with the original size

**Comment by lbelavoir** [comment]
@marcoavazquez unfortunately I've solved it by using [`react-native-camera`](https://github.com/react-native-community/react-native-camera) instead.

**Comment by marcoavazquez** [comment]
> @marcoavazquez unfortunately I've solved it by using [`react-native-camera`](https://github.com/react-native-community/react-native-camera) instead.

Ok, tank you very much. I was using react-native-camera, but I needed take the picture from the galery too, so I will use this library for that and the camera with the another one.

**Comment by Kavahardik** [comment]
Hello Everyone,

I am facing a crash issue in my React Native app when taking a photo using the camera. After capturing the photo, the app crashes when I click the right icon on the preview screen. Can anyone help me?

Details:

Dependency: react-native-image-picker
Device: Moto G52
Android Version: 13
