### ISSUE TITLE
RNImagePicker.xcodeproj is not available to select

### ISSUE THREAD

**Issue by Carey678** [react-native-community/react-native-image-picker#949]
When I followed the Manual Installation
iOS
In the XCode's "Project navigator", right click on your project's Libraries folder ➜ Add Files to <...>.
Go to node_modules ➜ react-native-image-picker ➜ ios ➜ select RNImagePicker.xcodeproj.

however, the RNImagePicker.xcodeproj is not available and i found it is already in xcode libraries

**Comment by guokangf** [comment]
+1
