### ISSUE TITLE
Android: Build fails with React Native 0.57.2 and newer

### ISSUE THREAD

**Issue by borisyankov** [react-native-community/react-native-image-picker#959]
### Description

After upgrading to React Native 0.57.2 (confirmed with 0.57.3 too) build on Android fails with error:

> Task :react-native-image-picker:compileDebugJavaWithJavac FAILED
/Users/boris/Code/zulip/zulip-mobile/node_modules/react-native-image-picker/android/src/main/java/com/imagepicker/ImagePickerModule.java:51: error: cannot find symbol import com.facebook.react.modules.core.PermissionListener;

### Additional Information

* React Native version: 0.57.2
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio

**Comment by murtraja** [comment]
Were you able to figure out how to make it work. I am currently using 0.57.3 with library version 0.26.10 and it is building properly on Android. So I am reluctant to upgrade in case I face any build issues. :)

**Comment by emil-alexandrescu** [comment]
+1

**Comment by charpeni** [comment]
I'm using `react-native-image-picker@0.27.0` with `react-native@0.57.5` and I do not have any issue.

Can you try with 0.57.5?

**Comment by charpeni** [comment]
You can check with the new example app on react native 0.57.5: https://github.com/react-community/react-native-image-picker/tree/master/example

**Comment by emiyake** [comment]
It works for me with:

- React native 0.57.7
- React Native Image Picker 0.27.2

**Comment by rajnishcoder** [comment]
I updated react native and picker too but did not worked,
```
"react-native": "~0.59.0",
"react-native-image-picker": "^0.28.1",
```

any update?

**Comment by rajnishcoder** [comment]
> * 0.27.2

tried exactly but did not worked

**Comment by rajnishcoder** [comment]
@emiyake tried exactly but did not worked

**Comment by HumphreyHuang** [comment]
> @emiyake tried exactly but did not worked

Try the lated version, works for me
https://github.com/react-native-community/react-native-image-picker/releases/tag/v1.0.1

**Comment by GreenRidingHood** [comment]
@rajnishcoder I tried 
https://github.com/react-native-community/react-native-image-picker/issues/1095#issuecomment-510169855 
that comment, also did not work. Where you able to solve?

issue #1095 is the exact my problem, all error message the same too :(

**Comment by rajnishcoder** [comment]
@GreenRidingHood It did not work, I created the whole new project and move my source code, 
Anyway react sucks, I'm working on it more than a year and almost every month it got some new weird problem.
