### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

### ISSUE THREAD

**Issue by rajnishcoder** [react-native-community/react-native-image-picker#961]
### Description

I'm using react-native-image-picker 0.26.10 it is showing `WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
on running android build OR running project.

the same warning is showing for the app so i changed 'compile' to 'implementation' in build.gradle file, it works for the app but it is still showing for image picker

### Solution

remove warning

### Additional Information

full warning 

`Configure project :react-native-image-picker 
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.4.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.`

**Comment by gvsharma** [comment]
since the library here is using the depricated keywords, ImagePicker is showing warnings.

**Comment by rajnishcoder** [comment]
I resolved this by changing `'compile' with 'implementation'` in the `react-native-image-picker` gradle file,
i found at the bottom if android studio navigating bar inside gradle

what I was doing wrong is changing `'compile' with 'implementation'` in app gradle file and hoping for react native image picker to remove the warning,

well you have to do in for both.

**Comment by twhoff** [comment]
This isn't a proper solution, as when you delete your NPM modules and reinstall them, the issue will return.

Is there a way to override the module settings in the apps main build.gradle file?

**Comment by rajnishcoder** [comment]
@twhoff I know that but at that time i just wanted to get rid of that warnings

**Comment by rajnishcoder** [comment]
@twhoff you are right I'm reopening this issue

**Comment by Johan-dutoit** [comment]
What version of the image picker are you using?

This was changed about 5 months ago: https://github.com/react-native-community/react-native-image-picker/blob/master/android/build.gradle#L56
