### ISSUE TITLE
_reactNativeImagePicker2.default.launchImageLibrary is not a function

### ISSUE THREAD

**Issue by wzup** [react-native-community/react-native-image-picker#962]
### Description

I wanted to barely test the package.
I simply followed steps in your docs.

```
$ npm i -S react-native-image-picker
$ react-native link react-native-image-picker
```

```javascript
import ImagePicker from 'react-native-image-picker';

_launchImageLib(ev) {
  const options = {
    title: 'Select Avatar',
    customButtons: [{ name: 'fb', title: 'Choose Photo from Facebook' }],
    storageOptions: {
      skipBackup: true,
      path: 'images'
    }
  };

  ImagePicker.launchImageLibrary(options, response => {
    console.log('[ImagePicker][response]', response);

    const source = { uri: response.uri };
    this.setState({
        avatarSource: source
    });
  });
}

render() {
        <View style={ styles.view }>
          <TouchableHighlight style={ styles.userpic } onPress={ this._launchImageLib }>
            <Icon name="photo-camera" size={ 30 } color={'red'} />
          </TouchableHighlight>
        </View>
}

```

### How to repeat issue and example

See my code above. Just copy/paste it in your component.

### Solution

What needs to be done to address this issue? How to solve it?

### Additional Information

```
  System:
    OS: macOS High Sierra 10.13.6
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 11.1.2

"react-native": "0.54.2",
"react-native-image-picker": "^0.27.1",
```

**Comment by wzup** [comment]
The way you advice to import your lib doesn't work.
Look at what is returned, `default`! How can it be?

![screen shot 2018-10-25 at 11 30 08 am](https://user-images.githubusercontent.com/3880497/47486822-e621ff00-d849-11e8-822f-fe2ad76ba38c.png)

All these options do not work.
```
import ImagePicker from 'react-native-image-picker';
import { default as ImagePicker } from 'react-native-image-picker';
import { ImagePicker } from 'react-native-image-picker';
```

**Comment by wzup** [comment]
same https://github.com/react-community/react-native-image-picker/issues/957

**Comment by wzup** [comment]
Manual linking solved the issue.
https://github.com/react-community/react-native-image-picker/issues/837#issuecomment-388014561

Too bad author can't write normal documentation

**Comment by riyaz1620390** [comment]
@Nullable
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return Arrays.asList(
      .........
      new ImagePickerPackage()   // <-- add this to your application class people!
    );
  }
