### ISSUE TITLE
Camera/Photo Library not being invoked on Android Pie

### ISSUE THREAD

**Issue by marcojr** [react-native-community/react-native-image-picker#964]
This code works good on iOS: 

    go() {
        var options = {
          quality       : 1,
          mediaType    : "photo",
          cameraType  : "back",
          allowsEditing : true,
          noData          : true,
          maxWidth      : 8000,
          maxHeight     : 8000,
        };

      ImagePicker.showImagePicker(options, (response) => {
          console.log('response: ', response);
          console.log('response latitude: ', response.latitude);
          console.log('response longitude: ', response.longitude);
          alert(response.latitude + ',' + response.longitude);
         }, err => {
          alert(JSON.stringify(err))
        });
      }

But on Android...

1st time: It cannot invoke the Photo Library nor Camera and execute the promise anyway and don't throw any error.

Android Version: Pie

"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",
"react-native-image-picker": "^0.27.1"

**Comment by EvanMaFYH** [comment]
the same issue only when i give the permission manually
it is strange that when i install my app by react-native run-android ,it works,however,if i use ./gradlew assembleRelease to build the apk ,it dose not work any more

**Comment by firdaussoberi** [comment]
I also have the same issue with assembleRelease but not with react-native run-android. Already gave permissions but still... anyone found solution?? Thanks

**Comment by juniorojha** [comment]
https://github.com/react-native-community/react-native-image-picker/issues/964 maybe a related reason.

**Comment by radjivF** [comment]
In my case I get a 

```blob:http://localhos…-51027d42e3c0:15193 Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.``` 

even with no setState

**Comment by mohammedSlimani** [comment]
The problem was in my phone. I rebooted it and it worked again.
