### ISSUE TITLE
CameraKitGallery.getImageForTapEvent not returning valid <IOS> URI

### ISSUE THREAD

**Issue by HotSpotNick** [react-native-community/react-native-image-picker#970]
### Description
I am trying to use the gallery to open an image and send it to our api however it seems as though the url filepath is incorrect 

  async onTapImage(event) {

        const id = event.nativeEvent.selected;
        const image = await CameraKitGallery.getImageForTapEvent(event.nativeEvent);
         console.log("here");

        let imageSize = {
            size: {width, height},
            offset: {x: 0, y: 0,},
        };

        if (image) {
                 ImageEditor.cropImage(image.imageUri, {offset:{x:0,y:0},size:{width:imageSize.width, height:imageSize.height}}, (imageURI) => {
                    ImageStore.getBase64ForTag(imageURI, (base64Data) => {
                        this.setState({ticketImage: base64Data, open: true});
                    }, (reason)  => console.log(reason))
                 }, (reason) => console.log(reason));
         }
    }

### Additional Information

The file path works on android but fails on ios.

Any ideas?
Cheers

**Comment by epjoy082277** [comment]
I am having the same issue.  I am able to see a selectedImageId if I log the image in the developer console, but no image URL.
