### ISSUE TITLE
flash back to the desktop for a while and then return to my application

### ISSUE THREAD

**Issue by suwu150** [react-native-community/react-native-image-picker#974]
### Description
in android mobile.
When I was using showImagePicker, when I finished the photo and prepared to return to my own application via callback callback, I would flash back to the desktop for a while and then return to my application. Is it normal? Is there any optimization method?

### How to repeat issue and example
it's mine code as below:

```
    const _openCamera = () => {
      const photoOptions = {
        title: '',
        quality: 0.8,
        cancelButtonTitle: '取消',
        takePhotoButtonTitle: '拍照',
        chooseFromLibraryButtonTitle: '相册选择',
        allowsEditing: true,
        noData: true,
        mediaType: 'photo',
        // storageOptions: { skipBackup: true, path: 'images', cameraRoll: false }
      };
      ImagePicker.showImagePicker(photoOptions, (response) => {});
    };
```
my react-native and picker version as below:
```
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-image-picker": "^0.26.10",
```
and my machine info:
```
HUAWEI TAG-AL00
8 core 1.5GHz
2.0Gb
Android version: 5.1
```
### Solution
i search issue:
  [https://github.com/react-community/react-native-image-picker/issues/471](https://github.com/react-community/react-native-image-picker/issues/471)

 [https://github.com/react-community/react-native-image-picker/issues/537](https://github.com/react-community/react-native-image-picker/issues/537)

### Additional Information

* Platform: [Android]
* Development Operating System: [ MacOS]

**Comment by yz1311** [comment]
remove 
<pre>
<item name="android:windowIsTranslucent">true</item>
</pre>
in android/app/main/res/values/styles.xml
