### ISSUE TITLE
Detected problems with api compatibility (visit g.co/dev/appcompat for more info) - Android 9

### ISSUE THREAD

**Issue by khalid283** [react-native-community/react-native-image-picker#978]
### Description

A dialog open with this message `Detected problems with api compatibility (visit g.co/dev/appcompat for more info)`.

![screen shot 2018-11-15 at 1 00 49 pm](https://user-images.githubusercontent.com/14539996/48537306-346d6f80-e8d7-11e8-8d79-318239289932.png)

`Accessing hidden method  Landroid/view/View;>computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)`

`Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)`

`Accessing hidden method Landroid/widget/ListView;->findMotionRow(I)I (dark greylist, reflection)`

`Accessing hidden field Landroid/app/AlertDialog;>mAlert:Lcom/android/internal/app/AlertController; (light greylist, reflection)`

`Accessing hidden field Lcom/android/internal/app/AlertController; >mTitle:Ljava/lang/CharSequence; (light greylist, reflection)
`

Related link
https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces
https://android-developers.googleblog.com/2018/02/improving-stability-by-reducing-usage.html

Future plan of react native
https://github.com/facebook/react-native/issues/19297

### How to repeat issue and example

Open gallery cancel without selecting any photo. The issue reproduced in both emulator and real device.

### Solution

Temporary solution use buildToolsVersion "28.0.1" targetSdkVersion 28. Tested in debug mode only.

### Additional Information

* React Native version: [0.56.0]
* Platform: [Android]
* Development Operating System: [MacOS]
* Dev tools: [Android Studio version - 3.2.1, Android SDK version - 27.0.2]

**Comment by Sike4games** [comment]
Thanks

**Comment by Tridev09** [comment]
Can you give me link of buildversion
