### ISSUE TITLE
[Android] Could not invoke .launchImageLibrary (no virtual method requestPermissions)

### ISSUE THREAD

**Issue by stefank-kolosek** [react-native-community/react-native-image-picker#979]
### Description

I followed installation guide. Everything works fine on iOS but it breaks on Android. Here's my AndroidManifest file:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.package">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <provider
          android:name="com.imagepicker.FileProvider"
          android:authorities="${applicationId}.provider"
          android:exported="false"
          android:grantUriPermissions="true">
          <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/provider_paths" />
      </provider>
    </application>
</manifest>
```
I even added provider paths based on other solutions:

`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="external_files" path="."/>
</paths>
`

### How to repeat issue and example

When ImagePicker.launchCamera or ImagePicker.launchImageLibrary is triggered, device asks for permission. After accepting, error screen with this message pops up:

> Could not invoke ImagePickerManager.launchImageLibrary
> 
> null
> 
> No virtual method
> requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)

### Additional Information

* React Native version: [0.57.5] (same error with every RN version >= 0.55)
* Platform: [Android] - Tested on Android 5,6,7,8 (real devices)
* Development Operating System: [Linux and macOS]
* Dev tools: [Android Studio 3.2.1]

**Comment by mindjaydeep** [comment]
yes error.

**Comment by mindjaydeep** [comment]
Please add  
 permission too.
Its working for me now..

**Comment by dimlksin2** [comment]
Could not invoke ImagePickerManager.launchImageLibrary

null

android.app.Activity.requestPermissions
invoke
    JavaMethodWrapper.java:383
invoke
    JavaModuleWrapper.java:158
run
    NativeRunnable.java
handleCallback
    Handler.java:733
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:29
loop
    Looper.java:136
run
    MessageQueueThreadImpl.java:232
run
    Thread.java:841
