### ISSUE TITLE
!!! HELP!!!!  set mediaType：“phone”  Invalid.The photo and video exist together！！

### ISSUE THREAD

**Issue by baokeyu123** [react-native-community/react-native-image-picker#981]
when i  open huawei phone about android 8.01 version.I have set "mediaType：phone".However,when i selected photo ablum in huawei phone about android 8.01version.  photo and video all exist.amazing !!!
application  stop working  and back to the menu when i selected video in photo album.

I'm going to Log it  and look for the question. this  ImagePicker.showImagePicker's function is invalid when i open photo ablum and selected video .because android don't support "mediaType：mixed".so, how can i solve the  problem.

thanks

**Comment by CJELLYS** [comment]
I also encountered this problem on Huawei phones.

**Comment by rahulcs1989** [comment]
Hi, I also encountered the same problem with Huawei phones. I have given mediaType for selecting photos only and it works pretty well in all devices except for Huawei. So if the user select any video instead of photo, the app will crash. So is there any solution for this?

**Comment by ngxu** [comment]
![image](https://user-images.githubusercontent.com/43433064/83092839-c52e2980-a0d0-11ea-845f-a67acf75f9f7.png)

ImagePickerModule.java

```java
    {
      requestCode = REQUEST_LAUNCH_IMAGE_LIBRARY;
      libraryIntent = new Intent(Intent.ACTION_PICK,
      MediaStore.Images.Media.EXTERNAL_CONTENT_URI);
      
      libraryIntent.setType("image/*");//This line

      
      if (pickBoth) 
      {
        libraryIntent.setType("image/* video/*");
      }
    }
```

It's useful to add this line of code here.
