### ISSUE TITLE
Always saving image, only base64 is needed

### ISSUE THREAD

**Issue by akapila011** [react-native-community/react-native-image-picker#986]
### Description

I am trying to use the library to take an image, display the base64 using React Native's 'Image' component and then send the base64 string to a server. However, every time I take a picture it always gets saved to the device (camera roll and pictures directories). I do not want it to save the image captured at any given time, I simply want it to return a base64 string for use. 

### How to repeat issue and example

Use the example demo code provided with the following options:
```
const cameraOptions = {
    title: 'Capture Image',
    quality: 1.0,
        cameraType: 'back',
        rotation: 0,
        mediaType: "photo",
        storageOptions: {
            cameraRoll: false, 
            skipBackup: true,
            path: null,
        }
};

ImagePicker.launchCamera(cameraOptions, (response) => {
  console.log('Response = ', response);

  if (response.didCancel) {
    console.log('User cancelled image picker');
  } else if (response.error) {
    console.log('ImagePicker Error: ', response.error);
  } else if (response.customButton) {
    console.log('User tapped custom button: ', response.customButton);
  } else {
    const source = { uri: response.uri };

    // You can also display the image using data:
    // const source = { uri: 'data:image/jpeg;base64,' + response.data };

    this.setState({
      avatarSource: source,
    });
  }
});
```
Your explanation here and source code or link

I have tried all various combinations of options to ensure the image is not saved to the device/storage but I can't stop it from happening.

### Solution

Ideally, if a path key is present but a null value is provided then it should not save the image taken, only provide the base64 string. Optionally, there could be a new prop to specify that only a base64 string is required and no saving should take place. 

### Additional Information

* React Native version: 2.0.1
* Platform: Android
* Development Operating System: Ubuntu 18.04
* Dev tools: Webstorm, Android Studio (3.0.0)

**Comment by jpdesignerrio** [comment]
What the documentation says about "storageOptions":

> If this key is provided, the image will be saved in your app's Documents directory on iOS, or your app's Pictures directory on Android (rather than a temporary directory)

So, do not use then! Remove this code:
`storageOptions: {
            cameraRoll: false, 
            skipBackup: true,
            path: null,
        }`

**Comment by akapila011** [comment]
After completely removing the storage options such that my new camera options look as follows:
```
const cameraOptions = {
    title: 'Capture Image',
    quality: 1.0,
        cameraType: 'back',
        rotation: 0,
        maxHeight: 675, 
        maxWidth: 900,  
        mediaType: "photo",
};
```

I still end up with 2 copies of the image taken. 1 is in the app's folder, 1 is in the DCIM folder for the camera. The path returned is for the image stored in the app directory and I am current using react-native-fs to delete this image but that still leaves me with the image in the camera directory/DCIM. 

I have tried this on 2 devices and I am getting similar results on both. I am currently using version 0.27.1 (react-native-image-picker).

**Comment by jpdesignerrio** [comment]
Please, Post your console log text...

**Comment by akapila011** [comment]
When using camera options with no storageOptions the response is : 
```
{
data: "base64 string"
fileName: "image-093f5749-4b37-430c-b49b-ee4dbaf05b08.jpg"
fileSize: 271940
height: 675
isVertical: true
latitude: null
longitude: null
originalRotation: 0
path: "/storage/emulated/0/Pictures/image-093f5749-4b37-430c-b49b-ee4dbaf05b08.jpg"
timestamp: "2019-01-09T06:55:49Z"
type: "image/jpeg"
uri: "file:///storage/emulated/0/Pictures/image-093f5749-4b37-430c-b49b-ee4dbaf05b08.jpg"
width: 506
}
```

When using storageOptions "storageOptions: { cameraRoll: false, skipBackup: true, path: null}" in the camera options:
```
{
data: "base64 string"
fileName: "image-8f5f6979-e355-4402-9a07-c02022df1d56.jpg"
fileSize: 153541
height: 675
isVertical: true
latitude: null
longitude: null
originalRotation: 0
path: "/storage/emulated/0/Pictures/image-8f5f6979-e355-4402-9a07-c02022df1d56.jpg"
timestamp: "2019-01-09T06:50:42Z"
type: "image/jpeg"
uri: "file:///storage/emulated/0/Pictures/image-8f5f6979-e355-4402-9a07-c02022df1d56.jpg"
width: 506
}
```

Looks like there is no effect when removing the storageOptions key.

**Comment by jpdesignerrio** [comment]
I'm using without storageOption and the "data" key not exists. What version are you using?

**Comment by akapila011** [comment]
Will this be fixed or should we rely on external libraries to clear out the saved image?

Currently, I am using react-native-fs to delete 1 image. Turns out that is actually saves 2 images. 1 image has it's path returned in the response object so getting rid of it is trivial. However, there is a second image that is also saved and it looks it is saved to the camera's image folder (DCIM folder). The problem comes in that we have of way of knowing this image's path and so it becomes really difficult to delete this second saved image.

**Comment by lbelavoir** [comment]
Duplicate of #941

**Comment by Josh2941** [comment]
I too face this same issue. Expecting a fix soon.

**Comment by akapila011** [comment]
Looks like pull request #687 might be addressing this issue.

**Comment by lbelavoir** [comment]
@akapila011 I hope that this branch is still valide since 2017

**Comment by Albert0405** [comment]
I have the same issue, i dont want to save the image taken from the camera. I only want to take a picture then save to my server storage

**Comment by jpdesignerrio** [comment]
Any solution? I'm getting 100% of internal storage occupied by taken photos...

**Comment by vaibsharma** [comment]
is there any fix to this issue?

**Comment by jpdesignerrio** [comment]
Yes, I fix it, but I don't know where is my code HAHAHA I'll put it here soon.

**Comment by jpdesignerrio** [comment]
```
async takePicture() {
    try {
      const options = {
        title: 'Whatever',
        chooseFromLibraryButtonTitle: null,
        cameraType: 'back',
        mediaType: 'photo',
        noData: true, // IMPORTANT TO MAKE IT FASTER
        cameraRoll: false,
        quality: 0.5,
        
        storageOptions: {
          skipBackup: true,
          path: 'tmp_files' // ANY NAME YOU WANT
        },
      };
      // Launch Camera:
      ImagePicker.launchCamera(options, (response) => {
        if (response.error) {
          console.error(response.error);
        } else if(!response.didCancel) {
         
          RNFS.readFile(response.uri, "base64").then(based => {
            // binary data
            _this.setState({
              photoUri: response.uri,
              photoData: based, // YOUR BASE64 STRING
            });

          });
        }
      });
    } catch(e) {
      console.error(e);
    }
  }

clearCameraCache() {
    try {
      var file = _this.state.photoUri.split('///').pop();
      const filePath = file.substring(0, file.lastIndexOf('/'));

      // read storageOptions.path and delete all inside it
      RNFS.readDir(filePath)
        .then(files => {
          for(let t of files) {
            RNFS.unlink(t.path);
          }

        })
        .catch(err => {
          console.error(err)
        });
      } catch (e) {
        Logger.report('Documentos.js clearCameraCache()', e.message);
      }
  }
```

**I Just "copy and past" the code, and added comment. So, tell me if you find errors.**

**Comment by agrass** [comment]
Hi @jpdesignerrio , but that code still generating two images in the tmp_files folder? The original and the resized. I'm with problem with that using 0.28.0 version.

**Comment by ShubhamBalgujar** [comment]
How to convert response.uri to base64 and then to byte array. I need byte-array to send via API.
Any help will be much appreciated.

**Comment by lbelavoir** [comment]
@ShubhamBalgujar did you find any patch for that?
In terms of privacy and security it's pretty bad as every picture is sent to Google drive ...

**Comment by ShubhamBalgujar** [comment]
No I am working on it but currently I am using the same.

**Comment by ShubhamBalgujar** [comment]
@lbelavoir No, working on that but currently I am using the same.

**Comment by lbelavoir** [comment]
Any updates ? I know this issue is closed but it's not resolved as far as I know. Anyone tried on v2.0.0 ?

**Comment by fadlykayo** [comment]
Auto saving still exist on ver 2.3.1. Is there any fix for this?

**Comment by kockok** [comment]
If I remove `storageOptions` completely, the image still save to the `/tmp` folder.

So, please set an option to only return the base64 data and NOT storing the captured image.
