### ISSUE TITLE
Modal stays on top of camera

### ISSUE THREAD

**Issue by ohpax** [react-native-community/react-native-image-picker#988]
When I open camera inside a react-native modal, the modal stays on top of camera screen and if I try to hide the modal eveything goes away.

**Comment by NicolasAlt128** [comment]
I have this same issue, there is any workaround ?

**Comment by Allmacamo** [comment]
I had the same problem and fixed it by changing  the picker.modalPresentationStyle to `UIModalPresentationPageSheet`

https://github.com/Allmacamo/rn-image-picker/commit/350593ef75b37255d6f01a344a27d796d947ac32

Will submit a PR when I get time.
