### ISSUE TITLE
ImagePicker.launchCamera not calling callback function on second call from a modal

### ISSUE THREAD

**Issue by jimcullenaus** [react-native-community/react-native-image-picker#989]
### Description

If `ImagePicker.launchCamera` is called from a modal dialog on iOS, it works fine the first time and returns to the original page. Then the second time the modal dialog is created and the camera called upon, the camera opens briefly before closing itself without any user interaction. The callback function does not get called at all. No response is set.

Android works totally fine. iOS also works fine if the camera is called from somewhere other than the modal.

The modal is a radio button selection when is closed before the camera is called normally, but is somehow *reopened* when the camera crashes. After a crash, the app is unresponsive. The scrollview containing the radio selection options allows scrolling up and down, but the selection chosen cannot be changed, and the modal cannot be closed.

Expected behaviour is the library would always call the callback function provided to it and return an error if something goes wrong. Or that the camera would not close itself prematurely.

### How to repeat issue and example

**calling-file.tsx:**

```typescript
beginUpload() : boolean {
  this.alertInput.showAlert();
  return false;
}

private completeUpload(documentDescription : string) {
  return new Promise((resolve, reject) => {
    ImageService.capture().then((response : <stuff>) => {
      resolve(response.uri);
      ... some logic
      this.setState(...);
    }).catch(not being called);
  }
}

render() {
  return(
    <View><Button-which-calls-beginUpload />
    <AlertInput
      ref={(alertInput : AlertInput) => this.alertInput = alertInput}
      callback={this.completeUpload}/>
    </View>
  );
```

**alert-input.tsx:**

```typescript
public showAlert() {
  if (Platform.OS === 'ios') {
    AlertIOS.prompt(
      'title', 'message', text => this.props.callback(text)
    );
}
``` 

**imageservice.ts:**

```typescript
export default class ImageService {
    static capture() {
        return new Promise<stuff>((resolve, reject) => {
            const options: any = {
                storageOptions: {
                    skipBackup: true,
                    waitUntilSaved: true,
                    cameraRoll: true,
                    path: '/'
                },
                mediaType: 'photo',
                cameraType: 'back',
                noData: true
            };
            ImagePicker.launchCamera(options, (response: any) => {
                console.log('this line not called second time');
                if (response.didCancel || response.error) { // (this part actually two separate if conditions in our code)
                    console.log('not called');
                    reject({cancelled: true}) || reject(response.error);
                }
                // not being called on second attempt.
            });
            console.log('this is called');
        } 
    }
}
```

### Solution

If it fails, image picker should always contain an error and the callback function should be called regardless, instead of just not being called in some cases.

### Additional Information

* React Native version: 0.57.1
* Platform: iOS
* Development Operating System: macOS
* Dev tools: Xcode 10.1, IPHONEOS_DEPLOYMENT_TARGET = 10.3

**Comment by marcioaso** [comment]
same to me

**Comment by jules097** [comment]
I have the same problem

**Comment by jimcullenaus** [comment]
Umm, this has not seen any resolution. Why would you have a bot that closes issues that haven't been addressed.

**Comment by jimcullenaus** [comment]
Still have not heard a solution...

**Comment by dembeEdward** [comment]
This is still an issue

**Comment by dembeEdward** [comment]
Found the solution.....just make sure your modal is closed before calling `launchCamera()`.

**Comment by fyoreo** [comment]
@dembeEdward fixed my problem.. thanks, you're my savior

**Comment by gagandesethi** [comment]
ImagePicker.launchCamera(response => {
      console.log('ResponseImage = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        const source = {uri: response.uri};

        // You can also display the image using data:
        // const source = { uri: 'data:image/jpeg;base64,' + response.data };

        this.setState({
          avatarSource: source,
        });
      }
    }

//camera get open but after clicking a pic  no response is coming

**Comment by jesimielefraimdias** [comment]
Same
