### ISSUE TITLE
Not working in Expo Snack

### ISSUE THREAD

**Issue by shivanraptor** [react-native-community/react-native-image-picker#993]
### Description

I try to use the example code in Expo Snack, run in iOS App

### How to repeat issue and example

Here is the Snack I'm working on: https://snack.expo.io/@raptorkwok/camera-and-image-library-example

It said, `undefined is not an object (evaluating 'i.showImagePicker')`. Please help.

### Solution

Not at this moment

### Additional Information

* React Native version: Expo 31.0.0, React Native 0.57
* Platform: iOS & Snack Expo
* Development Operating System: MacOS Mojave & Google Crhome
* Dev tools: Google Chrome

**Comment by andrewmarmion** [comment]
I don't think that this repo can be used with Expo as it requires you to link the dependency into the Android and iOS folders, which Expo does not have.
