### ISSUE TITLE
Could not find com.android.tools:common:25.2.3

### ISSUE THREAD

**Issue by davidlandais** [react-native-community/react-native-image-picker#999]
### Description

I tried to build my react-native application for android.
AndroidStudio tell me that common:25.2.3 is undefined in jcenter repository.
My build.gradle is configured to use 3.1.4 gradle version.

### How to repeat issue and example

Create a new react application (version should be `0.57.7`).
Install and link react-native-image-picker.
Open AndroidStudio, ask it to sync project file with gradle files.

### Solution

I edited build.gradle to update 2+ to 3.1.4 and added google in repositories.

### Additional Information

* React Native version: 0.57.7
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Android Studio v3.2.1

**Comment by nehvaleem** [comment]
having exact same issue but I don't feel like editing files in node_modules to get this to work

**Comment by davidlandais** [comment]
If you prefer to not edit files in node_modules, you could fork this repository and clone it on your computer. Then, you could use `npm link` to use your local respoitory. Make your changes in the cloned repo. And if you are confortable make a PR. ;)

**Comment by nehvaleem** [comment]
yeah, I know that. I mean by my previous comment that it would be awesome if there was some kind of workaround that wouldn't require modifying or copying source files of this plugin :)

**Comment by davidlandais** [comment]
Yeah totally agree !

**Comment by tkserver** [comment]
Is this the same problem you are having? Here's mine.

A problem occurred configuring project ':react-native-image-picker'.
> Could not resolve all files for configuration ':react-native-image-picker:classpath'.
   > Could not find com.android.tools:common:25.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.pom
         https://jcenter.bintray.com/com/android/tools/common/25.2.3/common-25.2.3.jar
     Required by:
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.build:manifest-merger:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.ddms:ddmlib:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:shared:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools.analytics-library:tracker:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools.layoutlib:layoutlib-api:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:dvlib:25.2.3
         project :react-native-image-picker > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3 > com.android.tools.build:builder:2.2.3 > com.android.tools:sdklib:25.2.3 > com.android.tools:repository:25.2.3

**Comment by davidlandais** [comment]
Yes, try to edit `node_modules/react-native-image-picker/android/build.gradle` and replace buildscript with:

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
    }
}
```

**Comment by KalebMatthews** [comment]
For those that do not use local builds you can edit your app's build.gradle (not app/build.gradle) to include:
```
subprojects {project ->
    if (project.name.contains('module name, e.g. react-native-image-picker')) {
            buildscript {
                repositories {
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }    
        }
    }
}
```

This will override the current configuration for you. This is for those that can not modify the projects gradle during the build process.

**Comment by tkserver** [comment]
> Yes, try to edit `node_modules/react-native-image-picker/android/build.gradle` and replace buildscript with:
> 
> ```
> buildscript {
>     repositories {
>         google()
>         jcenter()
>     }
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.1.4'
>     }
> }
> ```
> You should edit `classpath 'com.android.tools.build:gradle:3.1.4'` according to your main build.gradle (mine is configured to use v3.1.4):
> 
> ```
> dependencies {
>         classpath 'com.android.tools.build:gradle:3.1.4'
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> ```

Yes that fixed it for me. Thanks

**Comment by zerokol** [comment]
@KalebMatthews you save my life! I spent three days looking for it, I don't know if it is a final solution, but it works!

**Comment by davidlandais** [comment]
@KalebMatthews Thanks for sharing ;)
With your suggestion, i reverted my changes in node_modules and appended
```
subprojects {project ->
    if (project.name.contains('react-native-image-picker')) {
        buildscript {
            repositories {
                google()
                jcenter()
            }

            dependencies {
                classpath 'com.android.tools.build:gradle:3.1.4'
            }
        }
    }
}
```
I'm not a Java Android dev. so what do you think about it ?

**Comment by davidlandais** [comment]
Yes it's working. I noticed that using an other repository like `maven { url "https://dl.bintray.com/android/android-tools/"  }` trigger download of additionnals packages. Using the same repositories with `google()` skip that step.

**Comment by nicoara** [comment]
WHAT IS GOING ON???

**Comment by raikk** [comment]
i had a problem using `react-native-google-signin` in `react-native-firebase`
Thanks @davidlandais i added this (Project: build.gradles)

```
subprojects {project ->
  if (project.name.contains('react-native-google-signin')) {
    buildscript {
      repositories {
        google()
        maven { url "https://dl.bintray.com/android/android-tools/" }
        jcenter()
      }

      dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
      }
    }
  }
}

```
it trigger to download all packgages then started new issues i.e 
```

error: package co.apptailor.googlesignin does not exist
import co.apptailor.googlesignin.RNGoogleSigninPackage;
...
new RNGoogleSigninPackage(),
                ^
  symbol: class RNGoogleSigninPackage
2 errors
```

From  https://github.com/react-native-community/react-native-google-signin/issues/416#issuecomment-395882535  this i added

```
compile(project(":react-native-google-signin")){
    exclude group: "com.google.android.gms" 
  }
```

then my application can run and work fine.
